'use client';
import { useEditorStore } from '@/store/editor';
import Link from 'next/link';
import { useState } from 'react';

interface Props {
  initialProfile?: { credits: number; plan: string; email: string; id?: string } | null;
  projectId?: string;
  showCode?: boolean;
  showFileTree?: boolean;
  onToggleCode?: () => void;
  onToggleFileTree?: () => void;
}

function WyberIcon() {
  return (
    <svg width="24" height="24" viewBox="0 0 32 32" fill="none">
      <rect width="32" height="32" rx="8" fill="#0EA5E9"/>
      <path d="M20 7L11 16L20 25" stroke="white" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M23 11L28 16L23 21" stroke="white" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round" opacity="0.4"/>
    </svg>
  );
}

export function TopBar({ initialProfile, projectId, showCode, showFileTree, onToggleCode, onToggleFileTree }: Props = {}) {
  const { project, isGenerating, credits, files } = useEditorStore();
  const displayCredits = initialProfile?.credits ?? credits;
  const [exporting, setExporting] = useState(false);
  const [deploying, setDeploying] = useState(false);
  const [deployUrl, setDeployUrl] = useState('');

  const handleExport = async () => {
    if (exporting) return;
    setExporting(true);
    try {
      if (projectId) {
        const res = await fetch('/api/export', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId, format: 'zip' }) });
        if (res.ok) {
          const blob = await res.blob();
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url; a.download = `${project?.name ?? 'wyber-app'}.zip`; a.click();
          URL.revokeObjectURL(url);
        }
      } else {
        const JSZip = (await import('jszip')).default;
        const zip = new JSZip();
        for (const [path, file] of Object.entries(files)) zip.file(path, (file as any).content);
        zip.file('README.md', `# ${project?.name ?? 'Wyber App'}\n\nGenerated by Wyber AI\n`);
        const blob = await zip.generateAsync({ type: 'blob' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `${project?.name ?? 'wyber-app'}.zip`; a.click();
        URL.revokeObjectURL(url);
      }
    } catch {}
    setExporting(false);
  };

  const handleDeploy = async () => {
    if (!projectId) { window.dispatchEvent(new CustomEvent('wyber:switch-tab', { detail: 'deploy' })); return; }
    if (deploying) return;
    setDeploying(true);
    try {
      const res = await fetch('/api/deploy', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId, userId: initialProfile?.id, files, projectName: project?.name ?? 'wyber-app' }) });
      const data = await res.json();
      if (data.url) { setDeployUrl(data.url); window.open(data.url, '_blank'); }
    } catch {}
    setDeploying(false);
  };

  const divider = { width: 1, height: 18, background: 'var(--ide-border)', margin: '0 4px', flexShrink: 0 } as const;

  const toggleBtn = (active?: boolean) => ({
    display: 'flex', alignItems: 'center', gap: 5, padding: '4px 10px', borderRadius: 6,
    border: `1px solid ${active ? 'var(--ide-border-light)' : 'transparent'}`,
    background: active ? 'var(--bg-elevated)' : 'transparent',
    color: active ? 'var(--ide-text)' : 'var(--ide-text2)',
    fontSize: 11, fontWeight: 500, cursor: 'pointer', transition: 'var(--t)',
    fontFamily: 'var(--font-sans)', letterSpacing: '-0.01em',
  });

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '0 12px', height: 44, flexShrink: 0, background: 'var(--bg-base)', borderBottom: '1px solid var(--ide-border)', zIndex: 20 }}>

      <Link href="/dashboard" style={{ display: 'flex', alignItems: 'center', gap: 7, textDecoration: 'none', marginRight: 4, flexShrink: 0 }}>
        <WyberIcon />
        <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--ide-text)', letterSpacing: '-0.04em' }}>
          Wyber<span style={{ color: '#7C3AED' }}>AI</span>
        </span>
      </Link>

      <div style={divider} />

      <button onClick={onToggleFileTree} style={toggleBtn(showFileTree)}>
        <svg width="12" height="10" viewBox="0 0 16 12" fill="currentColor"><rect x="0" y="0" width="16" height="2" rx="1"/><rect x="0" y="5" width="12" height="2" rx="1"/><rect x="0" y="10" width="14" height="2" rx="1"/></svg>
        Files
      </button>

      <button onClick={onToggleCode} style={toggleBtn(showCode)}>
        <svg width="12" height="10" viewBox="0 0 16 12" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M5 2L1 6l4 4M11 2l4 4-4 4"/></svg>
        Code
      </button>

      <div style={divider} />

      {project && (
        <span style={{ fontSize: 12, color: 'var(--ide-text)', fontWeight: 600, maxWidth: 180, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', letterSpacing: '-0.02em' }}>
          {project.name}
        </span>
      )}

      <div style={{ flex: 1 }} />

      {isGenerating && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: 'var(--accent)', fontSize: 11, fontWeight: 600 }}>
          <div style={{ display: 'flex', gap: 3 }}>
            {[0,1,2].map(i => (
              <div key={i} style={{ width: 4, height: 4, borderRadius: '50%', background: 'var(--accent)', animation: `dot-pulse 1.2s ease-in-out ${i * 0.15}s infinite` }} />
            ))}
          </div>
          Building...
        </div>
      )}

      <div style={{ fontSize: 11, padding: '3px 9px', borderRadius: 20, background: displayCredits > 20 ? 'rgba(34,197,94,0.1)' : 'rgba(239,68,68,0.1)', color: displayCredits > 20 ? 'var(--ide-green)' : 'var(--ide-red)', fontWeight: 600, border: `1px solid ${displayCredits > 20 ? 'rgba(34,197,94,0.2)' : 'rgba(239,68,68,0.2)'}` }}>
        {displayCredits} cr
      </div>

      {initialProfile?.plan && initialProfile.plan !== 'free' && (
        <div style={{ fontSize: 10, padding: '2px 7px', borderRadius: 20, background: 'var(--accent-glow)', color: 'var(--accent)', fontWeight: 700, border: '1px solid var(--accent-dim)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
          {initialProfile.plan}
        </div>
      )}

      <div style={divider} />

      <button onClick={handleExport} disabled={exporting} title="Export as ZIP"
        style={{ display: 'flex', alignItems: 'center', gap: 5, fontSize: 11, padding: '5px 11px', borderRadius: 6, border: '1px solid var(--ide-border)', background: 'transparent', color: 'var(--ide-text2)', cursor: exporting ? 'wait' : 'pointer', transition: 'var(--t)', fontFamily: 'var(--font-sans)', fontWeight: 500 }}>
        <svg width="11" height="11" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d="M8 2v8M5 7l3 3 3-3M2 12v1a1 1 0 001 1h10a1 1 0 001-1v-1"/></svg>
        {exporting ? 'Exporting...' : 'Export'}
      </button>

      <button onClick={handleDeploy} disabled={deploying} title="Deploy to Vercel"
        style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, padding: '5px 13px', borderRadius: 6, border: 'none', background: deploying ? 'var(--bg-elevated)' : 'var(--accent)', color: deploying ? 'var(--ide-text2)' : 'white', cursor: deploying ? 'wait' : 'pointer', fontWeight: 700, transition: 'var(--t)', fontFamily: 'var(--font-sans)', boxShadow: deploying ? 'none' : '0 2px 12px rgba(124,58,237,0.35)' }}>
        {deploying ? (
          <><div style={{ width: 10, height: 10, border: '1.5px solid rgba(255,255,255,0.3)', borderTopColor: '#fff', borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} />Deploying</>
        ) : (
          <><svg width="10" height="10" viewBox="0 0 16 16" fill="currentColor"><path d="M8 0L0 16h16L8 0z"/></svg>{deployUrl ? 'Deployed ↗' : 'Deploy'}</>
        )}
      </button>
    </div>
  );
}