export const architectureStudio = {
  name: 'Architecture & Design Studio — Project & Proposal Suite',
  category: 'Creative',
  paletteId: 'brutalist-light',
  config: {
    description: 'Project tracking and client proposals for an architecture studio — phases, budgets, site visits.',
    appName: 'Ferro & Lund',
    tagline: 'Structural clarity for every project, from concept to occupancy.',
    loginQuote: 'Every project, every phase, one drawing set.',
    navIcon: 'Compass',
    primaryFeatureRoute: 'projects',
    primaryFeaturePascal: 'Projects',
    primaryFeatureLabel: 'Projects',
    primaryFeatureSingular: 'Project',
    greetingName: 'Marit Lund',
    greetingInsight: '3 projects entered Construction Documents this week — Kestrel House is 2 days from permit submission.',
    dashboardVariant: 'highlights',
    highlights: [
      { title: 'Kestrel House', description: 'Permit set due Friday — structural review 90% complete.' },
      { title: 'Alder Street Offices', description: 'Client sign-off pending on the schematic design package.' },
      { title: 'Birchwood Pavilion', description: 'Site visit scheduled Thursday with the structural engineer.' },
    ],
    kpis: [
      { label: 'Active Projects', value: 18, delta: 6, spark: [12, 13, 14, 15, 16, 17, 17, 18] },
      { label: 'Avg. Project Duration', value: '9 mo', spark: [11, 10, 10, 10, 9, 9, 9, 9] },
      { label: 'On-Budget Rate', value: 88, suffix: '%', delta: 3, spark: [80, 81, 83, 84, 85, 86, 87, 88] },
      { label: 'Billable Hours (MTD)', value: 512, spark: [50, 110, 170, 230, 300, 370, 440, 512] },
    ],
    weeklyBars: [
      { label: 'W1', value: 4 }, { label: 'W2', value: 6 }, { label: 'W3', value: 5 },
      { label: 'W4', value: 8 }, { label: 'W5', value: 7 }, { label: 'W6', value: 9 },
      { label: 'W7', value: 6 }, { label: 'W8', value: 10 },
    ],
    activity: [
      { label: 'Kestrel House entered Construction Documents phase', time: '1 hour ago' },
      { label: 'Site visit logged for Birchwood Pavilion', time: '3 hours ago' },
      { label: 'Budget revised for Alder Street Offices — +$40k contingency', time: 'yesterday' },
      { label: 'Permit submitted for the Colby Residence addition', time: 'yesterday' },
      { label: 'Client approved schematic design for Willow Creek Clinic', time: '2 days ago' },
    ],
    primaryTable: {
      columns: ['Client', 'Project Type', 'Phase', 'Lead Architect'],
      filters: ['In Progress', 'Pending Approval', 'Completed'],
      rows: [
        { cells: ['Kestrel Development Group', 'Multi-family Residential', 'Construction Documents', 'M. Lund'], status: 'In Progress' },
        { cells: ['Alder Street Partners', 'Commercial Office', 'Schematic Design', 'T. Ferro'], status: 'Pending Approval' },
        { cells: ['City of Birchwood', 'Public Pavilion', 'Design Development', 'M. Lund'], status: 'In Progress' },
        { cells: ['The Colby Family', 'Residential Addition', 'Permitting', 'A. Reyes'], status: 'Pending Approval' },
        { cells: ['Willow Creek Health', 'Medical Clinic', 'Construction Documents', 'T. Ferro'], status: 'In Progress' },
        { cells: ['Sundstrom Residence', 'Single-family Custom', 'Construction', 'A. Reyes'], status: 'In Progress' },
        { cells: ['Northgate Retail Group', 'Retail Renovation', 'Completed', 'M. Lund'], status: 'Completed' },
        { cells: ['Pemberton Vineyards', 'Hospitality — Tasting Room', 'Schematic Design', 'T. Ferro'], status: 'Pending Approval' },
        { cells: ['Ash & Iron Studio', 'Adaptive Reuse — Loft', 'Completed', 'A. Reyes'], status: 'Completed' },
      ],
    },
    analyticsKpis: [
      { label: 'New Projects', value: 5, delta: 12 },
      { label: 'Billable Hours', value: 512, delta: 8 },
      { label: 'On-Time Delivery', value: 84, suffix: '%', delta: -3 },
      { label: 'Avg. Fee per Project', value: 62, suffix: 'k', delta: 5 },
    ],
    trend: [
      { label: 'Jan', value: 380 }, { label: 'Feb', value: 410 }, { label: 'Mar', value: 460 },
      { label: 'Apr', value: 490 }, { label: 'May', value: 512 },
    ],
    sources: [
      { label: 'Referral', value: 9 }, { label: 'Repeat client', value: 6 },
      { label: 'Competition win', value: 2 }, { label: 'Cold inbound', value: 1 },
    ],
    rankedTable: {
      label: 'Projects by architect',
      rows: [
        { name: 'M. Lund', value: 7 },
        { name: 'T. Ferro', value: 6 },
        { name: 'A. Reyes', value: 5 },
      ],
    },
    notifications: [
      { title: 'Permit submitted', description: 'The Colby Residence addition permit set was submitted to the city.', time: '1 hour ago', unread: true, tone: 'default' },
      { title: 'Client approval pending', description: 'Alder Street Offices schematic design awaits sign-off.', time: '5 hours ago', unread: true, tone: 'outline' },
      { title: 'Site visit completed', description: 'Structural walkthrough logged for Birchwood Pavilion.', time: 'yesterday', unread: false, tone: 'solid' },
      { title: 'Project completed', description: 'Northgate Retail renovation closed out — final billing sent.', time: '3 days ago', unread: false, tone: 'default' },
    ],
    team: [
      { name: 'Marit Lund', email: 'm.lund@ferrolund.com', role: 'Principal' },
      { name: 'Tomas Ferro', email: 't.ferro@ferrolund.com', role: 'Principal' },
      { name: 'Ana Reyes', email: 'a.reyes@ferrolund.com', role: 'Project Architect' },
      { name: 'Jules Okafor', email: 'j.okafor@ferrolund.com', role: 'Architectural Designer' },
    ],
  },
}
