export const artGallery = {
  name: 'Fine Art Gallery — Collection & Client Suite',
  category: 'Creative',
  paletteId: 'gallery-red-light',
  config: {
    description: 'Inventory, private client relationships, and sales for a fine art gallery and auction house.',
    appName: 'Verrier & Cass',
    tagline: 'Representing artists whose work outlives the market cycle.',
    loginQuote: 'Every work, every collector, one ledger.',
    navIcon: 'Frame',
    primaryFeatureRoute: 'works',
    primaryFeaturePascal: 'Works',
    primaryFeatureLabel: 'Collection',
    primaryFeatureSingular: 'Work',
    greetingName: 'Colette Verrier',
    greetingInsight: "The autumn exhibition opens in 9 days — 6 works have private holds pending confirmation.",
    dashboardVariant: 'activity',
    kpis: [
      { label: 'Works in Collection', value: 84, delta: 5, spark: [70, 73, 76, 78, 80, 81, 83, 84] },
      { label: 'Collection Value', value: 6.4, suffix: 'M', delta: 8, spark: [5.2, 5.4, 5.7, 5.9, 6.0, 6.2, 6.3, 6.4] },
      { label: 'Private Clients', value: 112, delta: 4, spark: [98, 101, 103, 105, 107, 109, 110, 112] },
      { label: 'Sales (MTD)', value: 340, suffix: 'k', spark: [30, 70, 120, 170, 220, 270, 310, 340] },
    ],
    weeklyBars: [
      { label: 'W1', value: 2 }, { label: 'W2', value: 4 }, { label: 'W3', value: 3 },
      { label: 'W4', value: 5 }, { label: 'W5', value: 4 }, { label: 'W6', value: 6 },
      { label: 'W7', value: 5 }, { label: 'W8', value: 7 },
    ],
    activity: [
      { label: 'Private hold placed on "Meridian Fold" by R. Achebe', time: '45 minutes ago' },
      { label: 'New consignment received: 3 works by Ingrid Solheim', time: '2 hours ago' },
      { label: 'Sale confirmed — "Low Tide, Marrow Bay" to a private collector', time: '5 hours ago' },
      { label: 'Provenance research completed for the Castellano bequest', time: 'yesterday' },
      { label: 'Autumn exhibition catalog sent to 340 collectors', time: 'yesterday' },
    ],
    primaryTable: {
      columns: ['Title', 'Artist', 'Medium', 'Price'],
      filters: ['Available', 'Pending Sale', 'Sold'],
      rows: [
        { cells: ['Meridian Fold', 'Rem Achebe', 'Oil on linen', '$84,000'], status: 'Pending Sale' },
        { cells: ['Low Tide, Marrow Bay', 'Ingrid Solheim', 'Oil on canvas', '$62,000'], status: 'Sold' },
        { cells: ['Vessel, No. 7', 'Rem Achebe', 'Bronze', '$118,000'], status: 'Available' },
        { cells: ['Quiet Interior', 'Marguerite Fontaine', 'Oil on panel', '$47,000'], status: 'Available' },
        { cells: ['Threshold Study II', 'Ingrid Solheim', 'Charcoal on paper', '$18,500'], status: 'Available' },
        { cells: ['The Long Corridor', 'Marguerite Fontaine', 'Oil on canvas', '$96,000'], status: 'Pending Sale' },
        { cells: ['Ash Grove', 'Rem Achebe', 'Oil on linen', '$71,000'], status: 'Sold' },
        { cells: ['Fractured Light', 'Ingrid Solheim', 'Mixed media', '$54,000'], status: 'Available' },
      ],
    },
    analyticsKpis: [
      { label: 'Sales Volume (Q)', value: 890, suffix: 'k', delta: 16 },
      { label: 'Avg. Sale Price', value: 61, suffix: 'k', delta: 6 },
      { label: 'New Consignments', value: 11, delta: 22 },
      { label: 'Collector Retention', value: 88, suffix: '%', delta: 3 },
    ],
    trend: [
      { label: 'Jan', value: 5.2 }, { label: 'Feb', value: 5.7 }, { label: 'Mar', value: 6.0 },
      { label: 'Apr', value: 6.3 }, { label: 'May', value: 6.4 },
    ],
    sources: [
      { label: 'Private client', value: 6 }, { label: 'Art fair', value: 3 },
      { label: 'Advisor referral', value: 2 }, { label: 'Auction consignment', value: 2 },
    ],
    rankedTable: {
      label: 'Sales by artist',
      rows: [
        { name: 'Rem Achebe', value: 273 },
        { name: 'Ingrid Solheim', value: 134 },
        { name: 'Marguerite Fontaine', value: 96 },
      ],
    },
    notifications: [
      { title: 'Private hold placed', description: '"Meridian Fold" by Rem Achebe — hold confirmed pending payment.', time: '45 minutes ago', unread: true, tone: 'outline' },
      { title: 'Sale confirmed', description: '"Low Tide, Marrow Bay" sold to a private collector for $62,000.', time: '5 hours ago', unread: true, tone: 'solid' },
      { title: 'New consignment', description: '3 works by Ingrid Solheim received for the autumn exhibition.', time: 'yesterday', unread: false, tone: 'default' },
      { title: 'Catalog distributed', description: 'Autumn exhibition catalog sent to 340 collectors on the mailing list.', time: 'yesterday', unread: false, tone: 'default' },
    ],
    team: [
      { name: 'Colette Verrier', email: 'c.verrier@verriercass.com', role: 'Gallery Director' },
      { name: 'Julian Cass', email: 'j.cass@verriercass.com', role: 'Co-Director' },
      { name: 'Beatrix Ondo', email: 'b.ondo@verriercass.com', role: 'Registrar' },
      { name: 'Felix Marchetti', email: 'f.marchetti@verriercass.com', role: 'Client Relations' },
    ],
  },
}
