import { assembleConfig } from '../lib/content-pool.mjs'

const specs = [
  {
    seed: 1301, name: 'Estate & Probate Law Firm — Case Suite', category: 'Legal', paletteId: 'paper-oxblood-light',
    appName: 'Aldergate & Finch', tagline: 'Estate administration handled with the patience grief actually requires.',
    loginQuote: 'Every estate, every heir, accounted for.', navIcon: 'ScrollText',
    primaryFeatureRoute: 'estates', primaryFeaturePascal: 'Estates', primaryFeatureLabel: 'Estates', primaryFeatureSingular: 'Estate',
    greetingInsight: '4 estates enter final distribution this month — 2 probate filings are due this week.',
    dashboardVariant: 'activity', weeklyBase: 5,
    kpis: [
      { label: 'Active Estates', value: 26, delta: 6 }, { label: 'Avg. Administration Time', value: '11 mo', delta: -7 },
      { label: 'Estates Closed (YTD)', value: 9, delta: 12 }, { label: 'Avg. Estate Value', value: 1.4, suffix: 'M', delta: 4 },
    ],
    primaryTable: {
      columns: ['Estate', 'Matter Type', 'Attorney', 'Stage'], filters: ['Active', 'Court Filing', 'Closed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Court Filing', 'Closed'],
        itemTypes: ['Probate Administration', 'Trust Administration', 'Will Contest', 'Guardianship', 'Estate Tax Filing'],
        details: ['Inventory filed', 'Awaiting court date', 'Closed last month', 'Heir dispute pending', 'Distribution scheduled'] },
    },
    analyticsKpis: [{ label: 'New Estates', value: 3, delta: 10 }, { label: 'Closed Estates', value: 2, delta: 25 }, { label: 'Avg. Fee', value: 24, suffix: 'k', delta: 3 }, { label: 'Court Filings', value: 7, delta: 5 }],
    trend: [{ label: 'Jan', value: 20 }, { label: 'Feb', value: 22 }, { label: 'Mar', value: 23 }, { label: 'Apr', value: 25 }, { label: 'May', value: 26 }],
    sources: [{ label: 'Referral', value: 4 }, { label: 'Repeat client', value: 3 }, { label: 'Financial advisor referral', value: 2 }],
    rankedLabel: 'Estates by attorney',
  },
  {
    seed: 1302, name: 'Corporate Relocation Services — Move & Client Suite', category: 'Logistics', paletteId: 'open-air-light',
    appName: 'Meridian Relocation Partners', tagline: 'Corporate moves that land the employee, not just the boxes.',
    loginQuote: 'Every move, every family, settled.', navIcon: 'Route',
    primaryFeatureRoute: 'moves', primaryFeaturePascal: 'Moves', primaryFeatureLabel: 'Moves', primaryFeatureSingular: 'Move',
    greetingInsight: '6 relocations are in transit this week — 2 families arrive at their destination Friday.',
    dashboardVariant: 'activity', weeklyBase: 7,
    kpis: [
      { label: 'Active Moves', value: 24, delta: 9 }, { label: 'Avg. Move Duration', value: '6 wks', delta: -5 },
      { label: 'Client Satisfaction', value: 94, suffix: '%', delta: 2 }, { label: 'Corporate Accounts', value: 18, delta: 3 },
    ],
    primaryTable: {
      columns: ['Employee', 'Client Company', 'Relocation Consultant', 'Stage'], filters: ['In Transit', 'Planning', 'Settled'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['In Transit', 'Planning', 'Settled'],
        itemTypes: ['Domestic Relocation', 'International Relocation', 'Temporary Housing', 'Home Sale Assistance', 'School Search'],
        details: ['Household goods in transit', 'Visa processing', 'Settled last month', 'Home search underway', 'Lease signed'] },
    },
    analyticsKpis: [{ label: 'New Moves', value: 6, delta: 15 }, { label: 'Corporate Revenue', value: 210, suffix: 'k', delta: 8 }, { label: 'Avg. Time to Settle', value: '5.2 wks', delta: -8 }, { label: 'Account Retention', value: 91, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 18 }, { label: 'Feb', value: 20 }, { label: 'Mar', value: 21 }, { label: 'Apr', value: 23 }, { label: 'May', value: 24 }],
    sources: [{ label: 'Corporate contract', value: 12 }, { label: 'Repeat account', value: 8 }, { label: 'Referral', value: 4 }],
    rankedLabel: 'Moves by consultant',
  },
  {
    seed: 1303, name: 'Boutique PR Agency — Client & Placement Suite', category: 'Marketing', paletteId: 'editorial-ink-light',
    appName: 'Ashworth Communications', tagline: 'Earned media for brands that would rather not buy the attention.',
    loginQuote: 'Every pitch, every placement, tracked.', navIcon: 'Newspaper',
    primaryFeatureRoute: 'clients', primaryFeaturePascal: 'Clients', primaryFeatureLabel: 'Clients', primaryFeatureSingular: 'Client',
    greetingInsight: '3 placements confirmed this week — the Solace Skincare feature runs in print Sunday.',
    dashboardVariant: 'highlights', weeklyBase: 4,
    highlights: [
      { title: 'Solace Skincare', description: 'Print feature runs Sunday — digital pickup expected to follow.' },
      { title: 'Ferrous Coffee', description: 'Founder interview booked with a national morning show.' },
      { title: 'Halcyon Studio', description: 'Press kit finalized ahead of the product launch.' },
    ],
    kpis: [
      { label: 'Active Clients', value: 12, delta: 9 }, { label: 'Placements (MTD)', value: 28, delta: 14 },
      { label: 'Avg. Placement Value', value: 18, suffix: 'k', delta: 5 }, { label: 'Media Reach (MTD)', value: 4.2, suffix: 'M' },
    ],
    primaryTable: {
      columns: ['Client', 'Campaign Type', 'Account Lead', 'Status Detail'], filters: ['Active', 'Pitching', 'Placed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Pitching', 'Placed'],
        itemTypes: ['Product Launch Campaign', 'Founder Profile', 'Crisis Communications', 'Thought Leadership', 'Media Tour'],
        details: ['Pitching this week', 'Placed in national outlet', 'Interview scheduled', 'Awaiting response', 'Feature runs Sunday'] },
    },
    analyticsKpis: [{ label: 'New Clients', value: 2, delta: 20 }, { label: 'Placements', value: 28, delta: 14 }, { label: 'Media Reach', value: 4.2, suffix: 'M', delta: 18 }, { label: 'Avg. Response Time', value: '6h', delta: -12 }],
    trend: [{ label: 'Jan', value: 9 }, { label: 'Feb', value: 10 }, { label: 'Mar', value: 11 }, { label: 'Apr', value: 11 }, { label: 'May', value: 12 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Inbound pitch', value: 4 }, { label: 'Repeat client', value: 3 }],
    rankedLabel: 'Placements by account lead',
  },
  {
    seed: 1304, name: 'Private Chef & Catering Collective — Booking Suite', category: 'Food', paletteId: 'food-amber-light',
    appName: 'Ferrous Table Collective', tagline: 'Private chefs booked without twelve back-and-forth emails.',
    loginQuote: 'Every chef, every booking, confirmed.', navIcon: 'UtensilsCrossed',
    primaryFeatureRoute: 'bookings', primaryFeaturePascal: 'Bookings', primaryFeatureLabel: 'Bookings', primaryFeatureSingular: 'Booking',
    greetingInsight: '5 private dinners are booked this week — 2 menus still need client sign-off.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Active Bookings', value: 17, delta: 11 }, { label: 'Chefs on Roster', value: 14, delta: 2 },
      { label: 'Avg. Booking Value', value: 2.8, suffix: 'k', delta: 6 }, { label: 'Repeat Client Rate', value: 58, suffix: '%', delta: 4 },
    ],
    primaryTable: {
      columns: ['Client', 'Event Type', 'Chef', 'Menu Status'], filters: ['Confirmed', 'Menu Pending', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Confirmed', 'Menu Pending', 'Completed'],
        itemTypes: ['Private Dinner Party', 'Anniversary Dinner', 'Corporate Chef Experience', 'Wine Pairing Dinner', 'Holiday Gathering'],
        details: ['Menu approved', 'Awaiting sign-off', 'Completed last week', 'Tasting scheduled', 'Deposit received'] },
    },
    analyticsKpis: [{ label: 'New Bookings', value: 6, delta: 18 }, { label: 'Revenue (MTD)', value: 48, suffix: 'k', delta: 10 }, { label: 'Avg. Guests/Event', value: 8, delta: 2 }, { label: 'Chef Utilization', value: 71, suffix: '%', delta: 5 }],
    trend: [{ label: 'Jan', value: 12 }, { label: 'Feb', value: 13 }, { label: 'Mar', value: 15 }, { label: 'Apr', value: 16 }, { label: 'May', value: 17 }],
    sources: [{ label: 'Referral', value: 7 }, { label: 'Repeat client', value: 5 }, { label: 'Instagram inquiry', value: 2 }],
    rankedLabel: 'Bookings by chef',
  },
  {
    seed: 1305, name: 'Boutique Investment Fund Administrator — Fund Ops Suite', category: 'Finance', paletteId: 'saas-indigo-dark',
    appName: 'Ledgerstone Fund Services', tagline: 'Fund administration that closes the books on time, every time.',
    loginQuote: 'Every fund, every NAV, verified.', navIcon: 'Calculator',
    primaryFeatureRoute: 'funds', primaryFeaturePascal: 'Funds', primaryFeatureLabel: 'Funds', primaryFeatureSingular: 'Fund',
    greetingInsight: 'Month-end close is 80% complete — 2 funds are still awaiting broker statements.',
    dashboardVariant: 'activity', weeklyBase: 4,
    kpis: [
      { label: 'Funds Administered', value: 22, delta: 5 }, { label: 'AUA', value: 1.8, suffix: 'B', delta: 6 },
      { label: 'On-Time NAV Rate', value: 98, suffix: '%', delta: 1 }, { label: 'Investor Reports (MTD)', value: 340 },
    ],
    primaryTable: {
      columns: ['Fund', 'Fund Type', 'Fund Accountant', 'Close Status'], filters: ['Active', 'Reconciling', 'Closed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Reconciling', 'Closed'],
        itemTypes: ['Long/Short Equity Fund', 'Private Credit Fund', 'Real Estate Fund', 'Venture Fund', 'Multi-Strategy Fund'],
        details: ['NAV published', 'Awaiting broker statement', 'Closed on time', 'Reconciliation in progress', 'Investor report sent'] },
    },
    analyticsKpis: [{ label: 'New Funds', value: 2, delta: 12 }, { label: 'AUA Growth', value: 6, suffix: '%', delta: 2 }, { label: 'Avg. Close Time', value: '4.2 days', delta: -10 }, { label: 'Investor Queries', value: 84, delta: -8 }],
    trend: [{ label: 'Jan', value: 1.6 }, { label: 'Feb', value: 1.65 }, { label: 'Mar', value: 1.7 }, { label: 'Apr', value: 1.75 }, { label: 'May', value: 1.8 }],
    sources: [{ label: 'Sponsor referral', value: 3 }, { label: 'Law firm referral', value: 2 }, { label: 'Repeat sponsor', value: 1 }],
    rankedLabel: 'AUA by accountant',
  },
  {
    seed: 1306, name: 'High-End Landscape Design Studio — Project Suite', category: 'Creative', paletteId: 'forest-market-light',
    appName: 'Fernbrook Landscape Studio', tagline: 'Gardens designed to look established the day they are planted.',
    loginQuote: 'Every property, every planting plan, on schedule.', navIcon: 'TreePine',
    primaryFeatureRoute: 'projects', primaryFeaturePascal: 'Projects', primaryFeatureLabel: 'Projects', primaryFeatureSingular: 'Project',
    greetingInsight: 'Spring installs begin next week — 3 planting plans are in final client review.',
    dashboardVariant: 'highlights', weeklyBase: 4,
    highlights: [
      { title: 'Whitmore Estate Garden', description: 'Planting plan approved — installation begins Monday.' },
      { title: 'Alder Street Courtyard', description: 'Hardscape phase complete, awaiting plant delivery.' },
      { title: 'Birchwood Residence', description: 'Site consultation scheduled for next week.' },
    ],
    kpis: [
      { label: 'Active Projects', value: 15, delta: 10 }, { label: 'Avg. Project Budget', value: 84, suffix: 'k', delta: 6 },
      { label: 'On-Schedule Rate', value: 87, suffix: '%', delta: 3 }, { label: 'Nursery Orders (MTD)', value: 22 },
    ],
    primaryTable: {
      columns: ['Client', 'Project Type', 'Designer', 'Phase'], filters: ['Design', 'Installation', 'Complete'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Design', 'Installation', 'Complete'],
        itemTypes: ['Full Property Landscape', 'Kitchen Garden', 'Pool Surround', 'Native Plant Restoration', 'Courtyard Design'],
        details: ['Plan in review', 'Installation this week', 'Completed last month', 'Hardscape underway', 'Site consult scheduled'] },
    },
    analyticsKpis: [{ label: 'New Projects', value: 3, delta: 15 }, { label: 'Nursery Spend', value: 32, suffix: 'k', delta: 8 }, { label: 'Avg. Timeline', value: '10 wks', delta: -5 }, { label: 'Client Satisfaction', value: 96, suffix: '%', delta: 2 }],
    trend: [{ label: 'Jan', value: 10 }, { label: 'Feb', value: 12 }, { label: 'Mar', value: 13 }, { label: 'Apr', value: 14 }, { label: 'May', value: 15 }],
    sources: [{ label: 'Referral', value: 6 }, { label: 'Architect partner', value: 5 }, { label: 'Portfolio inbound', value: 4 }],
    rankedLabel: 'Projects by designer',
  },
  {
    seed: 1307, name: 'Private Security Staffing Agency — Detail Suite', category: 'Logistics', paletteId: 'mono-dev-dark',
    appName: 'Blackridge Protective Services', tagline: 'Executive protection staffed by people who have actually done the job.',
    loginQuote: 'Every detail, every principal, covered.', navIcon: 'Shield',
    primaryFeatureRoute: 'details', primaryFeaturePascal: 'Details', primaryFeatureLabel: 'Details', primaryFeatureSingular: 'Detail',
    greetingInsight: '8 active details this week — 2 new agents complete onboarding Friday.',
    dashboardVariant: 'activity', weeklyBase: 12,
    kpis: [
      { label: 'Active Details', value: 8, delta: 14 }, { label: 'Agents on Roster', value: 42, delta: 5 },
      { label: 'Incident-Free Days', value: 340, delta: 8 }, { label: 'Client Retention', value: 93, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Principal', 'Detail Type', 'Lead Agent', 'Status Detail'], filters: ['Active', 'Staffing', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Staffing', 'Completed'],
        itemTypes: ['Executive Protection', 'Event Security', 'Residential Detail', 'Travel Security', 'Corporate Site Security'],
        details: ['Detail active', 'Staffing in progress', 'Completed last week', 'Advance work underway', 'Contract renewed'] },
    },
    analyticsKpis: [{ label: 'New Details', value: 2, delta: 10 }, { label: 'Agent Hours', value: 1840, delta: 6 }, { label: 'Avg. Detail Length', value: '5 days', delta: -3 }, { label: 'Client Retention', value: 93, suffix: '%', delta: 2 }],
    trend: [{ label: 'Jan', value: 6 }, { label: 'Feb', value: 7 }, { label: 'Mar', value: 7 }, { label: 'Apr', value: 8 }, { label: 'May', value: 8 }],
    sources: [{ label: 'Referral', value: 4 }, { label: 'Repeat client', value: 3 }, { label: 'RFP win', value: 1 }],
    rankedLabel: 'Details by lead agent',
  },
  {
    seed: 1308, name: 'Bespoke Tailoring House — Client & Order Suite', category: 'RealEstate', paletteId: 'gallery-red-light',
    appName: 'Aldergate Bespoke', tagline: 'Suits built to the client, not the rack.',
    loginQuote: 'Every client, every fitting, precise.', navIcon: 'Shirt',
    primaryFeatureRoute: 'orders', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'Orders', primaryFeatureSingular: 'Order',
    greetingInsight: '4 fittings are scheduled this week — 2 finished garments are ready for pickup.',
    dashboardVariant: 'activity', weeklyBase: 5,
    kpis: [
      { label: 'Active Orders', value: 21, delta: 8 }, { label: 'Avg. Order Value', value: 3.8, suffix: 'k', delta: 5 },
      { label: 'Avg. Turnaround', value: '6 wks', delta: -4 }, { label: 'Client Retention', value: 84, suffix: '%', delta: 3 },
    ],
    primaryTable: {
      columns: ['Client', 'Garment Type', 'Tailor', 'Stage'], filters: ['In Progress', 'Fitting', 'Ready'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['In Progress', 'Fitting', 'Ready'],
        itemTypes: ['Bespoke Suit', 'Formal Evening Wear', 'Custom Shirt Order', 'Overcoat', 'Wedding Suit'],
        details: ['First fitting scheduled', 'Final fitting this week', 'Ready for pickup', 'Cutting in progress', 'Fabric selection'] },
    },
    analyticsKpis: [{ label: 'New Orders', value: 5, delta: 12 }, { label: 'Revenue (MTD)', value: 62, suffix: 'k', delta: 9 }, { label: 'Avg. Fittings/Order', value: 2.4, delta: -5 }, { label: 'Repeat Client Rate', value: 68, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 16 }, { label: 'Feb', value: 17 }, { label: 'Mar', value: 19 }, { label: 'Apr', value: 20 }, { label: 'May', value: 21 }],
    sources: [{ label: 'Referral', value: 8 }, { label: 'Repeat client', value: 6 }, { label: 'Walk-in', value: 3 }],
    rankedLabel: 'Orders by tailor',
  },
  {
    seed: 1309, name: 'Private Tutoring & Test Prep Firm — Student Suite', category: 'Education', paletteId: 'cobalt-pop-light',
    appName: 'Ashford Scholars Tutoring', tagline: 'Test prep for students who need a plan, not just a workbook.',
    loginQuote: 'Every student, every session, on track.', navIcon: 'BookOpen',
    primaryFeatureRoute: 'students', primaryFeaturePascal: 'Students', primaryFeatureLabel: 'Students', primaryFeatureSingular: 'Student',
    greetingInsight: '12 sessions are scheduled this week — 2 students test this Saturday.',
    dashboardVariant: 'activity', weeklyBase: 20,
    kpis: [
      { label: 'Active Students', value: 46, delta: 9 }, { label: 'Avg. Score Improvement', value: 180, delta: 6 },
      { label: 'Sessions (MTD)', value: 210, delta: 8 }, { label: 'Parent Satisfaction', value: 96, suffix: '%', delta: 1 },
    ],
    primaryTable: {
      columns: ['Student', 'Program', 'Tutor', 'Next Session'], filters: ['Active', 'Test Scheduled', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Test Scheduled', 'Completed'],
        itemTypes: ['SAT Prep', 'ACT Prep', 'AP Chemistry', 'AP Calculus', 'College Essay Coaching'],
        details: ['Session Tuesday', 'Test Saturday', 'Program completed', 'Session Thursday', 'Diagnostic scheduled'] },
    },
    analyticsKpis: [{ label: 'New Students', value: 6, delta: 14 }, { label: 'Sessions Delivered', value: 210, delta: 8 }, { label: 'Avg. Score Gain', value: 180, delta: 6 }, { label: 'Renewal Rate', value: 79, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 38 }, { label: 'Feb', value: 40 }, { label: 'Mar', value: 42 }, { label: 'Apr', value: 44 }, { label: 'May', value: 46 }],
    sources: [{ label: 'Parent referral', value: 9 }, { label: 'School counselor referral', value: 5 }, { label: 'Inbound', value: 3 }],
    rankedLabel: 'Students by tutor',
  },
  {
    seed: 1310, name: 'Marine Vessel Maintenance — Service Suite', category: 'Logistics', paletteId: 'precision-sky-dark',
    appName: 'Meridian Yacht Services', tagline: 'Vessel maintenance scheduled before the season, not during it.',
    loginQuote: 'Every vessel, every service, logged.', navIcon: 'Anchor',
    primaryFeatureRoute: 'vessels', primaryFeaturePascal: 'Vessels', primaryFeatureLabel: 'Vessels', primaryFeatureSingular: 'Vessel',
    greetingInsight: '9 vessels are in service this week — 2 are ready for spring launch.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Vessels Serviced (MTD)', value: 24, delta: 10 }, { label: 'Avg. Service Time', value: '4 days', delta: -8 },
      { label: 'Fleet Under Contract', value: 62, delta: 4 }, { label: 'Client Retention', value: 90, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Vessel', 'Service Type', 'Technician', 'Status Detail'], filters: ['In Service', 'Awaiting Parts', 'Ready'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['In Service', 'Awaiting Parts', 'Ready'],
        itemTypes: ['Engine Service', 'Hull Cleaning', 'Rigging Inspection', 'Electronics Upgrade', 'Spring Commissioning'],
        details: ['Service in progress', 'Parts on order', 'Ready for launch', 'Inspection scheduled', 'Completed yesterday'] },
    },
    analyticsKpis: [{ label: 'New Contracts', value: 3, delta: 15 }, { label: 'Service Revenue', value: 84, suffix: 'k', delta: 8 }, { label: 'Avg. Turnaround', value: '3.6 days', delta: -6 }, { label: 'Repeat Contracts', value: 84, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 52 }, { label: 'Feb', value: 55 }, { label: 'Mar', value: 58 }, { label: 'Apr', value: 60 }, { label: 'May', value: 62 }],
    sources: [{ label: 'Marina referral', value: 5 }, { label: 'Repeat client', value: 4 }, { label: 'Broker referral', value: 2 }],
    rankedLabel: 'Vessels by technician',
  },
]

export const batchSaas4 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: assembleConfig(spec),
}))
