import { assembleConfig } from '../lib/content-pool.mjs'

const specs = [
  {
    seed: 1201, name: 'Interior Design Studio — Project & Sourcing Suite', category: 'Creative', paletteId: 'clay-sand-light',
    appName: 'Aldergate Interiors', tagline: 'Interiors specified down to the last drawer pull.',
    loginQuote: 'Every room, every sourced piece, tracked.', navIcon: 'Sofa',
    primaryFeatureRoute: 'projects', primaryFeaturePascal: 'Projects', primaryFeatureLabel: 'Projects', primaryFeatureSingular: 'Project',
    greetingInsight: 'The Whitfield residence enters furniture install next week — 3 sourcing orders are still in transit.',
    dashboardVariant: 'highlights', weeklyBase: 4,
    highlights: [
      { title: 'Whitfield Residence', description: 'Furniture install scheduled next week — 3 pieces still in transit.' },
      { title: 'Marchbanks Penthouse', description: 'Client approved the final fabric selections.' },
      { title: 'Coppermill Office', description: 'Site measure completed, mood board due Friday.' },
    ],
    kpis: [
      { label: 'Active Projects', value: 13, delta: 8 }, { label: 'Avg. Project Budget', value: 240, suffix: 'k', delta: 5 },
      { label: 'On-Time Install Rate', value: 86, suffix: '%', delta: 2 }, { label: 'Sourced Orders (MTD)', value: 44 },
    ],
    primaryTable: {
      columns: ['Client', 'Project Type', 'Designer', 'Phase'], filters: ['In Progress', 'Sourcing', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['In Progress', 'Sourcing', 'Completed'],
        itemTypes: ['Full Home Renovation', 'Penthouse Redesign', 'Office Interior', 'Vacation Home', 'Kitchen & Living Refresh'],
        details: ['Furniture install', 'Fabric selection', 'Site measure', 'Mood board review', 'Final walkthrough'] },
    },
    analyticsKpis: [{ label: 'New Projects', value: 3, delta: 22 }, { label: 'Sourcing Spend', value: 180, suffix: 'k', delta: 9 }, { label: 'Avg. Timeline', value: '5 mo', delta: -8 }, { label: 'Client Satisfaction', value: 96, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 9 }, { label: 'Feb', value: 10 }, { label: 'Mar', value: 11 }, { label: 'Apr', value: 12 }, { label: 'May', value: 13 }],
    sources: [{ label: 'Referral', value: 6 }, { label: 'Architect partner', value: 4 }, { label: 'Portfolio inbound', value: 3 }],
    rankedLabel: 'Projects by designer',
  },
  {
    seed: 1202, name: 'Boutique Investment Bank — Deal Advisory Suite', category: 'Finance', paletteId: 'saas-indigo-light',
    appName: 'Ashworth Capital Advisors', tagline: 'M&A advisory for founders selling the company once.',
    loginQuote: 'Every mandate, every buyer, tracked.', navIcon: 'Handshake',
    primaryFeatureRoute: 'mandates', primaryFeaturePascal: 'Mandates', primaryFeatureLabel: 'Mandates', primaryFeatureSingular: 'Mandate',
    greetingInsight: 'The Vantage Materials sale process enters management presentations this week.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Mandates', value: 7, delta: 17 }, { label: 'Pipeline Value', value: 420, suffix: 'M', delta: 12 },
      { label: 'Avg. Deal Size', value: 60, suffix: 'M', delta: 4 }, { label: 'Closed (YTD)', value: 3, delta: 50 },
    ],
    primaryTable: {
      columns: ['Client', 'Transaction Type', 'Deal Lead', 'Stage'], filters: ['Active', 'Diligence', 'Closed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Diligence', 'Closed'],
        itemTypes: ['Sell-Side M&A', 'Buy-Side M&A', 'Growth Capital Raise', 'Recapitalization', 'Debt Advisory'],
        details: ['Management presentations', 'Buyer outreach', 'LOI negotiation', 'Closed last quarter', 'Data room open'] },
    },
    analyticsKpis: [{ label: 'New Mandates', value: 2, delta: 25 }, { label: 'Buyer Outreach', value: 84, delta: 10 }, { label: 'Avg. Time to Close', value: '7 mo', delta: -5 }, { label: 'Fee Revenue (Q)', value: 4.2, suffix: 'M', delta: 15 }],
    trend: [{ label: 'Jan', value: 4 }, { label: 'Feb', value: 5 }, { label: 'Mar', value: 6 }, { label: 'Apr', value: 7 }, { label: 'May', value: 7 }],
    sources: [{ label: 'Sponsor referral', value: 3 }, { label: 'Repeat client', value: 2 }, { label: 'Banker network', value: 2 }],
    rankedLabel: 'Pipeline by lead',
  },
  {
    seed: 1203, name: 'Private School Admissions — Enrollment Suite', category: 'Education', paletteId: 'editorial-ink-light',
    appName: 'Ashford Preparatory Academy', tagline: 'Admissions handled the way the school actually operates — carefully.',
    loginQuote: 'Every applicant, every family, considered.', navIcon: 'GraduationCap',
    primaryFeatureRoute: 'applicants', primaryFeaturePascal: 'Applicants', primaryFeatureLabel: 'Applicants', primaryFeatureSingular: 'Applicant',
    greetingInsight: 'Fall enrollment is 92% filled — 6 interviews are scheduled this week.',
    dashboardVariant: 'activity', weeklyBase: 11,
    kpis: [
      { label: 'Active Applicants', value: 84, delta: 6 }, { label: 'Enrollment Filled', value: 92, suffix: '%', delta: 3 },
      { label: 'Avg. Time to Decision', value: '18 days', delta: -6 }, { label: 'Yield Rate', value: 78, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Applicant', 'Grade Level', 'Admissions Officer', 'Status Detail'], filters: ['Under Review', 'Interview Scheduled', 'Accepted'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Under Review', 'Interview Scheduled', 'Accepted'],
        itemTypes: ['Grade 6 Applicant', 'Grade 9 Applicant', 'Kindergarten Applicant', 'Grade 3 Applicant', 'Transfer Applicant'],
        details: ['Interview Thursday', 'Awaiting transcripts', 'Financial aid pending', 'Decision letter sent', 'Campus tour completed'] },
    },
    analyticsKpis: [{ label: 'New Applications', value: 14, delta: 9 }, { label: 'Interviews Held', value: 22, delta: 11 }, { label: 'Acceptance Rate', value: 61, suffix: '%', delta: -3 }, { label: 'Financial Aid Awarded', value: 340, suffix: 'k', delta: 7 }],
    trend: [{ label: 'Jan', value: 60 }, { label: 'Feb', value: 68 }, { label: 'Mar', value: 74 }, { label: 'Apr', value: 80 }, { label: 'May', value: 84 }],
    sources: [{ label: 'Current family referral', value: 6 }, { label: 'Feeder school', value: 4 }, { label: 'Open house', value: 4 }],
    rankedLabel: 'Applicants by officer',
  },
  {
    seed: 1204, name: 'Boutique Winery — Club & Distribution Suite', category: 'Food', paletteId: 'supper-club-dark',
    appName: 'Ferrous Hollow Vineyards', tagline: 'Small-lot wine, tracked from barrel to wine club shipment.',
    loginQuote: 'Every vintage, every member, accounted for.', navIcon: 'Wine',
    primaryFeatureRoute: 'orders', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'Orders', primaryFeatureSingular: 'Order',
    greetingInsight: 'The spring wine club shipment goes out Friday — 340 member orders are queued.',
    dashboardVariant: 'activity', weeklyBase: 60,
    kpis: [
      { label: 'Wine Club Members', value: 680, delta: 9 }, { label: 'Case Sales (MTD)', value: 210, delta: 14 },
      { label: 'Avg. Order Value', value: 340, delta: 5 }, { label: 'Member Retention', value: 88, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Member', 'Order Type', 'Fulfillment Lead', 'Ship Date'], filters: ['Queued', 'Processing', 'Shipped'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Queued', 'Processing', 'Shipped'],
        itemTypes: ['Quarterly Club Shipment', 'Reserve Case', 'Direct-to-Consumer Order', 'Restaurant Wholesale Order', 'Tasting Room Order'],
        details: ['Mar 8', 'Mar 10', 'Shipped last week', 'Mar 15', 'Awaiting label approval'] },
    },
    analyticsKpis: [{ label: 'New Members', value: 22, delta: 18 }, { label: 'Revenue (MTD)', value: 92, suffix: 'k', delta: 11 }, { label: 'Avg. Case Price', value: 280, delta: 4 }, { label: 'Wholesale Accounts', value: 34, delta: 6 }],
    trend: [{ label: 'Jan', value: 560 }, { label: 'Feb', value: 600 }, { label: 'Mar', value: 630 }, { label: 'Apr', value: 655 }, { label: 'May', value: 680 }],
    sources: [{ label: 'Tasting room signup', value: 12 }, { label: 'Member referral', value: 7 }, { label: 'Online', value: 3 }],
    rankedLabel: 'Shipments by fulfillment lead',
  },
  {
    seed: 1205, name: 'Specialty Coffee Roaster — Wholesale & Subscription Suite', category: 'Food', paletteId: 'food-amber-light',
    appName: 'Marrow & Ash Roasters', tagline: 'Roasted to order, shipped before the roast curve cools.',
    loginQuote: 'Every roast, every account, tracked.', navIcon: 'Coffee',
    primaryFeatureRoute: 'accounts', primaryFeaturePascal: 'Accounts', primaryFeatureLabel: 'Wholesale Accounts', primaryFeatureSingular: 'Account',
    greetingInsight: 'This week’s roast schedule covers 6 wholesale accounts — the Birchwood Café order ships tomorrow.',
    dashboardVariant: 'activity', weeklyBase: 40,
    kpis: [
      { label: 'Wholesale Accounts', value: 58, delta: 7 }, { label: 'Subscription Members', value: 1240, delta: 12 },
      { label: 'Lbs Roasted (MTD)', value: 3400, delta: 9 }, { label: 'Account Retention', value: 91, suffix: '%', delta: 1 },
    ],
    primaryTable: {
      columns: ['Account', 'Account Type', 'Account Manager', 'Next Delivery'], filters: ['Active', 'Onboarding', 'Paused'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Onboarding', 'Paused'],
        itemTypes: ['Café Wholesale', 'Grocery Retail', 'Office Coffee Service', 'Restaurant Account', 'Hotel Program'],
        details: ['Mar 5', 'Mar 7', 'Weekly standing order', 'Paused — seasonal', 'Mar 12'] },
    },
    analyticsKpis: [{ label: 'New Accounts', value: 4, delta: 14 }, { label: 'Roast Volume', value: 3400, delta: 9 }, { label: 'Subscription Revenue', value: 62, suffix: 'k', delta: 13 }, { label: 'Avg. Account Size', value: '48 lbs/mo', delta: 3 }],
    trend: [{ label: 'Jan', value: 46 }, { label: 'Feb', value: 50 }, { label: 'Mar', value: 53 }, { label: 'Apr', value: 56 }, { label: 'May', value: 58 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Trade show', value: 2 }, { label: 'Inbound', value: 2 }],
    rankedLabel: 'Volume by account manager',
  },
  {
    seed: 1206, name: 'Boutique Fitness Studio — Membership & Class Suite', category: 'Productivity', paletteId: 'track-red-light',
    appName: 'Ironclad Performance Studio', tagline: 'Small-group training, run like it actually scales.',
    loginQuote: 'Every member, every class, full.', navIcon: 'Dumbbell',
    primaryFeatureRoute: 'members', primaryFeaturePascal: 'Members', primaryFeatureLabel: 'Members', primaryFeatureSingular: 'Member',
    greetingInsight: 'Class capacity is at 94% this week — the 6 AM strength cohort has a waitlist.',
    dashboardVariant: 'activity', weeklyBase: 50,
    kpis: [
      { label: 'Active Members', value: 380, delta: 8 }, { label: 'Class Capacity Rate', value: 94, suffix: '%', delta: 4 },
      { label: 'Avg. Visits/Member', value: 3.2, delta: 2 }, { label: 'Membership Revenue (MTD)', value: 58, suffix: 'k' },
    ],
    primaryTable: {
      columns: ['Member', 'Membership Tier', 'Trainer', 'Status Detail'], filters: ['Active', 'Trial', 'Paused'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Trial', 'Paused'],
        itemTypes: ['Unlimited Membership', 'Founding Member', '3x/Week Plan', 'Personal Training Add-On', 'Corporate Membership'],
        details: ['Renewed this month', 'Trial ends Friday', 'On hold — travel', 'Upgraded last week', 'Auto-renews Mar 15'] },
    },
    analyticsKpis: [{ label: 'New Members', value: 18, delta: 16 }, { label: 'Class Attendance', value: 1240, delta: 7 }, { label: 'Churn Rate', value: 4, suffix: '%', delta: -1 }, { label: 'Avg. Revenue/Member', value: 152, delta: 3 }],
    trend: [{ label: 'Jan', value: 320 }, { label: 'Feb', value: 340 }, { label: 'Mar', value: 355 }, { label: 'Apr', value: 368 }, { label: 'May', value: 380 }],
    sources: [{ label: 'Referral', value: 9 }, { label: 'Trial conversion', value: 6 }, { label: 'Corporate partner', value: 3 }],
    rankedLabel: 'Members by trainer',
  },
  {
    seed: 1207, name: 'Custom Furniture Workshop — Commission & Client Suite', category: 'Creative', paletteId: 'clay-sand-light',
    appName: 'Ashgrove Woodworks', tagline: 'Commissioned furniture, one piece at a time, tracked start to finish.',
    loginQuote: 'Every commission, every client, on schedule.', navIcon: 'Hammer',
    primaryFeatureRoute: 'commissions', primaryFeaturePascal: 'Commissions', primaryFeatureLabel: 'Commissions', primaryFeatureSingular: 'Commission',
    greetingInsight: 'The Whitmore dining table enters final finishing this week — 2 commissions ship Friday.',
    dashboardVariant: 'highlights', weeklyBase: 3,
    highlights: [
      { title: 'Whitmore Dining Table', description: 'Final finishing this week — walnut, seats 10.' },
      { title: 'Delacroix Credenza', description: 'Client approved the hardware selection.' },
      { title: 'Fenwick Studio Desk', description: 'New commission — design consult scheduled.' },
    ],
    kpis: [
      { label: 'Active Commissions', value: 9, delta: 12 }, { label: 'Avg. Commission Value', value: 12, suffix: 'k', delta: 6 },
      { label: 'On-Time Delivery', value: 88, suffix: '%', delta: 3 }, { label: 'Workshop Hours (MTD)', value: 340 },
    ],
    primaryTable: {
      columns: ['Client', 'Piece Type', 'Craftsperson', 'Phase'], filters: ['In Progress', 'Finishing', 'Delivered'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['In Progress', 'Finishing', 'Delivered'],
        itemTypes: ['Dining Table', 'Credenza', 'Custom Desk', 'Bed Frame', 'Bookcase'],
        details: ['Final finishing', 'Joinery in progress', 'Delivered last month', 'Design consult', 'Awaiting hardware'] },
    },
    analyticsKpis: [{ label: 'New Commissions', value: 2, delta: 25 }, { label: 'Workshop Hours', value: 340, delta: 8 }, { label: 'Avg. Build Time', value: '7 wks', delta: -4 }, { label: 'Client Satisfaction', value: 98, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 6 }, { label: 'Feb', value: 7 }, { label: 'Mar', value: 8 }, { label: 'Apr', value: 8 }, { label: 'May', value: 9 }],
    sources: [{ label: 'Referral', value: 4 }, { label: 'Designer partner', value: 3 }, { label: 'Portfolio inbound', value: 2 }],
    rankedLabel: 'Commissions by craftsperson',
  },
  {
    seed: 1208, name: 'Talent & Literary Agency — Roster & Deal Suite', category: 'Creative', paletteId: 'paper-oxblood-light',
    appName: 'Harcourt Fenwick Agency', tagline: 'Representing the work, not just the contract.',
    loginQuote: 'Every client, every deal, negotiated.', navIcon: 'Mic',
    primaryFeatureRoute: 'deals', primaryFeaturePascal: 'Deals', primaryFeatureLabel: 'Deals', primaryFeatureSingular: 'Deal',
    greetingInsight: '4 deals are in final negotiation this week — the Okonkwo book deal closes Friday.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Deals', value: 16, delta: 9 }, { label: 'Roster Size', value: 42, delta: 4 },
      { label: 'Avg. Deal Value', value: 84, suffix: 'k', delta: 7 }, { label: 'Closed (YTD)', value: 11, delta: 22 },
    ],
    primaryTable: {
      columns: ['Client', 'Deal Type', 'Agent', 'Stage'], filters: ['Active', 'Negotiation', 'Closed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Negotiation', 'Closed'],
        itemTypes: ['Book Deal', 'Speaking Engagement', 'Film Option', 'Brand Partnership', 'Podcast Deal'],
        details: ['Term sheet out', 'Contract review', 'Closed last week', 'Offer received', 'In discussion'] },
    },
    analyticsKpis: [{ label: 'New Deals', value: 3, delta: 20 }, { label: 'Commission Revenue', value: 210, suffix: 'k', delta: 12 }, { label: 'Avg. Time to Close', value: '6 wks', delta: -8 }, { label: 'Roster Retention', value: 94, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 12 }, { label: 'Feb', value: 13 }, { label: 'Mar', value: 14 }, { label: 'Apr', value: 15 }, { label: 'May', value: 16 }],
    sources: [{ label: 'Referral', value: 6 }, { label: 'Cold pitch', value: 3 }, { label: 'Repeat client', value: 4 }],
    rankedLabel: 'Deals by agent',
  },
  {
    seed: 1209, name: 'Corporate Security Consultancy — Engagement Suite', category: 'Logistics', paletteId: 'precision-acid-dark',
    appName: 'Blackridge Security Advisory', tagline: 'Risk assessments for organizations that would rather not find out the hard way.',
    loginQuote: 'Every engagement, every risk, documented.', navIcon: 'ShieldAlert',
    primaryFeatureRoute: 'engagements', primaryFeaturePascal: 'Engagements', primaryFeatureLabel: 'Engagements', primaryFeatureSingular: 'Engagement',
    greetingInsight: '3 site assessments are scheduled this week — the Coppermill report is due Thursday.',
    dashboardVariant: 'activity', weeklyBase: 4,
    kpis: [
      { label: 'Active Engagements', value: 12, delta: 9 }, { label: 'Avg. Engagement Value', value: 46, suffix: 'k', delta: 5 },
      { label: 'Findings Remediated', value: 82, suffix: '%', delta: 6 }, { label: 'Consultant Utilization', value: 79, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Client', 'Assessment Type', 'Lead Consultant', 'Stage'], filters: ['Active', 'Report Pending', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Report Pending', 'Completed'],
        itemTypes: ['Physical Security Assessment', 'Executive Protection Review', 'Facility Risk Audit', 'Travel Security Plan', 'Insider Threat Review'],
        details: ['Site visit scheduled', 'Report drafting', 'Completed last month', 'Findings under review', 'Client briefing Friday'] },
    },
    analyticsKpis: [{ label: 'New Engagements', value: 3, delta: 18 }, { label: 'Assessments Completed', value: 8, delta: 10 }, { label: 'Avg. Findings/Assessment', value: 14, delta: -6 }, { label: 'Client Retention', value: 90, suffix: '%', delta: 2 }],
    trend: [{ label: 'Jan', value: 8 }, { label: 'Feb', value: 9 }, { label: 'Mar', value: 10 }, { label: 'Apr', value: 11 }, { label: 'May', value: 12 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Insurance partner', value: 4 }, { label: 'RFP win', value: 3 }],
    rankedLabel: 'Engagements by consultant',
  },
  {
    seed: 1210, name: 'Private Equity-Backed Dental Group — Practice Suite', category: 'Healthcare', paletteId: 'wellness-sage-light',
    appName: 'Alderbrook Dental Partners', tagline: 'Multi-location dental care, run with one operating standard.',
    loginQuote: 'Every practice, every patient, one standard.', navIcon: 'Smile',
    primaryFeatureRoute: 'practices', primaryFeaturePascal: 'Practices', primaryFeatureLabel: 'Practices', primaryFeatureSingular: 'Practice',
    greetingInsight: 'Group-wide production is up 6% this month — 2 practices exceed their monthly target.',
    dashboardVariant: 'highlights', weeklyBase: 30,
    highlights: [
      { title: 'Birchwood Location', description: 'Exceeded monthly production target by 14%.' },
      { title: 'Marchbanks Location', description: 'New hygienist onboarding completes this week.' },
      { title: 'Coppermill Location', description: 'Equipment upgrade scheduled for next month.' },
    ],
    kpis: [
      { label: 'Active Locations', value: 9, delta: 12 }, { label: 'Group Production (MTD)', value: 1.2, suffix: 'M', delta: 6 },
      { label: 'Patient Retention', value: 87, suffix: '%', delta: 2 }, { label: 'Avg. Chair Utilization', value: 81, suffix: '%', delta: 3 },
    ],
    primaryTable: {
      columns: ['Location', 'Region', 'Practice Manager', 'Status Detail'], filters: ['On Target', 'Under Review', 'Exceeding'],
      rowsSpec: { count: 8, subjectKind: 'company', statuses: ['On Target', 'Under Review', 'Exceeding'],
        itemTypes: ['General Practice', 'Orthodontics', 'Pediatric Dentistry', 'Oral Surgery', 'Cosmetic Dentistry'],
        details: ['Q1 review scheduled', 'Staffing update pending', 'Exceeding target', 'New equipment installed', 'Marketing push planned'] },
    },
    analyticsKpis: [{ label: 'New Patients (MTD)', value: 210, delta: 9 }, { label: 'Production per Chair', value: 42, suffix: 'k', delta: 4 }, { label: 'No-Show Rate', value: 6, suffix: '%', delta: -2 }, { label: 'Staff Retention', value: 91, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 1.0 }, { label: 'Feb', value: 1.05 }, { label: 'Mar', value: 1.1 }, { label: 'Apr', value: 1.15 }, { label: 'May', value: 1.2 }],
    sources: [{ label: 'Patient referral', value: 8 }, { label: 'Insurance network', value: 6 }, { label: 'Online booking', value: 4 }],
    rankedLabel: 'Production by location',
  },
]

export const batchSaas3 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: assembleConfig(spec),
}))
