import { assembleConfig } from '../lib/content-pool.mjs'

const specs = [
  {
    seed: 1901, name: 'Private Numismatics Dealer — Coin & Collection Suite', category: 'Creative', paletteId: 'gallery-red-light',
    appName: 'Corbridge Numismatics', tagline: 'Rare coins graded, sourced, and sold with real provenance.',
    loginQuote: 'Every coin, every collection, catalogued.', navIcon: 'Coins',
    primaryFeatureRoute: 'coins', primaryFeaturePascal: 'Coins', primaryFeatureLabel: 'Inventory', primaryFeatureSingular: 'Coin',
    greetingInsight: 'A rare 1804 dollar just cleared grading — 3 collectors are on the notification list.',
    dashboardVariant: 'activity', weeklyBase: 12,
    kpis: [
      { label: 'Coins in Inventory', value: 620, delta: 5 }, { label: 'Inventory Value', value: 3.1, suffix: 'M', delta: 6 },
      { label: 'Sales (MTD)', value: 62, suffix: 'k' }, { label: 'Avg. Days to Sale', value: 48, delta: -6 },
    ],
    primaryTable: {
      columns: ['Coin', 'Grade', 'Price', 'Status Detail'], filters: ['Grading', 'Available', 'Sold'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Grading', 'Available', 'Sold'],
        itemTypes: ['Rare Silver Dollar', 'Gold Eagle', 'Ancient Roman Coin', 'Commemorative Set', 'Territorial Gold'],
        details: ['$4,200', '$18,600', '$2,400', '$980', '$12,400'] },
    },
    analyticsKpis: [{ label: 'New Acquisitions', value: 6, delta: 10 }, { label: 'Sales Volume', value: 62, suffix: 'k', delta: 7 }, { label: 'Avg. Sale Price', value: 3.4, suffix: 'k', delta: 4 }, { label: 'Repeat Buyer Rate', value: 58, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 560 }, { label: 'Feb', value: 580 }, { label: 'Mar', value: 595 }, { label: 'Apr', value: 608 }, { label: 'May', value: 620 }],
    sources: [{ label: 'Auction purchase', value: 4 }, { label: 'Collector referral', value: 3 }, { label: 'Estate sale', value: 2 }],
    rankedLabel: 'Sales by grade tier',
  },
  {
    seed: 1902, name: 'Audio Mastering Studio — Session & Release Suite', category: 'Creative', paletteId: 'mono-dev-dark',
    appName: 'Blacktape Mastering', tagline: 'Masters that actually translate across every playback system.',
    loginQuote: 'Every session, every release, on schedule.', navIcon: 'Disc3',
    primaryFeatureRoute: 'sessions', primaryFeaturePascal: 'Sessions', primaryFeatureLabel: 'Sessions', primaryFeatureSingular: 'Session',
    greetingInsight: '6 masters are in the queue — 1 album releases to streaming Friday.',
    dashboardVariant: 'activity', weeklyBase: 10,
    kpis: [
      { label: 'Active Sessions', value: 14, delta: 12 }, { label: 'Avg. Turnaround', value: '3 days', delta: -15 },
      { label: 'Releases (MTD)', value: 22 }, { label: 'Repeat Client Rate', value: 74, suffix: '%', delta: 4 },
    ],
    primaryTable: {
      columns: ['Artist', 'Release Type', 'Engineer', 'Status Detail'], filters: ['Mastering', 'Revisions', 'Delivered'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Mastering', 'Revisions', 'Delivered'],
        itemTypes: ['Full Album Master', 'Single Master', 'EP Master', 'Vinyl Cut', 'Streaming Master'],
        details: ['First pass complete', 'Revision requested', 'Delivered to distributor', 'Reference approved', 'Loudness matched'] },
    },
    analyticsKpis: [{ label: 'New Sessions', value: 6, delta: 14 }, { label: 'Revenue (MTD)', value: 22, suffix: 'k', delta: 9 }, { label: 'Avg. Revisions', value: 1.2, delta: -10 }, { label: 'Distributor Deliveries', value: 18, delta: 6 }],
    trend: [{ label: 'Jan', value: 40 }, { label: 'Feb', value: 44 }, { label: 'Mar', value: 48 }, { label: 'Apr', value: 52 }, { label: 'May', value: 58 }],
    sources: [{ label: 'Producer referral', value: 5 }, { label: 'Label relationship', value: 3 }, { label: 'Repeat artist', value: 4 }],
    rankedLabel: 'Sessions by engineer',
  },
  {
    seed: 1903, name: 'Custom Motorcycle Fabrication — Build & Client Suite', category: 'Creative', paletteId: 'brutalist-light',
    appName: 'Ferrous Custom Motorworks', tagline: 'Builds fabricated in-house, not assembled from a catalog.',
    loginQuote: 'Every build, every client, on the bench.', navIcon: 'Bike',
    primaryFeatureRoute: 'builds', primaryFeaturePascal: 'Builds', primaryFeatureLabel: 'Builds', primaryFeatureSingular: 'Build',
    greetingInsight: '3 builds are on the bench — 1 custom frame clears inspection this week.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Builds', value: 5, delta: 25 }, { label: 'Avg. Build Value', value: 42, suffix: 'k', delta: 6 },
      { label: 'Avg. Build Time', value: '5 mo', delta: -8 }, { label: 'Waitlist', value: 9 },
    ],
    primaryTable: {
      columns: ['Client', 'Build Type', 'Fabricator', 'Status Detail'], filters: ['Fabrication', 'Assembly', 'Testing'],
      rowsSpec: { count: 5, subjectKind: 'person', statuses: ['Fabrication', 'Assembly', 'Testing'],
        itemTypes: ['Custom Chopper', 'Cafe Racer Build', 'Bobber Conversion', 'Full Frame-Up Restoration', 'Electric Conversion'],
        details: ['Frame fabricated', 'Engine assembly', 'Road testing', 'Paint in progress', 'Wiring harness built'] },
    },
    analyticsKpis: [{ label: 'New Builds', value: 1, delta: 0 }, { label: 'Revenue (MTD)', value: 84, suffix: 'k', delta: 8 }, { label: 'Waitlist Growth', value: 2, delta: 15 }, { label: 'Show Placements', value: 3, delta: 20 }],
    trend: [{ label: 'Jan', value: 4 }, { label: 'Feb', value: 4 }, { label: 'Mar', value: 5 }, { label: 'Apr', value: 5 }, { label: 'May', value: 5 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Show appearance', value: 2 }, { label: 'Repeat client', value: 1 }],
    rankedLabel: 'Builds by fabricator',
  },
  {
    seed: 1904, name: 'Private Tea House & Import Merchant — Sourcing & Wholesale Suite', category: 'Food', paletteId: 'food-amber-light',
    appName: 'Fernbrook Tea Merchants', tagline: 'Tea sourced direct from the estate, not blended from a broker lot.',
    loginQuote: 'Every lot, every estate, verified.', navIcon: 'Coffee',
    primaryFeatureRoute: 'lots', primaryFeaturePascal: 'Lots', primaryFeatureLabel: 'Tea Lots', primaryFeatureSingular: 'Lot',
    greetingInsight: 'A first-flush Darjeeling lot just cleared cupping — 4 wholesale accounts have standing orders.',
    dashboardVariant: 'activity', weeklyBase: 8,
    kpis: [
      { label: 'Wholesale Accounts', value: 34, delta: 6 }, { label: 'Active Lots', value: 22, delta: 4 },
      { label: 'Avg. Lot Value', value: 4.2, suffix: 'k', delta: 5 }, { label: 'Cupping Score Avg.', value: 91 },
    ],
    primaryTable: {
      columns: ['Lot', 'Estate', 'Buyer', 'Status Detail'], filters: ['Cupping', 'Available', 'Sold'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Cupping', 'Available', 'Sold'],
        itemTypes: ['First-Flush Darjeeling', 'Aged Pu-erh', 'Single-Estate Oolong', 'Rare White Tea', 'Ceremonial Matcha'],
        details: ['Cupping scheduled', 'Sample sent', 'Wholesale reorder', 'Cupping score 94', 'Sold to restaurant account'] },
    },
    analyticsKpis: [{ label: 'New Accounts', value: 2, delta: 8 }, { label: 'Revenue (MTD)', value: 38, suffix: 'k', delta: 6 }, { label: 'Avg. Cupping Score', value: 91, delta: 1 }, { label: 'Estate Relationships', value: 18, delta: 3 }],
    trend: [{ label: 'Jan', value: 28 }, { label: 'Feb', value: 29 }, { label: 'Mar', value: 31 }, { label: 'Apr', value: 32 }, { label: 'May', value: 34 }],
    sources: [{ label: 'Restaurant referral', value: 3 }, { label: 'Estate relationship', value: 2 }, { label: 'Trade show', value: 1 }],
    rankedLabel: 'Lots by estate',
  },
  {
    seed: 1905, name: 'Private Astronomy Observatory & Retreat — Booking & Membership Suite', category: 'Travel', paletteId: 'midnight-press-dark',
    appName: 'Highridge Observatory', tagline: 'Dark-sky nights run by astronomers, not a telescope rental counter.',
    loginQuote: 'Every session, every member, scheduled around the sky.', navIcon: 'Telescope',
    primaryFeatureRoute: 'sessions', primaryFeaturePascal: 'Sessions', primaryFeatureLabel: 'Sessions', primaryFeatureSingular: 'Session',
    greetingInsight: 'Tonight’s viewing conditions are excellent — 3 sessions are booked, one is a private member reservation.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Sessions (MTD)', value: 22, delta: 8 }, { label: 'Clear-Sky Rate', value: 68, suffix: '%', delta: 4 },
      { label: 'Active Members', value: 84, delta: 6 }, { label: 'Avg. Group Size', value: 6 },
    ],
    primaryTable: {
      columns: ['Guest', 'Session Type', 'Astronomer', 'Status Detail'], filters: ['Confirmed', 'Weather Watch', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Confirmed', 'Weather Watch', 'Completed'],
        itemTypes: ['Private Viewing Session', 'Member Night', 'Group Astrophotography', 'Meteor Shower Event', 'Planetary Viewing'],
        details: ['Confirmed for tonight', 'Monitoring forecast', 'Completed last week', 'Equipment reserved', 'Rebooked for clear sky'] },
    },
    analyticsKpis: [{ label: 'New Members', value: 4, delta: 12 }, { label: 'Revenue (MTD)', value: 18, suffix: 'k', delta: 8 }, { label: 'Weather Reschedules', value: 5, delta: -10 }, { label: 'Repeat Guest Rate', value: 42, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 70 }, { label: 'Feb', value: 74 }, { label: 'Mar', value: 78 }, { label: 'Apr', value: 81 }, { label: 'May', value: 84 }],
    sources: [{ label: 'Online booking', value: 4 }, { label: 'Member referral', value: 3 }, { label: 'Astronomy club', value: 2 }],
    rankedLabel: 'Sessions by astronomer',
  },
  {
    seed: 1906, name: 'Bladesmith Workshop — Commission & Forge Suite', category: 'Creative', paletteId: 'midnight-press-dark',
    appName: 'Ashgrove Forgeworks', tagline: 'Blades forged to order, tested before they ever ship.',
    loginQuote: 'Every commission, every forge session, tracked.', navIcon: 'Swords',
    primaryFeatureRoute: 'commissions', primaryFeaturePascal: 'Commissions', primaryFeatureLabel: 'Commissions', primaryFeatureSingular: 'Commission',
    greetingInsight: '4 blades are on the forge — 1 chef’s knife clears heat treatment this week.',
    dashboardVariant: 'activity', weeklyBase: 4,
    kpis: [
      { label: 'Active Commissions', value: 7, delta: 17 }, { label: 'Avg. Commission Value', value: 1.8, suffix: 'k', delta: 5 },
      { label: 'Waitlist', value: 22 }, { label: 'Repeat Client Rate', value: 56, suffix: '%', delta: 3 },
    ],
    primaryTable: {
      columns: ['Client', 'Blade Type', 'Bladesmith', 'Status Detail'], filters: ['Forging', 'Heat Treatment', 'Finishing'],
      rowsSpec: { count: 7, subjectKind: 'person', statuses: ['Forging', 'Heat Treatment', 'Finishing'],
        itemTypes: ['Custom Chef\'s Knife', 'Damascus Hunting Knife', 'Collector Sword', 'Custom EDC Knife', 'Kitchen Knife Set'],
        details: ['Forge welded', 'Quenching complete', 'Handle fitted', 'Edge sharpened', 'Sheath in progress'] },
    },
    analyticsKpis: [{ label: 'New Commissions', value: 2, delta: 10 }, { label: 'Revenue (MTD)', value: 12, suffix: 'k', delta: 5 }, { label: 'Avg. Turnaround', value: '6 wks', delta: -6 }, { label: 'Waitlist Growth', value: 3, delta: 12 }],
    trend: [{ label: 'Jan', value: 5 }, { label: 'Feb', value: 5 }, { label: 'Mar', value: 6 }, { label: 'Apr', value: 6 }, { label: 'May', value: 7 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Show appearance', value: 2 }, { label: 'Repeat client', value: 2 }],
    rankedLabel: 'Commissions by bladesmith',
  },
  {
    seed: 1907, name: 'Luxury Pen & Writing Instrument Atelier — Commission Suite', category: 'Creative', paletteId: 'ledger-ivory-light',
    appName: 'Aldercroft Pen Atelier', tagline: 'Pens turned and finished by hand, one at a time.',
    loginQuote: 'Every pen, every client, hand-finished.', navIcon: 'PenTool',
    primaryFeatureRoute: 'orders', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'Orders', primaryFeatureSingular: 'Order',
    greetingInsight: '6 pens are in finishing — a corporate gift order for 40 pens ships next week.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Active Orders', value: 11, delta: 10 }, { label: 'Avg. Order Value', value: 620, delta: 4 },
      { label: 'Corporate Accounts', value: 14, delta: 3 }, { label: 'Repeat Client Rate', value: 61, suffix: '%', delta: 3 },
    ],
    primaryTable: {
      columns: ['Client', 'Pen Type', 'Turner', 'Status Detail'], filters: ['Turning', 'Finishing', 'Engraving'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Turning', 'Finishing', 'Engraving'],
        itemTypes: ['Custom Fountain Pen', 'Corporate Gift Set', 'Limited Edition Pen', 'Rollerball Commission', 'Engraved Presentation Pen'],
        details: ['Body turned', 'Lacquer curing', 'Nib fitted', 'Engraving in progress', 'Ready for shipping'] },
    },
    analyticsKpis: [{ label: 'New Orders', value: 4, delta: 10 }, { label: 'Revenue (MTD)', value: 14, suffix: 'k', delta: 6 }, { label: 'Avg. Turnaround', value: '4 wks', delta: -5 }, { label: 'Corporate Orders', value: 3, delta: 15 }],
    trend: [{ label: 'Jan', value: 8 }, { label: 'Feb', value: 9 }, { label: 'Mar', value: 9 }, { label: 'Apr', value: 10 }, { label: 'May', value: 11 }],
    sources: [{ label: 'Corporate referral', value: 4 }, { label: 'Retail inquiry', value: 3 }, { label: 'Repeat client', value: 2 }],
    rankedLabel: 'Orders by turner',
  },
  {
    seed: 1908, name: 'Private Helicopter Charter — Flight & Client Suite', category: 'Logistics', paletteId: 'precision-sky-dark',
    appName: 'Aerolume Helicopter Charter', tagline: 'Every leg flown by a pilot who knows your schedule, not a dispatcher.',
    loginQuote: 'Every flight, every client, on schedule.', navIcon: 'Plane',
    primaryFeatureRoute: 'flights', primaryFeaturePascal: 'Flights', primaryFeatureLabel: 'Flights', primaryFeatureSingular: 'Flight',
    greetingInsight: '5 flights are scheduled this week — 1 landing zone requires updated clearance.',
    dashboardVariant: 'activity', weeklyBase: 9,
    kpis: [
      { label: 'Flights This Week', value: 5, delta: 8 }, { label: 'Fleet Utilization', value: 72, suffix: '%', delta: 3 },
      { label: 'On-Time Rate', value: 97, suffix: '%', delta: 1 }, { label: 'Active Clients', value: 28, delta: 4 },
    ],
    primaryTable: {
      columns: ['Client', 'Route', 'Pilot', 'Status Detail'], filters: ['Scheduled', 'In Flight', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Scheduled', 'In Flight', 'Completed'],
        itemTypes: ['Airport Transfer', 'Sightseeing Charter', 'Corporate Shuttle', 'Event Transport', 'Medical Transport'],
        details: ['Departs tomorrow', 'Currently airborne', 'Landed on time', 'Landing zone confirmed', 'Ground transport arranged'] },
    },
    analyticsKpis: [{ label: 'New Clients', value: 2, delta: 8 }, { label: 'Revenue (MTD)', value: 84, suffix: 'k', delta: 6 }, { label: 'Avg. Flight Value', value: 4.2, suffix: 'k', delta: 3 }, { label: 'Weather Delays', value: 2, delta: -10 }],
    trend: [{ label: 'Jan', value: 20 }, { label: 'Feb', value: 22 }, { label: 'Mar', value: 24 }, { label: 'Apr', value: 26 }, { label: 'May', value: 28 }],
    sources: [{ label: 'Corporate referral', value: 2 }, { label: 'Concierge referral', value: 2 }, { label: 'Repeat client', value: 1 }],
    rankedLabel: 'Flights by pilot',
  },
  {
    seed: 1909, name: 'Artisan Stone & Masonry Restoration — Project Suite', category: 'Creative', paletteId: 'clay-sand-light',
    appName: 'Ashgrove Stoneworks', tagline: 'Stonework restored the way it was originally cut, not patched with cement.',
    loginQuote: 'Every stone, every project, matched to the original.', navIcon: 'Hammer',
    primaryFeatureRoute: 'projects', primaryFeaturePascal: 'Projects', primaryFeatureLabel: 'Projects', primaryFeatureSingular: 'Project',
    greetingInsight: '3 restorations are underway — the chapel facade repointing finishes this month.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Projects', value: 5, delta: 25 }, { label: 'Avg. Project Value', value: 180, suffix: 'k', delta: 6 },
      { label: 'Stone Sourced (MTD)', value: '12 tons' }, { label: 'On-Schedule Rate', value: 82, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Client', 'Structure Type', 'Mason', 'Phase'], filters: ['Assessment', 'Restoration', 'Repointing'],
      rowsSpec: { count: 5, subjectKind: 'company', statuses: ['Assessment', 'Restoration', 'Repointing'],
        itemTypes: ['Historic Chapel Facade', 'Estate Stone Wall', 'Manor House Restoration', 'Bridge Masonry', 'Monument Restoration'],
        details: ['Stone matched', 'Repointing underway', 'Final cleaning', 'Structural assessment', 'Permit approved'] },
    },
    analyticsKpis: [{ label: 'New Projects', value: 1, delta: 0 }, { label: 'Revenue (MTD)', value: 48, suffix: 'k', delta: 6 }, { label: 'Avg. Timeline', value: '6 mo', delta: -4 }, { label: 'Heritage Approvals', value: 2, delta: 10 }],
    trend: [{ label: 'Jan', value: 4 }, { label: 'Feb', value: 4 }, { label: 'Mar', value: 5 }, { label: 'Apr', value: 5 }, { label: 'May', value: 5 }],
    sources: [{ label: 'Heritage society referral', value: 2 }, { label: 'Architect referral', value: 2 }, { label: 'Repeat client', value: 1 }],
    rankedLabel: 'Projects by mason',
  },
  {
    seed: 1910, name: 'Rare Spirits Auction House — Lot & Bidder Suite', category: 'Creative', paletteId: 'supper-club-dark',
    appName: 'Corbridge Spirits Auctions', tagline: 'Rare bottles authenticated and auctioned, not flipped on a forum.',
    loginQuote: 'Every lot, every bidder, verified.', navIcon: 'Gavel',
    primaryFeatureRoute: 'lots', primaryFeaturePascal: 'Lots', primaryFeatureLabel: 'Lots', primaryFeatureSingular: 'Lot',
    greetingInsight: 'The autumn auction closes Friday — 3 lots have reached reserve.',
    dashboardVariant: 'highlights', weeklyBase: 14,
    highlights: [
      { title: 'Autumn Auction', description: '84 lots live, closing Friday at 6 PM — 3 have already reached reserve.' },
      { title: 'Top Lot Watch', description: 'A 1970s single-cask Macallan is drawing the most bidder interest this cycle.' },
      { title: 'New Consignments', description: '12 new lots added this week from a private collector consignment.' },
    ],
    kpis: [
      { label: 'Live Lots', value: 84, delta: 8 }, { label: 'Registered Bidders', value: 620, delta: 12 },
      { label: 'Avg. Hammer Price', value: 2.8, suffix: 'k', delta: 6 }, { label: 'Reserve Met Rate', value: 74, suffix: '%', delta: 3 },
    ],
    primaryTable: {
      columns: ['Lot', 'Category', 'Current Bid', 'Status Detail'], filters: ['Live', 'Reserve Met', 'Closing Soon'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Live', 'Reserve Met', 'Closing Soon'],
        itemTypes: ['Single-Cask Whisky', 'Vintage Cognac', 'Rare Rum', 'Limited Release Bourbon', 'Aged Armagnac'],
        details: ['$1,800 current bid', 'Reserve met', 'Closes in 2 hours', '12 bids placed', 'New consignment'] },
    },
    analyticsKpis: [{ label: 'New Consignments', value: 12, delta: 15 }, { label: 'Auction Revenue', value: 240, suffix: 'k', delta: 10 }, { label: 'New Bidders', value: 24, delta: 8 }, { label: 'Avg. Bids/Lot', value: 9, delta: 5 }],
    trend: [{ label: 'Jan', value: 520 }, { label: 'Feb', value: 540 }, { label: 'Mar', value: 565 }, { label: 'Apr', value: 590 }, { label: 'May', value: 620 }],
    sources: [{ label: 'Collector consignment', value: 6 }, { label: 'Estate sale', value: 3 }, { label: 'Distillery partnership', value: 3 }],
    rankedLabel: 'Lots by category',
  },
]

export const batchSaas10 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: assembleConfig(spec),
}))
