import { assembleConfig } from '../lib/content-pool.mjs'

const specs = [
  {
    seed: 1501, name: 'Boutique Ski Chalet Rental Group — Property Suite', category: 'RealEstate', paletteId: 'open-air-light',
    appName: 'Ridgeline Alpine Chalets', tagline: 'Chalets managed to hotel standard, without the hotel.',
    loginQuote: 'Every chalet, every guest, ready.', navIcon: 'Mountain',
    primaryFeatureRoute: 'chalets', primaryFeaturePascal: 'Chalets', primaryFeatureLabel: 'Chalets', primaryFeatureSingular: 'Chalet',
    greetingInsight: 'Peak season occupancy is at 94% — 3 turnovers are scheduled for tomorrow.',
    dashboardVariant: 'activity', weeklyBase: 12,
    kpis: [
      { label: 'Managed Chalets', value: 18, delta: 6 }, { label: 'Occupancy Rate', value: 94, suffix: '%', delta: 4 },
      { label: 'Avg. Nightly Rate', value: 620, delta: 5 }, { label: 'Repeat Guest Rate', value: 51, suffix: '%', delta: 3 },
    ],
    primaryTable: {
      columns: ['Guest', 'Chalet', 'Property Manager', 'Stay Detail'], filters: ['Confirmed', 'In Stay', 'Checked Out'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Confirmed', 'In Stay', 'Checked Out'],
        itemTypes: ['Alpine Lodge', 'Summit Chalet', 'Pinecrest Cabin', 'Ridgeview Retreat', 'Timberline House'],
        details: ['Check-in Friday', 'Checkout tomorrow', 'Turned over today', 'Check-in Saturday', 'Extended stay'] },
    },
    analyticsKpis: [{ label: 'New Bookings', value: 14, delta: 12 }, { label: 'Revenue (MTD)', value: 210, suffix: 'k', delta: 9 }, { label: 'Avg. Stay Length', value: '5.2 nights', delta: 3 }, { label: 'Cancellation Rate', value: 3, suffix: '%', delta: -2 }],
    trend: [{ label: 'Jan', value: 82 }, { label: 'Feb', value: 86 }, { label: 'Mar', value: 89 }, { label: 'Apr', value: 91 }, { label: 'May', value: 94 }],
    sources: [{ label: 'Direct booking', value: 9 }, { label: 'Travel advisor', value: 6 }, { label: 'Repeat guest', value: 4 }],
    rankedLabel: 'Bookings by property manager',
  },
  {
    seed: 1502, name: 'Fine Jewelry Atelier — Commission & Client Suite', category: 'Creative', paletteId: 'luxury-gold-dark',
    appName: 'Aldercroft Jewelers', tagline: 'Jewelry made once, for the person it is made for.',
    loginQuote: 'Every commission, every stone, verified.', navIcon: 'Gem',
    primaryFeatureRoute: 'commissions', primaryFeaturePascal: 'Commissions', primaryFeatureLabel: 'Commissions', primaryFeatureSingular: 'Commission',
    greetingInsight: '3 commissions enter final setting this week — 2 clients are scheduled for design review.',
    dashboardVariant: 'activity', weeklyBase: 4,
    kpis: [
      { label: 'Active Commissions', value: 14, delta: 9 }, { label: 'Avg. Commission Value', value: 18, suffix: 'k', delta: 6 },
      { label: 'On-Time Delivery', value: 90, suffix: '%', delta: 2 }, { label: 'Stones Sourced (MTD)', value: 22 },
    ],
    primaryTable: {
      columns: ['Client', 'Piece Type', 'Jeweler', 'Stage'], filters: ['Design', 'Setting', 'Delivered'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Design', 'Setting', 'Delivered'],
        itemTypes: ['Engagement Ring', 'Anniversary Band', 'Custom Necklace', 'Heirloom Redesign', 'Bespoke Earrings'],
        details: ['Design review Thursday', 'Stone setting in progress', 'Delivered last week', 'CAD model approved', 'Casting complete'] },
    },
    analyticsKpis: [{ label: 'New Commissions', value: 4, delta: 15 }, { label: 'Revenue (MTD)', value: 84, suffix: 'k', delta: 10 }, { label: 'Avg. Timeline', value: '6 wks', delta: -6 }, { label: 'Client Satisfaction', value: 98, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 10 }, { label: 'Feb', value: 11 }, { label: 'Mar', value: 12 }, { label: 'Apr', value: 13 }, { label: 'May', value: 14 }],
    sources: [{ label: 'Referral', value: 6 }, { label: 'Repeat client', value: 5 }, { label: 'Trunk show', value: 3 }],
    rankedLabel: 'Commissions by jeweler',
  },
  {
    seed: 1503, name: 'Corporate Board Governance Advisory — Engagement Suite', category: 'Legal', paletteId: 'counsel-navy-light',
    appName: 'Ashworth Governance Advisors', tagline: 'Board governance advisory for companies who take the fiduciary duty seriously.',
    loginQuote: 'Every board, every review, documented.', navIcon: 'Landmark',
    primaryFeatureRoute: 'engagements', primaryFeaturePascal: 'Engagements', primaryFeatureLabel: 'Engagements', primaryFeatureSingular: 'Engagement',
    greetingInsight: '2 board evaluations are due this month — the Halden Logistics governance review completes Friday.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Engagements', value: 9, delta: 12 }, { label: 'Avg. Engagement Value', value: 62, suffix: 'k', delta: 5 },
      { label: 'Board Evaluations (YTD)', value: 14, delta: 8 }, { label: 'Client Retention', value: 92, suffix: '%', delta: 1 },
    ],
    primaryTable: {
      columns: ['Client', 'Engagement Type', 'Lead Advisor', 'Status Detail'], filters: ['Active', 'Review', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Review', 'Completed'],
        itemTypes: ['Board Evaluation', 'Governance Audit', 'Succession Planning', 'Committee Structure Review', 'Director Onboarding'],
        details: ['Interviews underway', 'Report in review', 'Completed last month', 'Recommendations drafted', 'Board briefing scheduled'] },
    },
    analyticsKpis: [{ label: 'New Engagements', value: 2, delta: 10 }, { label: 'Board Evaluations', value: 4, delta: 5 }, { label: 'Avg. Engagement Length', value: '3 mo', delta: -5 }, { label: 'Referral Rate', value: 68, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 6 }, { label: 'Feb', value: 7 }, { label: 'Mar', value: 8 }, { label: 'Apr', value: 8 }, { label: 'May', value: 9 }],
    sources: [{ label: 'Board referral', value: 4 }, { label: 'Law firm referral', value: 3 }, { label: 'Repeat client', value: 2 }],
    rankedLabel: 'Engagements by advisor',
  },
  {
    seed: 1504, name: 'Boutique Ceramics & Pottery Studio — Order Suite', category: 'Creative', paletteId: 'clay-sand-light',
    appName: 'Fernbrook Ceramics Studio', tagline: 'Tableware thrown one piece at a time, not molded a thousand.',
    loginQuote: 'Every order, every kiln firing, on schedule.', navIcon: 'Flower2',
    primaryFeatureRoute: 'orders', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'Orders', primaryFeatureSingular: 'Order',
    greetingInsight: 'The wholesale order for Coppermill Café fires this week — 2 custom sets are ready for glazing.',
    dashboardVariant: 'activity', weeklyBase: 8,
    kpis: [
      { label: 'Active Orders', value: 19, delta: 10 }, { label: 'Avg. Order Value', value: 1.4, suffix: 'k', delta: 6 },
      { label: 'Kiln Utilization', value: 78, suffix: '%', delta: 5 }, { label: 'Wholesale Accounts', value: 14, delta: 2 },
    ],
    primaryTable: {
      columns: ['Client', 'Order Type', 'Potter', 'Stage'], filters: ['Throwing', 'Glazing', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Throwing', 'Glazing', 'Completed'],
        itemTypes: ['Custom Dinnerware Set', 'Wholesale Restaurant Order', 'Wedding Registry Set', 'Gallery Consignment', 'Single Commission Piece'],
        details: ['Throwing this week', 'Glazing in progress', 'Fired and delivered', 'Bisque fired', 'Awaiting glaze selection'] },
    },
    analyticsKpis: [{ label: 'New Orders', value: 5, delta: 12 }, { label: 'Revenue (MTD)', value: 22, suffix: 'k', delta: 8 }, { label: 'Avg. Turnaround', value: '4 wks', delta: -5 }, { label: 'Wholesale Growth', value: 14, suffix: '%', delta: 6 }],
    trend: [{ label: 'Jan', value: 14 }, { label: 'Feb', value: 15 }, { label: 'Mar', value: 17 }, { label: 'Apr', value: 18 }, { label: 'May', value: 19 }],
    sources: [{ label: 'Wholesale account', value: 6 }, { label: 'Referral', value: 4 }, { label: 'Craft fair', value: 3 }],
    rankedLabel: 'Orders by potter',
  },
  {
    seed: 1505, name: 'Private Aviation Maintenance Facility — Service Suite', category: 'Logistics', paletteId: 'precision-ember-dark',
    appName: 'Kestrel Ridge MRO', tagline: 'Aircraft maintenance for owners who read the logbook.',
    loginQuote: 'Every aircraft, every inspection, logged.', navIcon: 'Plane',
    primaryFeatureRoute: 'services', primaryFeaturePascal: 'Services', primaryFeatureLabel: 'Service Orders', primaryFeatureSingular: 'Service Order',
    greetingInsight: '4 aircraft are in the hangar this week — 2 annual inspections complete Friday.',
    dashboardVariant: 'activity', weeklyBase: 5,
    kpis: [
      { label: 'Active Service Orders', value: 11, delta: 8 }, { label: 'Hangar Capacity Used', value: 82, suffix: '%', delta: 4 },
      { label: 'Avg. Turnaround', value: '9 days', delta: -6 }, { label: 'On-Time Completion', value: 94, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Aircraft', 'Service Type', 'Lead Technician', 'Status Detail'], filters: ['In Progress', 'Awaiting Parts', 'Complete'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['In Progress', 'Awaiting Parts', 'Complete'],
        itemTypes: ['Annual Inspection', 'Engine Overhaul', 'Avionics Upgrade', 'Airframe Repair', 'Scheduled Maintenance'],
        details: ['Inspection underway', 'Parts on order', 'Completed yesterday', 'Test flight scheduled', 'Awaiting sign-off'] },
    },
    analyticsKpis: [{ label: 'New Service Orders', value: 3, delta: 10 }, { label: 'Revenue (MTD)', value: 210, suffix: 'k', delta: 8 }, { label: 'Avg. Days in Hangar', value: 9, delta: -8 }, { label: 'Customer Retention', value: 89, suffix: '%', delta: 2 }],
    trend: [{ label: 'Jan', value: 8 }, { label: 'Feb', value: 9 }, { label: 'Mar', value: 10 }, { label: 'Apr', value: 10 }, { label: 'May', value: 11 }],
    sources: [{ label: 'Owner referral', value: 4 }, { label: 'Fleet contract', value: 4 }, { label: 'FBO referral', value: 2 }],
    rankedLabel: 'Service orders by technician',
  },
  {
    seed: 1506, name: 'Boutique Perfumery & Fragrance House — Client Suite', category: 'Creative', paletteId: 'creative-coral-light',
    appName: 'Ferrous & Bloom Perfumery', tagline: 'Fragrance composed to the client, not blended off a shelf.',
    loginQuote: 'Every scent, every client, composed.', navIcon: 'Flower',
    primaryFeatureRoute: 'commissions', primaryFeaturePascal: 'Commissions', primaryFeatureLabel: 'Commissions', primaryFeatureSingular: 'Commission',
    greetingInsight: '3 bespoke fragrances are in final composition — 1 client approves their scent this week.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Commissions', value: 8, delta: 14 }, { label: 'Avg. Commission Value', value: 2.4, suffix: 'k', delta: 6 },
      { label: 'Client Retention', value: 82, suffix: '%', delta: 3 }, { label: 'Formulas in Library', value: 340 },
    ],
    primaryTable: {
      columns: ['Client', 'Fragrance Type', 'Perfumer', 'Stage'], filters: ['Composing', 'Client Review', 'Delivered'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Composing', 'Client Review', 'Delivered'],
        itemTypes: ['Bespoke Eau de Parfum', 'Signature Scent', 'Home Fragrance Line', 'Gift Collection', 'Wedding Fragrance'],
        details: ['Composition round 2', 'Awaiting client approval', 'Delivered last month', 'Sample sent', 'Final formula locked'] },
    },
    analyticsKpis: [{ label: 'New Commissions', value: 2, delta: 15 }, { label: 'Revenue (MTD)', value: 18, suffix: 'k', delta: 9 }, { label: 'Avg. Timeline', value: '8 wks', delta: -4 }, { label: 'Repeat Client Rate', value: 58, suffix: '%', delta: 5 }],
    trend: [{ label: 'Jan', value: 5 }, { label: 'Feb', value: 6 }, { label: 'Mar', value: 6 }, { label: 'Apr', value: 7 }, { label: 'May', value: 8 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Repeat client', value: 3 }, { label: 'Boutique inquiry', value: 2 }],
    rankedLabel: 'Commissions by perfumer',
  },
  {
    seed: 1507, name: 'Private Aircraft Charter Brokerage — Booking Suite', category: 'Logistics', paletteId: 'precision-sky-dark',
    appName: 'Meridian Charter Brokerage', tagline: 'The right aircraft, sourced across the whole market, not just one fleet.',
    loginQuote: 'Every trip, every operator, vetted.', navIcon: 'Plane',
    primaryFeatureRoute: 'trips', primaryFeaturePascal: 'Trips', primaryFeatureLabel: 'Trips', primaryFeatureSingular: 'Trip',
    greetingInsight: '6 trips are confirmed this week — 2 quotes are awaiting client approval.',
    dashboardVariant: 'activity', weeklyBase: 9,
    kpis: [
      { label: 'Active Trips', value: 16, delta: 10 }, { label: 'Operators in Network', value: 84, delta: 4 },
      { label: 'Avg. Trip Value', value: 42, suffix: 'k', delta: 6 }, { label: 'Client Retention', value: 87, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Client', 'Route', 'Broker', 'Status Detail'], filters: ['Confirmed', 'Quoting', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Confirmed', 'Quoting', 'Completed'],
        itemTypes: ['New York – London', 'Los Angeles – Tokyo', 'Miami – São Paulo', 'Chicago – Aspen', 'Dallas – Cabo'],
        details: ['Aircraft confirmed', 'Awaiting quote approval', 'Completed last week', 'Operator sourcing', 'Contract signed'] },
    },
    analyticsKpis: [{ label: 'New Trips', value: 5, delta: 12 }, { label: 'Booking Revenue', value: 280, suffix: 'k', delta: 10 }, { label: 'Avg. Time to Quote', value: '2h', delta: -15 }, { label: 'Repeat Client Rate', value: 71, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 12 }, { label: 'Feb', value: 13 }, { label: 'Mar', value: 14 }, { label: 'Apr', value: 15 }, { label: 'May', value: 16 }],
    sources: [{ label: 'Repeat client', value: 6 }, { label: 'Referral', value: 5 }, { label: 'Corporate account', value: 3 }],
    rankedLabel: 'Trips by broker',
  },
  {
    seed: 1508, name: 'Executive Office & Workspace Provider — Member Suite', category: 'RealEstate', paletteId: 'saas-indigo-dark',
    appName: 'Aldergate Executive Suites', tagline: 'Office space run to the standard our members expect, every floor.',
    loginQuote: 'Every member, every space, ready.', navIcon: 'Building2',
    primaryFeatureRoute: 'members', primaryFeaturePascal: 'Members', primaryFeatureLabel: 'Members', primaryFeatureSingular: 'Member',
    greetingInsight: 'Occupancy is at 89% across all floors — 2 members are due for lease renewal this month.',
    dashboardVariant: 'activity', weeklyBase: 15,
    kpis: [
      { label: 'Active Members', value: 84, delta: 6 }, { label: 'Occupancy Rate', value: 89, suffix: '%', delta: 3 },
      { label: 'Avg. Membership Value', value: 2.8, suffix: 'k', delta: 4 }, { label: 'Renewal Rate', value: 86, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Member Company', 'Suite Type', 'Community Manager', 'Status Detail'], filters: ['Active', 'Renewal Due', 'Onboarding'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Renewal Due', 'Onboarding'],
        itemTypes: ['Private Office Suite', 'Team Office', 'Dedicated Desk', 'Virtual Membership', 'Executive Suite'],
        details: ['Lease active', 'Renewal due Mar 15', 'Onboarding this week', 'Auto-renewed', 'Move-in scheduled'] },
    },
    analyticsKpis: [{ label: 'New Members', value: 6, delta: 10 }, { label: 'Revenue (MTD)', value: 240, suffix: 'k', delta: 5 }, { label: 'Avg. Tenure', value: '2.4 yrs', delta: 3 }, { label: 'Member Satisfaction', value: 93, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 76 }, { label: 'Feb', value: 78 }, { label: 'Mar', value: 80 }, { label: 'Apr', value: 82 }, { label: 'May', value: 84 }],
    sources: [{ label: 'Referral', value: 4 }, { label: 'Broker referral', value: 3 }, { label: 'Online inquiry', value: 2 }],
    rankedLabel: 'Members by community manager',
  },
  {
    seed: 1509, name: 'Private Chef Culinary School — Cohort Suite', category: 'Education', paletteId: 'food-amber-light',
    appName: 'Ferrous Culinary Academy', tagline: 'Culinary training for people who intend to actually run a kitchen.',
    loginQuote: 'Every student, every cohort, tracked.', navIcon: 'ChefHat',
    primaryFeatureRoute: 'students', primaryFeaturePascal: 'Students', primaryFeatureLabel: 'Students', primaryFeatureSingular: 'Student',
    greetingInsight: 'The spring cohort is 84% enrolled — 2 students complete their externship this week.',
    dashboardVariant: 'activity', weeklyBase: 10,
    kpis: [
      { label: 'Active Students', value: 42, delta: 8 }, { label: 'Cohort Fill Rate', value: 84, suffix: '%', delta: 5 },
      { label: 'Job Placement Rate', value: 91, suffix: '%', delta: 2 }, { label: 'Externship Partners', value: 22, delta: 3 },
    ],
    primaryTable: {
      columns: ['Student', 'Program', 'Chef Instructor', 'Status Detail'], filters: ['Active', 'Externship', 'Graduated'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Externship', 'Graduated'],
        itemTypes: ['Culinary Arts Certificate', 'Pastry Certificate', 'Restaurant Management', 'Wine & Beverage', 'Advanced Techniques'],
        details: ['Class this week', 'Externship at partner restaurant', 'Graduated last month', 'Practical exam scheduled', 'Placement in progress'] },
    },
    analyticsKpis: [{ label: 'New Enrollments', value: 8, delta: 12 }, { label: 'Tuition Revenue', value: 140, suffix: 'k', delta: 7 }, { label: 'Avg. Program Length', value: '9 mo', delta: 0 }, { label: 'Employer Partners', value: 22, delta: 3 }],
    trend: [{ label: 'Jan', value: 34 }, { label: 'Feb', value: 37 }, { label: 'Mar', value: 39 }, { label: 'Apr', value: 41 }, { label: 'May', value: 42 }],
    sources: [{ label: 'Referral', value: 6 }, { label: 'Open house', value: 5 }, { label: 'Industry partner', value: 3 }],
    rankedLabel: 'Students by chef instructor',
  },
  {
    seed: 1510, name: 'Luxury Car Dealership & Concierge — Client Suite', category: 'RealEstate', paletteId: 'luxury-gold-dark',
    appName: 'Ashcombe Motorcars', tagline: 'Vehicles sourced for the client, not off the lot.',
    loginQuote: 'Every client, every vehicle, sourced.', navIcon: 'Car',
    primaryFeatureRoute: 'clients', primaryFeaturePascal: 'Clients', primaryFeatureLabel: 'Clients', primaryFeatureSingular: 'Client',
    greetingInsight: '3 vehicles arrive for client delivery this week — 2 sourcing requests are active.',
    dashboardVariant: 'activity', weeklyBase: 5,
    kpis: [
      { label: 'Active Clients', value: 22, delta: 9 }, { label: 'Avg. Vehicle Value', value: 180, suffix: 'k', delta: 5 },
      { label: 'Sourcing Success Rate', value: 88, suffix: '%', delta: 3 }, { label: 'Deliveries (MTD)', value: 6 },
    ],
    primaryTable: {
      columns: ['Client', 'Vehicle', 'Sales Advisor', 'Status Detail'], filters: ['Sourcing', 'In Transit', 'Delivered'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Sourcing', 'In Transit', 'Delivered'],
        itemTypes: ['Vintage Sports Coupe', 'Luxury SUV', 'Limited Edition Roadster', 'Classic Restoration', 'Custom Performance Sedan'],
        details: ['Sourcing across network', 'In transit — 1 week', 'Delivered yesterday', 'Inspection scheduled', 'Financing finalized'] },
    },
    analyticsKpis: [{ label: 'New Clients', value: 4, delta: 12 }, { label: 'Sales Volume', value: 1.1, suffix: 'M', delta: 9 }, { label: 'Avg. Sourcing Time', value: '3 wks', delta: -8 }, { label: 'Repeat Client Rate', value: 62, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 16 }, { label: 'Feb', value: 18 }, { label: 'Mar', value: 19 }, { label: 'Apr', value: 21 }, { label: 'May', value: 22 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Repeat client', value: 4 }, { label: 'Auction network', value: 2 }],
    rankedLabel: 'Sales by advisor',
  },
]

export const batchSaas6 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: assembleConfig(spec),
}))
