import { assembleConfig } from '../lib/content-pool.mjs'

const specs = [
  {
    seed: 1801, name: 'Private Falconry School — Student & Certification Suite', category: 'Education', paletteId: 'precision-ember-dark',
    appName: 'Blackwood Falconry Academy', tagline: 'Falconry taught by licensed master falconers, not a weekend course.',
    loginQuote: 'Every apprentice, every certification, tracked.', navIcon: 'GraduationCap',
    primaryFeatureRoute: 'apprentices', primaryFeaturePascal: 'Apprentices', primaryFeatureLabel: 'Apprentices', primaryFeatureSingular: 'Apprentice',
    greetingInsight: '6 apprentices are active this season — 2 complete their general falconer exam this month.',
    dashboardVariant: 'activity', weeklyBase: 4,
    kpis: [
      { label: 'Active Apprentices', value: 14, delta: 8 }, { label: 'Certification Rate', value: 88, suffix: '%', delta: 3 },
      { label: 'Avg. Program Length', value: '2 yrs', delta: 0 }, { label: 'Birds in Training Program', value: 22 },
    ],
    primaryTable: {
      columns: ['Apprentice', 'License Level', 'Sponsor Falconer', 'Status Detail'], filters: ['Active', 'Exam Scheduled', 'Certified'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Exam Scheduled', 'Certified'],
        itemTypes: ['General Falconer', 'Apprentice Falconer', 'Master Falconer Track', 'Raptor Handling Certificate', 'Wildlife Rehabilitation'],
        details: ['Field hours logged', 'Exam next month', 'Certified last season', 'Mentor review scheduled', 'Practical test passed'] },
    },
    analyticsKpis: [{ label: 'New Apprentices', value: 2, delta: 12 }, { label: 'Field Hours Logged', value: 340, delta: 8 }, { label: 'Exams Passed', value: 4, delta: 20 }, { label: 'Program Revenue', value: 22, suffix: 'k', delta: 5 }],
    trend: [{ label: 'Jan', value: 10 }, { label: 'Feb', value: 11 }, { label: 'Mar', value: 12 }, { label: 'Apr', value: 13 }, { label: 'May', value: 14 }],
    sources: [{ label: 'Referral', value: 4 }, { label: 'Falconry club', value: 3 }, { label: 'Wildlife agency referral', value: 2 }],
    rankedLabel: 'Apprentices by sponsor',
  },
  {
    seed: 1802, name: 'Private Rare Book & Manuscript Dealer — Inventory Suite', category: 'Creative', paletteId: 'paper-oxblood-light',
    appName: 'Aldergate Rare Books', tagline: 'Rare books sourced, authenticated, and sold with real provenance.',
    loginQuote: 'Every volume, every provenance, verified.', navIcon: 'BookOpen',
    primaryFeatureRoute: 'volumes', primaryFeaturePascal: 'Volumes', primaryFeatureLabel: 'Inventory', primaryFeatureSingular: 'Volume',
    greetingInsight: '2 volumes sold this week — a new estate library acquisition arrives Thursday.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Volumes in Inventory', value: 340, delta: 4 }, { label: 'Inventory Value', value: 2.4, suffix: 'M', delta: 5 },
      { label: 'Sales (MTD)', value: 84, suffix: 'k' }, { label: 'Avg. Days to Sale', value: 62, delta: -6 },
    ],
    primaryTable: {
      columns: ['Volume', 'Category', 'Price', 'Status Detail'], filters: ['Available', 'Authenticating', 'Sold'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Available', 'Authenticating', 'Sold'],
        itemTypes: ['First Edition Novel', 'Illuminated Manuscript', 'Signed Author Copy', 'Antiquarian Atlas', 'Scientific First Edition'],
        details: ['$8,400', '$42,000', '$3,200', '$14,800', '$6,600'] },
    },
    analyticsKpis: [{ label: 'New Acquisitions', value: 4, delta: 10 }, { label: 'Sales Volume', value: 84, suffix: 'k', delta: 8 }, { label: 'Avg. Sale Price', value: 9.2, suffix: 'k', delta: 4 }, { label: 'Repeat Buyer Rate', value: 52, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 310 }, { label: 'Feb', value: 318 }, { label: 'Mar', value: 325 }, { label: 'Apr', value: 332 }, { label: 'May', value: 340 }],
    sources: [{ label: 'Estate library', value: 3 }, { label: 'Auction purchase', value: 2 }, { label: 'Private collector', value: 1 }],
    rankedLabel: 'Sales by category',
  },
  {
    seed: 1803, name: 'Boutique Pipe Organ Restoration Firm — Project Suite', category: 'Creative', paletteId: 'midnight-press-dark',
    appName: 'Aldergate Organ Works', tagline: 'Pipe organs restored to play in the room they were built for.',
    loginQuote: 'Every instrument, every pipe, voiced correctly.', navIcon: 'Music',
    primaryFeatureRoute: 'restorations', primaryFeaturePascal: 'Restorations', primaryFeatureLabel: 'Restorations', primaryFeatureSingular: 'Restoration',
    greetingInsight: 'The cathedral organ restoration enters final voicing this month — 2 pipe ranks remain.',
    dashboardVariant: 'activity', weeklyBase: 2,
    kpis: [
      { label: 'Active Restorations', value: 4, delta: 33 }, { label: 'Avg. Project Value', value: 120, suffix: 'k', delta: 6 },
      { label: 'On-Time Completion', value: 82, suffix: '%', delta: 2 }, { label: 'Pipe Ranks Voiced (MTD)', value: 18 },
    ],
    primaryTable: {
      columns: ['Client', 'Instrument Type', 'Organ Builder', 'Stage'], filters: ['Disassembly', 'Restoration', 'Voicing'],
      rowsSpec: { count: 4, subjectKind: 'company', statuses: ['Disassembly', 'Restoration', 'Voicing'],
        itemTypes: ['Cathedral Pipe Organ', 'Church Organ', 'Concert Hall Organ', 'Chamber Organ'],
        details: ['Pipe cleaning underway', 'Wind chest rebuild', 'Final voicing', 'Console restoration'] },
    },
    analyticsKpis: [{ label: 'New Restorations', value: 1, delta: 0 }, { label: 'Revenue (MTD)', value: 62, suffix: 'k', delta: 8 }, { label: 'Avg. Timeline', value: '14 mo', delta: -4 }, { label: 'Client Satisfaction', value: 98, suffix: '%' }],
    trend: [{ label: 'Jan', value: 3 }, { label: 'Feb', value: 3 }, { label: 'Mar', value: 4 }, { label: 'Apr', value: 4 }, { label: 'May', value: 4 }],
    sources: [{ label: 'Diocese referral', value: 2 }, { label: 'Repeat client', value: 1 }],
    rankedLabel: 'Restorations by builder',
  },
  {
    seed: 1804, name: 'Private Truffle Foraging & Distribution Company — Harvest Suite', category: 'Food', paletteId: 'forest-market-light',
    appName: 'Fernbrook Truffle Co.', tagline: 'Truffles foraged and delivered the same day, not flown in stale.',
    loginQuote: 'Every hunt, every delivery, fresh.', navIcon: 'Leaf',
    primaryFeatureRoute: 'accounts', primaryFeaturePascal: 'Accounts', primaryFeatureLabel: 'Restaurant Accounts', primaryFeatureSingular: 'Account',
    greetingInsight: 'Today’s harvest is 4.2 lbs — 6 restaurant accounts have standing daily orders.',
    dashboardVariant: 'activity', weeklyBase: 15,
    kpis: [
      { label: 'Restaurant Accounts', value: 22, delta: 6 }, { label: "Today's Harvest", value: '4.2 lbs' },
      { label: 'Avg. Daily Yield', value: '3.8 lbs', delta: 4 }, { label: 'Foraging Dogs Active', value: 4 },
    ],
    primaryTable: {
      columns: ['Restaurant', 'Order Type', 'Forager', 'Status Detail'], filters: ['Standing Order', 'Special Order', 'Delivered'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Standing Order', 'Special Order', 'Delivered'],
        itemTypes: ['Black Truffle Order', 'White Truffle Order', 'Truffle Oil Supply', 'Event Order', 'Tasting Menu Supply'],
        details: ['Daily delivery', 'Special event order', 'Delivered this morning', 'Weekly order', 'Seasonal supply'] },
    },
    analyticsKpis: [{ label: 'New Accounts', value: 2, delta: 10 }, { label: 'Revenue (MTD)', value: 42, suffix: 'k', delta: 12 }, { label: 'Avg. Price/lb', value: 680, delta: 5 }, { label: 'Yield Trend', value: '+8%', delta: 8 }],
    trend: [{ label: 'Jan', value: 16 }, { label: 'Feb', value: 18 }, { label: 'Mar', value: 20 }, { label: 'Apr', value: 21 }, { label: 'May', value: 22 }],
    sources: [{ label: 'Chef referral', value: 4 }, { label: 'Distributor partner', value: 2 }],
    rankedLabel: 'Yield by forager',
  },
  {
    seed: 1805, name: 'Private Hot Air Balloon Tour Company — Flight Suite', category: 'Logistics', paletteId: 'open-air-light',
    appName: 'Ridgeline Balloon Adventures', tagline: 'Sunrise flights planned around the weather, not the calendar.',
    loginQuote: 'Every flight, every passenger, briefed.', navIcon: 'Wind',
    primaryFeatureRoute: 'flights', primaryFeaturePascal: 'Flights', primaryFeatureLabel: 'Flights', primaryFeatureSingular: 'Flight',
    greetingInsight: 'Tomorrow’s sunrise flight is weather-confirmed — 6 passengers are booked.',
    dashboardVariant: 'activity', weeklyBase: 8,
    kpis: [
      { label: 'Flights (MTD)', value: 18, delta: 6 }, { label: 'Weather Cancellation Rate', value: 12, suffix: '%', delta: -4 },
      { label: 'Avg. Passengers/Flight', value: 6, delta: 0 }, { label: 'Pilot Hours (MTD)', value: 42 },
    ],
    primaryTable: {
      columns: ['Passenger', 'Flight Type', 'Pilot', 'Status Detail'], filters: ['Confirmed', 'Weather Watch', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Confirmed', 'Weather Watch', 'Completed'],
        itemTypes: ['Sunrise Flight', 'Private Charter', 'Proposal Flight', 'Group Tour', 'Sunset Flight'],
        details: ['Weather confirmed', 'Monitoring forecast', 'Completed yesterday', 'Champagne toast arranged', 'Rebooked for weather'] },
    },
    analyticsKpis: [{ label: 'New Bookings', value: 8, delta: 14 }, { label: 'Revenue (MTD)', value: 22, suffix: 'k', delta: 9 }, { label: 'Weather Reschedules', value: 3, delta: -20 }, { label: 'Repeat Passenger Rate', value: 24, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 12 }, { label: 'Feb', value: 14 }, { label: 'Mar', value: 16 }, { label: 'Apr', value: 17 }, { label: 'May', value: 18 }],
    sources: [{ label: 'Online booking', value: 6 }, { label: 'Referral', value: 3 }, { label: 'Hotel concierge partner', value: 2 }],
    rankedLabel: 'Flights by pilot',
  },
  {
    seed: 1806, name: 'Private Cigar Blending & Rolling House — Order Suite', category: 'Food', paletteId: 'supper-club-dark',
    appName: 'Aldercroft Cigar House', tagline: 'Cigars rolled to order, not stocked off a shelf.',
    loginQuote: 'Every blend, every roll, custom.', navIcon: 'Flame',
    primaryFeatureRoute: 'orders', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'Orders', primaryFeatureSingular: 'Order',
    greetingInsight: 'The wedding order for 200 custom-banded cigars ships Friday — 2 blend samples await approval.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Active Orders', value: 14, delta: 8 }, { label: 'Avg. Order Value', value: 1.8, suffix: 'k', delta: 5 },
      { label: 'Custom Blends (MTD)', value: 22 }, { label: 'Retail Accounts', value: 18, delta: 2 },
    ],
    primaryTable: {
      columns: ['Client', 'Order Type', 'Roller', 'Status Detail'], filters: ['Rolling', 'Aging', 'Shipped'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Rolling', 'Aging', 'Shipped'],
        itemTypes: ['Custom Wedding Order', 'Private Blend', 'Corporate Gift Order', 'Retail Restock', 'Anniversary Order'],
        details: ['Rolling this week', 'Aging in cedar', 'Shipped yesterday', 'Blend sample sent', 'Custom bands printed'] },
    },
    analyticsKpis: [{ label: 'New Orders', value: 4, delta: 10 }, { label: 'Revenue (MTD)', value: 28, suffix: 'k', delta: 6 }, { label: 'Avg. Turnaround', value: '3 wks', delta: -4 }, { label: 'Repeat Client Rate', value: 54, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 10 }, { label: 'Feb', value: 11 }, { label: 'Mar', value: 12 }, { label: 'Apr', value: 13 }, { label: 'May', value: 14 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Lounge partnership', value: 3 }, { label: 'Repeat client', value: 2 }],
    rankedLabel: 'Orders by roller',
  },
  {
    seed: 1807, name: 'Private Botanical Garden Design Firm — Project Suite', category: 'Creative', paletteId: 'forest-market-light',
    appName: 'Fernbrook Botanical Design', tagline: 'Gardens designed with the same rigor as a botanical collection.',
    loginQuote: 'Every garden, every specimen, documented.', navIcon: 'Flower2',
    primaryFeatureRoute: 'projects', primaryFeaturePascal: 'Projects', primaryFeatureLabel: 'Projects', primaryFeatureSingular: 'Project',
    greetingInsight: '4 gardens are in active planting — the Whitmore botanical collection completes this month.',
    dashboardVariant: 'highlights', weeklyBase: 4,
    highlights: [
      { title: 'Whitmore Collection', description: 'Rare specimen planting complete — irrigation testing this week.' },
      { title: 'Marchbanks Conservatory', description: 'Climate control systems installed.' },
      { title: 'Coppermill Estate', description: 'Design finalized, permits submitted.' },
    ],
    kpis: [
      { label: 'Active Projects', value: 9, delta: 12 }, { label: 'Avg. Project Value', value: 140, suffix: 'k', delta: 6 },
      { label: 'Rare Specimens Sourced', value: 84, delta: 8 }, { label: 'On-Schedule Rate', value: 84, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Client', 'Garden Type', 'Botanical Designer', 'Phase'], filters: ['Design', 'Planting', 'Complete'],
      rowsSpec: { count: 8, subjectKind: 'person', statuses: ['Design', 'Planting', 'Complete'],
        itemTypes: ['Rare Specimen Collection', 'Conservatory Design', 'Native Meadow Restoration', 'Formal Botanical Garden', 'Water Garden'],
        details: ['Specimen sourcing', 'Planting underway', 'Completed last season', 'Irrigation design', 'Permit submitted'] },
    },
    analyticsKpis: [{ label: 'New Projects', value: 2, delta: 15 }, { label: 'Specimen Spend', value: 62, suffix: 'k', delta: 8 }, { label: 'Avg. Timeline', value: '8 mo', delta: -5 }, { label: 'Client Satisfaction', value: 97, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 6 }, { label: 'Feb', value: 7 }, { label: 'Mar', value: 7 }, { label: 'Apr', value: 8 }, { label: 'May', value: 9 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Architect partner', value: 3 }, { label: 'Botanical society', value: 1 }],
    rankedLabel: 'Projects by designer',
  },
  {
    seed: 1808, name: 'Private Falconry Equipment Maker — Custom Order Suite', category: 'Creative', paletteId: 'clay-sand-light',
    appName: 'Aldergate Falconry Goods', tagline: 'Hoods, jesses, and gauntlets, hand-made to the bird.',
    loginQuote: 'Every piece, every falconer, fitted.', navIcon: 'Feather',
    primaryFeatureRoute: 'orders', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'Orders', primaryFeatureSingular: 'Order',
    greetingInsight: '9 custom orders are in production — 2 gauntlets ship Friday.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Active Orders', value: 16, delta: 9 }, { label: 'Avg. Order Value', value: 340, delta: 5 },
      { label: 'Leather Sourced (MTD)', value: '84 sq ft' }, { label: 'Repeat Customer Rate', value: 68, suffix: '%', delta: 4 },
    ],
    primaryTable: {
      columns: ['Client', 'Item Type', 'Leatherworker', 'Status Detail'], filters: ['Cutting', 'Stitching', 'Shipped'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Cutting', 'Stitching', 'Shipped'],
        itemTypes: ['Custom Gauntlet', 'Hand-Stitched Hood', 'Leather Jesses', 'Falconry Bag', 'Perch Equipment'],
        details: ['Pattern cut', 'Hand-stitching', 'Shipped yesterday', 'Measurements confirmed', 'Fitting scheduled'] },
    },
    analyticsKpis: [{ label: 'New Orders', value: 5, delta: 12 }, { label: 'Revenue (MTD)', value: 18, suffix: 'k', delta: 8 }, { label: 'Avg. Turnaround', value: '3 wks', delta: -4 }, { label: 'Repeat Rate', value: 68, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 12 }, { label: 'Feb', value: 13 }, { label: 'Mar', value: 14 }, { label: 'Apr', value: 15 }, { label: 'May', value: 16 }],
    sources: [{ label: 'Falconry club', value: 6 }, { label: 'Referral', value: 4 }, { label: 'Repeat client', value: 3 }],
    rankedLabel: 'Orders by leatherworker',
  },
  {
    seed: 1809, name: 'Private Beekeeping & Apiary Management Firm — Hive Suite', category: 'Food', paletteId: 'food-amber-light',
    appName: 'Fernbrook Apiary Management', tagline: 'Hives managed like a real agricultural operation, not a hobby.',
    loginQuote: 'Every hive, every yield, tracked.', navIcon: 'Flower',
    primaryFeatureRoute: 'hives', primaryFeaturePascal: 'Hives', primaryFeatureLabel: 'Hives', primaryFeatureSingular: 'Hive',
    greetingInsight: 'Spring inspections are complete across 84 hives — honey extraction begins next month.',
    dashboardVariant: 'activity', weeklyBase: 40,
    kpis: [
      { label: 'Managed Hives', value: 84, delta: 4 }, { label: 'Hive Health Rate', value: 92, suffix: '%', delta: 3 },
      { label: 'Honey Yield (YTD)', value: '2,400 lbs', delta: 6 }, { label: 'Client Apiaries', value: 22, delta: 3 },
    ],
    primaryTable: {
      columns: ['Client', 'Hive Count', 'Beekeeper', 'Status Detail'], filters: ['Healthy', 'Under Treatment', 'New Install'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Healthy', 'Under Treatment', 'New Install'],
        itemTypes: ['Residential Apiary', 'Commercial Farm Apiary', 'Vineyard Pollination Contract', 'Orchard Pollination', 'Educational Apiary'],
        details: ['Inspection current', 'Mite treatment applied', 'Installed this week', 'Queen replaced', 'Honey extraction scheduled'] },
    },
    analyticsKpis: [{ label: 'New Apiaries', value: 2, delta: 8 }, { label: 'Honey Sold', value: 12, suffix: 'k', delta: 6 }, { label: 'Hive Losses', value: 3, suffix: '%', delta: -2 }, { label: 'Pollination Contracts', value: 6, delta: 20 }],
    trend: [{ label: 'Jan', value: 76 }, { label: 'Feb', value: 78 }, { label: 'Mar', value: 80 }, { label: 'Apr', value: 82 }, { label: 'May', value: 84 }],
    sources: [{ label: 'Farm referral', value: 3 }, { label: 'Vineyard contract', value: 2 }, { label: 'Residential inquiry', value: 1 }],
    rankedLabel: 'Hives by beekeeper',
  },
  {
    seed: 1810, name: 'Private Antique Clock & Automata Restoration — Workshop Suite', category: 'Creative', paletteId: 'paper-oxblood-light',
    appName: 'Aldergate Clockworks', tagline: 'Mechanisms restored to run, not just to display.',
    loginQuote: 'Every mechanism, every restoration, timed precisely.', navIcon: 'Watch',
    primaryFeatureRoute: 'restorations', primaryFeaturePascal: 'Restorations', primaryFeatureLabel: 'Restorations', primaryFeatureSingular: 'Restoration',
    greetingInsight: '4 mechanisms are in active restoration — 1 automaton clears final testing this week.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Restorations', value: 7, delta: 8 }, { label: 'Avg. Restoration Value', value: 8.4, suffix: 'k', delta: 5 },
      { label: 'On-Time Completion', value: 86, suffix: '%', delta: 2 }, { label: 'Workshop Hours (MTD)', value: 210 },
    ],
    primaryTable: {
      columns: ['Client', 'Mechanism Type', 'Clockmaker', 'Stage'], filters: ['Disassembly', 'Restoration', 'Testing'],
      rowsSpec: { count: 8, subjectKind: 'person', statuses: ['Disassembly', 'Restoration', 'Testing'],
        itemTypes: ['Antique Automaton', 'Grandfather Clock', 'Mantel Clock', 'Musical Automaton', 'Pocket Watch'],
        details: ['Movement disassembled', 'Gear train rebuild', 'Final testing', 'Case refinishing', 'Escapement adjusted'] },
    },
    analyticsKpis: [{ label: 'New Restorations', value: 2, delta: 10 }, { label: 'Revenue (MTD)', value: 24, suffix: 'k', delta: 6 }, { label: 'Avg. Timeline', value: '3 mo', delta: -6 }, { label: 'Client Satisfaction', value: 97, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 5 }, { label: 'Feb', value: 5 }, { label: 'Mar', value: 6 }, { label: 'Apr', value: 6 }, { label: 'May', value: 7 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Auction house partner', value: 2 }, { label: 'Repeat client', value: 2 }],
    rankedLabel: 'Restorations by clockmaker',
  },
]

export const batchSaas9 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: assembleConfig(spec),
}))
