import { assembleConfig } from '../lib/content-pool.mjs'

const specs = [
  {
    seed: 1601, name: 'Private Equestrian Facility — Boarding & Lesson Suite', category: 'RealEstate', paletteId: 'clay-sand-light',
    appName: 'Birchwood Equestrian Center', tagline: 'Horses boarded and trained to the standard the owner actually expects.',
    loginQuote: 'Every horse, every rider, cared for.', navIcon: 'PawPrint',
    primaryFeatureRoute: 'horses', primaryFeaturePascal: 'Horses', primaryFeatureLabel: 'Horses', primaryFeatureSingular: 'Horse',
    greetingInsight: '34 horses are boarded this month — 2 lesson evaluations are scheduled this week.',
    dashboardVariant: 'activity', weeklyBase: 20,
    kpis: [
      { label: 'Horses Boarded', value: 34, delta: 3 }, { label: 'Lesson Students', value: 42, delta: 6 },
      { label: 'Stall Occupancy', value: 89, suffix: '%', delta: 2 }, { label: 'Training Revenue (MTD)', value: 28, suffix: 'k' },
    ],
    primaryTable: {
      columns: ['Horse', 'Boarding Type', 'Trainer', 'Status Detail'], filters: ['Active', 'Training', 'New Arrival'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Training', 'New Arrival'],
        itemTypes: ['Full Boarding', 'Training Board', 'Pasture Boarding', 'Lesson Horse Program', 'Retirement Boarding'],
        details: ['Farrier scheduled', 'Training session Thursday', 'Arrived this week', 'Vet check current', 'Turnout schedule updated'] },
    },
    analyticsKpis: [{ label: 'New Boarders', value: 2, delta: 10 }, { label: 'Lesson Revenue', value: 14, suffix: 'k', delta: 6 }, { label: 'Show Placements', value: 6, delta: 20 }, { label: 'Client Retention', value: 88, suffix: '%', delta: 2 }],
    trend: [{ label: 'Jan', value: 30 }, { label: 'Feb', value: 31 }, { label: 'Mar', value: 32 }, { label: 'Apr', value: 33 }, { label: 'May', value: 34 }],
    sources: [{ label: 'Referral', value: 4 }, { label: 'Horse show connection', value: 3 }, { label: 'Trainer network', value: 2 }],
    rankedLabel: 'Horses by trainer',
  },
  {
    seed: 1602, name: 'Private Vineyard Management Firm — Estate Suite', category: 'Food', paletteId: 'forest-market-light',
    appName: 'Fernbrook Vineyard Management', tagline: 'Managing other people’s vineyards like they were our own.',
    loginQuote: 'Every block, every harvest, planned.', navIcon: 'Grape',
    primaryFeatureRoute: 'estates', primaryFeaturePascal: 'Estates', primaryFeatureLabel: 'Managed Estates', primaryFeatureSingular: 'Estate',
    greetingInsight: 'Bud break is complete across 4 estates — 2 spring spray schedules are due this week.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Managed Estates', value: 11, delta: 8 }, { label: 'Acres Under Management', value: 420, delta: 4 },
      { label: 'Avg. Yield (tons/acre)', value: 3.8, delta: 3 }, { label: 'Harvest Readiness', value: 62, suffix: '%' },
    ],
    primaryTable: {
      columns: ['Estate', 'Varietal Focus', 'Vineyard Manager', 'Status Detail'], filters: ['Active', 'Spray Scheduled', 'Harvest'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Spray Scheduled', 'Harvest'],
        itemTypes: ['Pinot Noir Block', 'Cabernet Sauvignon Block', 'Chardonnay Block', 'Syrah Block', 'Mixed Varietal Estate'],
        details: ['Canopy management underway', 'Spray scheduled Friday', 'Harvest projected Sept', 'Soil testing complete', 'Irrigation adjusted'] },
    },
    analyticsKpis: [{ label: 'New Estates', value: 1, delta: 10 }, { label: 'Management Revenue', value: 84, suffix: 'k', delta: 6 }, { label: 'Avg. Brix at Harvest', value: 24.2, delta: 2 }, { label: 'Client Retention', value: 91, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 9 }, { label: 'Feb', value: 9 }, { label: 'Mar', value: 10 }, { label: 'Apr', value: 10 }, { label: 'May', value: 11 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Winemaker network', value: 2 }, { label: 'Repeat client', value: 1 }],
    rankedLabel: 'Acres by manager',
  },
  {
    seed: 1603, name: 'Corporate Art Advisory & Curation Firm — Collection Suite', category: 'Creative', paletteId: 'gallery-red-light',
    appName: 'Verrier Corporate Art Advisory', tagline: 'Corporate art collections curated with the same rigor as a museum.',
    loginQuote: 'Every collection, every placement, documented.', navIcon: 'Palette',
    primaryFeatureRoute: 'collections', primaryFeaturePascal: 'Collections', primaryFeatureLabel: 'Collections', primaryFeatureSingular: 'Collection',
    greetingInsight: '2 corporate collections are in active acquisition — the Halden Logistics lobby installation completes Friday.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Collections', value: 6, delta: 20 }, { label: 'Works Under Management', value: 340, delta: 8 },
      { label: 'Collection Value', value: 12, suffix: 'M', delta: 6 }, { label: 'Client Retention', value: 94, suffix: '%', delta: 1 },
    ],
    primaryTable: {
      columns: ['Client', 'Collection Focus', 'Curator', 'Status Detail'], filters: ['Active', 'Acquiring', 'Installed'],
      rowsSpec: { count: 8, subjectKind: 'company', statuses: ['Active', 'Acquiring', 'Installed'],
        itemTypes: ['Corporate Lobby Collection', 'Executive Floor Collection', 'Rotating Exhibition Program', 'Regional Office Collection', 'Headquarters Collection'],
        details: ['Acquisition in progress', 'Installation Friday', 'Annual rotation planned', 'Curatorial review complete', 'Budget approved'] },
    },
    analyticsKpis: [{ label: 'New Collections', value: 1, delta: 15 }, { label: 'Works Acquired', value: 22, delta: 10 }, { label: 'Avg. Collection Value', value: 2, suffix: 'M', delta: 5 }, { label: 'Client Retention', value: 94, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 4 }, { label: 'Feb', value: 5 }, { label: 'Mar', value: 5 }, { label: 'Apr', value: 6 }, { label: 'May', value: 6 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Architect partner', value: 2 }, { label: 'Repeat client', value: 1 }],
    rankedLabel: 'Collections by curator',
  },
  {
    seed: 1604, name: 'Private Diving & Marine Expedition Company — Trip Suite', category: 'Logistics', paletteId: 'precision-sky-dark',
    appName: 'Meridian Marine Expeditions', tagline: 'Dive expeditions planned by people who have actually done the dive.',
    loginQuote: 'Every expedition, every diver, briefed.', navIcon: 'Anchor',
    primaryFeatureRoute: 'expeditions', primaryFeaturePascal: 'Expeditions', primaryFeatureLabel: 'Expeditions', primaryFeatureSingular: 'Expedition',
    greetingInsight: '3 expeditions are booked this month — the Red Sea trip departs in 2 weeks.',
    dashboardVariant: 'activity', weeklyBase: 4,
    kpis: [
      { label: 'Active Expeditions', value: 6, delta: 20 }, { label: 'Divers Booked', value: 42, delta: 12 },
      { label: 'Avg. Trip Value', value: 8.4, suffix: 'k', delta: 5 }, { label: 'Repeat Diver Rate', value: 58, suffix: '%', delta: 4 },
    ],
    primaryTable: {
      columns: ['Diver', 'Expedition', 'Dive Master', 'Status Detail'], filters: ['Confirmed', 'Waitlisted', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Confirmed', 'Waitlisted', 'Completed'],
        itemTypes: ['Red Sea Expedition', 'Galapagos Expedition', 'Palau Expedition', 'Great Barrier Reef Expedition', 'Cenote Expedition'],
        details: ['Departs in 2 weeks', 'Waitlist position 2', 'Completed last month', 'Deposit received', 'Gear check scheduled'] },
    },
    analyticsKpis: [{ label: 'New Bookings', value: 8, delta: 18 }, { label: 'Revenue (MTD)', value: 62, suffix: 'k', delta: 10 }, { label: 'Avg. Group Size', value: 8, delta: 2 }, { label: 'Safety Incidents', value: 0 }],
    trend: [{ label: 'Jan', value: 3 }, { label: 'Feb', value: 4 }, { label: 'Mar', value: 5 }, { label: 'Apr', value: 5 }, { label: 'May', value: 6 }],
    sources: [{ label: 'Repeat diver', value: 5 }, { label: 'Referral', value: 3 }, { label: 'Dive club partner', value: 2 }],
    rankedLabel: 'Bookings by dive master',
  },
  {
    seed: 1605, name: 'High-End Kitchen & Bath Remodeling Firm — Project Suite', category: 'Creative', paletteId: 'brutalist-light',
    appName: 'Aldergate Remodeling', tagline: 'Kitchens and baths rebuilt without the six-month horror story.',
    loginQuote: 'Every project, every trade, coordinated.', navIcon: 'Hammer',
    primaryFeatureRoute: 'projects', primaryFeaturePascal: 'Projects', primaryFeatureLabel: 'Projects', primaryFeatureSingular: 'Project',
    greetingInsight: '4 projects are in active construction — the Whitmore kitchen passes final inspection this week.',
    dashboardVariant: 'highlights', weeklyBase: 5,
    highlights: [
      { title: 'Whitmore Kitchen', description: 'Final inspection scheduled — cabinetry install complete.' },
      { title: 'Marchbanks Bath', description: 'Tile work begins Monday.' },
      { title: 'Coppermill Kitchen', description: 'Design finalized, permits submitted.' },
    ],
    kpis: [
      { label: 'Active Projects', value: 12, delta: 9 }, { label: 'Avg. Project Budget', value: 96, suffix: 'k', delta: 5 },
      { label: 'On-Budget Rate', value: 86, suffix: '%', delta: 3 }, { label: 'Subcontractors Active', value: 22 },
    ],
    primaryTable: {
      columns: ['Client', 'Project Type', 'Project Manager', 'Phase'], filters: ['Design', 'Construction', 'Complete'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Design', 'Construction', 'Complete'],
        itemTypes: ['Full Kitchen Remodel', 'Primary Bath Remodel', 'Kitchen & Bath Combo', 'Basement Renovation', 'Addition & Remodel'],
        details: ['Design finalized', 'Framing underway', 'Completed last month', 'Permit submitted', 'Final walkthrough scheduled'] },
    },
    analyticsKpis: [{ label: 'New Projects', value: 3, delta: 12 }, { label: 'Revenue (MTD)', value: 210, suffix: 'k', delta: 8 }, { label: 'Avg. Timeline', value: '12 wks', delta: -5 }, { label: 'Client Satisfaction', value: 92, suffix: '%', delta: 2 }],
    trend: [{ label: 'Jan', value: 8 }, { label: 'Feb', value: 9 }, { label: 'Mar', value: 10 }, { label: 'Apr', value: 11 }, { label: 'May', value: 12 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Designer partner', value: 4 }, { label: 'Repeat client', value: 3 }],
    rankedLabel: 'Projects by manager',
  },
  {
    seed: 1606, name: 'Boutique Cigar & Spirits Lounge — Membership Suite', category: 'Food', paletteId: 'supper-club-dark',
    appName: 'Ashcombe Lounge', tagline: 'A members’ lounge run like the club it actually is.',
    loginQuote: 'Every member, every reservation, remembered.', navIcon: 'Flame',
    primaryFeatureRoute: 'members', primaryFeaturePascal: 'Members', primaryFeatureLabel: 'Members', primaryFeatureSingular: 'Member',
    greetingInsight: 'Member reservations are up 9% this month — 2 private humidor lockers are available.',
    dashboardVariant: 'activity', weeklyBase: 20,
    kpis: [
      { label: 'Active Members', value: 210, delta: 6 }, { label: 'Humidor Lockers Filled', value: 88, suffix: '%', delta: 4 },
      { label: 'Reservations (MTD)', value: 84, delta: 9 }, { label: 'Member Retention', value: 91, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Member', 'Membership Tier', 'Host', 'Status Detail'], filters: ['Active', 'Renewal Due', 'New'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Renewal Due', 'New'],
        itemTypes: ['Founding Member', 'Full Member', 'Corporate Membership', 'Social Membership', 'Reciprocal Member'],
        details: ['Locker assigned', 'Renews in 2 weeks', 'Onboarding this week', 'Auto-renewed', 'Guest privileges active'] },
    },
    analyticsKpis: [{ label: 'New Members', value: 6, delta: 10 }, { label: 'Revenue (MTD)', value: 62, suffix: 'k', delta: 6 }, { label: 'Avg. Visit Frequency', value: '2.4/wk', delta: 3 }, { label: 'Waitlist', value: 14, delta: 8 }],
    trend: [{ label: 'Jan', value: 190 }, { label: 'Feb', value: 196 }, { label: 'Mar', value: 200 }, { label: 'Apr', value: 205 }, { label: 'May', value: 210 }],
    sources: [{ label: 'Member referral', value: 4 }, { label: 'Waitlist conversion', value: 2 }, { label: 'Reciprocal club', value: 1 }],
    rankedLabel: 'Reservations by host',
  },
  {
    seed: 1607, name: 'Private Museum & Estate Collection — Curatorial Suite', category: 'Creative', paletteId: 'paper-oxblood-light',
    appName: 'Aldergate Estate Collection', tagline: 'A private collection catalogued to museum standard.',
    loginQuote: 'Every object, every provenance, documented.', navIcon: 'Landmark',
    primaryFeatureRoute: 'objects', primaryFeaturePascal: 'Objects', primaryFeatureLabel: 'Collection', primaryFeatureSingular: 'Object',
    greetingInsight: 'Conservation review is complete for 4 objects this month — 2 loans are pending approval.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Cataloged Objects', value: 420, delta: 2 }, { label: 'Collection Value', value: 18, suffix: 'M', delta: 4 },
      { label: 'Objects on Loan', value: 6, delta: 0 }, { label: 'Conservation Reviews (MTD)', value: 4 },
    ],
    primaryTable: {
      columns: ['Object', 'Category', 'Curator', 'Status Detail'], filters: ['Cataloged', 'Under Review', 'On Loan'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Cataloged', 'Under Review', 'On Loan'],
        itemTypes: ['18th Century Painting', 'Bronze Sculpture', 'Rare Manuscript', 'Decorative Arts Piece', 'Historical Furniture'],
        details: ['Fully cataloged', 'Conservation review', 'On loan to museum', 'Provenance verified', 'Insurance appraisal current'] },
    },
    analyticsKpis: [{ label: 'New Acquisitions', value: 2, delta: 5 }, { label: 'Conservation Spend', value: 42, suffix: 'k', delta: 8 }, { label: 'Loan Requests', value: 3, delta: 10 }, { label: 'Appraisal Updates', value: 6, delta: 4 }],
    trend: [{ label: 'Jan', value: 410 }, { label: 'Feb', value: 412 }, { label: 'Mar', value: 415 }, { label: 'Apr', value: 418 }, { label: 'May', value: 420 }],
    sources: [{ label: 'Estate acquisition', value: 1 }, { label: 'Auction purchase', value: 1 }],
    rankedLabel: 'Objects by curator',
  },
  {
    seed: 1608, name: 'Corporate Flight Department — Operations Suite', category: 'Logistics', paletteId: 'precision-ember-dark',
    appName: 'Halden Industries Flight Ops', tagline: 'A corporate flight department run to airline-grade standards.',
    loginQuote: 'Every flight, every crew, scheduled.', navIcon: 'Plane',
    primaryFeatureRoute: 'flights', primaryFeaturePascal: 'Flights', primaryFeatureLabel: 'Flights', primaryFeatureSingular: 'Flight',
    greetingInsight: '6 flights are scheduled this week — crew duty limits are within compliance on all legs.',
    dashboardVariant: 'activity', weeklyBase: 8,
    kpis: [
      { label: 'Flights (MTD)', value: 24, delta: 6 }, { label: 'Dispatch Reliability', value: 99, suffix: '%', delta: 1 },
      { label: 'Crew Duty Compliance', value: 100, suffix: '%' }, { label: 'Aircraft Utilization', value: 68, suffix: '%', delta: 4 },
    ],
    primaryTable: {
      columns: ['Executive', 'Route', 'Captain', 'Status Detail'], filters: ['Scheduled', 'En Route', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Scheduled', 'En Route', 'Completed'],
        itemTypes: ['HQ – Regional Office', 'HQ – Client Site', 'HQ – Board Meeting', 'HQ – Conference', 'Regional – Regional'],
        details: ['Departs Thursday', 'Currently en route', 'Completed yesterday', 'Crew briefed', 'Flight plan filed'] },
    },
    analyticsKpis: [{ label: 'New Flights', value: 6, delta: 8 }, { label: 'Flight Hours', value: 84, delta: 5 }, { label: 'On-Time Departure', value: 97, suffix: '%', delta: 1 }, { label: 'Maintenance Events', value: 1, delta: -20 }],
    trend: [{ label: 'Jan', value: 20 }, { label: 'Feb', value: 21 }, { label: 'Mar', value: 22 }, { label: 'Apr', value: 23 }, { label: 'May', value: 24 }],
    sources: [{ label: 'Executive request', value: 18 }, { label: 'Board meeting', value: 4 }, { label: 'Client visit', value: 2 }],
    rankedLabel: 'Flight hours by captain',
  },
  {
    seed: 1609, name: 'Private Golf Club — Member & Course Suite', category: 'RealEstate', paletteId: 'forest-market-light',
    appName: 'Birchwood Golf Club', tagline: 'Tee times and member services run without the pro shop phone tag.',
    loginQuote: 'Every member, every tee time, confirmed.', navIcon: 'Flag',
    primaryFeatureRoute: 'members', primaryFeaturePascal: 'Members', primaryFeatureLabel: 'Members', primaryFeatureSingular: 'Member',
    greetingInsight: 'Course utilization is at 76% this week — 2 member events are scheduled this weekend.',
    dashboardVariant: 'activity', weeklyBase: 30,
    kpis: [
      { label: 'Active Members', value: 340, delta: 3 }, { label: 'Course Utilization', value: 76, suffix: '%', delta: 5 },
      { label: 'Tee Times (MTD)', value: 620, delta: 6 }, { label: 'Member Retention', value: 92, suffix: '%', delta: 1 },
    ],
    primaryTable: {
      columns: ['Member', 'Membership Tier', 'Pro Shop Lead', 'Status Detail'], filters: ['Active', 'Renewal Due', 'New'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Renewal Due', 'New'],
        itemTypes: ['Full Golf Membership', 'Social Membership', 'Junior Membership', 'Corporate Membership', 'Weekday Membership'],
        details: ['Tee time booked', 'Renews next month', 'Onboarding this week', 'Auto-renewed', 'Handicap updated'] },
    },
    analyticsKpis: [{ label: 'New Members', value: 5, delta: 8 }, { label: 'Tee Times', value: 620, delta: 6 }, { label: 'Pro Shop Revenue', value: 34, suffix: 'k', delta: 4 }, { label: 'Waitlist', value: 22, delta: 12 }],
    trend: [{ label: 'Jan', value: 320 }, { label: 'Feb', value: 326 }, { label: 'Mar', value: 330 }, { label: 'Apr', value: 335 }, { label: 'May', value: 340 }],
    sources: [{ label: 'Member referral', value: 3 }, { label: 'Waitlist', value: 2 }],
    rankedLabel: 'Tee times by pro shop lead',
  },
  {
    seed: 1610, name: 'Boutique Watch & Timepiece Dealer — Inventory Suite', category: 'Creative', paletteId: 'gallery-red-light',
    appName: 'Aldercroft Timepieces', tagline: 'Watches sourced, authenticated, and sold with real paperwork.',
    loginQuote: 'Every timepiece, every authentication, verified.', navIcon: 'Watch',
    primaryFeatureRoute: 'pieces', primaryFeaturePascal: 'Pieces', primaryFeatureLabel: 'Inventory', primaryFeatureSingular: 'Piece',
    greetingInsight: '2 timepieces sold this week — a new consignment arrives Thursday for authentication.',
    dashboardVariant: 'activity', weeklyBase: 4,
    kpis: [
      { label: 'Pieces in Inventory', value: 68, delta: 5 }, { label: 'Inventory Value', value: 3.4, suffix: 'M', delta: 6 },
      { label: 'Sales (MTD)', value: 180, suffix: 'k' }, { label: 'Avg. Days to Sale', value: 34, delta: -8 },
    ],
    primaryTable: {
      columns: ['Timepiece', 'Brand', 'Price', 'Status Detail'], filters: ['Available', 'Authenticating', 'Sold'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Available', 'Authenticating', 'Sold'],
        itemTypes: ['Vintage Chronograph', 'Limited Edition Diver', 'Classic Dress Watch', 'Sports Model', 'Rare Complication'],
        details: ['$28,000', '$42,000', '$14,500', '$19,800', '$68,000'] },
    },
    analyticsKpis: [{ label: 'New Consignments', value: 4, delta: 10 }, { label: 'Sales Volume', value: 180, suffix: 'k', delta: 8 }, { label: 'Avg. Sale Price', value: 22, suffix: 'k', delta: 5 }, { label: 'Repeat Buyer Rate', value: 48, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 58 }, { label: 'Feb', value: 61 }, { label: 'Mar', value: 64 }, { label: 'Apr', value: 66 }, { label: 'May', value: 68 }],
    sources: [{ label: 'Private consignment', value: 4 }, { label: 'Auction purchase', value: 3 }, { label: 'Repeat client', value: 2 }],
    rankedLabel: 'Sales by brand',
  },
]

export const batchSaas7 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: assembleConfig(spec),
}))
