import { assembleConfig } from '../lib/content-pool.mjs'

const specs = [
  {
    seed: 1701, name: 'Private Falconry & Wildlife Abatement Service — Contract Suite', category: 'Logistics', paletteId: 'precision-ember-dark',
    appName: 'Blackwood Falconry Services', tagline: 'Bird abatement handled by people who actually understand raptors.',
    loginQuote: 'Every site, every contract, cleared.', navIcon: 'Bird',
    primaryFeatureRoute: 'contracts', primaryFeaturePascal: 'Contracts', primaryFeatureLabel: 'Contracts', primaryFeatureSingular: 'Contract',
    greetingInsight: '6 sites are under active abatement this week — 2 new contracts start Monday.',
    dashboardVariant: 'activity', weeklyBase: 8,
    kpis: [
      { label: 'Active Contracts', value: 14, delta: 10 }, { label: 'Sites Covered', value: 22, delta: 6 },
      { label: 'Avg. Contract Value', value: 8, suffix: 'k', delta: 4 }, { label: 'Renewal Rate', value: 84, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Client', 'Site Type', 'Falconer', 'Status Detail'], filters: ['Active', 'Starting', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Starting', 'Completed'],
        itemTypes: ['Airport Bird Abatement', 'Landfill Contract', 'Vineyard Protection', 'Stadium Contract', 'Rooftop Solar Farm'],
        details: ['Daily patrols active', 'Starts Monday', 'Completed last season', 'Weekly patrols', 'Seasonal contract'] },
    },
    analyticsKpis: [{ label: 'New Contracts', value: 2, delta: 12 }, { label: 'Revenue (MTD)', value: 84, suffix: 'k', delta: 6 }, { label: 'Incident Reduction', value: 92, suffix: '%', delta: 4 }, { label: 'Bird Strikes Prevented', value: 340 }],
    trend: [{ label: 'Jan', value: 10 }, { label: 'Feb', value: 11 }, { label: 'Mar', value: 12 }, { label: 'Apr', value: 13 }, { label: 'May', value: 14 }],
    sources: [{ label: 'Government contract', value: 5 }, { label: 'Repeat client', value: 4 }, { label: 'Referral', value: 3 }],
    rankedLabel: 'Sites by falconer',
  },
  {
    seed: 1702, name: 'Executive Home Staging Firm — Project Suite', category: 'RealEstate', paletteId: 'gallery-red-light',
    appName: 'Marchetti Home Staging', tagline: 'Homes staged to sell, not just to photograph well.',
    loginQuote: 'Every listing, every room, staged.', navIcon: 'Sofa',
    primaryFeatureRoute: 'projects', primaryFeaturePascal: 'Projects', primaryFeatureLabel: 'Projects', primaryFeatureSingular: 'Project',
    greetingInsight: '5 homes are staged this week — 2 listings go live Friday.',
    dashboardVariant: 'activity', weeklyBase: 8,
    kpis: [
      { label: 'Active Projects', value: 16, delta: 12 }, { label: 'Avg. Days on Market Reduction', value: 34, suffix: '%', delta: 4 },
      { label: 'Inventory Utilization', value: 78, suffix: '%', delta: 5 }, { label: 'Realtor Partners', value: 22, delta: 3 },
    ],
    primaryTable: {
      columns: ['Property', 'Staging Type', 'Stager', 'Status Detail'], filters: ['Staging', 'Live', 'De-Staged'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Staging', 'Live', 'De-Staged'],
        itemTypes: ['Full Home Staging', 'Vacant Home Staging', 'Partial Staging', 'Luxury Staging', 'Occupied Consultation'],
        details: ['Install this week', 'Listed and live', 'De-staged after sale', 'Photography scheduled', 'Consultation complete'] },
    },
    analyticsKpis: [{ label: 'New Projects', value: 5, delta: 15 }, { label: 'Revenue (MTD)', value: 62, suffix: 'k', delta: 8 }, { label: 'Avg. Sale Premium', value: 6, suffix: '%', delta: 2 }, { label: 'Realtor Retention', value: 88, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 12 }, { label: 'Feb', value: 13 }, { label: 'Mar', value: 14 }, { label: 'Apr', value: 15 }, { label: 'May', value: 16 }],
    sources: [{ label: 'Realtor referral', value: 12 }, { label: 'Repeat realtor', value: 3 }, { label: 'Direct inquiry', value: 1 }],
    rankedLabel: 'Projects by stager',
  },
  {
    seed: 1703, name: 'Private Cellar & Wine Storage Facility — Client Suite', category: 'Food', paletteId: 'supper-club-dark',
    appName: 'Meridian Private Cellars', tagline: 'Wine storage run to the standard a real collection deserves.',
    loginQuote: 'Every bottle, every collector, cataloged.', navIcon: 'Wine',
    primaryFeatureRoute: 'collections', primaryFeaturePascal: 'Collections', primaryFeatureLabel: 'Collections', primaryFeatureSingular: 'Collection',
    greetingInsight: 'Cellar occupancy is at 84% — 2 collectors requested pull-and-ship this week.',
    dashboardVariant: 'activity', weeklyBase: 5,
    kpis: [
      { label: 'Active Collectors', value: 84, delta: 6 }, { label: 'Bottles Stored', value: 12400, delta: 4 },
      { label: 'Cellar Occupancy', value: 84, suffix: '%', delta: 3 }, { label: 'Pull Requests (MTD)', value: 22 },
    ],
    primaryTable: {
      columns: ['Collector', 'Collection Size', 'Cellar Manager', 'Status Detail'], filters: ['Active', 'Pull Requested', 'New'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Pull Requested', 'New'],
        itemTypes: ['Private Reserve Collection', 'Investment Collection', 'Personal Cellar', 'Restaurant Reserve', 'Estate Collection'],
        details: ['Climate monitored', 'Pull scheduled Friday', 'Onboarding this week', 'Insurance updated', 'Catalog current'] },
    },
    analyticsKpis: [{ label: 'New Collectors', value: 3, delta: 10 }, { label: 'Storage Revenue', value: 42, suffix: 'k', delta: 5 }, { label: 'Avg. Collection Value', value: 84, suffix: 'k', delta: 4 }, { label: 'Collector Retention', value: 92, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 76 }, { label: 'Feb', value: 78 }, { label: 'Mar', value: 80 }, { label: 'Apr', value: 82 }, { label: 'May', value: 84 }],
    sources: [{ label: 'Referral', value: 4 }, { label: 'Sommelier network', value: 3 }, { label: 'Auction house partner', value: 2 }],
    rankedLabel: 'Collections by cellar manager',
  },
  {
    seed: 1704, name: 'Boutique Piano & Instrument Restoration — Workshop Suite', category: 'Creative', paletteId: 'paper-oxblood-light',
    appName: 'Aldergate Piano Restoration', tagline: 'Instruments restored to play, not just to display.',
    loginQuote: 'Every instrument, every restoration, documented.', navIcon: 'Music',
    primaryFeatureRoute: 'restorations', primaryFeaturePascal: 'Restorations', primaryFeatureLabel: 'Restorations', primaryFeatureSingular: 'Restoration',
    greetingInsight: '3 instruments enter final voicing this week — 1 concert grand is ready for delivery.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Restorations', value: 9, delta: 8 }, { label: 'Avg. Restoration Value', value: 24, suffix: 'k', delta: 5 },
      { label: 'On-Time Completion', value: 88, suffix: '%', delta: 3 }, { label: 'Workshop Hours (MTD)', value: 340 },
    ],
    primaryTable: {
      columns: ['Client', 'Instrument Type', 'Technician', 'Stage'], filters: ['Disassembly', 'Restoration', 'Voicing'],
      rowsSpec: { count: 8, subjectKind: 'person', statuses: ['Disassembly', 'Restoration', 'Voicing'],
        itemTypes: ['Concert Grand Piano', 'Upright Piano', 'Antique Harpsichord', 'Chamber Organ', 'Vintage Violin'],
        details: ['Action rebuild', 'Soundboard repair', 'Final voicing', 'String replacement', 'Case refinishing'] },
    },
    analyticsKpis: [{ label: 'New Restorations', value: 2, delta: 12 }, { label: 'Revenue (MTD)', value: 48, suffix: 'k', delta: 6 }, { label: 'Avg. Timeline', value: '4 mo', delta: -8 }, { label: 'Client Satisfaction', value: 97, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 6 }, { label: 'Feb', value: 7 }, { label: 'Mar', value: 7 }, { label: 'Apr', value: 8 }, { label: 'May', value: 9 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Concert hall partner', value: 2 }, { label: 'Repeat client', value: 2 }],
    rankedLabel: 'Restorations by technician',
  },
  {
    seed: 1705, name: 'Private Falcon-Grade Drone Inspection Firm — Contract Suite', category: 'Logistics', paletteId: 'precision-acid-dark',
    appName: 'Blackridge Aerial Inspections', tagline: 'Infrastructure inspected from the air, documented like it matters.',
    loginQuote: 'Every asset, every inspection, logged.', navIcon: 'Radar',
    primaryFeatureRoute: 'inspections', primaryFeaturePascal: 'Inspections', primaryFeatureLabel: 'Inspections', primaryFeatureSingular: 'Inspection',
    greetingInsight: '4 inspections are scheduled this week — 2 reports are ready for client delivery.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Active Contracts', value: 12, delta: 10 }, { label: 'Inspections (MTD)', value: 34, delta: 8 },
      { label: 'Avg. Report Turnaround', value: '2 days', delta: -15 }, { label: 'Client Retention', value: 89, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Client', 'Asset Type', 'Pilot', 'Status Detail'], filters: ['Scheduled', 'In Progress', 'Report Delivered'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Scheduled', 'In Progress', 'Report Delivered'],
        itemTypes: ['Cell Tower Inspection', 'Wind Turbine Inspection', 'Solar Farm Survey', 'Bridge Inspection', 'Pipeline Survey'],
        details: ['Scheduled Thursday', 'Flight in progress', 'Report delivered', 'Data processing', 'Weather delay'] },
    },
    analyticsKpis: [{ label: 'New Contracts', value: 2, delta: 15 }, { label: 'Revenue (MTD)', value: 92, suffix: 'k', delta: 9 }, { label: 'Flight Hours', value: 84, delta: 6 }, { label: 'Defects Identified', value: 62, delta: 10 }],
    trend: [{ label: 'Jan', value: 8 }, { label: 'Feb', value: 9 }, { label: 'Mar', value: 10 }, { label: 'Apr', value: 11 }, { label: 'May', value: 12 }],
    sources: [{ label: 'Utility contract', value: 6 }, { label: 'Referral', value: 4 }, { label: 'RFP win', value: 2 }],
    rankedLabel: 'Inspections by pilot',
  },
  {
    seed: 1706, name: 'Private Chocolate & Confectionery House — Order Suite', category: 'Food', paletteId: 'food-amber-light',
    appName: 'Ferrous & Cacao Confectionery', tagline: 'Chocolate made in small batches, not mass-tempered.',
    loginQuote: 'Every batch, every order, tempered right.', navIcon: 'IceCream',
    primaryFeatureRoute: 'orders', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'Orders', primaryFeatureSingular: 'Order',
    greetingInsight: 'The corporate gift order for Halden Industries ships Friday — 2 custom molds are in production.',
    dashboardVariant: 'activity', weeklyBase: 15,
    kpis: [
      { label: 'Active Orders', value: 24, delta: 10 }, { label: 'Avg. Order Value', value: 640, delta: 6 },
      { label: 'Wholesale Accounts', value: 18, delta: 3 }, { label: 'Batches This Week', value: 12 },
    ],
    primaryTable: {
      columns: ['Client', 'Order Type', 'Chocolatier', 'Status Detail'], filters: ['Production', 'Packaging', 'Shipped'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Production', 'Packaging', 'Shipped'],
        itemTypes: ['Corporate Gift Order', 'Wedding Favors', 'Wholesale Restock', 'Custom Molded Order', 'Holiday Collection'],
        details: ['Molds in production', 'Packaging this week', 'Shipped yesterday', 'Tempering in progress', 'Design approved'] },
    },
    analyticsKpis: [{ label: 'New Orders', value: 8, delta: 14 }, { label: 'Revenue (MTD)', value: 34, suffix: 'k', delta: 8 }, { label: 'Avg. Batch Size', value: '40 lbs', delta: 5 }, { label: 'Repeat Client Rate', value: 56, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 16 }, { label: 'Feb', value: 18 }, { label: 'Mar', value: 20 }, { label: 'Apr', value: 22 }, { label: 'May', value: 24 }],
    sources: [{ label: 'Corporate account', value: 8 }, { label: 'Referral', value: 6 }, { label: 'Wedding planner referral', value: 4 }],
    rankedLabel: 'Orders by chocolatier',
  },
  {
    seed: 1707, name: 'Private Genealogy & Family History Firm — Research Suite', category: 'Legal', paletteId: 'paper-oxblood-light',
    appName: 'Aldergate Genealogy Research', tagline: 'Family history researched with the rigor of a legal case, not a hobby.',
    loginQuote: 'Every family, every record, verified.', navIcon: 'Users',
    primaryFeatureRoute: 'projects', primaryFeaturePascal: 'Projects', primaryFeatureLabel: 'Research Projects', primaryFeatureSingular: 'Project',
    greetingInsight: '4 research projects are active — the Whitmore family lineage report completes Friday.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Projects', value: 11, delta: 10 }, { label: 'Avg. Project Value', value: 4.8, suffix: 'k', delta: 5 },
      { label: 'Records Verified (MTD)', value: 340 }, { label: 'Client Satisfaction', value: 96, suffix: '%', delta: 1 },
    ],
    primaryTable: {
      columns: ['Client', 'Research Focus', 'Genealogist', 'Status Detail'], filters: ['Research', 'Verification', 'Report Complete'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Research', 'Verification', 'Report Complete'],
        itemTypes: ['Family Lineage Report', 'Immigration Records', 'DNA Analysis Support', 'Heraldry Research', 'Estate Documentation'],
        details: ['Archive research underway', 'Records cross-verified', 'Report delivered', 'International records requested', 'Interview scheduled'] },
    },
    analyticsKpis: [{ label: 'New Projects', value: 3, delta: 15 }, { label: 'Revenue (MTD)', value: 32, suffix: 'k', delta: 8 }, { label: 'Avg. Timeline', value: '10 wks', delta: -5 }, { label: 'Referral Rate', value: 62, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 8 }, { label: 'Feb', value: 9 }, { label: 'Mar', value: 10 }, { label: 'Apr', value: 10 }, { label: 'May', value: 11 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Repeat client', value: 3 }, { label: 'Estate attorney referral', value: 3 }],
    rankedLabel: 'Projects by genealogist',
  },
  {
    seed: 1708, name: 'High-End Home Theater & Screening Room Design — Project Suite', category: 'Creative', paletteId: 'midnight-press-dark',
    appName: 'Blackwood Screening Room Design', tagline: 'Screening rooms calibrated the way a real theater is calibrated.',
    loginQuote: 'Every room, every calibration, precise.', navIcon: 'Film',
    primaryFeatureRoute: 'projects', primaryFeaturePascal: 'Projects', primaryFeatureLabel: 'Projects', primaryFeatureSingular: 'Project',
    greetingInsight: '3 screening rooms are in calibration this week — 1 client walkthrough is scheduled Friday.',
    dashboardVariant: 'activity', weeklyBase: 4,
    kpis: [
      { label: 'Active Projects', value: 8, delta: 14 }, { label: 'Avg. Project Value', value: 180, suffix: 'k', delta: 6 },
      { label: 'On-Time Completion', value: 90, suffix: '%', delta: 2 }, { label: 'Calibration Sessions (MTD)', value: 14 },
    ],
    primaryTable: {
      columns: ['Client', 'Room Type', 'Lead Designer', 'Status Detail'], filters: ['Design', 'Install', 'Calibrating'],
      rowsSpec: { count: 8, subjectKind: 'person', statuses: ['Design', 'Install', 'Calibrating'],
        itemTypes: ['Dedicated Theater Room', 'Media Room', 'Outdoor Screening Space', 'Screening Room Renovation', 'Acoustic Treatment Project'],
        details: ['Acoustic design phase', 'Equipment install', 'Final calibration', 'Wiring complete', 'Client walkthrough Friday'] },
    },
    analyticsKpis: [{ label: 'New Projects', value: 2, delta: 10 }, { label: 'Revenue (MTD)', value: 240, suffix: 'k', delta: 8 }, { label: 'Avg. Timeline', value: '10 wks', delta: -4 }, { label: 'Client Satisfaction', value: 97, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 5 }, { label: 'Feb', value: 6 }, { label: 'Mar', value: 6 }, { label: 'Apr', value: 7 }, { label: 'May', value: 8 }],
    sources: [{ label: 'Architect referral', value: 4 }, { label: 'Repeat client', value: 2 }, { label: 'Referral', value: 2 }],
    rankedLabel: 'Projects by designer',
  },
  {
    seed: 1709, name: 'Private Falconry Estate Bird Sanctuary — Membership Suite', category: 'NonProfit', paletteId: 'moss-archive-light',
    appName: 'Fernbrook Raptor Sanctuary', tagline: 'A sanctuary funded by members who actually visit.',
    loginQuote: 'Every bird, every member, cared for.', navIcon: 'Bird',
    primaryFeatureRoute: 'members', primaryFeaturePascal: 'Members', primaryFeatureLabel: 'Members', primaryFeatureSingular: 'Member',
    greetingInsight: 'Membership visits are up 14% this month — 2 rehabilitated birds are ready for release.',
    dashboardVariant: 'highlights', weeklyBase: 15,
    highlights: [
      { title: 'Release Program', description: '2 rehabilitated red-tailed hawks are ready for release this week.' },
      { title: 'Education Program', description: 'School visits are booked through the end of the semester.' },
      { title: 'Membership Growth', description: 'Visits up 14% this month over last.' },
    ],
    kpis: [
      { label: 'Active Members', value: 420, delta: 8 }, { label: 'Birds in Care', value: 34, delta: 4 },
      { label: 'Rehabilitations (YTD)', value: 62, delta: 12 }, { label: 'Member Retention', value: 84, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Member', 'Membership Type', 'Program Coordinator', 'Status Detail'], filters: ['Active', 'Renewal Due', 'New'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Renewal Due', 'New'],
        itemTypes: ['Family Membership', 'Individual Membership', 'Educator Membership', 'Sponsor Membership', 'Lifetime Membership'],
        details: ['Visited this month', 'Renews next month', 'Onboarding this week', 'Auto-renewed', 'Sponsorship active'] },
    },
    analyticsKpis: [{ label: 'New Members', value: 22, delta: 14 }, { label: 'Donations (MTD)', value: 18, suffix: 'k', delta: 9 }, { label: 'Birds Released', value: 8, delta: 25 }, { label: 'School Visits', value: 14, delta: 8 }],
    trend: [{ label: 'Jan', value: 380 }, { label: 'Feb', value: 392 }, { label: 'Mar', value: 402 }, { label: 'Apr', value: 412 }, { label: 'May', value: 420 }],
    sources: [{ label: 'Member referral', value: 9 }, { label: 'School program', value: 7 }, { label: 'Event', value: 6 }],
    rankedLabel: 'Members by program coordinator',
  },
  {
    seed: 1710, name: 'Private Cheese Affinage & Import House — Wholesale Suite', category: 'Food', paletteId: 'food-amber-light',
    appName: 'Aldergate Cheese Cellars', tagline: 'Cheese aged in-house, not just imported and resold.',
    loginQuote: 'Every wheel, every account, tracked.', navIcon: 'UtensilsCrossed',
    primaryFeatureRoute: 'accounts', primaryFeaturePascal: 'Accounts', primaryFeatureLabel: 'Wholesale Accounts', primaryFeatureSingular: 'Account',
    greetingInsight: 'Cave occupancy is at 82% — 2 wholesale accounts are due for reorder this week.',
    dashboardVariant: 'activity', weeklyBase: 20,
    kpis: [
      { label: 'Wholesale Accounts', value: 46, delta: 6 }, { label: 'Cave Occupancy', value: 82, suffix: '%', delta: 3 },
      { label: 'Wheels Aging', value: 340, delta: 4 }, { label: 'Account Retention', value: 90, suffix: '%', delta: 1 },
    ],
    primaryTable: {
      columns: ['Account', 'Cheese Program', 'Account Manager', 'Status Detail'], filters: ['Active', 'Reorder Due', 'Onboarding'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Reorder Due', 'Onboarding'],
        itemTypes: ['Restaurant Cheese Program', 'Specialty Retail', 'Hotel Program', 'Wine Bar Program', 'Gift Basket Wholesale'],
        details: ['Standing weekly order', 'Reorder due Friday', 'Onboarding this month', 'Custom aging request', 'Delivery scheduled'] },
    },
    analyticsKpis: [{ label: 'New Accounts', value: 3, delta: 8 }, { label: 'Revenue (MTD)', value: 48, suffix: 'k', delta: 6 }, { label: 'Avg. Aging Time', value: '8 mo', delta: 2 }, { label: 'Import Volume', value: '2.4 tons', delta: 5 }],
    trend: [{ label: 'Jan', value: 40 }, { label: 'Feb', value: 42 }, { label: 'Mar', value: 43 }, { label: 'Apr', value: 45 }, { label: 'May', value: 46 }],
    sources: [{ label: 'Referral', value: 3 }, { label: 'Trade show', value: 2 }, { label: 'Distributor partner', value: 1 }],
    rankedLabel: 'Accounts by manager',
  },
]

export const batchSaas8 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: assembleConfig(spec),
}))
