import { assembleConfig } from '../lib/content-pool.mjs'

const specs = [
  {
    seed: 1401, name: 'Private Aircraft Management — Fleet Owner Suite', category: 'Logistics', paletteId: 'precision-ember-dark',
    appName: 'Kestrel Ridge Aviation Management', tagline: 'Aircraft ownership without the operational headache.',
    loginQuote: 'Every aircraft, every owner, managed.', navIcon: 'Plane',
    primaryFeatureRoute: 'aircraft', primaryFeaturePascal: 'Aircraft', primaryFeatureLabel: 'Managed Aircraft', primaryFeatureSingular: 'Aircraft',
    greetingInsight: 'Fleet-wide dispatch reliability is at 99.2% this month — 2 aircraft are due for scheduled maintenance.',
    dashboardVariant: 'activity', weeklyBase: 8,
    kpis: [
      { label: 'Managed Aircraft', value: 18, delta: 6 }, { label: 'Dispatch Reliability', value: 99.2, suffix: '%', delta: 1 },
      { label: 'Owner Utilization', value: 62, suffix: '%', delta: 4 }, { label: 'Charter Revenue (MTD)', value: 340, suffix: 'k' },
    ],
    primaryTable: {
      columns: ['Aircraft', 'Owner', 'Chief Pilot', 'Status Detail'], filters: ['Active', 'In Maintenance', 'Chartered'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'In Maintenance', 'Chartered'],
        itemTypes: ['Gulfstream G650', 'Citation X', 'Challenger 350', 'Phenom 300', 'Global 6000'],
        details: ['Available for owner use', 'Scheduled inspection', 'On charter this week', 'Available', 'Returning from MX'] },
    },
    analyticsKpis: [{ label: 'Flight Hours (MTD)', value: 210, delta: 8 }, { label: 'Charter Revenue', value: 340, suffix: 'k', delta: 12 }, { label: 'Owner Satisfaction', value: 96, suffix: '%', delta: 1 }, { label: 'Maintenance Events', value: 4, delta: -10 }],
    trend: [{ label: 'Jan', value: 14 }, { label: 'Feb', value: 15 }, { label: 'Mar', value: 16 }, { label: 'Apr', value: 17 }, { label: 'May', value: 18 }],
    sources: [{ label: 'Owner referral', value: 4 }, { label: 'Broker referral', value: 3 }, { label: 'Direct inquiry', value: 1 }],
    rankedLabel: 'Flight hours by chief pilot',
  },
  {
    seed: 1402, name: 'Boutique Architecture Photography Studio — Shoot Suite', category: 'Creative', paletteId: 'gallery-red-light',
    appName: 'Aldergate Photography Studio', tagline: 'Architectural photography that survives the redesign trend cycle.',
    loginQuote: 'Every shoot, every deliverable, on time.', navIcon: 'Camera',
    primaryFeatureRoute: 'shoots', primaryFeaturePascal: 'Shoots', primaryFeatureLabel: 'Shoots', primaryFeatureSingular: 'Shoot',
    greetingInsight: '3 shoots are scheduled this week — the Ferro & Lund gallery delivers Friday.',
    dashboardVariant: 'activity', weeklyBase: 4,
    kpis: [
      { label: 'Active Shoots', value: 9, delta: 12 }, { label: 'Avg. Turnaround', value: '5 days', delta: -10 },
      { label: 'Client Retention', value: 88, suffix: '%', delta: 3 }, { label: 'Deliverables (MTD)', value: 22 },
    ],
    primaryTable: {
      columns: ['Client', 'Shoot Type', 'Photographer', 'Status Detail'], filters: ['Scheduled', 'Editing', 'Delivered'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Scheduled', 'Editing', 'Delivered'],
        itemTypes: ['Architecture Exterior', 'Interior Design', 'Commercial Space', 'Real Estate Listing', 'Portfolio Gallery'],
        details: ['Shoot Thursday', 'Editing in progress', 'Delivered yesterday', 'Awaiting golden hour', 'Gallery delivered Friday'] },
    },
    analyticsKpis: [{ label: 'New Shoots', value: 3, delta: 15 }, { label: 'Revenue (MTD)', value: 28, suffix: 'k', delta: 8 }, { label: 'Avg. Shoot Value', value: 3.1, suffix: 'k', delta: 4 }, { label: 'Repeat Client Rate', value: 62, suffix: '%', delta: 5 }],
    trend: [{ label: 'Jan', value: 6 }, { label: 'Feb', value: 7 }, { label: 'Mar', value: 8 }, { label: 'Apr', value: 8 }, { label: 'May', value: 9 }],
    sources: [{ label: 'Architect referral', value: 5 }, { label: 'Repeat client', value: 3 }, { label: 'Portfolio inbound', value: 1 }],
    rankedLabel: 'Shoots by photographer',
  },
  {
    seed: 1403, name: 'High-End Audio/Visual Integration Firm — Install Suite', category: 'Logistics', paletteId: 'precision-sky-dark',
    appName: 'Blackwood AV Integration', tagline: 'Home theater and smart home systems that actually work when the client presses play.',
    loginQuote: 'Every install, every system, tested.', navIcon: 'Speaker',
    primaryFeatureRoute: 'installs', primaryFeaturePascal: 'Installs', primaryFeatureLabel: 'Installs', primaryFeatureSingular: 'Install',
    greetingInsight: '4 installs are in progress this week — the Whitmore home theater completes Friday.',
    dashboardVariant: 'activity', weeklyBase: 5,
    kpis: [
      { label: 'Active Installs', value: 11, delta: 8 }, { label: 'Avg. Install Value', value: 42, suffix: 'k', delta: 6 },
      { label: 'On-Time Completion', value: 91, suffix: '%', delta: 2 }, { label: 'Service Calls (MTD)', value: 14 },
    ],
    primaryTable: {
      columns: ['Client', 'System Type', 'Lead Technician', 'Status Detail'], filters: ['In Progress', 'Testing', 'Complete'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['In Progress', 'Testing', 'Complete'],
        itemTypes: ['Home Theater', 'Whole-Home Audio', 'Smart Home Automation', 'Lighting Control', 'Security Integration'],
        details: ['Wiring in progress', 'System testing', 'Completed last week', 'Programming underway', 'Client walkthrough Friday'] },
    },
    analyticsKpis: [{ label: 'New Installs', value: 3, delta: 12 }, { label: 'Revenue (MTD)', value: 180, suffix: 'k', delta: 9 }, { label: 'Avg. Install Time', value: '3 wks', delta: -8 }, { label: 'Service Calls', value: 14, delta: -15 }],
    trend: [{ label: 'Jan', value: 8 }, { label: 'Feb', value: 9 }, { label: 'Mar', value: 10 }, { label: 'Apr', value: 10 }, { label: 'May', value: 11 }],
    sources: [{ label: 'Architect referral', value: 5 }, { label: 'Builder partner', value: 4 }, { label: 'Repeat client', value: 2 }],
    rankedLabel: 'Installs by technician',
  },
  {
    seed: 1404, name: 'Private Jet Card & Membership Club — Member Suite', category: 'Logistics', paletteId: 'luxury-gold-dark',
    appName: 'Aerolume Membership Club', tagline: 'Guaranteed lift, without owning the aircraft.',
    loginQuote: 'Every member, every flight, guaranteed.', navIcon: 'Plane',
    primaryFeatureRoute: 'members', primaryFeaturePascal: 'Members', primaryFeatureLabel: 'Members', primaryFeatureSingular: 'Member',
    greetingInsight: 'Member flight requests are up 14% this month — 3 members are approaching their hour renewal.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Active Members', value: 84, delta: 9 }, { label: 'Hours Flown (MTD)', value: 340, delta: 11 },
      { label: 'Guaranteed Availability', value: 99, suffix: '%', delta: 0.5 }, { label: 'Renewal Rate', value: 91, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Member', 'Card Type', 'Account Manager', 'Renewal Detail'], filters: ['Active', 'Renewal Due', 'Lapsed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Renewal Due', 'Lapsed'],
        itemTypes: ['25-Hour Jet Card', '50-Hour Jet Card', 'Unlimited Membership', 'Corporate Card', '10-Hour Jet Card'],
        details: ['12 hours remaining', 'Renews in 30 days', 'Auto-renewed', 'Lapsed — reach out', '3 hours remaining'] },
    },
    analyticsKpis: [{ label: 'New Members', value: 6, delta: 14 }, { label: 'Hours Sold', value: 420, delta: 10 }, { label: 'Avg. Card Value', value: 180, suffix: 'k', delta: 5 }, { label: 'Member Satisfaction', value: 95, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 68 }, { label: 'Feb', value: 72 }, { label: 'Mar', value: 76 }, { label: 'Apr', value: 80 }, { label: 'May', value: 84 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Broker network', value: 3 }, { label: 'Repeat charter client', value: 2 }],
    rankedLabel: 'Members by account manager',
  },
  {
    seed: 1405, name: 'Boutique Ski & Alpine Resort Concierge — Guest Suite', category: 'Food', paletteId: 'open-air-light',
    appName: 'Ridgeline Alpine Concierge', tagline: 'The mountain, arranged before you land.',
    loginQuote: 'Every guest, every arrangement, ready.', navIcon: 'Mountain',
    primaryFeatureRoute: 'guests', primaryFeaturePascal: 'Guests', primaryFeatureLabel: 'Guests', primaryFeatureSingular: 'Guest',
    greetingInsight: 'Peak season occupancy is at 96% — 3 guest itineraries need final confirmation.',
    dashboardVariant: 'activity', weeklyBase: 10,
    kpis: [
      { label: 'Active Guests', value: 28, delta: 12 }, { label: 'Occupancy Rate', value: 96, suffix: '%', delta: 4 },
      { label: 'Avg. Stay Length', value: '6 nights', delta: 2 }, { label: 'Repeat Guest Rate', value: 54, suffix: '%', delta: 5 },
    ],
    primaryTable: {
      columns: ['Guest', 'Arrangement Type', 'Concierge Lead', 'Stay Detail'], filters: ['Confirmed', 'Pending', 'Departed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Confirmed', 'Pending', 'Departed'],
        itemTypes: ['Chalet Rental', 'Private Ski Instruction', 'Airport Transfer', 'Dining Reservations', 'Equipment Rental'],
        details: ['Confirmed for Sat', 'Awaiting itinerary approval', 'Departed yesterday', 'Instructor assigned', 'Delivered to chalet'] },
    },
    analyticsKpis: [{ label: 'New Guests', value: 8, delta: 18 }, { label: 'Revenue (MTD)', value: 210, suffix: 'k', delta: 14 }, { label: 'Avg. Spend/Guest', value: 7.5, suffix: 'k', delta: 6 }, { label: 'Guest Satisfaction', value: 97, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 22 }, { label: 'Feb', value: 24 }, { label: 'Mar', value: 26 }, { label: 'Apr', value: 27 }, { label: 'May', value: 28 }],
    sources: [{ label: 'Repeat guest', value: 9 }, { label: 'Travel advisor', value: 6 }, { label: 'Referral', value: 3 }],
    rankedLabel: 'Guests by concierge lead',
  },
  {
    seed: 1406, name: 'Specialty Insurance Underwriting Boutique — Policy Suite', category: 'Finance', paletteId: 'ledger-ivory-light',
    appName: 'Corbridge Specialty Underwriters', tagline: 'Underwriting for risks the standard carriers pass on.',
    loginQuote: 'Every policy, every risk, underwritten.', navIcon: 'ShieldCheck',
    primaryFeatureRoute: 'policies', primaryFeaturePascal: 'Policies', primaryFeatureLabel: 'Policies', primaryFeatureSingular: 'Policy',
    greetingInsight: '6 submissions are under review this week — 2 binders are ready to issue.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Active Policies', value: 210, delta: 5 }, { label: 'Premium Written (MTD)', value: 1.2, suffix: 'M', delta: 8 },
      { label: 'Bind Rate', value: 62, suffix: '%', delta: 3 }, { label: 'Loss Ratio', value: 41, suffix: '%', delta: -3 },
    ],
    primaryTable: {
      columns: ['Client', 'Coverage Type', 'Underwriter', 'Status Detail'], filters: ['Submitted', 'Under Review', 'Bound'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Submitted', 'Under Review', 'Bound'],
        itemTypes: ['Excess Liability', 'Environmental Liability', 'Cyber Liability', 'Professional Indemnity', 'Product Liability'],
        details: ['Submission received', 'Under review', 'Bound yesterday', 'Additional info requested', 'Ready to issue'] },
    },
    analyticsKpis: [{ label: 'New Submissions', value: 18, delta: 10 }, { label: 'Premium Bound', value: 620, suffix: 'k', delta: 9 }, { label: 'Avg. Turnaround', value: '4.1 days', delta: -12 }, { label: 'Renewal Rate', value: 87, suffix: '%', delta: 2 }],
    trend: [{ label: 'Jan', value: 190 }, { label: 'Feb', value: 196 }, { label: 'Mar', value: 200 }, { label: 'Apr', value: 205 }, { label: 'May', value: 210 }],
    sources: [{ label: 'Broker submission', value: 14 }, { label: 'Renewal', value: 8 }, { label: 'MGA referral', value: 4 }],
    rankedLabel: 'Premium by underwriter',
  },
  {
    seed: 1407, name: 'Bridal & Formal Wear Atelier — Client Suite', category: 'RealEstate', paletteId: 'gallery-red-light',
    appName: 'Marchetti Bridal Atelier', tagline: 'Gowns fitted to the client, not adjusted from a rack sample.',
    loginQuote: 'Every bride, every fitting, precise.', navIcon: 'Sparkle',
    primaryFeatureRoute: 'clients', primaryFeaturePascal: 'Clients', primaryFeatureLabel: 'Clients', primaryFeatureSingular: 'Client',
    greetingInsight: '5 fittings are scheduled this week — 2 gowns are ready for final pickup.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Active Orders', value: 24, delta: 9 }, { label: 'Avg. Order Value', value: 4.6, suffix: 'k', delta: 5 },
      { label: 'On-Time Delivery', value: 93, suffix: '%', delta: 2 }, { label: 'Repeat Referral Rate', value: 71, suffix: '%', delta: 4 },
    ],
    primaryTable: {
      columns: ['Client', 'Order Type', 'Seamstress', 'Stage'], filters: ['In Progress', 'Fitting', 'Ready'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['In Progress', 'Fitting', 'Ready'],
        itemTypes: ['Bridal Gown', 'Bridesmaid Dresses', 'Mother of the Bride', 'Evening Gown', 'Custom Alteration'],
        details: ['First fitting scheduled', 'Final fitting this week', 'Ready for pickup', 'Alterations in progress', 'Design consult'] },
    },
    analyticsKpis: [{ label: 'New Orders', value: 6, delta: 14 }, { label: 'Revenue (MTD)', value: 84, suffix: 'k', delta: 8 }, { label: 'Avg. Fittings/Order', value: 3.1, delta: -4 }, { label: 'Referral Rate', value: 71, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 18 }, { label: 'Feb', value: 20 }, { label: 'Mar', value: 21 }, { label: 'Apr', value: 23 }, { label: 'May', value: 24 }],
    sources: [{ label: 'Referral', value: 9 }, { label: 'Wedding planner referral', value: 6 }, { label: 'Instagram inquiry', value: 3 }],
    rankedLabel: 'Orders by seamstress',
  },
  {
    seed: 1408, name: 'Corporate Wellness Program Provider — Client & Program Suite', category: 'Healthcare', paletteId: 'wellness-sage-light',
    appName: 'Willowmere Corporate Wellness', tagline: 'Employee wellness programs that companies actually see used.',
    loginQuote: 'Every company, every program, measured.', navIcon: 'HeartPulse',
    primaryFeatureRoute: 'programs', primaryFeaturePascal: 'Programs', primaryFeatureLabel: 'Programs', primaryFeatureSingular: 'Program',
    greetingInsight: 'Program engagement is up 12% this quarter — 2 client renewals are due this month.',
    dashboardVariant: 'highlights', weeklyBase: 20,
    highlights: [
      { title: 'Halden Industries', description: 'Program engagement up 18% since the Q1 refresh.' },
      { title: 'Coppermill Retail', description: 'Renewal due this month — usage data ready to share.' },
      { title: 'Ashgrove Insurance', description: 'New biometric screening event scheduled.' },
    ],
    kpis: [
      { label: 'Active Programs', value: 14, delta: 8 }, { label: 'Employees Enrolled', value: 3400, delta: 9 },
      { label: 'Program Engagement', value: 68, suffix: '%', delta: 12 }, { label: 'Client Retention', value: 91, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Client Company', 'Program Type', 'Program Manager', 'Status Detail'], filters: ['Active', 'Renewal Due', 'Onboarding'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Renewal Due', 'Onboarding'],
        itemTypes: ['Biometric Screening', 'Mental Health Program', 'Fitness Challenge', 'Nutrition Coaching', 'Ergonomic Assessment'],
        details: ['Engagement up 18%', 'Renewal this month', 'Onboarding in progress', 'Event scheduled', 'Quarterly report sent'] },
    },
    analyticsKpis: [{ label: 'New Clients', value: 2, delta: 10 }, { label: 'Enrollment Growth', value: 9, suffix: '%', delta: 3 }, { label: 'Avg. Engagement', value: 68, suffix: '%', delta: 12 }, { label: 'NPS', value: 62, delta: 5 }],
    trend: [{ label: 'Jan', value: 3000 }, { label: 'Feb', value: 3100 }, { label: 'Mar', value: 3220 }, { label: 'Apr', value: 3320 }, { label: 'May', value: 3400 }],
    sources: [{ label: 'Broker referral', value: 5 }, { label: 'RFP win', value: 4 }, { label: 'Referral', value: 3 }],
    rankedLabel: 'Enrollment by program manager',
  },
  {
    seed: 1409, name: 'Antique & Fine Furnishings Dealer — Inventory Suite', category: 'Creative', paletteId: 'paper-oxblood-light',
    appName: 'Aldergate Antiques', tagline: 'Provenance documented as carefully as the piece itself.',
    loginQuote: 'Every piece, every provenance, verified.', navIcon: 'Archive',
    primaryFeatureRoute: 'pieces', primaryFeaturePascal: 'Pieces', primaryFeatureLabel: 'Collection', primaryFeatureSingular: 'Piece',
    greetingInsight: '2 pieces sold this week — a new estate acquisition arrives Thursday.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Pieces in Collection', value: 140, delta: 4 }, { label: 'Collection Value', value: 2.8, suffix: 'M', delta: 6 },
      { label: 'Sales (MTD)', value: 84, suffix: 'k' }, { label: 'Avg. Days to Sale', value: 68, delta: -8 },
    ],
    primaryTable: {
      columns: ['Piece', 'Category', 'Price', 'Status Detail'], filters: ['Available', 'On Hold', 'Sold'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Available', 'On Hold', 'Sold'],
        itemTypes: ['Georgian Writing Desk', 'French Empire Clock', 'Victorian Chaise', 'Regency Sideboard', 'Louis XV Armchair'],
        details: ['$18,000', '$9,400', '$6,200', '$14,500', '$4,800'] },
    },
    analyticsKpis: [{ label: 'New Acquisitions', value: 4, delta: 15 }, { label: 'Sales Volume', value: 84, suffix: 'k', delta: 9 }, { label: 'Avg. Sale Price', value: 8.2, suffix: 'k', delta: 5 }, { label: 'Repeat Buyer Rate', value: 44, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 120 }, { label: 'Feb', value: 126 }, { label: 'Mar', value: 132 }, { label: 'Apr', value: 136 }, { label: 'May', value: 140 }],
    sources: [{ label: 'Estate sale', value: 4 }, { label: 'Private consignment', value: 3 }, { label: 'Auction purchase', value: 1 }],
    rankedLabel: 'Sales by category',
  },
  {
    seed: 1410, name: 'Private Chef Placement Agency — Placement Suite', category: 'HRPeople', paletteId: 'food-amber-light',
    appName: 'Halcyon Culinary Placement', tagline: 'Private chefs placed by people who have worked a real kitchen.',
    loginQuote: 'Every chef, every placement, matched.', navIcon: 'ChefHat',
    primaryFeatureRoute: 'placements', primaryFeaturePascal: 'Placements', primaryFeatureLabel: 'Placements', primaryFeatureSingular: 'Placement',
    greetingInsight: '4 placements are in final interview stage — 2 households are finalizing offers this week.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Active Placements', value: 12, delta: 10 }, { label: 'Chef Roster', value: 68, delta: 4 },
      { label: 'Placement Rate', value: 82, suffix: '%', delta: 3 }, { label: 'Avg. Placement Fee', value: 8, suffix: 'k', delta: 5 },
    ],
    primaryTable: {
      columns: ['Household', 'Placement Type', 'Placement Consultant', 'Stage'], filters: ['Active', 'Final Interview', 'Placed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Final Interview', 'Placed'],
        itemTypes: ['Full-Time Private Chef', 'Seasonal Placement', 'Yacht Chef', 'Event Chef', 'Trial Placement'],
        details: ['Trial scheduled', 'Final interview Friday', 'Placed last week', 'Sourcing candidates', 'Offer pending'] },
    },
    analyticsKpis: [{ label: 'New Placements', value: 3, delta: 12 }, { label: 'Placement Revenue', value: 32, suffix: 'k', delta: 8 }, { label: 'Avg. Time to Place', value: '5 wks', delta: -10 }, { label: 'Chef Retention', value: 78, suffix: '%', delta: 4 }],
    trend: [{ label: 'Jan', value: 9 }, { label: 'Feb', value: 10 }, { label: 'Mar', value: 11 }, { label: 'Apr', value: 11 }, { label: 'May', value: 12 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Chef network', value: 4 }, { label: 'Repeat household', value: 3 }],
    rankedLabel: 'Placements by consultant',
  },
]

export const batchSaas5 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: assembleConfig(spec),
}))
