import { assembleConfig } from '../lib/content-pool.mjs'

const specs = [
  {
    seed: 1101, name: 'Executive Search Firm — Candidate & Client Suite', category: 'HRPeople', paletteId: 'saas-indigo-dark',
    appName: 'Harrowgate Search', tagline: 'Placing executives who outlast the org chart that hired them.',
    loginQuote: 'Every search, every candidate, one pipeline.', navIcon: 'UserSearch',
    primaryFeatureRoute: 'searches', primaryFeaturePascal: 'Searches', primaryFeatureLabel: 'Active Searches', primaryFeatureSingular: 'Search',
    greetingInsight: '4 searches are in final-round interviews this week — 2 offers are pending signature.',
    dashboardVariant: 'activity', weeklyBase: 6,
    kpis: [
      { label: 'Active Searches', value: 22, delta: 10 }, { label: 'Avg. Time to Fill', value: '48 days', delta: -8 },
      { label: 'Placement Rate', value: 89, suffix: '%', delta: 3 }, { label: 'Retained Fees (MTD)', value: 310, suffix: 'k' },
    ],
    primaryTable: {
      columns: ['Client', 'Role', 'Search Consultant', 'Stage'], filters: ['Active', 'Final Round', 'Placed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Final Round', 'Placed'],
        itemTypes: ['Chief Financial Officer', 'VP of Engineering', 'Chief Marketing Officer', 'General Counsel', 'Chief Operating Officer', 'VP of Sales', 'Chief Product Officer'],
        details: ['Onsite scheduled', 'Reference checks underway', 'Offer extended', 'Sourcing candidates', 'Panel interview next week'] },
    },
    analyticsKpis: [{ label: 'New Searches', value: 5, delta: 25 }, { label: 'Candidates Sourced', value: 310, delta: 14 }, { label: 'Offer Acceptance', value: 92, suffix: '%', delta: 2 }, { label: 'Avg. Fee', value: 68, suffix: 'k', delta: 4 }],
    trend: [{ label: 'Jan', value: 16 }, { label: 'Feb', value: 18 }, { label: 'Mar', value: 20 }, { label: 'Apr', value: 21 }, { label: 'May', value: 22 }],
    sources: [{ label: 'Client referral', value: 9 }, { label: 'Board referral', value: 6 }, { label: 'Repeat client', value: 5 }, { label: 'Inbound', value: 2 }],
    rankedLabel: 'Placements by consultant',
  },
  {
    seed: 1102, name: 'Management Consulting Firm — Engagement Suite', category: 'Legal', paletteId: 'precision-sky-dark',
    appName: 'Northbridge Advisory', tagline: 'Strategy work that survives contact with the org chart.',
    loginQuote: 'Every engagement, every deliverable, on scope.', navIcon: 'Presentation',
    primaryFeatureRoute: 'engagements', primaryFeaturePascal: 'Engagements', primaryFeatureLabel: 'Engagements', primaryFeatureSingular: 'Engagement',
    greetingInsight: '3 engagements enter final readout this week — the Halden Logistics workstream wraps Friday.',
    dashboardVariant: 'highlights', weeklyBase: 5,
    highlights: [
      { title: 'Halden Logistics', description: 'Final readout Friday — cost model validated with client finance team.' },
      { title: 'Coppermill Retail', description: 'Phase 2 kickoff scheduled — org design workstream begins Monday.' },
      { title: 'Ashgrove Insurance', description: 'Steering committee requested an interim update deck.' },
    ],
    kpis: [
      { label: 'Active Engagements', value: 11, delta: 5 }, { label: 'Avg. Engagement Value', value: 180, suffix: 'k', delta: 6 },
      { label: 'Utilization Rate', value: 84, suffix: '%', delta: 2 }, { label: 'Billable Hours (MTD)', value: 620 },
    ],
    primaryTable: {
      columns: ['Client', 'Workstream', 'Engagement Manager', 'Phase'], filters: ['Active', 'Final Readout', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Final Readout', 'Completed'],
        itemTypes: ['Cost Reduction Program', 'Org Design', 'Market Entry Strategy', 'Operating Model Redesign', 'Supply Chain Optimization', 'Digital Transformation'],
        details: ['Diagnostic phase', 'Implementation planning', 'Steering committee review', 'Data validation', 'Readout preparation'] },
    },
    analyticsKpis: [{ label: 'New Engagements', value: 3, delta: 15 }, { label: 'Billable Hours', value: 620, delta: 9 }, { label: 'Realization Rate', value: 91, suffix: '%', delta: 1 }, { label: 'Client NPS', value: 71, delta: 6 }],
    trend: [{ label: 'Jan', value: 8 }, { label: 'Feb', value: 9 }, { label: 'Mar', value: 10 }, { label: 'Apr', value: 11 }, { label: 'May', value: 11 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Repeat client', value: 4 }, { label: 'RFP win', value: 2 }],
    rankedLabel: 'Revenue by manager',
  },
  {
    seed: 1103, name: 'Commercial Insurance Brokerage — Policy & Renewal Suite', category: 'Finance', paletteId: 'ledger-ivory-light',
    appName: 'Corbridge Underwriting Partners', tagline: 'Commercial coverage placed by people who read the fine print first.',
    loginQuote: 'Every policy, every renewal, tracked.', navIcon: 'ShieldCheck',
    primaryFeatureRoute: 'policies', primaryFeaturePascal: 'Policies', primaryFeatureLabel: 'Policies', primaryFeatureSingular: 'Policy',
    greetingInsight: '7 renewals are due in the next 30 days — 2 carriers still owe quotes.',
    dashboardVariant: 'activity', weeklyBase: 8,
    kpis: [
      { label: 'Active Policies', value: 340, delta: 6 }, { label: 'Premium Under Mgmt', value: 18, suffix: 'M', delta: 9 },
      { label: 'Renewal Rate', value: 94, suffix: '%', delta: 1 }, { label: 'Claims Open', value: 12, delta: -15 },
    ],
    primaryTable: {
      columns: ['Client', 'Coverage Type', 'Broker', 'Renewal Date'], filters: ['Active', 'Renewal Pending', 'Claim Open'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Active', 'Renewal Pending', 'Claim Open'],
        itemTypes: ['General Liability', "Directors & Officers", 'Property & Casualty', 'Cyber Liability', 'Workers Compensation', 'Professional Liability'],
        details: ['Quote requested', 'Binder issued', 'Under review', 'Awaiting carrier', 'Renewed'] },
    },
    analyticsKpis: [{ label: 'New Policies', value: 14, delta: 12 }, { label: 'Premium Volume', value: 2.1, suffix: 'M', delta: 8 }, { label: 'Loss Ratio', value: 38, suffix: '%', delta: -4 }, { label: 'Avg. Days to Bind', value: 9, delta: -10 }],
    trend: [{ label: 'Jan', value: 300 }, { label: 'Feb', value: 312 }, { label: 'Mar', value: 320 }, { label: 'Apr', value: 330 }, { label: 'May', value: 340 }],
    sources: [{ label: 'Referral', value: 8 }, { label: 'Renewal upsell', value: 6 }, { label: 'Cold outreach', value: 3 }],
    rankedLabel: 'Premium by broker',
  },
  {
    seed: 1104, name: 'Boutique Media Agency — Campaign Suite', category: 'Marketing', paletteId: 'creative-coral-light',
    appName: 'Halcyon Media Partners', tagline: 'Media buying for brands that would rather not waste the budget.',
    loginQuote: 'Every campaign, every placement, accountable.', navIcon: 'Megaphone',
    primaryFeatureRoute: 'campaigns', primaryFeaturePascal: 'Campaigns', primaryFeatureLabel: 'Campaigns', primaryFeatureSingular: 'Campaign',
    greetingInsight: 'Q1 spend is pacing 8% under budget — 3 campaigns launch this week.',
    dashboardVariant: 'highlights', weeklyBase: 4,
    highlights: [
      { title: 'Ferrous Coffee Launch', description: 'Cross-channel launch goes live Monday — creative finalized.' },
      { title: 'Coppermill Retail', description: 'Mid-flight optimization reduced CPA by 18%.' },
      { title: 'Meridian Fitness', description: 'Q2 planning deck due to the client Friday.' },
    ],
    kpis: [
      { label: 'Active Campaigns', value: 16, delta: 14 }, { label: 'Managed Ad Spend', value: 2.4, suffix: 'M', delta: 7 },
      { label: 'Avg. ROAS', value: 4.2, delta: 5 }, { label: 'Client Retention', value: 90, suffix: '%', delta: 2 },
    ],
    primaryTable: {
      columns: ['Client', 'Channel', 'Media Planner', 'Flight Dates'], filters: ['Live', 'In Production', 'Wrapped'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Live', 'In Production', 'Wrapped'],
        itemTypes: ['Paid Social', 'Programmatic Display', 'Connected TV', 'Search', 'Influencer Partnership', 'Out-of-Home'],
        details: ['Mar 1 – Mar 31', 'Feb 15 – Mar 15', 'Mar 10 – Apr 10', 'Ongoing retainer', 'Wrapped last week'] },
    },
    analyticsKpis: [{ label: 'New Campaigns', value: 4, delta: 30 }, { label: 'Managed Spend', value: 480, suffix: 'k', delta: 11 }, { label: 'Avg. CPA', value: 42, delta: -12 }, { label: 'Avg. ROAS', value: 4.2, delta: 5 }],
    trend: [{ label: 'Jan', value: 11 }, { label: 'Feb', value: 13 }, { label: 'Mar', value: 14 }, { label: 'Apr', value: 15 }, { label: 'May', value: 16 }],
    sources: [{ label: 'Referral', value: 6 }, { label: 'Pitch win', value: 5 }, { label: 'Repeat client', value: 4 }, { label: 'Inbound', value: 1 }],
    rankedLabel: 'Spend by planner',
  },
  {
    seed: 1105, name: 'Veterinary Specialty Hospital — Patient & Case Suite', category: 'Healthcare', paletteId: 'wellness-teal-dark',
    appName: 'Alderbrook Veterinary Specialists', tagline: 'Referral-level veterinary care, coordinated like it matters.',
    loginQuote: 'Every patient, every case, coordinated.', navIcon: 'PawPrint',
    primaryFeatureRoute: 'cases', primaryFeaturePascal: 'Cases', primaryFeatureLabel: 'Cases', primaryFeatureSingular: 'Case',
    greetingInsight: '9 referral cases are active — 2 surgical cases are scheduled for tomorrow.',
    dashboardVariant: 'activity', weeklyBase: 22,
    kpis: [
      { label: 'Active Cases', value: 38, delta: 9 }, { label: "Today's Appointments", value: 14 },
      { label: 'Avg. Case Duration', value: '6 days', delta: -5 }, { label: 'Referral Volume (MTD)', value: 61, delta: 12 },
    ],
    primaryTable: {
      columns: ['Patient', 'Species / Breed', 'Referring Vet', 'Case Type'], filters: ['Active', 'Scheduled', 'Discharged'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Scheduled', 'Discharged'],
        itemTypes: ['Canine — Labrador', 'Feline — Domestic Shorthair', 'Canine — German Shepherd', 'Equine — Thoroughbred', 'Canine — Golden Retriever', 'Feline — Maine Coon'],
        details: ['Orthopedic surgery', 'Oncology consult', 'Cardiology workup', 'Internal medicine referral', 'Post-op recheck'] },
    },
    analyticsKpis: [{ label: 'New Referrals', value: 14, delta: 18 }, { label: 'Surgical Cases', value: 9, delta: 8 }, { label: 'Avg. Wait Time', value: '1.4d', delta: -20 }, { label: 'Client Satisfaction', value: 97, suffix: '%', delta: 1 }],
    trend: [{ label: 'Jan', value: 30 }, { label: 'Feb', value: 33 }, { label: 'Mar', value: 35 }, { label: 'Apr', value: 37 }, { label: 'May', value: 38 }],
    sources: [{ label: 'Referring vet', value: 9 }, { label: 'Repeat client', value: 4 }, { label: 'Emergency intake', value: 1 }],
    rankedLabel: 'Cases by specialist',
  },
  {
    seed: 1106, name: 'Private Aviation Charter — Fleet & Booking Suite', category: 'Logistics', paletteId: 'precision-ember-dark',
    appName: 'Aerolume Jet Charter', tagline: 'Private aviation, coordinated to the minute.',
    loginQuote: 'Every flight, every aircraft, on schedule.', navIcon: 'Plane',
    primaryFeatureRoute: 'flights', primaryFeaturePascal: 'Flights', primaryFeatureLabel: 'Flights', primaryFeatureSingular: 'Flight',
    greetingInsight: 'Fleet utilization is at 78% this week — 3 flights depart today.',
    dashboardVariant: 'activity', weeklyBase: 12,
    kpis: [
      { label: 'Flights (MTD)', value: 46, delta: 9 }, { label: 'Fleet Utilization', value: 78, suffix: '%', delta: 4 },
      { label: 'Avg. Flight Revenue', value: 24, suffix: 'k', delta: 6 }, { label: 'On-Time Departure', value: 96, suffix: '%', delta: 1 },
    ],
    primaryTable: {
      columns: ['Client', 'Route', 'Aircraft', 'Departure'], filters: ['Confirmed', 'Pending', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Confirmed', 'Pending', 'Completed'],
        itemTypes: ['New York – Aspen', 'London – Geneva', 'Miami – Nassau', 'Los Angeles – Cabo San Lucas', 'Chicago – Teterboro', 'Dallas – Vail'],
        details: ['Gulfstream G650', 'Citation X', 'Challenger 350', 'Phenom 300', 'Global 6000'] },
    },
    analyticsKpis: [{ label: 'New Bookings', value: 12, delta: 20 }, { label: 'Revenue (MTD)', value: 1.1, suffix: 'M', delta: 14 }, { label: 'Avg. Flight Time', value: '2.4h', delta: -3 }, { label: 'Repeat Client Rate', value: 68, suffix: '%', delta: 5 }],
    trend: [{ label: 'Jan', value: 34 }, { label: 'Feb', value: 38 }, { label: 'Mar', value: 41 }, { label: 'Apr', value: 44 }, { label: 'May', value: 46 }],
    sources: [{ label: 'Repeat client', value: 7 }, { label: 'Broker referral', value: 4 }, { label: 'Membership program', value: 1 }],
    rankedLabel: 'Revenue by aircraft',
  },
  {
    seed: 1107, name: 'Yacht Brokerage — Fleet & Client Suite', category: 'RealEstate', paletteId: 'open-air-light',
    appName: 'Meridian Yacht Group', tagline: 'Representing vessels that deserve a discreet buyer, not a listing site.',
    loginQuote: 'Every vessel, every buyer, discreet.', navIcon: 'Anchor',
    primaryFeatureRoute: 'vessels', primaryFeaturePascal: 'Vessels', primaryFeatureLabel: 'Vessels', primaryFeatureSingular: 'Vessel',
    greetingInsight: '2 sea trials are scheduled this week — the Serenata sale is in final survey.',
    dashboardVariant: 'activity', weeklyBase: 3,
    kpis: [
      { label: 'Listed Vessels', value: 19, delta: 6 }, { label: 'Fleet Value', value: 84, suffix: 'M', delta: 8 },
      { label: 'Avg. Days to Sale', value: 62, delta: -10 }, { label: 'Sales (MTD)', value: 2, delta: 100 },
    ],
    primaryTable: {
      columns: ['Vessel', 'Type', 'Price', 'Broker'], filters: ['Listed', 'Under Survey', 'Sold'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Listed', 'Under Survey', 'Sold'],
        itemTypes: ['Motor Yacht, 120ft', 'Sailing Yacht, 78ft', 'Catamaran, 62ft', 'Motor Yacht, 95ft', 'Explorer Yacht, 140ft'],
        details: ['$8.2M', '$3.4M', '$1.9M', '$6.7M', '$14.5M'] },
    },
    analyticsKpis: [{ label: 'New Listings', value: 3, delta: 25 }, { label: 'Sales Volume', value: 11, suffix: 'M', delta: 18 }, { label: 'Avg. Sale Price', value: 5.5, suffix: 'M', delta: 6 }, { label: 'Charter Bookings', value: 8, delta: 12 }],
    trend: [{ label: 'Jan', value: 15 }, { label: 'Feb', value: 16 }, { label: 'Mar', value: 17 }, { label: 'Apr', value: 18 }, { label: 'May', value: 19 }],
    sources: [{ label: 'Broker network', value: 5 }, { label: 'Repeat client', value: 3 }, { label: 'Boat show', value: 1 }],
    rankedLabel: 'Sales by broker',
  },
  {
    seed: 1108, name: 'Corporate Event Production — Production Suite', category: 'Events', paletteId: 'midnight-press-dark',
    appName: 'Bellcourt Productions', tagline: 'Corporate events produced like the client’s reputation depends on it — because it does.',
    loginQuote: 'Every event, every run-of-show, rehearsed.', navIcon: 'CalendarClock',
    primaryFeatureRoute: 'events', primaryFeaturePascal: 'Events', primaryFeatureLabel: 'Events', primaryFeatureSingular: 'Event',
    greetingInsight: 'The Halden Logistics annual summit loads in Thursday — 3 vendor confirmations still pending.',
    dashboardVariant: 'highlights', weeklyBase: 3,
    highlights: [
      { title: 'Halden Logistics Summit', description: 'Load-in Thursday — AV vendor confirmed, catering pending final count.' },
      { title: 'Coppermill Product Launch', description: 'Venue walkthrough completed — run of show in final review.' },
      { title: 'Ashgrove Awards Gala', description: 'Talent booking confirmed — save-the-dates sent to 400 guests.' },
    ],
    kpis: [
      { label: 'Active Productions', value: 8, delta: 14 }, { label: 'Avg. Production Budget', value: 220, suffix: 'k', delta: 5 },
      { label: 'On-Budget Rate', value: 91, suffix: '%', delta: 3 }, { label: 'Attendee Satisfaction', value: 95, suffix: '%', delta: 1 },
    ],
    primaryTable: {
      columns: ['Client', 'Event Type', 'Producer', 'Event Date'], filters: ['In Production', 'Final Review', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['In Production', 'Final Review', 'Completed'],
        itemTypes: ['Annual Summit', 'Product Launch', 'Awards Gala', 'Board Retreat', 'Investor Day', 'Trade Show Activation'],
        details: ['Mar 14', 'Mar 22', 'Apr 3', 'Feb 28 — Completed', 'Apr 18'] },
    },
    analyticsKpis: [{ label: 'New Productions', value: 2, delta: 20 }, { label: 'Managed Budget', value: 1.8, suffix: 'M', delta: 9 }, { label: 'Vendor On-Time Rate', value: 93, suffix: '%', delta: 2 }, { label: 'Avg. Attendance', value: 340, delta: 7 }],
    trend: [{ label: 'Jan', value: 5 }, { label: 'Feb', value: 6 }, { label: 'Mar', value: 7 }, { label: 'Apr', value: 8 }, { label: 'May', value: 8 }],
    sources: [{ label: 'Repeat client', value: 4 }, { label: 'Referral', value: 3 }, { label: 'RFP win', value: 1 }],
    rankedLabel: 'Budget by producer',
  },
  {
    seed: 1109, name: 'Executive Coaching Firm — Client & Program Suite', category: 'HRPeople', paletteId: 'cobalt-pop-light',
    appName: 'Ashford Leadership Partners', tagline: 'Executive coaching for leaders who already know the theory.',
    loginQuote: 'Every leader, every program, tracked.', navIcon: 'Target',
    primaryFeatureRoute: 'clients', primaryFeaturePascal: 'Clients', primaryFeatureLabel: 'Coaching Clients', primaryFeatureSingular: 'Client',
    greetingInsight: '6 coaching sessions are scheduled this week — 2 clients complete their program this month.',
    dashboardVariant: 'activity', weeklyBase: 9,
    kpis: [
      { label: 'Active Clients', value: 28, delta: 8 }, { label: 'Avg. Program Length', value: '9 mo', delta: -4 },
      { label: 'Program Completion', value: 93, suffix: '%', delta: 2 }, { label: 'Sessions (MTD)', value: 52 },
    ],
    primaryTable: {
      columns: ['Client', 'Program Type', 'Coach', 'Next Session'], filters: ['Active', 'Onboarding', 'Completed'],
      rowsSpec: { count: 9, subjectKind: 'person', statuses: ['Active', 'Onboarding', 'Completed'],
        itemTypes: ['Executive Presence', 'New Leader Transition', 'Team Effectiveness', '360 Feedback Program', 'Succession Readiness'],
        details: ['Mar 5', 'Mar 8', 'Mar 12', 'Completed last month', 'Mar 20'] },
    },
    analyticsKpis: [{ label: 'New Clients', value: 4, delta: 18 }, { label: 'Sessions Delivered', value: 52, delta: 6 }, { label: 'Avg. NPS', value: 74, delta: 4 }, { label: 'Renewal Rate', value: 82, suffix: '%', delta: 3 }],
    trend: [{ label: 'Jan', value: 22 }, { label: 'Feb', value: 24 }, { label: 'Mar', value: 26 }, { label: 'Apr', value: 27 }, { label: 'May', value: 28 }],
    sources: [{ label: 'HR partner referral', value: 5 }, { label: 'Alumni referral', value: 4 }, { label: 'Inbound', value: 2 }],
    rankedLabel: 'Clients by coach',
  },
  {
    seed: 1110, name: 'Patent & IP Law Firm — Docket & Prosecution Suite', category: 'Legal', paletteId: 'mono-dev-dark',
    appName: 'Sterling Yates IP Law', tagline: 'Patent prosecution for inventions that took longer to build than to explain.',
    loginQuote: 'Every filing, every deadline, docketed.', navIcon: 'FileText',
    primaryFeatureRoute: 'filings', primaryFeaturePascal: 'Filings', primaryFeatureLabel: 'Filings', primaryFeatureSingular: 'Filing',
    greetingInsight: '5 office action responses are due this month — 2 filed early this week.',
    dashboardVariant: 'activity', weeklyBase: 7,
    kpis: [
      { label: 'Active Filings', value: 64, delta: 7 }, { label: 'Patents Granted (YTD)', value: 18, delta: 20 },
      { label: 'Avg. Prosecution Time', value: '22 mo', delta: -6 }, { label: 'Docket Compliance', value: 100, suffix: '%' },
    ],
    primaryTable: {
      columns: ['Client', 'Filing Type', 'Prosecuting Attorney', 'Next Deadline'], filters: ['Pending', 'Office Action', 'Granted'],
      rowsSpec: { count: 9, subjectKind: 'company', statuses: ['Pending', 'Office Action', 'Granted'],
        itemTypes: ['Utility Patent', 'Design Patent', 'PCT Application', 'Trademark Registration', 'Provisional Application'],
        details: ['Mar 10 — Response due', 'Mar 18 — Filing deadline', 'Granted Feb 2026', 'Mar 25 — Office action', 'Apr 2 — Maintenance fee'] },
    },
    analyticsKpis: [{ label: 'New Filings', value: 9, delta: 12 }, { label: 'Office Actions Resolved', value: 14, delta: 8 }, { label: 'Grant Rate', value: 87, suffix: '%', delta: 3 }, { label: 'Avg. Fee per Matter', value: 12, suffix: 'k', delta: 2 }],
    trend: [{ label: 'Jan', value: 52 }, { label: 'Feb', value: 56 }, { label: 'Mar', value: 59 }, { label: 'Apr', value: 61 }, { label: 'May', value: 64 }],
    sources: [{ label: 'Referral', value: 5 }, { label: 'Repeat client', value: 4 }, { label: 'VC portfolio referral', value: 2 }],
    rankedLabel: 'Filings by attorney',
  },
]

export const batchSaas2 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: assembleConfig(spec),
}))
