export const conciergeClinic = {
  name: 'Private Concierge Clinic — Patient & Visit Suite',
  category: 'Healthcare',
  paletteId: 'wellness-sage-light',
  config: {
    description: 'Membership-based patient portal for a concierge clinic — visits, care plans, lab results.',
    appName: 'Willowmere Clinic',
    tagline: 'Unhurried, membership-based primary care — same-day visits, no waiting room.',
    loginQuote: 'Every patient, every visit, unhurried.',
    navIcon: 'HeartPulse',
    primaryFeatureRoute: 'patients',
    primaryFeaturePascal: 'Patients',
    primaryFeatureLabel: 'Patients',
    primaryFeatureSingular: 'Patient',
    greetingName: 'Dr. Amara Osei',
    greetingInsight: '11 visits scheduled today — 2 patients are due for their annual wellness panel.',
    dashboardVariant: 'highlights',
    highlights: [
      { title: 'Panel size', description: '412 of 450 member capacity — 38 slots open for new members.' },
      { title: 'Lab turnaround', description: 'Average result turnaround down to 1.8 days, from 3.1 last quarter.' },
      { title: 'Member renewal', description: '94% annual renewal rate — highest in clinic history.' },
    ],
    kpis: [
      { label: 'Active Members', value: 412, delta: 5, spark: [370, 380, 388, 395, 401, 406, 409, 412] },
      { label: "Today's Visits", value: 11, spark: [6, 8, 7, 9, 10, 9, 10, 11] },
      { label: 'Avg. Visit Length', value: '38 min', spark: [45, 43, 42, 41, 40, 39, 38, 38] },
      { label: 'Member Satisfaction', value: 98, suffix: '%', delta: 1, spark: [95, 95, 96, 96, 97, 97, 98, 98] },
    ],
    weeklyBars: [
      { label: 'W1', value: 48 }, { label: 'W2', value: 52 }, { label: 'W3', value: 45 },
      { label: 'W4', value: 58 }, { label: 'W5', value: 50 }, { label: 'W6', value: 61 },
      { label: 'W7', value: 55 }, { label: 'W8', value: 63 },
    ],
    activity: [
      { label: 'Lab results ready for Priya Anand — annual wellness panel', time: '15 minutes ago' },
      { label: 'New member onboarded: the Castellano family (4 members)', time: '1 hour ago' },
      { label: 'Care plan updated for Marcus Webb — hypertension management', time: '3 hours ago' },
      { label: 'Same-day visit completed for Elin Torvald', time: 'yesterday' },
      { label: 'Referral sent to cardiology for Harold Whitfield', time: 'yesterday' },
    ],
    primaryTable: {
      columns: ['Patient', 'Care Focus', 'Primary Physician', 'Next Visit'],
      filters: ['Active', 'Pending', 'Discharged'],
      rows: [
        { cells: ['Priya Anand', 'Annual Wellness', 'Dr. A. Osei', 'Mar 6 — Follow-up'], status: 'Active' },
        { cells: ['Marcus Webb', 'Hypertension Mgmt', 'Dr. R. Solis', 'Mar 9 — Check-in'], status: 'Active' },
        { cells: ['Elin Torvald', 'Sports Medicine', 'Dr. A. Osei', 'Mar 4 — Physio'], status: 'Active' },
        { cells: ['Harold Whitfield', 'Cardiology Referral', 'Dr. R. Solis', 'Mar 14 — Specialist'], status: 'Pending' },
        { cells: ['The Castellano Family', 'New Member Intake', 'Dr. A. Osei', 'Mar 5 — Intake'], status: 'Pending' },
        { cells: ['Dana Kessler', 'Diabetes Mgmt', 'Dr. R. Solis', 'Mar 11 — Labs'], status: 'Active' },
        { cells: ['Tobias Renner', 'Post-Op Recovery', 'Dr. A. Osei', 'Feb 20 — Discharged'], status: 'Discharged' },
        { cells: ['Marguerite Boone', 'Preventive Care', 'Dr. R. Solis', 'Mar 18 — Annual panel'], status: 'Active' },
      ],
    },
    analyticsKpis: [
      { label: 'New Members', value: 9, delta: 22 },
      { label: 'Visit Volume', value: 63, delta: 14 },
      { label: 'No-Show Rate', value: 2, suffix: '%', delta: -1 },
      { label: 'Avg. Lab Turnaround', value: '1.8d', delta: -8 },
    ],
    trend: [
      { label: 'Jan', value: 370 }, { label: 'Feb', value: 388 }, { label: 'Mar', value: 401 },
      { label: 'Apr', value: 406 }, { label: 'May', value: 412 },
    ],
    sources: [
      { label: 'Member referral', value: 6 }, { label: 'Employer benefit', value: 5 },
      { label: 'Web inquiry', value: 3 }, { label: 'Physician referral', value: 2 },
    ],
    rankedTable: {
      label: 'Visits by physician',
      rows: [
        { name: 'Dr. A. Osei', value: 34 },
        { name: 'Dr. R. Solis', value: 29 },
      ],
    },
    notifications: [
      { title: 'Lab results ready', description: "Priya Anand's annual wellness panel results are in — all within range.", time: '15 minutes ago', unread: true, tone: 'default' },
      { title: 'New member intake', description: 'The Castellano family joins Monday — 4 new member profiles created.', time: '1 hour ago', unread: true, tone: 'outline' },
      { title: 'Referral confirmed', description: 'Harold Whitfield confirmed his cardiology appointment for Mar 14.', time: 'yesterday', unread: false, tone: 'solid' },
      { title: 'Discharge summary sent', description: "Tobias Renner's post-op discharge summary was sent to his file.", time: '3 days ago', unread: false, tone: 'default' },
    ],
    team: [
      { name: 'Amara Osei', email: 'a.osei@willowmere.com', role: 'Physician, Founder' },
      { name: 'Rafael Solis', email: 'r.solis@willowmere.com', role: 'Physician' },
      { name: 'Noor Farooqi', email: 'n.farooqi@willowmere.com', role: 'Nurse Practitioner' },
      { name: 'Ellie Marchetti', email: 'e.marchetti@willowmere.com', role: 'Member Services' },
    ],
  },
}
