export const creativeAgency = {
  name: 'Creative & Branding Agency — Client Engagement Suite',
  category: 'Creative',
  paletteId: 'creative-violet-dark',
  config: {
    description: 'Client engagements, creative deliverables, and retainer tracking for a branding agency.',
    appName: 'Nocturne & Bloom',
    tagline: 'Brand systems for companies that refuse to look like everyone else.',
    loginQuote: 'Every brand, every deliverable, on brief.',
    navIcon: 'Sparkles',
    primaryFeatureRoute: 'engagements',
    primaryFeaturePascal: 'Engagements',
    primaryFeatureLabel: 'Engagements',
    primaryFeatureSingular: 'Engagement',
    greetingName: 'Yuki Tanaka',
    greetingInsight: '5 deliverables due this week — the Solace Skincare rebrand presents to the client Thursday.',
    dashboardVariant: 'highlights',
    highlights: [
      { title: 'Solace Skincare', description: 'Full identity system presents Thursday — 3 rounds of revisions closed.' },
      { title: 'Ferrous Coffee', description: 'Packaging system in final production proofing this week.' },
      { title: 'Halcyon Studio', description: 'Discovery workshop scheduled for the new retainer client.' },
    ],
    kpis: [
      { label: 'Active Engagements', value: 14, delta: 8, spark: [9, 10, 11, 11, 12, 13, 13, 14] },
      { label: 'Avg. Engagement Value', value: 48, suffix: 'k', delta: 6, spark: [38, 40, 42, 44, 45, 46, 47, 48] },
      { label: 'On-Brief Approval Rate', value: 92, suffix: '%', delta: 4, spark: [82, 84, 86, 88, 89, 90, 91, 92] },
      { label: 'Billable Hours (MTD)', value: 486, spark: [50, 110, 170, 240, 310, 380, 440, 486] },
    ],
    weeklyBars: [
      { label: 'W1', value: 5 }, { label: 'W2', value: 7 }, { label: 'W3', value: 6 },
      { label: 'W4', value: 9 }, { label: 'W5', value: 8 }, { label: 'W6', value: 11 },
      { label: 'W7', value: 9 }, { label: 'W8', value: 12 },
    ],
    activity: [
      { label: 'Solace Skincare identity system entered final review', time: '40 minutes ago' },
      { label: 'New engagement kicked off: Halcyon Studio brand refresh', time: '2 hours ago' },
      { label: 'Ferrous Coffee packaging sent to production proofing', time: '5 hours ago' },
      { label: 'Client feedback received on the Meridian Fitness campaign', time: 'yesterday' },
      { label: 'Retainer renewed: Quill & Co., 12 more months', time: 'yesterday' },
    ],
    primaryTable: {
      columns: ['Client', 'Engagement Type', 'Creative Lead', 'Next Deliverable'],
      filters: ['Active', 'In Review', 'Delivered'],
      rows: [
        { cells: ['Solace Skincare', 'Full Identity System', 'Y. Tanaka', 'Mar 6 — Client presentation'], status: 'In Review' },
        { cells: ['Ferrous Coffee', 'Packaging System', 'D. Okonkwo', 'Mar 4 — Production proof'], status: 'Active' },
        { cells: ['Halcyon Studio', 'Brand Refresh', 'Y. Tanaka', 'Mar 10 — Discovery deck'], status: 'Active' },
        { cells: ['Meridian Fitness', 'Campaign Concepts', 'L. Bergström', 'Mar 7 — Revised concepts'], status: 'In Review' },
        { cells: ['Quill & Co.', 'Ongoing Retainer', 'D. Okonkwo', 'Mar 12 — Monthly deliverables'], status: 'Active' },
        { cells: ['Aster & Rowe', 'Website Redesign', 'L. Bergström', 'Feb 26 — Delivered'], status: 'Delivered' },
        { cells: ['The Marrow Collective', 'Naming & Identity', 'Y. Tanaka', 'Mar 18 — Name options'], status: 'Active' },
        { cells: ['Birchfield Winery', 'Label Redesign', 'D. Okonkwo', 'Feb 20 — Delivered'], status: 'Delivered' },
      ],
    },
    analyticsKpis: [
      { label: 'New Engagements', value: 3, delta: 20 },
      { label: 'Retainer Revenue', value: 92, suffix: 'k', delta: 7 },
      { label: 'Avg. Revision Rounds', value: 2.4, delta: -10 },
      { label: 'Client Retention', value: 89, suffix: '%', delta: 4 },
    ],
    trend: [
      { label: 'Jan', value: 380 }, { label: 'Feb', value: 410 }, { label: 'Mar', value: 440 },
      { label: 'Apr', value: 465 }, { label: 'May', value: 486 },
    ],
    sources: [
      { label: 'Referral', value: 8 }, { label: 'Portfolio inbound', value: 5 },
      { label: 'Past client', value: 4 }, { label: 'Pitch win', value: 2 },
    ],
    rankedTable: {
      label: 'Engagements by lead',
      rows: [
        { name: 'Y. Tanaka', value: 6 },
        { name: 'D. Okonkwo', value: 5 },
        { name: 'L. Bergström', value: 3 },
      ],
    },
    notifications: [
      { title: 'Client presentation Thursday', description: 'Solace Skincare identity system presents at 2 PM — deck finalized.', time: '40 minutes ago', unread: true, tone: 'outline' },
      { title: 'Retainer renewed', description: 'Quill & Co. renewed their ongoing retainer for 12 more months.', time: 'yesterday', unread: true, tone: 'solid' },
      { title: 'Feedback received', description: 'Meridian Fitness sent notes on the campaign concept round.', time: 'yesterday', unread: false, tone: 'default' },
      { title: 'Deliverable shipped', description: 'Birchfield Winery label redesign delivered and invoiced.', time: '3 days ago', unread: false, tone: 'default' },
    ],
    team: [
      { name: 'Yuki Tanaka', email: 'y.tanaka@nocturnebloom.com', role: 'Creative Director' },
      { name: 'Dara Okonkwo', email: 'd.okonkwo@nocturnebloom.com', role: 'Senior Designer' },
      { name: 'Liv Bergström', email: 'l.bergstrom@nocturnebloom.com', role: 'Brand Strategist' },
      { name: 'Rosa Mancini', email: 'r.mancini@nocturnebloom.com', role: 'Account Director' },
    ],
  },
}
