export const lawFirm = {
  name: 'Boutique Law Firm — Case Intake & Client Portal',
  category: 'Legal',
  paletteId: 'counsel-navy-light',
  config: {
    description: 'Full practice-management suite for a boutique law firm — matter intake, client portal, billing, and team, not a single stripped-down page.',
    appName: 'Harrow & Voss',
    tagline: 'Practice management for firms that still answer their own phones.',
    loginQuote: 'Every matter, every client, one view.',
    navIcon: 'Scale',
    primaryFeatureRoute: 'matters',
    primaryFeaturePascal: 'Matters',
    primaryFeatureLabel: 'Matters',
    primaryFeatureSingular: 'Matter',
    greetingName: 'Elena Voss',
    greetingInsight: "You've closed 4 matters this month — 80% to target, with 3 deadlines this week.",
    kpis: [
      { label: 'Active Matters', value: 34, delta: 12, spark: [21, 24, 22, 27, 29, 31, 30, 34] },
      { label: 'Avg. Resolution', value: '18 days', spark: [24, 23, 22, 20, 19, 19, 18, 18] },
      { label: 'Client Satisfaction', value: 96, suffix: '%', delta: 4, spark: [88, 90, 91, 93, 94, 95, 95, 96] },
      { label: 'Billable Hours (MTD)', value: 412, spark: [40, 85, 130, 180, 240, 300, 360, 412] },
    ],
    weeklyBars: [
      { label: 'W1', value: 6 }, { label: 'W2', value: 9 }, { label: 'W3', value: 7 },
      { label: 'W4', value: 11 }, { label: 'W5', value: 8 }, { label: 'W6', value: 12 },
      { label: 'W7', value: 10 }, { label: 'W8', value: 13 },
    ],
    activity: [
      { label: 'Whitfield Holdings LLC moved to Filing — E. Voss', time: '12 minutes ago' },
      { label: 'Marguerite Sato signed the estate planning docs', time: '1 hour ago' },
      { label: 'New matter opened: Fenwick Design Studio — IP Licensing', time: '3 hours ago' },
      { label: 'Delacroix Family Trust deposition rescheduled to Mar 12', time: 'yesterday' },
      { label: 'Invoice #2291 sent to Anders & Cole Partners', time: 'yesterday' },
    ],
    primaryTable: {
      columns: ['Client', 'Matter Type', 'Lead Attorney', 'Next Deadline'],
      filters: ['Active', 'Pending Review', 'Closed'],
      rows: [
        { cells: ['Whitfield Holdings LLC', 'Corporate Formation', 'E. Voss', 'Mar 4 — Filing'], status: 'Active' },
        { cells: ['Marguerite Sato', 'Estate Planning', 'A. Harrow', 'Mar 9 — Signing'], status: 'Active' },
        { cells: ['Delacroix Family Trust', 'Estate Litigation', 'E. Voss', 'Mar 12 — Deposition'], status: 'Pending Review' },
        { cells: ['Ridgeline Property Group', 'Real Estate Closing', 'M. Okafor', 'Feb 27 — Closing'], status: 'Closed' },
        { cells: ['Anders & Cole Partners', 'Contract Review', 'A. Harrow', 'Mar 6 — Redline'], status: 'Active' },
        { cells: ['Priya Nair', 'Employment Dispute', 'M. Okafor', 'Mar 15 — Mediation'], status: 'Pending Review' },
        { cells: ['Fenwick Design Studio', 'IP Licensing', 'E. Voss', 'Mar 20 — Draft due'], status: 'Active' },
        { cells: ['Thomas & Renée Girard', 'Family Law — Custody', 'A. Harrow', 'Feb 18 — Hearing'], status: 'Closed' },
        { cells: ['Blackwood Ventures', 'M&A Due Diligence', 'E. Voss', 'Mar 22 — Data room'], status: 'Active' },
        { cells: ['Sofia Marchetti', 'Trademark Registration', 'M. Okafor', 'Mar 10 — Office action'], status: 'Pending Review' },
      ],
    },
    analyticsKpis: [
      { label: 'New Matters', value: 12, delta: 8 },
      { label: 'Billable Hours', value: 412, delta: 6 },
      { label: 'Realization Rate', value: 91, suffix: '%', delta: 2 },
      { label: 'Avg. Days to Close', value: 18, delta: -5 },
    ],
    trend: [
      { label: 'Jan', value: 280 }, { label: 'Feb', value: 340 }, { label: 'Mar', value: 310 },
      { label: 'Apr', value: 390 }, { label: 'May', value: 412 },
    ],
    sources: [
      { label: 'Referral', value: 14 }, { label: 'Web', value: 9 },
      { label: 'Repeat client', value: 7 }, { label: 'Bar directory', value: 4 },
    ],
    rankedTable: {
      label: 'Matters by attorney',
      rows: [
        { name: 'E. Voss', value: 14 },
        { name: 'A. Harrow', value: 11 },
        { name: 'M. Okafor', value: 9 },
      ],
    },
    notifications: [
      { title: 'Deposition rescheduled', description: 'Delacroix Family Trust deposition moved to Mar 12, 10:00 AM.', time: '2 hours ago', unread: true, tone: 'outline' },
      { title: 'Document signed', description: 'Marguerite Sato signed the estate planning package.', time: '5 hours ago', unread: true, tone: 'default' },
      { title: 'Invoice paid', description: 'Ridgeline Property Group paid invoice #2287 — $4,200.', time: 'yesterday', unread: false, tone: 'solid' },
      { title: 'New matter assigned', description: "You've been assigned Blackwood Ventures — M&A Due Diligence.", time: '2 days ago', unread: false, tone: 'default' },
    ],
    team: [
      { name: 'Elena Voss', email: 'e.voss@harrowvoss.com', role: 'Owner' },
      { name: 'Adrian Harrow', email: 'a.harrow@harrowvoss.com', role: 'Partner' },
      { name: 'Marcus Okafor', email: 'm.okafor@harrowvoss.com', role: 'Associate' },
      { name: 'Ines Torres', email: 'i.torres@harrowvoss.com', role: 'Paralegal' },
    ],
  },
}
