const specs = [
  {
    seed: 3101, name: 'Ironclad Performance — Member App', category: 'Mobile-Fitness', paletteId: 'track-red-light',
    description: 'Client-facing app for a boutique fitness studio — class booking, check-in, progress tracking.',
    appName: 'Ironclad Performance', navIcon: 'barbell', primaryFeaturePascal: 'Classes', primaryFeatureLabel: 'Classes',
    greetingName: 'Priya Sharma', greetingInsight: "You're 2 sessions from your monthly streak badge.",
    insightCard: 'Your 6 AM strength class has 2 spots left — you usually book this one on Tuesdays.',
    kpis: [{ label: 'Classes This Month', value: 14, delta: 12 }, { label: 'Streak', value: 6, suffix: 'd' }, { label: 'Calories (wk)', value: 4200, delta: 8 }],
    actionItems: [{ title: 'Confirm tomorrow’s class', detail: '6 AM Strength — spots filling fast', tone: 'warning' }, { title: 'Membership renews in 3 days', detail: 'Auto-renew is on', tone: 'accent' }],
    activity: [{ label: 'Checked into 6 AM Strength', time: '2h ago' }, { label: 'Booked Saturday HIIT', time: 'yesterday' }, { label: 'Hit a new deadlift PR', time: '2 days ago' }, { label: 'Missed Thursday Mobility', time: '3 days ago' }, { label: 'Joined the studio', time: '6 mo ago' }],
    tableColumns: ['Class', 'Instructor'], filters: ['Confirmed', 'Waitlisted', 'Completed'],
    itemTypes: ['6 AM Strength', 'HIIT Circuit', 'Mobility Flow', 'Olympic Lifting', 'Recovery Session'],
    details: ['Tomorrow 6 AM', 'Waitlist #2', 'Completed', 'Sat 9 AM', 'This evening'],
  },
  {
    seed: 3102, name: 'Ashcombe & Vale — Agent App', category: 'Mobile-RealEstate', paletteId: 'luxury-gold-dark',
    description: 'Mobile CRM for luxury real estate agents — showings, leads, and listings on the go.',
    appName: 'Ashcombe & Vale', navIcon: 'business', primaryFeaturePascal: 'Listings', primaryFeatureLabel: 'Listings',
    greetingName: 'Isabelle Vale', greetingInsight: 'You have 2 private showings today.',
    insightCard: 'The Havenwood showing at 2 PM has a pre-qualified buyer — send the disclosure packet before you arrive.',
    kpis: [{ label: 'Active Listings', value: 27, delta: 8 }, { label: 'Showings (wk)', value: 9 }, { label: 'Portfolio Value', value: '340M' }],
    actionItems: [{ title: 'Confirm 2 PM showing', detail: '14 Havenwood Cliff Estate', tone: 'accent' }, { title: 'Price adjustment pending sign-off', detail: 'Lindenhurst Manor', tone: 'warning' }],
    activity: [{ label: 'New private showing scheduled', time: '30m ago' }, { label: 'Offer accepted on The Whitmore Penthouse', time: '2h ago' }, { label: 'Uploaded new listing photos', time: 'yesterday' }, { label: 'Client follow-up sent', time: 'yesterday' }, { label: 'Closed on Windward Point Villa', time: '3 days ago' }],
    tableColumns: ['Property', 'Type'], filters: ['Active', 'Under Contract', 'Closed'],
    itemTypes: ['Oceanfront Estate', 'Penthouse Condo', 'Vineyard Estate', 'Townhouse', 'Country Manor'],
    details: ['$18.5M', '$12.4M', '$9.2M', '$6.1M', '$8.9M'],
  },
  {
    seed: 3103, name: 'Marrow & Ash — Guest App', category: 'Mobile-Food', paletteId: 'supper-club-dark',
    description: 'Reservation and loyalty app for a fine dining restaurant.',
    appName: 'Marrow & Ash', navIcon: 'restaurant', primaryFeaturePascal: 'Reservations', primaryFeatureLabel: 'Reservations',
    greetingName: 'Kofi Mensah', greetingInsight: 'Your table for Friday is confirmed.',
    insightCard: 'You are 2 visits from unlocking the Chef’s Table experience — your next reservation qualifies.',
    kpis: [{ label: 'Visits', value: 8, delta: 14 }, { label: 'Loyalty Points', value: 420 }, { label: 'Next Reward', value: '2 visits' }],
    actionItems: [{ title: 'Confirm Friday reservation', detail: '7:30 PM, table for 2', tone: 'accent' }, { title: 'Leave a review', detail: 'From your last visit', tone: 'default' }],
    activity: [{ label: 'Reservation confirmed for Friday', time: '1h ago' }, { label: 'Earned 40 loyalty points', time: 'yesterday' }, { label: 'Dined — tasting menu', time: '2 weeks ago' }, { label: 'Redeemed a wine pairing reward', time: '1 mo ago' }, { label: 'Joined the loyalty program', time: '4 mo ago' }],
    tableColumns: ['Date', 'Party Size'], filters: ['Confirmed', 'Waitlisted', 'Completed'],
    itemTypes: ['Fri 7:30 PM', 'Sat 8:00 PM', "Chef's Table", 'Wine Pairing Dinner', 'Private Room'],
    details: ['2 guests', '4 guests', '2 guests', '6 guests', '10 guests'],
  },
  {
    seed: 3104, name: 'Meridian Capital — Client App', category: 'Mobile-Finance', paletteId: 'ledger-ivory-light',
    description: 'Private client portal app for a wealth advisory firm.',
    appName: 'Meridian Capital', navIcon: 'trending-up', primaryFeaturePascal: 'Portfolio', primaryFeatureLabel: 'Portfolio',
    greetingName: 'David Reyes', greetingInsight: 'Your portfolio is up 2.1% this week.',
    insightCard: 'Your ESG Focused allocation outperformed the benchmark by 1.4% this quarter — no action needed.',
    kpis: [{ label: 'Portfolio Value', value: '4.2M', delta: 6 }, { label: 'YTD Return', value: 14, suffix: '%', delta: 3 }, { label: 'Next Review', value: 'Mar 12' }],
    actionItems: [{ title: 'Quarterly review scheduled', detail: 'Mar 12, 2 PM with D. Reyes', tone: 'accent' }, { title: 'Tax document ready', detail: '2025 year-end statement', tone: 'default' }],
    activity: [{ label: 'Portfolio rebalanced toward fixed income', time: '2h ago' }, { label: 'Dividend reinvested — $1,240', time: 'yesterday' }, { label: 'Statement generated', time: '3 days ago' }, { label: 'Advisor note added', time: '1 week ago' }, { label: 'Account opened', time: '3 yrs ago' }],
    tableColumns: ['Holding', 'Allocation'], filters: ['Active', 'Under Review', 'Rebalancing'],
    itemTypes: ['Growth Equity', 'Fixed Income Ladder', 'ESG Focused', 'Balanced Income', 'Cash Reserve'],
    details: ['32%', '24%', '18%', '20%', '6%'],
  },
  {
    seed: 3105, name: 'Willowmere Aesthetics — Patient App', category: 'Mobile-Healthcare', paletteId: 'wellness-sage-light',
    description: 'Booking and treatment tracking app for a medical aesthetics clinic.',
    appName: 'Willowmere Aesthetics', navIcon: 'sparkles', primaryFeaturePascal: 'Appointments', primaryFeatureLabel: 'Appointments',
    greetingName: 'Marguerite Boone', greetingInsight: 'Your next appointment is in 4 days.',
    insightCard: 'Your last treatment was 8 weeks ago — you’re due for a follow-up per Dr. Osei’s plan.',
    kpis: [{ label: 'Treatments', value: 6 }, { label: 'Next Visit', value: '4 days' }, { label: 'Rewards Points', value: 280 }],
    actionItems: [{ title: 'Confirm appointment', detail: 'Thu 2 PM with Dr. Osei', tone: 'accent' }, { title: 'Pre-treatment form pending', detail: 'Complete before your visit', tone: 'warning' }],
    activity: [{ label: 'Appointment confirmed for Thursday', time: '1h ago' }, { label: 'Treatment plan updated', time: '2 weeks ago' }, { label: 'Completed a follow-up visit', time: '2 mo ago' }, { label: 'Redeemed a loyalty reward', time: '3 mo ago' }, { label: 'First consultation', time: '8 mo ago' }],
    tableColumns: ['Treatment', 'Provider'], filters: ['Upcoming', 'Pending Forms', 'Completed'],
    itemTypes: ['Consultation', 'Injectable Treatment', 'Laser Resurfacing', 'Follow-up Visit', 'Skin Health Review'],
    details: ['Thu 2 PM', 'Forms pending', 'Completed', 'Next month', 'Completed'],
  },
  {
    seed: 3106, name: 'Larkspur & Stone — Guest App', category: 'Mobile-Food', paletteId: 'crema-fraunces-light',
    description: 'Guest companion app for a boutique hotel group — bookings, requests, concierge.',
    appName: 'Larkspur & Stone', navIcon: 'bed', primaryFeaturePascal: 'Stays', primaryFeatureLabel: 'Stays',
    greetingName: 'Elena Beaumont', greetingInsight: 'Your stay at The Stonecroft begins in 3 days.',
    insightCard: 'Your room includes a garden terrace — the concierge recommends the 6 PM vineyard tour.',
    kpis: [{ label: 'Upcoming Stays', value: 1 }, { label: 'Nights (YTD)', value: 12, delta: 20 }, { label: 'Member Tier', value: 'Gold' }],
    actionItems: [{ title: 'Check-in opens tomorrow', detail: 'The Stonecroft, Garden Room', tone: 'accent' }, { title: 'Request late checkout', detail: 'One tap request', tone: 'default' }],
    activity: [{ label: 'Reservation confirmed at The Stonecroft', time: '2h ago' }, { label: 'Requested a late checkout — approved', time: '1 mo ago' }, { label: 'Stayed at Larkspur House', time: '2 mo ago' }, { label: 'Earned Gold tier status', time: '3 mo ago' }, { label: 'Joined the guest program', time: '1 yr ago' }],
    tableColumns: ['Property', 'Room Type'], filters: ['Upcoming', 'Requested', 'Past'],
    itemTypes: ['The Stonecroft', 'Larkspur House', 'Millbrook Inn', 'The Stonecroft', 'Larkspur House'],
    details: ['Garden Room', 'Coastal Suite', 'Family Suite', 'Loft Suite', 'Vineyard View'],
  },
  {
    seed: 3107, name: 'Ferrous & Kin — Field App', category: 'Mobile-Logistics', paletteId: 'precision-ember-dark',
    description: 'Field app for construction site supervisors — daily logs, crew, and inspections.',
    appName: 'Ferrous & Kin', navIcon: 'construct', primaryFeaturePascal: 'Sites', primaryFeatureLabel: 'Job Sites',
    greetingName: 'Marit Lund', greetingInsight: 'The Kestrel site passes inspection today.',
    insightCard: 'Kestrel House is 2 days ahead of schedule — consider pulling the Birchwood crew forward.',
    kpis: [{ label: 'Active Sites', value: 11, delta: 10 }, { label: 'Crew Deployed', value: 84 }, { label: 'Safety Days', value: 62 }],
    actionItems: [{ title: 'Inspection today', detail: 'Kestrel House, 10 AM', tone: 'accent' }, { title: 'Weather delay flagged', detail: 'Birchwood Pavilion', tone: 'warning' }],
    activity: [{ label: 'Daily log submitted for Kestrel House', time: '1h ago' }, { label: 'Crew reassigned to Birchwood', time: '4h ago' }, { label: 'Inspection passed at Northgate', time: 'yesterday' }, { label: 'Material delivery logged', time: 'yesterday' }, { label: 'Site opened — Coppermill Retail', time: '3 days ago' }],
    tableColumns: ['Site', 'Project Type'], filters: ['On Schedule', 'Delayed', 'Complete'],
    itemTypes: ['Multi-family Build', 'Commercial Renovation', 'Public Pavilion', 'Retail Buildout', 'Road Infrastructure'],
    details: ['On schedule', 'Weather delay', 'Complete', 'On schedule', 'Permit pending'],
  },
  {
    seed: 3108, name: 'Alderbrook Veterinary — Client App', category: 'Mobile-Healthcare', paletteId: 'wellness-teal-dark',
    description: 'Client app for a veterinary specialty hospital — appointments and patient records.',
    appName: 'Alderbrook Veterinary', navIcon: 'paw', primaryFeaturePascal: 'Patients', primaryFeatureLabel: 'My Pets',
    greetingName: 'Elin Torvald', greetingInsight: 'Your pet’s follow-up is in 2 days.',
    insightCard: 'Bramble’s lab results are ready — Dr. Osei added a note to the chart.',
    kpis: [{ label: 'Pets Registered', value: 2 }, { label: 'Next Visit', value: '2 days' }, { label: 'Vaccines Due', value: 1 }],
    actionItems: [{ title: 'Lab results ready', detail: 'Bramble — annual panel', tone: 'accent' }, { title: 'Vaccine due soon', detail: 'Rabies booster', tone: 'warning' }],
    activity: [{ label: 'Lab results received for Bramble', time: '2h ago' }, { label: 'Appointment confirmed for Thursday', time: '1 day ago' }, { label: 'Prescription refilled', time: '1 week ago' }, { label: 'Completed a wellness exam', time: '1 mo ago' }, { label: 'Registered a new pet', time: '2 mo ago' }],
    tableColumns: ['Pet', 'Care Focus'], filters: ['Upcoming', 'Results Ready', 'Completed'],
    itemTypes: ['Bramble — Labrador', 'Juniper — Tabby Cat'],
    details: ['Annual wellness', 'Sports medicine follow-up', 'Results ready', 'Vaccine due', 'Completed'],
  },
  {
    seed: 3109, name: 'Marrow & Ash Roasters — Loyalty App', category: 'Mobile-Food', paletteId: 'food-amber-light',
    description: 'Subscription and loyalty app for a specialty coffee roaster.',
    appName: 'Marrow & Ash Roasters', navIcon: 'cafe', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'Orders',
    greetingName: 'Owen Fairbanks', greetingInsight: 'Your next bag ships in 2 days.',
    insightCard: 'You’ve reordered the Ethiopia Yirgacheffe 3 times — want to make it your subscription default?',
    kpis: [{ label: 'Bags (YTD)', value: 18, delta: 12 }, { label: 'Loyalty Points', value: 640 }, { label: 'Next Ship', value: '2 days' }],
    actionItems: [{ title: 'Subscription renews Friday', detail: 'Ethiopia Yirgacheffe, 12oz', tone: 'accent' }, { title: 'New seasonal roast available', detail: 'Guatemala Antigua', tone: 'default' }],
    activity: [{ label: 'Subscription order shipped', time: '2h ago' }, { label: 'Redeemed 100 points for a free bag', time: '1 week ago' }, { label: 'Rated Ethiopia Yirgacheffe 5 stars', time: '2 weeks ago' }, { label: 'Updated subscription frequency', time: '1 mo ago' }, { label: 'Joined the loyalty program', time: '6 mo ago' }],
    tableColumns: ['Roast', 'Format'], filters: ['Shipping', 'Processing', 'Delivered'],
    itemTypes: ['Ethiopia Yirgacheffe', 'Guatemala Antigua', 'Colombia Reserve', 'Kenya AA', 'House Blend'],
    details: ['12oz bag', '12oz bag', '5lb wholesale', '12oz bag', '2lb bag'],
  },
  {
    seed: 3110, name: 'Blackridge Field Ops — Technician App', category: 'Mobile-Logistics', paletteId: 'precision-acid-dark',
    description: 'Field dispatch app for home service technicians.',
    appName: 'Blackridge Field Ops', navIcon: 'map', primaryFeaturePascal: 'Jobs', primaryFeatureLabel: 'Jobs',
    greetingName: 'Diego Álvarez', greetingInsight: 'You have 4 jobs today, starting at 9 AM.',
    insightCard: 'Your 11 AM job is 12 minutes from your current stop — you’re on pace to arrive early.',
    kpis: [{ label: "Today's Jobs", value: 4 }, { label: 'Avg. Rating', value: 4.9 }, { label: 'This Week', value: 18, delta: 6 }],
    actionItems: [{ title: 'Next job in 25 minutes', detail: 'HVAC Repair, 220 Marchbanks Terrace', tone: 'accent' }, { title: 'Parts needed for 2 PM job', detail: 'Confirm availability', tone: 'warning' }],
    activity: [{ label: 'Completed job at Coppermill Foods', time: '1h ago' }, { label: 'En route to next job', time: '15m ago' }, { label: 'Customer rated your visit 5 stars', time: 'yesterday' }, { label: 'Parts request submitted', time: 'yesterday' }, { label: 'Started shift', time: 'today' }],
    tableColumns: ['Customer', 'Job Type'], filters: ['Dispatched', 'En Route', 'Completed'],
    itemTypes: ['HVAC Repair', 'Plumbing Service', 'Electrical Inspection', 'Appliance Install', 'Emergency Call'],
    details: ['9 AM', '11 AM', '2 PM', '4 PM', 'Completed'],
  },
]

export const mobileBatch1 = specs.map((spec) => {
  // Mobile list rows are named by the item itself (class name, property,
  // treatment, job type) rather than a generated company/person name.
  const realRows = spec.itemTypes.slice(0, 5).map((item, i) => ({
    cells: [item, spec.details[i % spec.details.length]],
    status: spec.filters[i % spec.filters.length],
  }))
  return {
    name: spec.name,
    category: spec.category,
    paletteId: spec.paletteId,
    config: {
      description: spec.description,
      appName: spec.appName,
      navIcon: spec.navIcon,
      primaryFeaturePascal: spec.primaryFeaturePascal,
      primaryFeatureLabel: spec.primaryFeatureLabel,
      greetingName: spec.greetingName,
      greetingInsight: spec.greetingInsight,
      insightCard: spec.insightCard,
      kpis: spec.kpis,
      actionItems: spec.actionItems,
      activity: spec.activity,
      primaryTable: { columns: spec.tableColumns, filters: spec.filters, rows: realRows },
    },
  }
})
