const specs = [
  {
    name: 'Harrow & Voss — Client App', category: 'Mobile-Legal', paletteId: 'counsel-navy-light',
    description: 'Client portal app for a boutique law firm — case status, documents, secure messaging.',
    appName: 'Harrow & Voss', navIcon: 'briefcase', primaryFeaturePascal: 'Matters', primaryFeatureLabel: 'My Matters',
    greetingName: 'Marguerite Sato', greetingInsight: 'Your estate plan signing is scheduled for Thursday.',
    insightCard: 'Your document package is ready for e-signature — completing it today keeps your matter on schedule.',
    kpis: [{ label: 'Active Matters', value: 1 }, { label: 'Documents', value: 8 }, { label: 'Next Deadline', value: '3 days' }],
    actionItems: [{ title: 'Sign estate documents', detail: 'Due before Thursday', tone: 'accent' }, { title: 'New message from A. Harrow', detail: 'Re: signing appointment', tone: 'default' }],
    activity: [{ label: 'Document package sent for signature', time: '2h ago' }, { label: 'Attorney note added to your matter', time: 'yesterday' }, { label: 'Signing appointment confirmed', time: '2 days ago' }, { label: 'Initial consultation completed', time: '3 weeks ago' }, { label: 'Matter opened', time: '1 mo ago' }],
    tableColumns: ['Matter', 'Attorney'], filters: ['Active', 'Awaiting Signature', 'Closed'],
    itemTypes: ['Estate Planning', 'Trust Amendment', 'Power of Attorney'],
    details: ['A. Harrow', 'A. Harrow', 'E. Voss'],
  },
  {
    name: 'Meridian Relocation — Employee App', category: 'Mobile-Logistics', paletteId: 'open-air-light',
    description: 'Companion app for employees going through a corporate relocation.',
    appName: 'Meridian Relocation', navIcon: 'airplane', primaryFeaturePascal: 'Move', primaryFeatureLabel: 'My Move',
    greetingName: 'James O’Brien', greetingInsight: 'Your household goods arrive in 4 days.',
    insightCard: 'Your temporary housing lease ends in 2 weeks — your consultant recommends finalizing a home search this week.',
    kpis: [{ label: 'Move Progress', value: 68, suffix: '%' }, { label: 'Days to Arrival', value: 4 }, { label: 'Open Tasks', value: 3 }],
    actionItems: [{ title: 'Confirm delivery window', detail: 'Household goods, Thursday', tone: 'accent' }, { title: 'Home search update needed', detail: 'Consultant is waiting on your feedback', tone: 'warning' }],
    activity: [{ label: 'Household goods shipment confirmed', time: '3h ago' }, { label: 'Temporary housing extended 2 weeks', time: 'yesterday' }, { label: 'School search list shared', time: '3 days ago' }, { label: 'Visa documents approved', time: '1 week ago' }, { label: 'Relocation kicked off', time: '6 weeks ago' }],
    tableColumns: ['Task', 'Consultant'], filters: ['In Progress', 'Pending', 'Complete'],
    itemTypes: ['Household Goods Shipment', 'Temporary Housing', 'School Search', 'Home Sale Assistance', 'Visa Processing'],
    details: ['M. Ellison', 'M. Ellison', 'S. Kwan', 'Complete', 'Complete'],
  },
  {
    name: 'Ashford Scholars — Student App', category: 'Mobile-Education', paletteId: 'cobalt-pop-light',
    description: 'Student companion app for a private tutoring and test prep firm.',
    appName: 'Ashford Scholars', navIcon: 'book', primaryFeaturePascal: 'Sessions', primaryFeatureLabel: 'My Sessions',
    greetingName: 'Tomás Kowalski', greetingInsight: 'Your SAT practice score improved 60 points this month.',
    insightCard: 'Your next practice test is Saturday — review the algebra section, it’s your lowest-scoring area right now.',
    kpis: [{ label: 'Practice Score', value: 1420, delta: 4 }, { label: 'Sessions This Month', value: 6 }, { label: 'Test Date', value: '32 days' }],
    actionItems: [{ title: 'Practice test Saturday', detail: '9 AM, full-length SAT', tone: 'accent' }, { title: 'Homework due tomorrow', detail: 'Algebra problem set', tone: 'warning' }],
    activity: [{ label: 'Completed a practice test — scored 1420', time: '1 day ago' }, { label: 'Tutor left feedback on your essay', time: '2 days ago' }, { label: 'Session completed with M. Reyes', time: '4 days ago' }, { label: 'New homework assigned', time: '4 days ago' }, { label: 'Enrolled in SAT Prep program', time: '2 mo ago' }],
    tableColumns: ['Program', 'Tutor'], filters: ['Active', 'Test Scheduled', 'Completed'],
    itemTypes: ['SAT Prep', 'Essay Coaching', 'Algebra Review'],
    details: ['M. Reyes', 'M. Reyes', 'K. Sharma'],
  },
  {
    name: 'Ashgrove Woodworks — Client App', category: 'Mobile-Creative', paletteId: 'clay-sand-light',
    description: 'Client app for a custom furniture workshop — commission progress and approvals.',
    appName: 'Ashgrove Woodworks', navIcon: 'hammer', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Priya Nair', greetingInsight: 'Your dining table enters final finishing this week.',
    insightCard: 'Your table’s hardware selection is due — choosing today keeps delivery on the original 8-week timeline.',
    kpis: [{ label: 'Progress', value: 82, suffix: '%' }, { label: 'Est. Delivery', value: '2 wks' }, { label: 'Approvals Needed', value: 1 }],
    actionItems: [{ title: 'Approve hardware selection', detail: 'Brass pulls, brushed finish', tone: 'accent' }, { title: 'Final finishing photos ready', detail: 'Review before delivery', tone: 'default' }],
    activity: [{ label: 'Final finishing began', time: '1 day ago' }, { label: 'Hardware options sent for approval', time: '3 days ago' }, { label: 'Joinery completed', time: '1 week ago' }, { label: 'Wood selection confirmed', time: '3 weeks ago' }, { label: 'Commission started', time: '5 weeks ago' }],
    tableColumns: ['Piece', 'Craftsperson'], filters: ['In Progress', 'Finishing', 'Delivered'],
    itemTypes: ['Dining Table'],
    details: ['A. Reyes'],
  },
  {
    name: 'Fernbrook Studio — Member App', category: 'Mobile-Healthcare', paletteId: 'wellness-teal-dark',
    description: 'Member app for a private yoga and wellness studio.',
    appName: 'Fernbrook Studio', navIcon: 'body', primaryFeaturePascal: 'Classes', primaryFeatureLabel: 'Classes',
    greetingName: 'Naomi Sato', greetingInsight: 'You’ve practiced 3 times this week — one more for your goal.',
    insightCard: 'Your usual Tuesday breathwork session has 2 spots left — you haven’t missed one in 6 weeks.',
    kpis: [{ label: 'Sessions (mo)', value: 12, delta: 9 }, { label: 'Streak', value: 4, suffix: 'wk' }, { label: 'Membership', value: 'Unlimited' }],
    actionItems: [{ title: 'Confirm Tuesday breathwork', detail: '2 spots left', tone: 'accent' }, { title: 'Membership renews in 5 days', detail: 'Auto-renew is on', tone: 'default' }],
    activity: [{ label: 'Attended Tuesday breathwork', time: '2 days ago' }, { label: 'Booked Saturday recovery session', time: '3 days ago' }, { label: 'Completed a private session', time: '1 week ago' }, { label: 'Reached a 4-week streak', time: '1 week ago' }, { label: 'Joined the studio', time: '4 mo ago' }],
    tableColumns: ['Class', 'Instructor'], filters: ['Confirmed', 'Waitlisted', 'Completed'],
    itemTypes: ['Breathwork', 'Small-Group Practice', 'Private Session', 'Recovery Session'],
    details: ['Tue 6 PM', 'Waitlist #1', 'Completed', 'Sat 10 AM'],
  },
  {
    name: 'Ferrous Hollow Vineyards — Club App', category: 'Mobile-Food', paletteId: 'supper-club-dark',
    description: 'Wine club member app for a boutique winery.',
    appName: 'Ferrous Hollow Vineyards', navIcon: 'wine', primaryFeaturePascal: 'Shipments', primaryFeatureLabel: 'Shipments',
    greetingName: 'Kofi Mensah', greetingInsight: 'Your spring shipment ships Friday.',
    insightCard: 'This shipment includes a new Reserve Pinot — reviews from other members have been excellent.',
    kpis: [{ label: 'Bottles (YTD)', value: 24, delta: 9 }, { label: 'Club Tier', value: 'Reserve' }, { label: 'Next Ship', value: '3 days' }],
    actionItems: [{ title: 'Confirm shipping address', detail: 'Spring shipment, ships Friday', tone: 'accent' }, { title: 'Rate your last shipment', detail: 'Help us pick your next selections', tone: 'default' }],
    activity: [{ label: 'Spring shipment prepared', time: '1 day ago' }, { label: 'Rated the winter shipment 5 stars', time: '2 weeks ago' }, { label: 'Upgraded to Reserve tier', time: '1 mo ago' }, { label: 'Visited the tasting room', time: '2 mo ago' }, { label: 'Joined the wine club', time: '1 yr ago' }],
    tableColumns: ['Shipment', 'Wines'], filters: ['Shipping', 'Processing', 'Delivered'],
    itemTypes: ['Spring Shipment', 'Winter Shipment', 'Reserve Add-On'],
    details: ['6 bottles', '6 bottles', '2 bottles'],
  },
  {
    name: 'Ironclad Performance — Coach App', category: 'Mobile-Productivity', paletteId: 'track-red-light',
    description: 'Coach-facing app for a personal training business — client sessions and programming.',
    appName: 'Ironclad Coaching', navIcon: 'fitness', primaryFeaturePascal: 'Clients', primaryFeatureLabel: 'My Clients',
    greetingName: 'Marcus Rivera', greetingInsight: 'You have 5 sessions today, starting at 6 AM.',
    insightCard: 'Dana Kessler hasn’t logged a session in 9 days — a quick check-in message usually re-engages clients like this.',
    kpis: [{ label: "Today's Sessions", value: 5 }, { label: 'Active Clients', value: 24 }, { label: 'This Week', value: 22, delta: 8 }],
    actionItems: [{ title: 'Check in with Dana Kessler', detail: 'No session in 9 days', tone: 'warning' }, { title: 'Next session in 40 minutes', detail: 'Aisha Patel, Strength Program', tone: 'accent' }],
    activity: [{ label: 'Completed session with Aisha Patel', time: '1h ago' }, { label: 'Updated program for James O’Brien', time: '3h ago' }, { label: 'New client onboarded', time: 'yesterday' }, { label: 'Client hit a new PR', time: 'yesterday' }, { label: 'Program review completed', time: '2 days ago' }],
    tableColumns: ['Client', 'Program'], filters: ['Active', 'Program Review', 'Paused'],
    itemTypes: ['Aisha Patel', 'James O’Brien', 'Dana Kessler', 'Priya Sharma', 'Marcus Webb'],
    details: ['Strength Program', 'Weight Loss', 'Sport-Specific', 'General Fitness', 'Post-Injury'],
  },
  {
    name: 'Bellcourt Events — Client App', category: 'Mobile-Events', paletteId: 'gallery-red-light',
    description: 'Client app for a wedding and event planning company.',
    appName: 'Bellcourt Events', navIcon: 'calendar', primaryFeaturePascal: 'Timeline', primaryFeatureLabel: 'My Timeline',
    greetingName: 'Corinne Voss', greetingInsight: 'Your wedding is 62 days away.',
    insightCard: 'Your final headcount is due in 2 weeks — vendors need this number to finalize catering and seating.',
    kpis: [{ label: 'Days to Event', value: 62 }, { label: 'Tasks Complete', value: 74, suffix: '%' }, { label: 'Vendors Booked', value: 8 }],
    actionItems: [{ title: 'Submit final headcount', detail: 'Due in 2 weeks', tone: 'warning' }, { title: 'Approve floral proposal', detail: 'From your florist', tone: 'accent' }],
    activity: [{ label: 'Floral proposal received', time: '4h ago' }, { label: 'Venue walkthrough completed', time: '3 days ago' }, { label: 'Caterer confirmed', time: '1 week ago' }, { label: 'Save-the-dates sent', time: '3 weeks ago' }, { label: 'Planning kicked off', time: '4 mo ago' }],
    tableColumns: ['Task', 'Vendor'], filters: ['Upcoming', 'Awaiting You', 'Complete'],
    itemTypes: ['Final Headcount', 'Floral Approval', 'Catering Confirmed', 'Save-the-Dates', 'Venue Booking'],
    details: ['Due in 2 weeks', 'Your approval needed', 'Complete', 'Complete', 'Complete'],
  },
  {
    name: 'Aldergate Bespoke — Client App', category: 'Mobile-Creative', paletteId: 'gallery-red-light',
    description: 'Client app for a bespoke tailoring house — fitting schedule and order status.',
    appName: 'Aldergate Bespoke', navIcon: 'shirt', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'My Orders',
    greetingName: 'Thomas Girard', greetingInsight: 'Your suit is ready for its final fitting.',
    insightCard: 'Your final fitting is scheduled for Thursday — this is typically the last appointment before delivery.',
    kpis: [{ label: 'Active Orders', value: 1 }, { label: 'Fittings Complete', value: 2 }, { label: 'Est. Ready', value: '1 wk' }],
    actionItems: [{ title: 'Confirm final fitting', detail: 'Thursday 2 PM', tone: 'accent' }, { title: 'Select lining fabric', detail: 'Choose before Thursday', tone: 'default' }],
    activity: [{ label: 'Second fitting completed', time: '1 week ago' }, { label: 'Cutting began', time: '2 weeks ago' }, { label: 'Fabric selection confirmed', time: '3 weeks ago' }, { label: 'First fitting completed', time: '3 weeks ago' }, { label: 'Order placed', time: '5 weeks ago' }],
    tableColumns: ['Garment', 'Tailor'], filters: ['In Progress', 'Fitting', 'Ready'],
    itemTypes: ['Bespoke Suit'],
    details: ['Fitting Thursday'],
  },
  {
    name: 'Aerolume Jet Charter — Member App', category: 'Mobile-Logistics', paletteId: 'precision-ember-dark',
    description: 'Member app for a private aviation charter company.',
    appName: 'Aerolume', navIcon: 'airplane', primaryFeaturePascal: 'Flights', primaryFeatureLabel: 'My Flights',
    greetingName: 'Grace Whitfield', greetingInsight: 'Your flight to Aspen departs tomorrow at 9 AM.',
    insightCard: 'Weather in Aspen is clear for your arrival window — no delays expected on tomorrow’s flight.',
    kpis: [{ label: 'Flights (YTD)', value: 14, delta: 8 }, { label: 'Member Tier', value: 'Elite' }, { label: 'Next Flight', value: 'Tomorrow' }],
    actionItems: [{ title: 'Confirm ground transport', detail: 'Aspen arrival, tomorrow 11 AM', tone: 'accent' }, { title: 'Catering preferences', detail: 'Set for tomorrow’s flight', tone: 'default' }],
    activity: [{ label: 'Flight confirmed to Aspen', time: '2h ago' }, { label: 'Catering order placed', time: '1 day ago' }, { label: 'Completed flight from Miami', time: '1 week ago' }, { label: 'Upgraded to Elite tier', time: '2 mo ago' }, { label: 'Joined the membership program', time: '8 mo ago' }],
    tableColumns: ['Route', 'Aircraft'], filters: ['Confirmed', 'Pending', 'Completed'],
    itemTypes: ['New York – Aspen', 'Miami – Nassau', 'Chicago – Teterboro'],
    details: ['Gulfstream G650', 'Completed', 'Completed'],
  },
]

export const mobileBatch2 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: {
    description: spec.description,
    appName: spec.appName,
    navIcon: spec.navIcon,
    primaryFeaturePascal: spec.primaryFeaturePascal,
    primaryFeatureLabel: spec.primaryFeatureLabel,
    greetingName: spec.greetingName,
    greetingInsight: spec.greetingInsight,
    insightCard: spec.insightCard,
    kpis: spec.kpis,
    actionItems: spec.actionItems,
    activity: spec.activity,
    primaryTable: {
      columns: spec.tableColumns,
      filters: spec.filters,
      rows: spec.itemTypes.map((item, i) => ({
        cells: [item, spec.details[i % spec.details.length]],
        status: spec.filters[i % spec.filters.length],
      })),
    },
  },
}))
