const specs = [
  {
    name: 'Meridian Sail Loft — Client App', category: 'Mobile-Creative', paletteId: 'precision-sky-dark',
    description: 'Client app for a custom sailmaking loft — commission status and delivery.',
    appName: 'Meridian Sail Loft', navIcon: 'boat', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Skipper Freya Lindstrom', greetingInsight: 'Your spinnaker clears final inspection this week.',
    insightCard: 'The sailmaker finished the panel stitching ahead of schedule — final inspection is set for Thursday, in time for the weekend regatta.',
    kpis: [{ label: 'Commission Progress', value: 88, suffix: '%' }, { label: 'Est. Delivery', value: 'Thursday' }, { label: 'Commission Value', value: '8.4K' }],
    actionItems: [{ title: 'Final inspection Thursday', detail: 'Ready in time for the regatta', tone: 'accent' }, { title: 'Confirm delivery to marina', detail: 'Or pickup at loft', tone: 'default' }],
    activity: [{ label: 'Panel stitching completed', time: '1 day ago' }, { label: 'Panels cut', time: '1 week ago' }, { label: 'Design approved', time: '2 weeks ago' }, { label: 'Commission started', time: '3 weeks ago' }, { label: 'Became a client', time: '4 yrs ago' }],
    tableColumns: ['Milestone', 'Sailmaker'], filters: ['Complete', 'In Progress', 'Upcoming'],
    itemTypes: ['Panel Stitching', 'Final Inspection'], details: ['Complete', 'Thursday'],
  },
  {
    name: 'Aldergate Concert Piano — Venue App', category: 'Mobile-Business', paletteId: 'midnight-press-dark',
    description: 'Venue app for a concert piano rental service — rental status and tuning schedule.',
    appName: 'Aldergate Concert Piano', navIcon: 'musical-notes', primaryFeaturePascal: 'Rental', primaryFeatureLabel: 'My Rental',
    greetingName: 'Venue Director Casimir Wren', greetingInsight: 'Tomorrow’s tuning is confirmed ahead of the performance.',
    insightCard: 'The tuner will arrive three hours before doors open — enough time for a full climate-adjustment pass before the recital.',
    kpis: [{ label: 'Rental Status', value: 'Active' }, { label: 'Next Tuning', value: 'Tomorrow' }, { label: 'Venue Since', value: '6 yrs' }],
    actionItems: [{ title: 'Tuning confirmed for tomorrow', detail: '3 hours before doors', tone: 'accent' }, { title: 'Confirm load-in access', detail: 'For piano delivery crew', tone: 'default' }],
    activity: [{ label: 'Tuning confirmed', time: '2h ago' }, { label: 'Piano delivered to venue', time: '1 day ago' }, { label: 'Rental booked', time: '2 weeks ago' }, { label: 'Previous rental completed', time: '2 mo ago' }, { label: 'Became a venue account', time: '6 yrs ago' }],
    tableColumns: ['Instrument', 'Tuner'], filters: ['Delivered', 'Tuning Scheduled', 'Performance Ready'],
    itemTypes: ['Concert Grand Rental'], details: ['Tuning tomorrow'],
  },
  {
    name: 'Ashgrove Upholstery — Client App', category: 'Mobile-Creative', paletteId: 'clay-sand-light',
    description: 'Client app for a leather furniture upholstery workshop — commission progress.',
    appName: 'Ashgrove Upholstery', navIcon: 'construct', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Odile Fontaine', greetingInsight: 'Your sofa reupholstery finishes this week.',
    insightCard: 'The upholsterer finished fitting the leather panels ahead of schedule — final stitching is the only step remaining.',
    kpis: [{ label: 'Commission Progress', value: 84, suffix: '%' }, { label: 'Est. Completion', value: '3 days' }, { label: 'Commission Value', value: '2.2K' }],
    actionItems: [{ title: 'Final stitching this week', detail: 'Ready for delivery soon', tone: 'accent' }, { title: 'Approve final leather sample', detail: 'Confirmed match', tone: 'default' }],
    activity: [{ label: 'Leather panels fitted', time: '1 day ago' }, { label: 'Frame repair completed', time: '2 weeks ago' }, { label: 'Frame stripped', time: '3 weeks ago' }, { label: 'Commission started', time: '1 mo ago' }, { label: 'Became a client', time: '2 yrs ago' }],
    tableColumns: ['Piece', 'Upholsterer'], filters: ['Stripping', 'Frame Repair', 'Upholstery'],
    itemTypes: ['Antique Sofa Reupholstery'], details: ['Final stitching'],
  },
  {
    name: 'Frostwork Culinary Art — Client App', category: 'Mobile-Business', paletteId: 'precision-acid-dark',
    description: 'Client app for an ice sculpture and culinary art studio — event status.',
    appName: 'Frostwork Culinary Art', navIcon: 'snow', primaryFeaturePascal: 'Event', primaryFeatureLabel: 'My Event',
    greetingName: 'Event Planner Isolde March', greetingInsight: 'Your centerpiece carve begins tomorrow.',
    insightCard: 'The sculptor finalized the design a day early — carving begins tomorrow with delivery scheduled two hours before your event.',
    kpis: [{ label: 'Event Progress', value: 62, suffix: '%' }, { label: 'Delivery Window', value: '2 hrs before' }, { label: 'Event Value', value: '3.2K' }],
    actionItems: [{ title: 'Carving begins tomorrow', detail: 'Design finalized early', tone: 'accent' }, { title: 'Confirm delivery address', detail: 'Venue loading dock', tone: 'default' }],
    activity: [{ label: 'Design finalized', time: '4h ago' }, { label: 'Design draft approved', time: '3 days ago' }, { label: 'Event booked', time: '3 weeks ago' }, { label: 'Previous event completed', time: '3 mo ago' }, { label: 'Became a client', time: '1 yr ago' }],
    tableColumns: ['Carve', 'Sculptor'], filters: ['Design', 'Carving', 'Delivery'],
    itemTypes: ['Gala Centerpiece'], details: ['Carving tomorrow'],
  },
  {
    name: 'Aldercroft Eyewear Atelier — Client App', category: 'Mobile-Lifestyle', paletteId: 'ledger-ivory-light',
    description: 'Client app for a bespoke eyewear atelier — commission status and fittings.',
    appName: 'Aldercroft Eyewear', navIcon: 'glasses', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Phineas Okoro', greetingInsight: 'Your frame clears final polish this week.',
    insightCard: 'The frame maker finished shaping ahead of schedule — final polish is the only step remaining before your lenses are fitted.',
    kpis: [{ label: 'Commission Progress', value: 76, suffix: '%' }, { label: 'Est. Completion', value: '1 wk' }, { label: 'Commission Value', value: '1.4K' }],
    actionItems: [{ title: 'Final polish this week', detail: 'Lens fitting to follow', tone: 'accent' }, { title: 'Confirm prescription with optician', detail: 'Final step before lens order', tone: 'default' }],
    activity: [{ label: 'Acetate shaping completed', time: '2 days ago' }, { label: 'Fitting appointment completed', time: '1 week ago' }, { label: 'Design consultation', time: '2 weeks ago' }, { label: 'Commission started', time: '3 weeks ago' }, { label: 'Became a client', time: '3 yrs ago' }],
    tableColumns: ['Frame', 'Frame Maker'], filters: ['Shaping', 'Fitting', 'Polishing'],
    itemTypes: ['Custom Acetate Frame'], details: ['Final polish'],
  },
  {
    name: 'Ashgrove Highland Tailors — Client App', category: 'Mobile-Lifestyle', paletteId: 'forest-market-light',
    description: 'Client app for a Highland dress tailor — commission status for wedding parties.',
    appName: 'Ashgrove Highland Tailors', navIcon: 'shirt', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Angus Fairweather', greetingInsight: 'Your kilt fitting is scheduled this week.',
    insightCard: 'The tailor finished hand-pleating your kilt ahead of schedule — final fitting is set for Wednesday, well before the wedding.',
    kpis: [{ label: 'Commission Progress', value: 71, suffix: '%' }, { label: 'Est. Fitting', value: 'Wednesday' }, { label: 'Commission Value', value: '780' }],
    actionItems: [{ title: 'Fitting scheduled Wednesday', detail: 'Ahead of schedule', tone: 'accent' }, { title: 'Confirm sporran selection', detail: 'Awaiting your choice', tone: 'default' }],
    activity: [{ label: 'Hand-pleating completed', time: '1 day ago' }, { label: 'Tartan cut', time: '1 week ago' }, { label: 'Measurements confirmed', time: '2 weeks ago' }, { label: 'Commission started', time: '3 weeks ago' }, { label: 'Became a client', time: '1 yr ago' }],
    tableColumns: ['Piece', 'Tailor'], filters: ['Cutting', 'Pleating', 'Fitting'],
    itemTypes: ['Wedding Party Kilt'], details: ['Fitting Wednesday'],
  },
  {
    name: 'Fernbrook Mycology — Wholesale App', category: 'Mobile-Food', paletteId: 'moss-archive-light',
    description: 'Wholesale account app for a wild mushroom foraging company — standing orders.',
    appName: 'Fernbrook Mycology', navIcon: 'leaf', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'My Orders',
    greetingName: 'Chef Halcyon Reyes', greetingInsight: 'This week’s chanterelle harvest is ready for delivery.',
    insightCard: 'The forager found an unusually large chanterelle flush this week — your standing order includes an extra 2 lbs at no charge.',
    kpis: [{ label: 'Standing Order', value: 'Weekly' }, { label: 'This Week’s Allocation', value: '4 lbs' }, { label: 'Account Since', value: '3 yrs' }],
    actionItems: [{ title: 'Bonus allocation included', detail: 'Extra 2 lbs, no charge', tone: 'accent' }, { title: 'Confirm delivery window', detail: 'Standard weekly slot', tone: 'default' }],
    activity: [{ label: 'Bonus allocation added', time: '3h ago' }, { label: 'Weekly order confirmed', time: '1 day ago' }, { label: 'Last delivery received', time: '1 week ago' }, { label: 'Order size increased', time: '1 mo ago' }, { label: 'Became a wholesale account', time: '3 yrs ago' }],
    tableColumns: ['Order', 'Forager'], filters: ['Standing', 'Special', 'Delivered'],
    itemTypes: ['Weekly Chanterelle Order'], details: ['Ready for delivery'],
  },
  {
    name: 'Blackridge Cinematography — Client App', category: 'Mobile-Business', paletteId: 'precision-acid-dark',
    description: 'Client app for an aerial cinematography studio — shoot status and deliverables.',
    appName: 'Blackridge Cinematography', navIcon: 'videocam', primaryFeaturePascal: 'Shoot', primaryFeatureLabel: 'My Shoot',
    greetingName: 'Producer Emrys Falk', greetingInsight: 'Your listing footage is ready for review.',
    insightCard: 'The edit came back a day early — the drone pilot flagged the golden-hour pass as the strongest footage in the set.',
    kpis: [{ label: 'Shoot Progress', value: 90, suffix: '%' }, { label: 'Est. Delivery', value: 'Today' }, { label: 'Shoot Value', value: '2.8K' }],
    actionItems: [{ title: 'Review edited footage', detail: 'Ready a day early', tone: 'accent' }, { title: 'Approve final cut', detail: 'For listing publication', tone: 'default' }],
    activity: [{ label: 'Edit delivered for review', time: '2h ago' }, { label: 'Filming completed', time: '2 days ago' }, { label: 'FAA waiver confirmed', time: '4 days ago' }, { label: 'Shoot booked', time: '2 weeks ago' }, { label: 'Became a client', time: '1 yr ago' }],
    tableColumns: ['Shoot', 'Pilot'], filters: ['Permitting', 'Filming', 'Editing'],
    itemTypes: ['Real Estate Campaign'], details: ['Ready for review'],
  },
  {
    name: 'Aldergate Cartography — Collector App', category: 'Mobile-Creative', paletteId: 'paper-oxblood-light',
    description: 'Collector app for an antique map and globe dealer — watchlist and authentication.',
    appName: 'Aldergate Cartography', navIcon: 'map', primaryFeaturePascal: 'Watchlist', primaryFeatureLabel: 'My Watchlist',
    greetingName: 'Professor Linnea Voss', greetingInsight: 'A 17th-century atlas on your watchlist just cleared authentication.',
    insightCard: 'The atlas you flagged came back from authentication with confirmed first-state plates — rarer than the initial listing suggested.',
    kpis: [{ label: 'Watchlist Items', value: 4 }, { label: 'Pieces Owned', value: 11 }, { label: 'Collection Value', value: '240K' }],
    actionItems: [{ title: 'Authentication result received', detail: 'Confirmed first-state plates', tone: 'accent' }, { title: 'Insurance appraisal due', detail: 'Annual renewal', tone: 'default' }],
    activity: [{ label: 'Authentication result received', time: '5h ago' }, { label: 'Purchased a nautical chart', time: '3 weeks ago' }, { label: 'Appraisal completed', time: '2 mo ago' }, { label: 'Added item to watchlist', time: '2 mo ago' }, { label: 'Became a client', time: '5 yrs ago' }],
    tableColumns: ['Piece', 'Dealer Contact'], filters: ['Watching', 'Available', 'Acquired'],
    itemTypes: ['17th-Century Atlas'], details: ['Authenticated'],
  },
  {
    name: 'Ridgeline Watercraft — Client App', category: 'Mobile-Travel', paletteId: 'open-air-light',
    description: 'Client app for a custom kayak and canoe building workshop — build progress.',
    appName: 'Ridgeline Watercraft', navIcon: 'boat', primaryFeaturePascal: 'Build', primaryFeatureLabel: 'My Build',
    greetingName: 'Paddler Torsten Kjeld', greetingInsight: 'Your kayak hull just cleared water testing.',
    insightCard: 'The builder ran your kayak through initial water testing a week early — balance and tracking both exceeded expectations.',
    kpis: [{ label: 'Build Progress', value: 92, suffix: '%' }, { label: 'Est. Delivery', value: '1 wk' }, { label: 'Build Value', value: '3.4K' }],
    actionItems: [{ title: 'Water testing passed', detail: 'Ahead of schedule', tone: 'accent' }, { title: 'Schedule pickup or delivery', detail: 'Ready next week', tone: 'default' }],
    activity: [{ label: 'Water testing passed', time: '1 day ago' }, { label: 'Seat fitting completed', time: '1 week ago' }, { label: 'Hull layup completed', time: '3 weeks ago' }, { label: 'Build started', time: '5 weeks ago' }, { label: 'Deposit paid', time: '6 weeks ago' }],
    tableColumns: ['Milestone', 'Builder'], filters: ['Layup', 'Fitting', 'Testing'],
    itemTypes: ['Water Testing'], details: ['Passed'],
  },
]

export const mobileBatch9 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: {
    description: spec.description,
    appName: spec.appName,
    navIcon: spec.navIcon,
    primaryFeaturePascal: spec.primaryFeaturePascal,
    primaryFeatureLabel: spec.primaryFeatureLabel,
    greetingName: spec.greetingName,
    greetingInsight: spec.greetingInsight,
    insightCard: spec.insightCard,
    kpis: spec.kpis,
    actionItems: spec.actionItems,
    activity: spec.activity,
    primaryTable: {
      columns: spec.tableColumns,
      filters: spec.filters,
      rows: spec.itemTypes.map((item, i) => ({
        cells: [item, spec.details[i % spec.details.length]],
        status: spec.filters[i % spec.filters.length],
      })),
    },
  },
}))
