const specs = [
  {
    name: 'Ashworth Capital — Deal Room App', category: 'Mobile-Finance', paletteId: 'saas-indigo-light',
    description: 'Deal room companion app for investment banking clients tracking a live transaction.',
    appName: 'Ashworth Capital', navIcon: 'briefcase', primaryFeaturePascal: 'Deal', primaryFeatureLabel: 'Deal Room',
    greetingName: 'Colin Whitford', greetingInsight: 'Your data room has 3 new document requests.',
    insightCard: 'Buyer diligence requested 3 new documents yesterday — responding within 24 hours keeps the process on pace.',
    kpis: [{ label: 'Deal Stage', value: 'Diligence' }, { label: 'Documents', value: 84 }, { label: 'Days to Close', value: 42 }],
    actionItems: [{ title: 'Respond to document request', detail: '3 items pending, due tomorrow', tone: 'warning' }, { title: 'Management call scheduled', detail: 'Thursday, 2 PM', tone: 'accent' }],
    activity: [{ label: 'Buyer requested 3 additional documents', time: '2h ago' }, { label: 'Management presentation uploaded', time: 'yesterday' }, { label: 'LOI executed', time: '1 week ago' }, { label: 'Data room opened to buyer', time: '2 weeks ago' }, { label: 'Engagement letter signed', time: '5 weeks ago' }],
    tableColumns: ['Document', 'Requested By'], filters: ['Pending', 'Uploaded', 'Reviewed'],
    itemTypes: ['Financial Statements', 'Customer Contracts', 'Cap Table', 'IP Assignments', 'Employment Agreements'],
    details: ['Buyer counsel', 'Buyer counsel', 'Uploaded', 'Reviewed', 'Pending'],
  },
  {
    name: 'Fernbrook Foundation — Donor App', category: 'Mobile-NonProfit', paletteId: 'moss-archive-light',
    description: 'Donor engagement app for an environmental foundation.',
    appName: 'Fernbrook Foundation', navIcon: 'leaf', primaryFeaturePascal: 'Impact', primaryFeatureLabel: 'My Impact',
    greetingName: 'Owen Fairbanks', greetingInsight: 'Your gifts have funded 340 acres of restoration.',
    insightCard: 'Your recurring gift funded this quarter’s wetlands grant — the program officer shared new photos from the site.',
    kpis: [{ label: 'Total Given', value: '48K' }, { label: 'Acres Funded', value: 340 }, { label: 'Years Giving', value: 6 }],
    actionItems: [{ title: 'New impact report available', detail: 'Wetlands Restoration Fund', tone: 'accent' }, { title: 'Annual gift renews in 2 weeks', detail: 'Recurring donation', tone: 'default' }],
    activity: [{ label: 'Impact report published for your fund', time: '1 day ago' }, { label: 'Recurring gift processed', time: '1 mo ago' }, { label: 'Site photos shared from Cascade Riverkeepers', time: '2 mo ago' }, { label: 'Annual giving summary sent', time: '3 mo ago' }, { label: 'Became a recurring donor', time: '6 yrs ago' }],
    tableColumns: ['Fund', 'Focus Area'], filters: ['Active', 'Completed', 'New'],
    itemTypes: ['Watershed Restoration Fund', 'Wetlands Protection Fund', 'Grassland Conservation Fund'],
    details: ['Active', 'Active', 'New this year'],
  },
  {
    name: 'Aldercroft Jewelers — Client App', category: 'Mobile-Creative', paletteId: 'luxury-gold-dark',
    description: 'Client app for a fine jewelry atelier — commission tracking and design approvals.',
    appName: 'Aldercroft Jewelers', navIcon: 'diamond', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Priya Sharma', greetingInsight: 'Your ring enters final setting this week.',
    insightCard: 'Your stone setting begins Thursday — this is typically the final step before delivery.',
    kpis: [{ label: 'Progress', value: 88, suffix: '%' }, { label: 'Est. Delivery', value: '9 days' }, { label: 'Design Revisions', value: 2 }],
    actionItems: [{ title: 'Final setting begins Thursday', detail: 'No action needed', tone: 'accent' }, { title: 'Approve final photos', detail: 'Before shipping', tone: 'default' }],
    activity: [{ label: 'Stone setting scheduled', time: '1 day ago' }, { label: 'CAD model approved', time: '1 week ago' }, { label: 'Stone sourced and verified', time: '2 weeks ago' }, { label: 'Design consultation completed', time: '4 weeks ago' }, { label: 'Commission started', time: '5 weeks ago' }],
    tableColumns: ['Piece', 'Jeweler'], filters: ['Design', 'Setting', 'Delivered'],
    itemTypes: ['Engagement Ring'],
    details: ['Setting in progress'],
  },
  {
    name: 'Ridgeline Alpine — Guest App', category: 'Mobile-Food', paletteId: 'open-air-light',
    description: 'Guest app for a boutique ski chalet rental group.',
    appName: 'Ridgeline Alpine', navIcon: 'snow', primaryFeaturePascal: 'Stay', primaryFeatureLabel: 'My Stay',
    greetingName: 'James O’Brien', greetingInsight: 'Your chalet stay begins in 5 days.',
    insightCard: 'Fresh snowfall is forecasted for your arrival — your concierge recommends booking a lesson before the weekend rush.',
    kpis: [{ label: 'Days to Arrival', value: 5 }, { label: 'Nights Booked', value: 7 }, { label: 'Concierge Requests', value: 2 }],
    actionItems: [{ title: 'Confirm ski instructor', detail: 'Recommended before weekend', tone: 'accent' }, { title: 'Grocery pre-stock list due', detail: 'Submit before Wednesday', tone: 'warning' }],
    activity: [{ label: 'Chalet confirmed — Summit Chalet', time: '2 days ago' }, { label: 'Private chef arranged for arrival night', time: '3 days ago' }, { label: 'Airport transfer booked', time: '1 week ago' }, { label: 'Deposit paid', time: '3 weeks ago' }, { label: 'Booking made', time: '2 mo ago' }],
    tableColumns: ['Chalet', 'Dates'], filters: ['Confirmed', 'Requested', 'Past'],
    itemTypes: ['Summit Chalet'],
    details: ['Mar 15 – Mar 22'],
  },
  {
    name: 'Ashford Early Learning — Parent App', category: 'Mobile-Education', paletteId: 'cobalt-pop-light',
    description: 'Parent companion app for a daycare and early learning center.',
    appName: 'Ashford Early Learning', navIcon: 'happy', primaryFeaturePascal: 'Updates', primaryFeatureLabel: 'Daily Updates',
    greetingName: 'Aisha Patel', greetingInsight: 'Your child had a great day today.',
    insightCard: 'Today’s report shows 2 naps, a full lunch, and outdoor play — no incidents to note.',
    kpis: [{ label: 'Days This Month', value: 18 }, { label: 'Photos Shared', value: 24 }, { label: 'Next Event', value: 'Spring Fair' }],
    actionItems: [{ title: 'Sign permission slip', detail: 'Spring field trip', tone: 'warning' }, { title: 'New photos posted', detail: '4 from today', tone: 'default' }],
    activity: [{ label: 'Daily report posted — great day', time: '3h ago' }, { label: '4 new photos shared', time: '3h ago' }, { label: 'Nap and meal logged', time: 'today' }, { label: 'Teacher note added', time: 'yesterday' }, { label: 'Enrolled in Preschool Room', time: '6 mo ago' }],
    tableColumns: ['Date', 'Classroom'], filters: ['Today', 'This Week', 'Past'],
    itemTypes: ['Today', 'Yesterday', 'This Week'],
    details: ['Preschool Room', 'Preschool Room', 'Preschool Room'],
  },
  {
    name: 'Alderbrook Dental — Patient App', category: 'Mobile-Healthcare', paletteId: 'wellness-sage-light',
    description: 'Patient app for a multi-location dental practice group.',
    appName: 'Alderbrook Dental', navIcon: 'medical', primaryFeaturePascal: 'Appointments', primaryFeatureLabel: 'Appointments',
    greetingName: 'Marcus Webb', greetingInsight: 'Your cleaning is scheduled for next week.',
    insightCard: 'It’s been 6 months since your last cleaning — booking now keeps your preferred hygienist available.',
    kpis: [{ label: 'Next Visit', value: '7 days' }, { label: 'Last Visit', value: '6 mo ago' }, { label: 'Outstanding Balance', value: '$0' }],
    actionItems: [{ title: 'Confirm next week’s cleaning', detail: 'Tue 10 AM', tone: 'accent' }, { title: 'Update insurance info', detail: 'Card on file expiring', tone: 'warning' }],
    activity: [{ label: 'Appointment confirmed for next week', time: '1 day ago' }, { label: 'X-rays reviewed by Dr. Solis', time: '6 mo ago' }, { label: 'Cleaning completed', time: '6 mo ago' }, { label: 'Insurance verified', time: '6 mo ago' }, { label: 'Became a patient', time: '3 yrs ago' }],
    tableColumns: ['Visit Type', 'Provider'], filters: ['Upcoming', 'Past', 'Cancelled'],
    itemTypes: ['Cleaning', 'X-Ray Review', 'Filling'],
    details: ['Next Tue', 'Completed', 'Completed'],
  },
  {
    name: 'Ironclad Racquet Club — Member App', category: 'Mobile-Productivity', paletteId: 'track-red-light',
    description: 'Member app for a private racquet club — court booking and league play.',
    appName: 'Ironclad Racquet Club', navIcon: 'tennisball', primaryFeaturePascal: 'Courts', primaryFeatureLabel: 'Court Booking',
    greetingName: 'Marcus Rivera', greetingInsight: 'Your league match is Saturday at 10 AM.',
    insightCard: 'Court 2 has a same-time slot open Thursday — you usually practice before league matches.',
    kpis: [{ label: 'Bookings (mo)', value: 8, delta: 12 }, { label: 'League Rank', value: 4 }, { label: 'Win Rate', value: 68, suffix: '%' }],
    actionItems: [{ title: 'Confirm Saturday league match', detail: '10 AM, Court 1', tone: 'accent' }, { title: 'Membership renews in 10 days', detail: 'Auto-renew on', tone: 'default' }],
    activity: [{ label: 'Booked Court 2 for Thursday practice', time: '1h ago' }, { label: 'Won league match against T. Ferro', time: '3 days ago' }, { label: 'Booked a lesson with the pro', time: '1 week ago' }, { label: 'Joined the spring league', time: '3 weeks ago' }, { label: 'Became a member', time: '2 yrs ago' }],
    tableColumns: ['Court', 'Time'], filters: ['Confirmed', 'League Play', 'Completed'],
    itemTypes: ['Indoor Court 1', 'Indoor Court 2', 'Outdoor Court'],
    details: ['Sat 10 AM', 'Thu 6 PM', 'Completed'],
  },
  {
    name: 'Corbridge Underwriters — Broker App', category: 'Mobile-Finance', paletteId: 'ledger-ivory-light',
    description: 'Broker-facing app for a specialty insurance underwriting boutique.',
    appName: 'Corbridge Underwriters', navIcon: 'shield-checkmark', primaryFeaturePascal: 'Submissions', primaryFeatureLabel: 'Submissions',
    greetingName: 'Sade Adeyemi', greetingInsight: 'You have 6 submissions under review this week.',
    insightCard: 'Your Coppermill Foods submission is ready to bind — the underwriter approved terms this morning.',
    kpis: [{ label: 'Active Submissions', value: 6 }, { label: 'Bind Rate', value: 62, suffix: '%' }, { label: 'Premium (MTD)', value: '1.2M' }],
    actionItems: [{ title: 'Coppermill Foods ready to bind', detail: 'Terms approved', tone: 'accent' }, { title: 'Additional info requested', detail: 'Ashgrove Insurance submission', tone: 'warning' }],
    activity: [{ label: 'Coppermill Foods terms approved', time: '2h ago' }, { label: 'Submitted new cyber liability application', time: 'yesterday' }, { label: 'Bound policy for Halden Industries', time: '3 days ago' }, { label: 'Additional info requested', time: '4 days ago' }, { label: 'Onboarded as a broker partner', time: '1 yr ago' }],
    tableColumns: ['Client', 'Coverage'], filters: ['Submitted', 'Under Review', 'Bound'],
    itemTypes: ['Excess Liability', 'Cyber Liability', 'Professional Indemnity'],
    details: ['Ready to bind', 'Under review', 'Bound'],
  },
  {
    name: 'Ferrous Auto Body — Customer App', category: 'Mobile-Logistics', paletteId: 'mono-dev-dark',
    description: 'Customer app for a multi-location auto body repair shop.',
    appName: 'Ferrous Auto Body', navIcon: 'car-sport', primaryFeaturePascal: 'Repair', primaryFeatureLabel: 'My Repair',
    greetingName: 'Elena Vasquez', greetingInsight: 'Your vehicle is in the paint booth today.',
    insightCard: 'Your insurance adjuster approved the estimate yesterday — repair is on track for pickup Friday.',
    kpis: [{ label: 'Repair Progress', value: 74, suffix: '%' }, { label: 'Est. Completion', value: 'Friday' }, { label: 'Insurance Status', value: 'Approved' }],
    actionItems: [{ title: 'Pickup scheduled Friday', detail: '10 AM – 6 PM', tone: 'accent' }, { title: 'Rental car return reminder', detail: 'Due at pickup', tone: 'default' }],
    activity: [{ label: 'Vehicle entered paint booth', time: '3h ago' }, { label: 'Insurance estimate approved', time: 'yesterday' }, { label: 'Parts received', time: '2 days ago' }, { label: 'Frame straightening completed', time: '4 days ago' }, { label: 'Vehicle dropped off', time: '1 week ago' }],
    tableColumns: ['Repair Stage', 'Shop Manager'], filters: ['In Progress', 'Awaiting Parts', 'Complete'],
    itemTypes: ['Paint & Body', 'Frame Straightening', 'Parts Installation'],
    details: ['In progress', 'Complete', 'Complete'],
  },
  {
    name: 'Willowmere Senior Living — Family App', category: 'Mobile-Healthcare', paletteId: 'wellness-teal-dark',
    description: 'Family communication app for an assisted living community.',
    appName: 'Willowmere Senior Living', navIcon: 'heart', primaryFeaturePascal: 'Updates', primaryFeatureLabel: 'Care Updates',
    greetingName: 'Nina Whitfield', greetingInsight: 'Your mother had a great week.',
    insightCard: 'Her care coordinator noted improved appetite this week and joined two community activities.',
    kpis: [{ label: 'Updates This Week', value: 5 }, { label: 'Last Visit', value: '3 days ago' }, { label: 'Care Plan Status', value: 'Current' }],
    actionItems: [{ title: 'Care plan review scheduled', detail: 'Next Tuesday, 2 PM', tone: 'accent' }, { title: 'New photos shared', detail: 'From the spring social', tone: 'default' }],
    activity: [{ label: 'Care coordinator posted a weekly update', time: '1 day ago' }, { label: 'Photos shared from the spring social', time: '2 days ago' }, { label: 'Care plan reviewed — no changes needed', time: '1 week ago' }, { label: 'Family visit logged', time: '1 week ago' }, { label: 'Moved into Assisted Living', time: '8 mo ago' }],
    tableColumns: ['Update Type', 'Care Coordinator'], filters: ['New', 'Reviewed', 'Archived'],
    itemTypes: ['Weekly Update', 'Care Plan Review', 'Photo Update'],
    details: ['New', 'Reviewed', 'New'],
  },
]

export const mobileBatch3 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: {
    description: spec.description,
    appName: spec.appName,
    navIcon: spec.navIcon,
    primaryFeaturePascal: spec.primaryFeaturePascal,
    primaryFeatureLabel: spec.primaryFeatureLabel,
    greetingName: spec.greetingName,
    greetingInsight: spec.greetingInsight,
    insightCard: spec.insightCard,
    kpis: spec.kpis,
    actionItems: spec.actionItems,
    activity: spec.activity,
    primaryTable: {
      columns: spec.tableColumns,
      filters: spec.filters,
      rows: spec.itemTypes.map((item, i) => ({
        cells: [item, spec.details[i % spec.details.length]],
        status: spec.filters[i % spec.filters.length],
      })),
    },
  },
}))
