const specs = [
  {
    name: 'Blackwood Falconry Academy — Apprentice App', category: 'Mobile-Education', paletteId: 'precision-ember-dark',
    description: 'Apprentice app for a licensed falconry academy — field hours and certification tracking.',
    appName: 'Blackwood Falconry', navIcon: 'school', primaryFeaturePascal: 'Hours', primaryFeatureLabel: 'Field Hours',
    greetingName: 'Priya Anand', greetingInsight: 'You are 4 field hours from your next certification review.',
    insightCard: 'Your sponsor logged 3 hours from last weekend’s hunt — you’re on pace to sit the general falconer exam this spring.',
    kpis: [{ label: 'Field Hours (YTD)', value: 112 }, { label: 'Hours to Next Review', value: 4 }, { label: 'Certification', value: 'Apprentice' }],
    actionItems: [{ title: 'Log this weekend’s hunt', detail: 'Pending sponsor sign-off', tone: 'accent' }, { title: 'Exam registration opens soon', detail: 'General falconer exam', tone: 'default' }],
    activity: [{ label: 'Sponsor logged 3 field hours', time: '2 days ago' }, { label: 'Mentor review completed', time: '1 week ago' }, { label: 'Passed raptor handling module', time: '3 weeks ago' }, { label: 'Bird assigned for training', time: '2 mo ago' }, { label: 'Started apprenticeship', time: '8 mo ago' }],
    tableColumns: ['Session', 'Mentor'], filters: ['Logged', 'Pending Sign-off', 'Reviewed'],
    itemTypes: ['Weekend Hunt Log', 'Mentor Review Session'], details: ['Pending sign-off', 'Scheduled'],
  },
  {
    name: 'Aldergate Rare Books — Collector App', category: 'Mobile-Creative', paletteId: 'paper-oxblood-light',
    description: 'Collector app for a rare book and manuscript dealer — watchlist and acquisitions.',
    appName: 'Aldergate Rare Books', navIcon: 'book', primaryFeaturePascal: 'Watchlist', primaryFeatureLabel: 'My Watchlist',
    greetingName: 'Marguerite Sto', greetingInsight: 'A first edition on your watchlist just became available.',
    insightCard: 'The 1851 first edition you flagged six months ago was just acquired from an estate library — provenance is fully documented.',
    kpis: [{ label: 'Watchlist Items', value: 6 }, { label: 'Volumes Owned', value: 22 }, { label: 'Collection Value', value: '410K' }],
    actionItems: [{ title: 'Review new acquisition', detail: '1851 first edition available', tone: 'accent' }, { title: 'Appraisal due for insurance', detail: 'Annual renewal', tone: 'default' }],
    activity: [{ label: 'Watchlist match found', time: '4h ago' }, { label: 'Purchased a signed first edition', time: '2 weeks ago' }, { label: 'Appraisal report received', time: '1 mo ago' }, { label: 'Added item to watchlist', time: '2 mo ago' }, { label: 'Became a client', time: '5 yrs ago' }],
    tableColumns: ['Volume', 'Dealer Contact'], filters: ['Watching', 'Available', 'Acquired'],
    itemTypes: ['1851 First Edition', 'Illuminated Manuscript'], details: ['Available now', 'Watching'],
  },
  {
    name: 'Aldergate Organ Works — Client App', category: 'Mobile-Creative', paletteId: 'midnight-press-dark',
    description: 'Client app for a pipe organ restoration firm — restoration status and voicing schedule.',
    appName: 'Aldergate Organ Works', navIcon: 'musical-notes', primaryFeaturePascal: 'Restoration', primaryFeatureLabel: 'My Restoration',
    greetingName: 'Father Elias Munro', greetingInsight: 'Final voicing begins next week.',
    insightCard: 'Two pipe ranks remain before final voicing — the crew expects the console restoration to finish ahead of schedule.',
    kpis: [{ label: 'Restoration Progress', value: 84, suffix: '%' }, { label: 'Pipe Ranks Remaining', value: 2 }, { label: 'Est. Completion', value: '3 wks' }],
    actionItems: [{ title: 'Final voicing scheduled', detail: 'Starts next Monday', tone: 'accent' }, { title: 'Console restoration ahead of schedule', detail: 'No action needed', tone: 'default' }],
    activity: [{ label: 'Console restoration completed', time: '1 day ago' }, { label: 'Wind chest testing passed', time: '1 week ago' }, { label: 'Pipe cleaning completed', time: '3 weeks ago' }, { label: 'Restoration began', time: '11 mo ago' }, { label: 'Contract signed', time: '1 yr ago' }],
    tableColumns: ['Milestone', 'Restorer'], filters: ['Complete', 'In Progress', 'Scheduled'],
    itemTypes: ['Final Voicing', 'Console Restoration'], details: ['Starts Monday', 'Complete'],
  },
  {
    name: 'Fernbrook Truffle Co. — Restaurant Account App', category: 'Mobile-Food', paletteId: 'forest-market-light',
    description: 'Restaurant account app for a private truffle foraging company — standing orders and daily harvest.',
    appName: 'Fernbrook Truffle Co.', navIcon: 'restaurant', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'My Orders',
    greetingName: 'Chef Antoine Rousset', greetingInsight: "Today's harvest is 4.2 lbs — your standing order ships this afternoon.",
    insightCard: 'A larger-than-average black truffle came in this morning — your account manager set one aside for tonight’s tasting menu.',
    kpis: [{ label: 'Standing Order', value: 'Daily' }, { label: "Today's Allocation", value: '0.6 lbs' }, { label: 'Account Since', value: '2 yrs' }],
    actionItems: [{ title: 'Special allocation available', detail: 'Large black truffle, reserved for you', tone: 'accent' }, { title: 'Confirm this afternoon’s delivery', detail: 'Standard daily order', tone: 'default' }],
    activity: [{ label: 'Daily order confirmed', time: '1h ago' }, { label: 'Special allocation offered', time: '3h ago' }, { label: 'Yesterday’s delivery received', time: '1 day ago' }, { label: 'Order size increased for event', time: '1 week ago' }, { label: 'Became a standing account', time: '2 yrs ago' }],
    tableColumns: ['Order', 'Forager'], filters: ['Standing', 'Special', 'Delivered'],
    itemTypes: ['Daily Standing Order', 'Special Allocation'], details: ['Ships today', 'Reserved'],
  },
  {
    name: 'Ridgeline Balloon Adventures — Passenger App', category: 'Mobile-Logistics', paletteId: 'open-air-light',
    description: 'Passenger app for a hot air balloon tour company — flight status and weather updates.',
    appName: 'Ridgeline Balloon', navIcon: 'airplane', primaryFeaturePascal: 'Flights', primaryFeatureLabel: 'My Flights',
    greetingName: 'Harriet Lowell', greetingInsight: 'Your sunrise flight is weather-confirmed for tomorrow.',
    insightCard: 'Forecast conditions are ideal for tomorrow’s 5:45 AM launch — arrive 30 minutes early for the pre-flight safety briefing.',
    kpis: [{ label: 'Upcoming Flights', value: 1 }, { label: 'Flights Completed', value: 3 }, { label: 'Weather Status', value: 'Confirmed' }],
    actionItems: [{ title: 'Flight confirmed for tomorrow', detail: '5:45 AM launch, arrive by 5:15', tone: 'accent' }, { title: 'Review pre-flight safety info', detail: 'Takes 2 minutes', tone: 'default' }],
    activity: [{ label: 'Weather confirmed for tomorrow’s flight', time: '2h ago' }, { label: 'Flight booked', time: '3 days ago' }, { label: 'Previous flight completed', time: '2 mo ago' }, { label: 'Rebooked due to weather', time: '2 mo ago' }, { label: 'First flight booked', time: '1 yr ago' }],
    tableColumns: ['Flight', 'Pilot'], filters: ['Confirmed', 'Weather Watch', 'Completed'],
    itemTypes: ['Sunrise Flight'], details: ['Confirmed'],
  },
  {
    name: 'Aldercroft Cigar House — Member App', category: 'Mobile-Food', paletteId: 'supper-club-dark',
    description: 'Member app for a custom cigar blending house — order status and locker inventory.',
    appName: 'Aldercroft Cigar House', navIcon: 'flame', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'My Orders',
    greetingName: 'Desmond Okafor', greetingInsight: 'Your custom blend sample is ready for approval.',
    insightCard: 'The roller finished your requested adjustment — a touch more pepper in the finish, as you asked after the last batch.',
    kpis: [{ label: 'Active Orders', value: 1 }, { label: 'Locker Inventory', value: 48 }, { label: 'Custom Blends', value: 3 }],
    actionItems: [{ title: 'Approve blend sample', detail: 'Adjusted per your feedback', tone: 'accent' }, { title: 'Locker running low', detail: '48 remaining, reorder suggested', tone: 'default' }],
    activity: [{ label: 'Blend sample sent for approval', time: '5h ago' }, { label: 'Previous order rolled', time: '1 week ago' }, { label: 'Locker restocked', time: '3 weeks ago' }, { label: 'New custom blend developed', time: '2 mo ago' }, { label: 'Became a member', time: '3 yrs ago' }],
    tableColumns: ['Order', 'Roller'], filters: ['Rolling', 'Aging', 'Ready'],
    itemTypes: ['Custom Blend Sample'], details: ['Awaiting approval'],
  },
  {
    name: 'Fernbrook Botanical Design — Client App', category: 'Mobile-RealEstate', paletteId: 'forest-market-light',
    description: 'Client app for a botanical garden design firm — project status and specimen sourcing.',
    appName: 'Fernbrook Botanical', navIcon: 'flower', primaryFeaturePascal: 'Project', primaryFeatureLabel: 'My Project',
    greetingName: 'Rosalind Fairweather', greetingInsight: 'Your specimen sourcing is complete — planting begins Monday.',
    insightCard: 'All 14 rare specimens for your conservatory arrived and passed inspection — the planting crew starts Monday morning.',
    kpis: [{ label: 'Project Progress', value: 62, suffix: '%' }, { label: 'Specimens Sourced', value: 14 }, { label: 'Est. Completion', value: '4 mo' }],
    actionItems: [{ title: 'Planting begins Monday', detail: 'All specimens on site', tone: 'accent' }, { title: 'Irrigation design review', detail: 'Awaiting your approval', tone: 'default' }],
    activity: [{ label: 'Final specimen delivery arrived', time: '1 day ago' }, { label: 'Irrigation design submitted', time: '1 week ago' }, { label: 'Specimen sourcing began', time: '2 mo ago' }, { label: 'Design finalized', time: '3 mo ago' }, { label: 'Project kicked off', time: '4 mo ago' }],
    tableColumns: ['Milestone', 'Designer'], filters: ['Complete', 'In Progress', 'Upcoming'],
    itemTypes: ['Specimen Sourcing', 'Planting Phase'], details: ['Complete', 'Starts Monday'],
  },
  {
    name: 'Aldergate Falconry Goods — Client App', category: 'Mobile-Creative', paletteId: 'clay-sand-light',
    description: 'Client app for a falconry equipment maker — custom order status and fittings.',
    appName: 'Aldergate Falconry Goods', navIcon: 'construct', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'My Orders',
    greetingName: 'Owen Blackwood', greetingInsight: 'Your custom gauntlet ships Friday.',
    insightCard: 'The leatherworker finished hand-stitching your gauntlet a day early — measurements were confirmed against your last fitting.',
    kpis: [{ label: 'Active Orders', value: 1 }, { label: 'Items Owned', value: 5 }, { label: 'Member Since', value: '4 yrs' }],
    actionItems: [{ title: 'Gauntlet ships Friday', detail: 'Ahead of schedule', tone: 'accent' }, { title: 'Rate your last hood', detail: 'Help us improve fit', tone: 'default' }],
    activity: [{ label: 'Gauntlet stitching completed', time: '1 day ago' }, { label: 'Measurements confirmed', time: '2 weeks ago' }, { label: 'Custom order placed', time: '3 weeks ago' }, { label: 'Previous hood delivered', time: '8 mo ago' }, { label: 'First order placed', time: '4 yrs ago' }],
    tableColumns: ['Item', 'Leatherworker'], filters: ['Cutting', 'Stitching', 'Shipped'],
    itemTypes: ['Custom Gauntlet'], details: ['Ships Friday'],
  },
  {
    name: 'Fernbrook Apiary Management — Client App', category: 'Mobile-Food', paletteId: 'food-amber-light',
    description: 'Client app for a private apiary management firm — hive health and honey yield.',
    appName: 'Fernbrook Apiary', navIcon: 'leaf', primaryFeaturePascal: 'Hives', primaryFeatureLabel: 'My Hives',
    greetingName: 'Constance Wray', greetingInsight: 'Spring inspection complete — all 6 hives are healthy.',
    insightCard: 'Your beekeeper noted unusually strong brood patterns this spring — honey extraction is on track for a record yield this season.',
    kpis: [{ label: 'Managed Hives', value: 6 }, { label: 'Hive Health', value: 100, suffix: '%' }, { label: 'Est. Yield (YTD)', value: '84 lbs' }],
    actionItems: [{ title: 'Extraction scheduled', detail: 'Next month, record yield expected', tone: 'accent' }, { title: 'Review spring inspection report', detail: '6 hives, all healthy', tone: 'default' }],
    activity: [{ label: 'Spring inspection completed', time: '2 days ago' }, { label: 'Mite treatment applied', time: '3 weeks ago' }, { label: 'New hive installed', time: '2 mo ago' }, { label: 'Winter inspection passed', time: '4 mo ago' }, { label: 'Became a client', time: '5 yrs ago' }],
    tableColumns: ['Hive', 'Beekeeper'], filters: ['Healthy', 'Under Treatment', 'New'],
    itemTypes: ['Hive Group A', 'Hive Group B'], details: ['Healthy', 'Healthy'],
  },
  {
    name: 'Aldergate Clockworks — Client App', category: 'Mobile-Creative', paletteId: 'paper-oxblood-light',
    description: 'Client app for an antique clock and automata restoration workshop.',
    appName: 'Aldergate Clockworks', navIcon: 'time', primaryFeaturePascal: 'Restoration', primaryFeatureLabel: 'My Restoration',
    greetingName: 'Beatrix Holloway', greetingInsight: 'Final testing begins this week on your automaton.',
    insightCard: 'The gear train rebuild is complete and the movement is holding time within two seconds a day — final testing starts Thursday.',
    kpis: [{ label: 'Restoration Progress', value: 78, suffix: '%' }, { label: 'Timing Accuracy', value: '±2 sec/day' }, { label: 'Est. Completion', value: '3 wks' }],
    actionItems: [{ title: 'Final testing begins Thursday', detail: 'Automaton motion calibration', tone: 'accent' }, { title: 'Case refinishing options', detail: 'Awaiting your selection', tone: 'default' }],
    activity: [{ label: 'Gear train rebuild completed', time: '2 days ago' }, { label: 'Escapement adjusted', time: '2 weeks ago' }, { label: 'Movement disassembled', time: '1 mo ago' }, { label: 'Restoration began', time: '2 mo ago' }, { label: 'Estimate approved', time: '3 mo ago' }],
    tableColumns: ['Milestone', 'Clockmaker'], filters: ['Complete', 'In Progress', 'Upcoming'],
    itemTypes: ['Gear Train Rebuild', 'Final Testing'], details: ['Complete', 'Starts Thursday'],
  },
]

export const mobileBatch6 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: {
    description: spec.description,
    appName: spec.appName,
    navIcon: spec.navIcon,
    primaryFeaturePascal: spec.primaryFeaturePascal,
    primaryFeatureLabel: spec.primaryFeatureLabel,
    greetingName: spec.greetingName,
    greetingInsight: spec.greetingInsight,
    insightCard: spec.insightCard,
    kpis: spec.kpis,
    actionItems: spec.actionItems,
    activity: spec.activity,
    primaryTable: {
      columns: spec.tableColumns,
      filters: spec.filters,
      rows: spec.itemTypes.map((item, i) => ({
        cells: [item, spec.details[i % spec.details.length]],
        status: spec.filters[i % spec.filters.length],
      })),
    },
  },
}))
