const specs = [
  {
    name: 'Blackwood Falconry — Client App', category: 'Mobile-Logistics', paletteId: 'precision-ember-dark',
    description: 'Client app for a bird abatement service — site status and reporting.',
    appName: 'Blackwood Falconry', navIcon: 'airplane', primaryFeaturePascal: 'Sites', primaryFeatureLabel: 'My Sites',
    greetingName: 'Marcus Webb', greetingInsight: 'All your sites are covered this week.',
    insightCard: 'Bird activity at your landfill site dropped 40% since patrols began — the falconer noted it in this week’s report.',
    kpis: [{ label: 'Sites Covered', value: 3 }, { label: 'Incidents (mo)', value: 2, delta: -60 }, { label: 'Contract Renews', value: '60 days' }],
    actionItems: [{ title: 'Review this week’s report', detail: 'Landfill site', tone: 'accent' }, { title: 'Contract renewal coming up', detail: '60 days out', tone: 'default' }],
    activity: [{ label: 'Weekly report submitted for landfill site', time: '1 day ago' }, { label: 'Patrol completed at airport site', time: '2 days ago' }, { label: 'Incident logged and resolved', time: '1 week ago' }, { label: 'Contract renewed for vineyard site', time: '1 mo ago' }, { label: 'Service started', time: '1 yr ago' }],
    tableColumns: ['Site', 'Falconer'], filters: ['Active', 'Starting', 'Completed'],
    itemTypes: ['Landfill Contract', 'Airport Bird Abatement'], details: ['Active', 'Active'],
  },
  {
    name: 'Marchetti Home Staging — Realtor App', category: 'Mobile-RealEstate', paletteId: 'gallery-red-light',
    description: 'Realtor-facing app for a home staging company — project status and booking.',
    appName: 'Marchetti Staging', navIcon: 'home', primaryFeaturePascal: 'Projects', primaryFeatureLabel: 'My Listings',
    greetingName: 'Noelle Devereux', greetingInsight: 'Your listing stages tomorrow morning.',
    insightCard: 'Staging installs typically take 3 hours — your photographer is booked for 2 PM, right after the install finishes.',
    kpis: [{ label: 'Active Stagings', value: 2 }, { label: 'Avg. DOM Reduction', value: 34, suffix: '%' }, { label: 'This Month', value: 6, delta: 20 }],
    actionItems: [{ title: 'Staging install tomorrow', detail: '9 AM, 2-3 hour install', tone: 'accent' }, { title: 'Photography confirmed', detail: '2 PM, same day', tone: 'default' }],
    activity: [{ label: 'Staging scheduled for tomorrow', time: '2h ago' }, { label: 'Previous listing sold in 4 days', time: '1 week ago' }, { label: 'De-staged a completed listing', time: '1 week ago' }, { label: 'Consultation completed', time: '2 weeks ago' }, { label: 'Became a partner realtor', time: '2 yrs ago' }],
    tableColumns: ['Property', 'Stager'], filters: ['Staging', 'Live', 'De-Staged'],
    itemTypes: ['123 Maple Street', '89 Oak Avenue'], details: ['Install tomorrow', 'Live'],
  },
  {
    name: 'Aldergate Cheese Cellars — Account App', category: 'Mobile-Food', paletteId: 'food-amber-light',
    description: 'Wholesale account app for a specialty cheese affinage house.',
    appName: 'Aldergate Cheese Cellars', navIcon: 'restaurant', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'My Orders',
    greetingName: 'Elena Vasquez', greetingInsight: 'Your weekly order ships tomorrow.',
    insightCard: 'A new washed-rind wheel just reached peak aging — your account manager flagged it as a good fit for your current menu.',
    kpis: [{ label: 'Standing Order', value: 'Weekly' }, { label: 'Next Delivery', value: 'Tomorrow' }, { label: 'Account Since', value: '3 yrs' }],
    actionItems: [{ title: 'New wheel recommendation', detail: 'Washed-rind, peak aged', tone: 'accent' }, { title: 'Confirm tomorrow’s delivery', detail: 'Standard weekly order', tone: 'default' }],
    activity: [{ label: 'Weekly order confirmed', time: '3h ago' }, { label: 'Account manager recommended a new wheel', time: '1 day ago' }, { label: 'Last delivery received', time: '1 week ago' }, { label: 'Custom aging request fulfilled', time: '1 mo ago' }, { label: 'Became a wholesale account', time: '3 yrs ago' }],
    tableColumns: ['Order', 'Manager'], filters: ['Active', 'Reorder Due', 'Shipped'],
    itemTypes: ['Weekly Standing Order'], details: ['Ships tomorrow'],
  },
  {
    name: 'Aldergate Photography — Client App', category: 'Mobile-Creative', paletteId: 'gallery-red-light',
    description: 'Client app for an architecture photography studio — gallery delivery and booking.',
    appName: 'Aldergate Photography', navIcon: 'camera', primaryFeaturePascal: 'Galleries', primaryFeatureLabel: 'My Galleries',
    greetingName: 'Tomás Kowalski', greetingInsight: 'Your gallery is ready for review.',
    insightCard: 'Your exterior shoot gallery is ready — golden hour shots are marked as the photographer’s top picks.',
    kpis: [{ label: 'Galleries', value: 3 }, { label: 'Photos Delivered', value: 84 }, { label: 'Next Shoot', value: 'None scheduled' }],
    actionItems: [{ title: 'Review new gallery', detail: 'Exterior shoot, 28 photos', tone: 'accent' }, { title: 'Download high-res files', detail: 'Available for 90 days', tone: 'default' }],
    activity: [{ label: 'Gallery delivered — exterior shoot', time: '1 day ago' }, { label: 'Shoot completed', time: '5 days ago' }, { label: 'Shoot scheduled and confirmed', time: '1 week ago' }, { label: 'Previous gallery downloaded', time: '2 mo ago' }, { label: 'Became a client', time: '1 yr ago' }],
    tableColumns: ['Gallery', 'Photographer'], filters: ['Scheduled', 'Editing', 'Delivered'],
    itemTypes: ['Exterior Shoot', 'Interior Shoot'], details: ['Delivered', 'Editing'],
  },
  {
    name: 'Aldergate Remodeling Ops — Trade App', category: 'Mobile-Creative', paletteId: 'brutalist-light',
    description: 'Subcontractor-facing app for a remodeling firm — schedule and inspection status.',
    appName: 'Aldergate Trade App', navIcon: 'hammer', primaryFeaturePascal: 'Jobs', primaryFeatureLabel: 'My Jobs',
    greetingName: 'Diego Álvarez', greetingInsight: 'You have 2 jobs scheduled this week.',
    insightCard: 'Your plumbing rough-in at the Whitmore project needs inspection sign-off before cabinetry can start Monday.',
    kpis: [{ label: 'Jobs This Week', value: 2 }, { label: 'Pending Inspections', value: 1 }, { label: 'Completed (mo)', value: 6 }],
    actionItems: [{ title: 'Schedule inspection', detail: 'Whitmore project, plumbing', tone: 'warning' }, { title: 'Job starts Monday', detail: 'Marchbanks project', tone: 'accent' }],
    activity: [{ label: 'Plumbing rough-in completed', time: '2h ago' }, { label: 'Materials delivered to site', time: '1 day ago' }, { label: 'Job assigned — Marchbanks project', time: '2 days ago' }, { label: 'Previous job passed inspection', time: '1 week ago' }, { label: 'Onboarded as a trade partner', time: '2 yrs ago' }],
    tableColumns: ['Job', 'Project Manager'], filters: ['Scheduled', 'In Progress', 'Inspected'],
    itemTypes: ['Whitmore Plumbing', 'Marchbanks Framing'], details: ['Inspection pending', 'Starts Monday'],
  },
  {
    name: 'Meridian Cellars — Collector App', category: 'Mobile-Food', paletteId: 'supper-club-dark',
    description: 'Collector app for a private wine cellar storage facility.',
    appName: 'Meridian Cellars', navIcon: 'wine', primaryFeaturePascal: 'Collection', primaryFeatureLabel: 'My Collection',
    greetingName: 'Julian Marsh', greetingInsight: 'A pull request you made is ready.',
    insightCard: 'Your requested bottles are packed and ready for pickup — cellar temperature stayed within range the entire storage period.',
    kpis: [{ label: 'Bottles Stored', value: 340 }, { label: 'Collection Value', value: '84K' }, { label: 'Pull Requests', value: 1 }],
    actionItems: [{ title: 'Pull request ready', detail: '3 bottles, ready for pickup', tone: 'accent' }, { title: 'Annual insurance appraisal due', detail: 'Schedule with cellar manager', tone: 'default' }],
    activity: [{ label: 'Pull request fulfilled', time: '3h ago' }, { label: 'Added 6 bottles to collection', time: '1 week ago' }, { label: 'Catalog updated', time: '1 week ago' }, { label: 'Insurance appraisal completed', time: '3 mo ago' }, { label: 'Became a collector', time: '4 yrs ago' }],
    tableColumns: ['Collection', 'Cellar Manager'], filters: ['Active', 'Pull Requested', 'New'],
    itemTypes: ['Private Reserve Collection'], details: ['Pull ready'],
  },
  {
    name: 'Fernbrook Sanctuary — Member App', category: 'Mobile-NonProfit', paletteId: 'moss-archive-light',
    description: 'Member app for a raptor rescue and education sanctuary.',
    appName: 'Fernbrook Sanctuary', navIcon: 'leaf', primaryFeaturePascal: 'Visits', primaryFeatureLabel: 'My Visits',
    greetingName: 'Helga Berg', greetingInsight: 'A release event is happening this Saturday.',
    insightCard: 'The hawk you sponsored is ready for release Saturday — members get first access to the viewing area.',
    kpis: [{ label: 'Visits (YTD)', value: 8 }, { label: 'Sponsored Birds', value: 1 }, { label: 'Member Since', value: '3 yrs' }],
    actionItems: [{ title: 'Release event Saturday', detail: 'Your sponsored hawk', tone: 'accent' }, { title: 'Membership renews in 2 weeks', detail: 'Auto-renew on', tone: 'default' }],
    activity: [{ label: 'Release event announced', time: '1 day ago' }, { label: 'Visited the sanctuary', time: '2 weeks ago' }, { label: 'Sponsored a red-tailed hawk', time: '2 mo ago' }, { label: 'Attended an education program', time: '3 mo ago' }, { label: 'Became a member', time: '3 yrs ago' }],
    tableColumns: ['Event', 'Coordinator'], filters: ['Upcoming', 'Attended', 'Past'],
    itemTypes: ['Release Event'], details: ['Saturday'],
  },
  {
    name: 'Blackridge Aerial — Client App', category: 'Mobile-Logistics', paletteId: 'precision-acid-dark',
    description: 'Client app for a drone infrastructure inspection company.',
    appName: 'Blackridge Aerial', navIcon: 'airplane', primaryFeaturePascal: 'Inspections', primaryFeatureLabel: 'My Inspections',
    greetingName: 'Sade Adeyemi', greetingInsight: 'Your inspection report is ready.',
    insightCard: 'The cell tower inspection found 2 minor findings — both flagged as low priority in the full report.',
    kpis: [{ label: 'Active Contracts', value: 1 }, { label: 'Reports (YTD)', value: 6 }, { label: 'Findings This Report', value: 2 }],
    actionItems: [{ title: 'Review inspection report', detail: 'Cell tower, 2 findings', tone: 'accent' }, { title: 'Next inspection scheduling', detail: 'Quarterly contract', tone: 'default' }],
    activity: [{ label: 'Inspection report delivered', time: '4h ago' }, { label: 'Flight completed', time: '1 day ago' }, { label: 'Inspection scheduled', time: '1 week ago' }, { label: 'Previous report reviewed', time: '3 mo ago' }, { label: 'Contract signed', time: '1 yr ago' }],
    tableColumns: ['Asset', 'Pilot'], filters: ['Scheduled', 'In Progress', 'Delivered'],
    itemTypes: ['Cell Tower Inspection'], details: ['Delivered'],
  },
  {
    name: 'Ferrous & Cacao — Wholesale App', category: 'Mobile-Food', paletteId: 'food-amber-light',
    description: 'Wholesale ordering app for a boutique chocolate house.',
    appName: 'Ferrous & Cacao', navIcon: 'restaurant', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'My Orders',
    greetingName: 'Kwame Asante', greetingInsight: 'Your holiday order is in production.',
    insightCard: 'Your custom molds finished production early — packaging begins today, ahead of the original schedule.',
    kpis: [{ label: 'Active Orders', value: 1 }, { label: 'Order Value', value: '$1,200' }, { label: 'Ships', value: 'Friday' }],
    actionItems: [{ title: 'Packaging begins today', detail: 'Ahead of schedule', tone: 'accent' }, { title: 'Confirm delivery address', detail: 'For Friday shipment', tone: 'default' }],
    activity: [{ label: 'Custom molds completed', time: '3h ago' }, { label: 'Order confirmed', time: '1 week ago' }, { label: 'Design approved', time: '2 weeks ago' }, { label: 'Previous order delivered', time: '6 mo ago' }, { label: 'Became a wholesale client', time: '2 yrs ago' }],
    tableColumns: ['Order', 'Chocolatier'], filters: ['Production', 'Packaging', 'Shipped'],
    itemTypes: ['Holiday Collection'], details: ['Packaging'],
  },
  {
    name: 'Meridian Marine Expeditions — Booking App', category: 'Mobile-Logistics', paletteId: 'precision-sky-dark',
    description: 'Booking companion app for a diving expedition company.',
    appName: 'Meridian Marine', navIcon: 'boat', primaryFeaturePascal: 'Bookings', primaryFeatureLabel: 'My Bookings',
    greetingName: 'Beatrix Ondo', greetingInsight: 'A new expedition just opened for booking.',
    insightCard: 'The Galapagos expedition you were watching just opened 4 new spots — similar trips sell out within a week.',
    kpis: [{ label: 'Upcoming Trips', value: 1 }, { label: 'Dives Logged', value: 62 }, { label: 'Watchlist', value: 1 }],
    actionItems: [{ title: 'Galapagos spots available', detail: '4 spots just opened', tone: 'accent' }, { title: 'Complete trip waiver', detail: 'For your upcoming Red Sea trip', tone: 'warning' }],
    activity: [{ label: 'Galapagos expedition opened for booking', time: '2h ago' }, { label: 'Waiver reminder sent', time: '1 day ago' }, { label: 'Red Sea trip confirmed', time: '2 weeks ago' }, { label: 'Deposit paid', time: '3 weeks ago' }, { label: 'Added Galapagos to watchlist', time: '1 mo ago' }],
    tableColumns: ['Expedition', 'Dive Master'], filters: ['Confirmed', 'Waitlisted', 'Completed'],
    itemTypes: ['Red Sea Expedition'], details: ['Confirmed'],
  },
]

export const mobileBatch5 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: {
    description: spec.description,
    appName: spec.appName,
    navIcon: spec.navIcon,
    primaryFeaturePascal: spec.primaryFeaturePascal,
    primaryFeatureLabel: spec.primaryFeatureLabel,
    greetingName: spec.greetingName,
    greetingInsight: spec.greetingInsight,
    insightCard: spec.insightCard,
    kpis: spec.kpis,
    actionItems: spec.actionItems,
    activity: spec.activity,
    primaryTable: {
      columns: spec.tableColumns,
      filters: spec.filters,
      rows: spec.itemTypes.map((item, i) => ({
        cells: [item, spec.details[i % spec.details.length]],
        status: spec.filters[i % spec.filters.length],
      })),
    },
  },
}))
