const specs = [
  {
    name: 'Meridian Wine Imports — Account App', category: 'Mobile-Food', paletteId: 'supper-club-dark',
    description: 'Restaurant account app for a private wine importer — allocations and standing orders.',
    appName: 'Meridian Wine Imports', navIcon: 'wine', primaryFeaturePascal: 'Allocations', primaryFeatureLabel: 'My Allocations',
    greetingName: 'Sommelier Beatrice Lund', greetingInsight: 'A Burgundy allocation clears customs tomorrow.',
    insightCard: 'Your requested Burgundy futures cleared customs a day early — the rep flagged 6 cases as available for immediate pickup.',
    kpis: [{ label: 'Standing Allocation', value: 'Monthly' }, { label: 'Cases in Transit', value: 18 }, { label: 'Account Since', value: '5 yrs' }],
    actionItems: [{ title: 'Allocation ready for pickup', detail: '6 cases, cleared customs early', tone: 'accent' }, { title: 'Confirm futures order', detail: 'Bordeaux, next vintage', tone: 'default' }],
    activity: [{ label: 'Allocation cleared customs', time: '4h ago' }, { label: 'Futures order placed', time: '1 week ago' }, { label: 'Previous allocation delivered', time: '3 weeks ago' }, { label: 'Tasting sample sent', time: '1 mo ago' }, { label: 'Became an account', time: '5 yrs ago' }],
    tableColumns: ['Allocation', 'Rep'], filters: ['In Transit', 'Cleared', 'Delivered'],
    itemTypes: ['Burgundy Allocation'], details: ['Ready for pickup'],
  },
  {
    name: 'Blackridge Security — Client App', category: 'Mobile-RealEstate', paletteId: 'mono-dev-dark',
    description: 'Client app for a residential security installation firm — system status and monitoring.',
    appName: 'Blackridge Security', navIcon: 'lock-closed', primaryFeaturePascal: 'System', primaryFeatureLabel: 'My System',
    greetingName: 'Vivienne Ashcroft', greetingInsight: 'Your perimeter system passed its quarterly test.',
    insightCard: 'All access points tested clean this quarter — the technician noted the east gate sensor could use a battery swap next visit.',
    kpis: [{ label: 'System Status', value: 'Active' }, { label: 'Last Test', value: 'Passed' }, { label: 'Service Contract', value: 'Active' }],
    actionItems: [{ title: 'Quarterly test passed', detail: 'All access points clear', tone: 'accent' }, { title: 'Battery swap suggested', detail: 'East gate sensor', tone: 'default' }],
    activity: [{ label: 'Quarterly test completed', time: '2 days ago' }, { label: 'Access log reviewed', time: '1 week ago' }, { label: 'System upgrade installed', time: '3 mo ago' }, { label: 'Safe room commissioned', time: '8 mo ago' }, { label: 'Became a client', time: '3 yrs ago' }],
    tableColumns: ['System', 'Technician'], filters: ['Active', 'Testing', 'Servicing'],
    itemTypes: ['Perimeter System'], details: ['Active'],
  },
  {
    name: 'Meridian Boat Works — Owner App', category: 'Mobile-RealEstate', paletteId: 'precision-sky-dark',
    description: 'Owner app for a custom boat building yard — build progress and photos.',
    appName: 'Meridian Boat Works', navIcon: 'boat', primaryFeaturePascal: 'Build', primaryFeatureLabel: 'My Build',
    greetingName: 'Captain Silas Moreau', greetingInsight: 'Hull layup is complete — fit-out begins next week.',
    insightCard: 'The hull came out of the mold ahead of schedule — the yard is ready to start interior fit-out a week early if you approve.',
    kpis: [{ label: 'Build Progress', value: 48, suffix: '%' }, { label: 'Est. Completion', value: '5 mo' }, { label: 'Build Value', value: '380K' }],
    actionItems: [{ title: 'Fit-out can start early', detail: 'Pending your approval', tone: 'accent' }, { title: 'Approve interior finish samples', detail: 'Awaiting selection', tone: 'default' }],
    activity: [{ label: 'Hull layup completed', time: '1 day ago' }, { label: 'Mold released early', time: '3 days ago' }, { label: 'Hull layup began', time: '3 weeks ago' }, { label: 'Design finalized', time: '2 mo ago' }, { label: 'Contract signed', time: '3 mo ago' }],
    tableColumns: ['Milestone', 'Builder'], filters: ['Complete', 'In Progress', 'Upcoming'],
    itemTypes: ['Hull Layup', 'Fit-Out'], details: ['Complete', 'Starts next week'],
  },
  {
    name: 'Aldergate Rug & Textile — Collector App', category: 'Mobile-Creative', paletteId: 'paper-oxblood-light',
    description: 'Collector app for an antique rug and textile dealer — watchlist and restoration status.',
    appName: 'Aldergate Rug & Textile', navIcon: 'layers', primaryFeaturePascal: 'Watchlist', primaryFeatureLabel: 'My Watchlist',
    greetingName: 'Margarethe Voss', greetingInsight: 'Your Tabriz restoration just finished — ready for pickup.',
    insightCard: 'The reweaving on your 19th-century Tabriz matched the original pattern almost seamlessly — the restorer is quite proud of this one.',
    kpis: [{ label: 'Watchlist Items', value: 3 }, { label: 'Pieces Owned', value: 9 }, { label: 'Collection Value', value: '180K' }],
    actionItems: [{ title: 'Restoration complete', detail: '19th-century Tabriz, ready for pickup', tone: 'accent' }, { title: 'New estate acquisition available', detail: 'Matches your watchlist criteria', tone: 'default' }],
    activity: [{ label: 'Restoration completed', time: '1 day ago' }, { label: 'Restoration began', time: '6 weeks ago' }, { label: 'Piece purchased', time: '2 mo ago' }, { label: 'Watchlist match found', time: '3 mo ago' }, { label: 'Became a client', time: '4 yrs ago' }],
    tableColumns: ['Piece', 'Dealer Contact'], filters: ['Watching', 'Available', 'Acquired'],
    itemTypes: ['19th-Century Tabriz'], details: ['Restored, ready'],
  },
  {
    name: 'Aldercroft Neon Works — Client App', category: 'Mobile-Creative', paletteId: 'creative-violet-dark',
    description: 'Client app for a custom neon and signage fabrication studio — commission status.',
    appName: 'Aldercroft Neon Works', navIcon: 'bulb', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Django Marchetti', greetingInsight: 'Your sign install is scheduled for Friday.',
    insightCard: 'The fabricator finished wiring a day early — the install crew can move your rooftop sign up to Friday if that works.',
    kpis: [{ label: 'Commission Progress', value: 84, suffix: '%' }, { label: 'Est. Install', value: 'Friday' }, { label: 'Commission Value', value: '6.2K' }],
    actionItems: [{ title: 'Install moved to Friday', detail: 'Ahead of original schedule', tone: 'accent' }, { title: 'Permit confirmed', detail: 'No further action needed', tone: 'default' }],
    activity: [{ label: 'Wiring completed early', time: '1 day ago' }, { label: 'Glass bending completed', time: '1 week ago' }, { label: 'Permit approved', time: '2 weeks ago' }, { label: 'Design approved', time: '3 weeks ago' }, { label: 'Commission started', time: '1 mo ago' }],
    tableColumns: ['Milestone', 'Fabricator'], filters: ['Complete', 'In Progress', 'Upcoming'],
    itemTypes: ['Wiring', 'Installation'], details: ['Complete', 'Friday'],
  },
  {
    name: 'Aldergate Glass Studio — Client App', category: 'Mobile-Creative', paletteId: 'gallery-red-light',
    description: 'Client app for a stained glass studio — commission and restoration status.',
    appName: 'Aldergate Glass Studio', navIcon: 'color-palette', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Reverend Alden Voss', greetingInsight: 'Final leading begins on the window this week.',
    insightCard: 'The heritage board approved the restoration materials without changes — final leading can begin as scheduled.',
    kpis: [{ label: 'Commission Progress', value: 66, suffix: '%' }, { label: 'Est. Completion', value: '6 wks' }, { label: 'Commission Value', value: '22K' }],
    actionItems: [{ title: 'Final leading begins this week', detail: 'Materials approved', tone: 'accent' }, { title: 'Heritage approval received', detail: 'No further action needed', tone: 'default' }],
    activity: [{ label: 'Heritage approval received', time: '2 days ago' }, { label: 'Glass cutting completed', time: '2 weeks ago' }, { label: 'Design finalized', time: '1 mo ago' }, { label: 'Assessment completed', time: '2 mo ago' }, { label: 'Contract signed', time: '2 mo ago' }],
    tableColumns: ['Milestone', 'Glassworker'], filters: ['Complete', 'In Progress', 'Upcoming'],
    itemTypes: ['Glass Cutting', 'Final Leading'], details: ['Complete', 'Starts this week'],
  },
  {
    name: 'Fernbrook Cider House — Wholesale App', category: 'Mobile-Food', paletteId: 'forest-market-light',
    description: 'Wholesale account app for a private cider house — standing orders and new batches.',
    appName: 'Fernbrook Cider House', navIcon: 'nutrition', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'My Orders',
    greetingName: 'Beverage Director Otto Lindqvist', greetingInsight: 'The new barrel-aged reserve just released.',
    insightCard: 'This season’s barrel-aged reserve came out drier than last year’s batch — your rep set aside a case for you to taste first.',
    kpis: [{ label: 'Standing Order', value: 'Monthly' }, { label: 'Next Delivery', value: '1 wk' }, { label: 'Account Since', value: '2 yrs' }],
    actionItems: [{ title: 'New reserve released', detail: 'Taste sample reserved', tone: 'accent' }, { title: 'Confirm next order', detail: 'Standard monthly order', tone: 'default' }],
    activity: [{ label: 'New reserve released', time: '2 days ago' }, { label: 'Monthly order confirmed', time: '1 week ago' }, { label: 'Last delivery received', time: '3 weeks ago' }, { label: 'Tasting sample requested', time: '1 mo ago' }, { label: 'Became a wholesale account', time: '2 yrs ago' }],
    tableColumns: ['Batch', 'Cellar Master'], filters: ['Available', 'Sample Sent', 'Ordered'],
    itemTypes: ['Barrel-Aged Reserve'], details: ['Sample reserved'],
  },
  {
    name: 'Aldercroft Fur Atelier — Client App', category: 'Mobile-Creative', paletteId: 'luxury-gold-dark',
    description: 'Client app for a fur restoration atelier — commission status and cold storage.',
    appName: 'Aldercroft Fur Atelier', navIcon: 'shirt', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Genevieve Thorncroft', greetingInsight: 'Your coat relining finishes this week.',
    insightCard: 'The furrier finished relining a few days early — final pressing is the only step remaining before pickup.',
    kpis: [{ label: 'Commission Progress', value: 88, suffix: '%' }, { label: 'Est. Completion', value: '3 days' }, { label: 'Storage Status', value: 'Active' }],
    actionItems: [{ title: 'Final pressing this week', detail: 'Ready for pickup soon', tone: 'accent' }, { title: 'Storage renewal due', detail: 'Annual renewal', tone: 'default' }],
    activity: [{ label: 'Relining completed', time: '1 day ago' }, { label: 'Condition assessment completed', time: '3 weeks ago' }, { label: 'Commission started', time: '1 mo ago' }, { label: 'Cold storage inspection passed', time: '3 mo ago' }, { label: 'Became a client', time: '6 yrs ago' }],
    tableColumns: ['Garment', 'Furrier'], filters: ['Assessment', 'Restoration', 'Finishing'],
    itemTypes: ['Coat Relining'], details: ['Final pressing'],
  },
  {
    name: 'Aldergate Regalia House — Client App', category: 'Mobile-Creative', paletteId: 'midnight-press-dark',
    description: 'Institutional client app for an embroidery and regalia house — commission status.',
    appName: 'Aldergate Regalia House', navIcon: 'ribbon', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Registrar Cornelius Whitfield', greetingInsight: 'Your regalia commission clears final inspection this week.',
    insightCard: 'The goldwork on your ceremonial sash matched the heraldic reference exactly — final inspection is scheduled for Thursday.',
    kpis: [{ label: 'Commission Progress', value: 91, suffix: '%' }, { label: 'Est. Delivery', value: '1 wk' }, { label: 'Institution Since', value: '12 yrs' }],
    actionItems: [{ title: 'Final inspection Thursday', detail: 'Ceremonial sash', tone: 'accent' }, { title: 'Confirm delivery address', detail: 'For upcoming ceremony', tone: 'default' }],
    activity: [{ label: 'Goldwork completed', time: '2 days ago' }, { label: 'Design digitized', time: '3 weeks ago' }, { label: 'Commission started', time: '1 mo ago' }, { label: 'Previous order delivered', time: '1 yr ago' }, { label: 'Became an institutional client', time: '12 yrs ago' }],
    tableColumns: ['Piece', 'Embroiderer'], filters: ['Digitizing', 'Stitching', 'Finishing'],
    itemTypes: ['Ceremonial Sash'], details: ['Final inspection'],
  },
  {
    name: 'Ferrous Detailing Studio — Client App', category: 'Mobile-RealEstate', paletteId: 'mono-dev-dark',
    description: 'Client app for a concours car detailing studio — job status and photos.',
    appName: 'Ferrous Detailing', navIcon: 'car-sport', primaryFeaturePascal: 'Job', primaryFeatureLabel: 'My Job',
    greetingName: 'Maximilian Reyes', greetingInsight: 'Your paint correction finishes tomorrow.',
    insightCard: 'The multi-stage correction removed swirl marks the previous shop couldn’t — the detailer says it’s ready for coating tomorrow.',
    kpis: [{ label: 'Job Progress', value: 78, suffix: '%' }, { label: 'Est. Completion', value: 'Tomorrow' }, { label: 'Job Value', value: '1.8K' }],
    actionItems: [{ title: 'Coating scheduled tomorrow', detail: 'Correction complete', tone: 'accent' }, { title: 'Review before/after photos', detail: 'Just uploaded', tone: 'default' }],
    activity: [{ label: 'Paint correction completed', time: '3h ago' }, { label: 'Multi-stage correction began', time: '3 days ago' }, { label: 'Vehicle dropped off', time: '4 days ago' }, { label: 'Booking confirmed', time: '1 week ago' }, { label: 'Became a client', time: '2 yrs ago' }],
    tableColumns: ['Job', 'Detailer'], filters: ['Correction', 'Coating', 'Finishing'],
    itemTypes: ['Multi-Stage Correction'], details: ['Coating tomorrow'],
  },
]

export const mobileBatch8 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: {
    description: spec.description,
    appName: spec.appName,
    navIcon: spec.navIcon,
    primaryFeaturePascal: spec.primaryFeaturePascal,
    primaryFeatureLabel: spec.primaryFeatureLabel,
    greetingName: spec.greetingName,
    greetingInsight: spec.greetingInsight,
    insightCard: spec.insightCard,
    kpis: spec.kpis,
    actionItems: spec.actionItems,
    activity: spec.activity,
    primaryTable: {
      columns: spec.tableColumns,
      filters: spec.filters,
      rows: spec.itemTypes.map((item, i) => ({
        cells: [item, spec.details[i % spec.details.length]],
        status: spec.filters[i % spec.filters.length],
      })),
    },
  },
}))
