const specs = [
  {
    name: 'Birchwood Equestrian — Boarder App', category: 'Mobile-RealEstate', paletteId: 'clay-sand-light',
    description: 'Boarder app for an equestrian facility — horse care updates and billing.',
    appName: 'Birchwood Equestrian', navIcon: 'paw', primaryFeaturePascal: 'Horse', primaryFeatureLabel: 'My Horse',
    greetingName: 'Elin Torvald', greetingInsight: 'Your horse had a great week.',
    insightCard: 'Your farrier visit is scheduled for Thursday — no action needed on your end.',
    kpis: [{ label: 'Turnout (wk)', value: 6 }, { label: 'Next Vet Visit', value: '12 days' }, { label: 'Feed Plan', value: 'Current' }],
    actionItems: [{ title: 'Farrier visit Thursday', detail: 'No action needed', tone: 'accent' }, { title: 'Update emergency contact', detail: 'On file info outdated', tone: 'warning' }],
    activity: [{ label: 'Turnout logged — 2 hours', time: '3h ago' }, { label: 'Feeding plan updated by barn manager', time: 'yesterday' }, { label: 'Vet visit completed — all clear', time: '2 weeks ago' }, { label: 'Training session logged', time: '2 weeks ago' }, { label: 'Boarding started', time: '1 yr ago' }],
    tableColumns: ['Service', 'Barn Manager'], filters: ['Scheduled', 'Completed', 'Upcoming'],
    itemTypes: ['Farrier Visit', 'Vet Checkup', 'Training Session'],
    details: ['Thursday', 'Completed', 'Completed'],
  },
  {
    name: 'Ashcombe Lounge — Member App', category: 'Mobile-Food', paletteId: 'supper-club-dark',
    description: 'Member app for a private cigar and spirits lounge.',
    appName: 'Ashcombe Lounge', navIcon: 'flame', primaryFeaturePascal: 'Reservations', primaryFeatureLabel: 'Reservations',
    greetingName: 'Julian Marsh', greetingInsight: 'Your table is confirmed for Friday.',
    insightCard: 'Your humidor locker is due for a humidity check — the lounge team can handle it during your next visit.',
    kpis: [{ label: 'Visits (mo)', value: 6 }, { label: 'Locker Status', value: 'Active' }, { label: 'Member Tier', value: 'Founding' }],
    actionItems: [{ title: 'Confirm Friday reservation', detail: '7 PM, lounge table', tone: 'accent' }, { title: 'Locker humidity check due', detail: 'Next visit', tone: 'default' }],
    activity: [{ label: 'Reservation confirmed for Friday', time: '1h ago' }, { label: 'Locker restocked', time: '1 week ago' }, { label: 'Attended a tasting event', time: '2 weeks ago' }, { label: 'Renewed founding membership', time: '2 mo ago' }, { label: 'Joined the lounge', time: '4 yrs ago' }],
    tableColumns: ['Reservation', 'Host'], filters: ['Confirmed', 'Waitlisted', 'Past'],
    itemTypes: ['Lounge Table', 'Private Room'], details: ['Fri 7 PM', 'Past event'],
  },
  {
    name: 'Verrier Corporate Art — Client App', category: 'Mobile-Creative', paletteId: 'gallery-red-light',
    description: 'Client app for a corporate art advisory firm.',
    appName: 'Verrier Advisory', navIcon: 'color-palette', primaryFeaturePascal: 'Collection', primaryFeatureLabel: 'Our Collection',
    greetingName: 'Nina Whitfield', greetingInsight: 'A new work was added to your lobby collection.',
    insightCard: 'The rotation schedule suggests refreshing the executive floor collection next quarter — your curator has 3 proposals ready.',
    kpis: [{ label: 'Works Managed', value: 42 }, { label: 'Collection Value', value: '2.1M' }, { label: 'Next Rotation', value: 'Q3' }],
    actionItems: [{ title: 'Review rotation proposals', detail: '3 options from your curator', tone: 'accent' }, { title: 'Insurance appraisal due', detail: 'Annual update', tone: 'default' }],
    activity: [{ label: 'New work installed in lobby', time: '2 days ago' }, { label: 'Curatorial proposal received', time: '1 week ago' }, { label: 'Insurance appraisal completed', time: '3 weeks ago' }, { label: 'Executive floor collection reviewed', time: '1 mo ago' }, { label: 'Collection program started', time: '2 yrs ago' }],
    tableColumns: ['Work', 'Location'], filters: ['Installed', 'In Review', 'Rotating'],
    itemTypes: ['Corporate Lobby Collection', 'Executive Floor Collection'], details: ['Installed', 'Rotation planned'],
  },
  {
    name: 'Aldergate Remodeling — Client App', category: 'Mobile-Creative', paletteId: 'brutalist-light',
    description: 'Client app for a kitchen and bath remodeling firm — project progress and approvals.',
    appName: 'Aldergate Remodeling', navIcon: 'hammer', primaryFeaturePascal: 'Project', primaryFeatureLabel: 'My Project',
    greetingName: 'Marcus Rivera', greetingInsight: 'Your kitchen enters cabinetry install this week.',
    insightCard: 'Your final inspection is scheduled for Friday — this is typically the last step before completion.',
    kpis: [{ label: 'Progress', value: 84, suffix: '%' }, { label: 'Est. Completion', value: '2 wks' }, { label: 'Change Orders', value: 0 }],
    actionItems: [{ title: 'Final inspection Friday', detail: 'No action needed', tone: 'accent' }, { title: 'Approve final fixture selections', detail: 'Before Friday', tone: 'warning' }],
    activity: [{ label: 'Cabinetry installation began', time: '1 day ago' }, { label: 'Countertop template completed', time: '4 days ago' }, { label: 'Plumbing rough-in passed inspection', time: '1 week ago' }, { label: 'Framing completed', time: '2 weeks ago' }, { label: 'Project started', time: '6 weeks ago' }],
    tableColumns: ['Phase', 'Project Manager'], filters: ['Scheduled', 'In Progress', 'Complete'],
    itemTypes: ['Cabinetry Install', 'Final Inspection'], details: ['In progress', 'Friday'],
  },
  {
    name: 'Meridian Marine — Diver App', category: 'Mobile-Logistics', paletteId: 'precision-sky-dark',
    description: 'Diver app for a marine expedition company — trip prep and gear checklists.',
    appName: 'Meridian Marine', navIcon: 'boat', primaryFeaturePascal: 'Expedition', primaryFeatureLabel: 'My Expedition',
    greetingName: 'Rafael Solis', greetingInsight: 'Your Red Sea expedition departs in 12 days.',
    insightCard: 'Your gear checklist is 80% complete — your dive computer certification is the last item needed.',
    kpis: [{ label: 'Days to Departure', value: 12 }, { label: 'Gear Checklist', value: 80, suffix: '%' }, { label: 'Dives Logged', value: 84 }],
    actionItems: [{ title: 'Upload dive computer certification', detail: 'Last item on checklist', tone: 'warning' }, { title: 'Final briefing call', detail: 'Scheduled 3 days before departure', tone: 'accent' }],
    activity: [{ label: 'Gear checklist updated — 4 of 5 complete', time: '2h ago' }, { label: 'Medical form submitted', time: '3 days ago' }, { label: 'Deposit paid', time: '1 week ago' }, { label: 'Expedition confirmed', time: '2 weeks ago' }, { label: 'Joined as a repeat diver', time: '3 yrs ago' }],
    tableColumns: ['Item', 'Status'], filters: ['Confirmed', 'Pending', 'Complete'],
    itemTypes: ['Red Sea Expedition'], details: ['Departs in 12 days'],
  },
  {
    name: 'Aldercroft Timepieces — Collector App', category: 'Mobile-Creative', paletteId: 'gallery-red-light',
    description: 'Collector app for a fine watch dealer — wishlist and consignment tracking.',
    appName: 'Aldercroft Timepieces', navIcon: 'watch', primaryFeaturePascal: 'Watchlist', primaryFeatureLabel: 'My Watchlist',
    greetingName: 'Rem Achebe', greetingInsight: 'A watch on your wishlist just became available.',
    insightCard: 'The Vintage Chronograph you saved last month is now available and authenticated — similar pieces sell within days.',
    kpis: [{ label: 'Watchlist Items', value: 4 }, { label: 'Pieces Owned', value: 3 }, { label: 'New Matches', value: 1 }],
    actionItems: [{ title: 'Vintage Chronograph now available', detail: 'From your watchlist', tone: 'accent' }, { title: 'Consignment offer pending', detail: 'Review the appraisal', tone: 'default' }],
    activity: [{ label: 'Vintage Chronograph matched your watchlist', time: '2h ago' }, { label: 'Consignment appraisal received', time: '3 days ago' }, { label: 'Purchased a Classic Dress Watch', time: '2 mo ago' }, { label: 'Added a piece to watchlist', time: '3 mo ago' }, { label: 'Became a client', time: '2 yrs ago' }],
    tableColumns: ['Piece', 'Status'], filters: ['Available', 'Watchlist', 'Owned'],
    itemTypes: ['Vintage Chronograph', 'Classic Dress Watch'], details: ['Available', 'Owned'],
  },
  {
    name: 'Birchwood Golf Club — Member App', category: 'Mobile-RealEstate', paletteId: 'forest-market-light',
    description: 'Member app for a private golf club — tee time booking and events.',
    appName: 'Birchwood Golf Club', navIcon: 'flag', primaryFeaturePascal: 'TeeTimes', primaryFeatureLabel: 'Tee Times',
    greetingName: 'Owen Berg', greetingInsight: 'Your tee time is confirmed for Saturday.',
    insightCard: 'The member-guest tournament fills up fast — registration opened this morning.',
    kpis: [{ label: 'Rounds (mo)', value: 6 }, { label: 'Handicap', value: 12.4 }, { label: 'Next Tee Time', value: 'Sat 9 AM' }],
    actionItems: [{ title: 'Register for member-guest', detail: 'Registration just opened', tone: 'accent' }, { title: 'Confirm Saturday tee time', detail: '9 AM, Course A', tone: 'default' }],
    activity: [{ label: 'Booked Saturday tee time', time: '1h ago' }, { label: 'Round logged — shot 84', time: '1 week ago' }, { label: 'Handicap updated', time: '1 week ago' }, { label: 'Attended the spring social', time: '3 weeks ago' }, { label: 'Became a member', time: '5 yrs ago' }],
    tableColumns: ['Tee Time', 'Course'], filters: ['Confirmed', 'Waitlisted', 'Past'],
    itemTypes: ['Saturday 9 AM', 'Sunday 11 AM'], details: ['Course A', 'Course B'],
  },
  {
    name: 'Fernbrook Ceramics — Client App', category: 'Mobile-Creative', paletteId: 'clay-sand-light',
    description: 'Client app for a ceramics studio — custom order tracking.',
    appName: 'Fernbrook Ceramics', navIcon: 'flower', primaryFeaturePascal: 'Order', primaryFeatureLabel: 'My Order',
    greetingName: 'Aisha Patel', greetingInsight: 'Your dinnerware set enters glazing this week.',
    insightCard: 'Your glaze selection was confirmed — the set fires next Tuesday and typically cools for 48 hours after.',
    kpis: [{ label: 'Progress', value: 68, suffix: '%' }, { label: 'Est. Ready', value: '10 days' }, { label: 'Pieces', value: 12 }],
    actionItems: [{ title: 'Firing scheduled Tuesday', detail: 'No action needed', tone: 'accent' }, { title: 'Pickup reminder', detail: 'When ready', tone: 'default' }],
    activity: [{ label: 'Glaze selection confirmed', time: '2 days ago' }, { label: 'Bisque firing completed', time: '1 week ago' }, { label: 'Throwing completed', time: '2 weeks ago' }, { label: 'Order placed', time: '3 weeks ago' }],
    tableColumns: ['Order', 'Potter'], filters: ['Throwing', 'Glazing', 'Complete'],
    itemTypes: ['Custom Dinnerware Set'], details: ['Glazing this week'],
  },
  {
    name: 'Ferrous Culinary Academy — Student App', category: 'Mobile-Education', paletteId: 'food-amber-light',
    description: 'Student app for a private culinary school — schedule and externship tracking.',
    appName: 'Ferrous Culinary Academy', navIcon: 'restaurant', primaryFeaturePascal: 'Schedule', primaryFeatureLabel: 'My Schedule',
    greetingName: 'Tomás Kowalski', greetingInsight: 'Your externship starts next week.',
    insightCard: 'Your practical exam is scheduled for Friday — review your knife skills checklist before then.',
    kpis: [{ label: 'Program Progress', value: 74, suffix: '%' }, { label: 'Externship', value: 'Next week' }, { label: 'GPA', value: 3.8 }],
    actionItems: [{ title: 'Practical exam Friday', detail: 'Review knife skills checklist', tone: 'warning' }, { title: 'Externship orientation', detail: 'Monday, 9 AM', tone: 'accent' }],
    activity: [{ label: 'Grade posted for pastry module', time: '1 day ago' }, { label: 'Externship placement confirmed', time: '3 days ago' }, { label: 'Completed knife skills assessment', time: '1 week ago' }, { label: 'Started advanced techniques module', time: '2 weeks ago' }, { label: 'Enrolled in Culinary Arts Certificate', time: '4 mo ago' }],
    tableColumns: ['Module', 'Instructor'], filters: ['Active', 'Upcoming', 'Complete'],
    itemTypes: ['Advanced Techniques', 'Externship'], details: ['In progress', 'Starts Monday'],
  },
  {
    name: 'Ashcombe Motorcars — Client App', category: 'Mobile-RealEstate', paletteId: 'luxury-gold-dark',
    description: 'Client app for a luxury and classic car dealership — sourcing updates.',
    appName: 'Ashcombe Motorcars', navIcon: 'car', primaryFeaturePascal: 'Search', primaryFeatureLabel: 'My Search',
    greetingName: 'Colin Whitford', greetingInsight: 'A match for your search was found at auction.',
    insightCard: 'Your sourcing advisor found a matching vehicle at a European auction — bidding opens Thursday.',
    kpis: [{ label: 'Active Search', value: 1 }, { label: 'Matches Found', value: 2 }, { label: 'Budget', value: '$220K' }],
    actionItems: [{ title: 'Review auction match', detail: 'Bidding opens Thursday', tone: 'accent' }, { title: 'Approve inspection report', detail: 'For the second match', tone: 'default' }],
    activity: [{ label: 'Auction match found in Europe', time: '3h ago' }, { label: 'Inspection report received', time: '2 days ago' }, { label: 'Sourcing advisor assigned', time: '1 week ago' }, { label: 'Search criteria confirmed', time: '1 week ago' }, { label: 'Became a client', time: '2 yrs ago' }],
    tableColumns: ['Vehicle', 'Source'], filters: ['Sourcing', 'Inspecting', 'Found'],
    itemTypes: ['Vintage Sports Coupe'], details: ['European auction'],
  },
]

export const mobileBatch4 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: {
    description: spec.description,
    appName: spec.appName,
    navIcon: spec.navIcon,
    primaryFeaturePascal: spec.primaryFeaturePascal,
    primaryFeatureLabel: spec.primaryFeatureLabel,
    greetingName: spec.greetingName,
    greetingInsight: spec.greetingInsight,
    insightCard: spec.insightCard,
    kpis: spec.kpis,
    actionItems: spec.actionItems,
    activity: spec.activity,
    primaryTable: {
      columns: spec.tableColumns,
      filters: spec.filters,
      rows: spec.itemTypes.map((item, i) => ({
        cells: [item, spec.details[i % spec.details.length]],
        status: spec.filters[i % spec.filters.length],
      })),
    },
  },
}))
