const specs = [
  {
    name: 'Corbridge Numismatics — Collector App', category: 'Mobile-Creative', paletteId: 'gallery-red-light',
    description: 'Collector app for a private numismatics dealer — watchlist and grading updates.',
    appName: 'Corbridge Numismatics', navIcon: 'diamond', primaryFeaturePascal: 'Watchlist', primaryFeatureLabel: 'My Watchlist',
    greetingName: 'Alistair Pemberton', greetingInsight: 'A coin on your watchlist just cleared grading.',
    insightCard: 'The 1804 dollar you flagged came back from grading at MS-63 — better than the estimate given at intake.',
    kpis: [{ label: 'Watchlist Items', value: 4 }, { label: 'Coins Owned', value: 18 }, { label: 'Collection Value', value: '210K' }],
    actionItems: [{ title: 'Review grading result', detail: '1804 dollar graded MS-63', tone: 'accent' }, { title: 'Insurance appraisal due', detail: 'Annual renewal', tone: 'default' }],
    activity: [{ label: 'Grading result received', time: '3h ago' }, { label: 'Purchased a territorial gold coin', time: '3 weeks ago' }, { label: 'Appraisal completed', time: '2 mo ago' }, { label: 'Added item to watchlist', time: '2 mo ago' }, { label: 'Became a client', time: '6 yrs ago' }],
    tableColumns: ['Coin', 'Dealer Contact'], filters: ['Watching', 'Available', 'Acquired'],
    itemTypes: ['1804 Silver Dollar', 'Territorial Gold Coin'], details: ['Graded MS-63', 'Owned'],
  },
  {
    name: 'Blacktape Mastering — Artist App', category: 'Mobile-Creative', paletteId: 'mono-dev-dark',
    description: 'Artist app for an audio mastering studio — session status and delivery.',
    appName: 'Blacktape Mastering', navIcon: 'musical-notes', primaryFeaturePascal: 'Sessions', primaryFeatureLabel: 'My Sessions',
    greetingName: 'Nadia Okonkwo', greetingInsight: 'Your album master is ready for review.',
    insightCard: 'The engineer matched loudness across all 11 tracks — the reference mix note about track 6 has been addressed.',
    kpis: [{ label: 'Active Sessions', value: 1 }, { label: 'Releases Delivered', value: 4 }, { label: 'Avg. Turnaround', value: '3 days' }],
    actionItems: [{ title: 'Review album master', detail: '11 tracks, ready for approval', tone: 'accent' }, { title: 'Confirm distributor delivery', detail: 'Releases Friday', tone: 'default' }],
    activity: [{ label: 'Album master delivered for review', time: '5h ago' }, { label: 'Revision requested on track 6', time: '2 days ago' }, { label: 'First pass completed', time: '4 days ago' }, { label: 'Session started', time: '1 week ago' }, { label: 'Became a client', time: '2 yrs ago' }],
    tableColumns: ['Release', 'Engineer'], filters: ['Mastering', 'Revisions', 'Delivered'],
    itemTypes: ['Full Album Master'], details: ['Ready for review'],
  },
  {
    name: 'Ferrous Custom Motorworks — Client App', category: 'Mobile-Creative', paletteId: 'brutalist-light',
    description: 'Client app for a custom motorcycle fabrication shop — build progress and photos.',
    appName: 'Ferrous Motorworks', navIcon: 'construct', primaryFeaturePascal: 'Build', primaryFeatureLabel: 'My Build',
    greetingName: 'Rufus Calloway', greetingInsight: 'Your frame passed inspection — assembly starts this week.',
    insightCard: 'The fabricator finished the frame welds a few days early — engine assembly begins Monday if parts arrive on time.',
    kpis: [{ label: 'Build Progress', value: 58, suffix: '%' }, { label: 'Est. Completion', value: '3 mo' }, { label: 'Build Value', value: '42K' }],
    actionItems: [{ title: 'Assembly starts Monday', detail: 'Pending final parts delivery', tone: 'accent' }, { title: 'Approve paint color', detail: 'Awaiting your selection', tone: 'default' }],
    activity: [{ label: 'Frame passed inspection', time: '1 day ago' }, { label: 'Frame welding completed', time: '1 week ago' }, { label: 'Parts ordered', time: '3 weeks ago' }, { label: 'Design finalized', time: '1 mo ago' }, { label: 'Deposit paid', time: '2 mo ago' }],
    tableColumns: ['Milestone', 'Fabricator'], filters: ['Complete', 'In Progress', 'Upcoming'],
    itemTypes: ['Frame Fabrication', 'Engine Assembly'], details: ['Complete', 'Starts Monday'],
  },
  {
    name: 'Fernbrook Tea Merchants — Wholesale App', category: 'Mobile-Food', paletteId: 'food-amber-light',
    description: 'Wholesale account app for a private tea import merchant — standing orders and new lots.',
    appName: 'Fernbrook Tea Merchants', navIcon: 'cafe', primaryFeaturePascal: 'Orders', primaryFeatureLabel: 'My Orders',
    greetingName: 'Yuki Tanaka', greetingInsight: 'A new first-flush Darjeeling lot just cleared cupping.',
    insightCard: 'This season’s first-flush Darjeeling scored 94 in cupping — your buyer flagged it as a strong match for your menu.',
    kpis: [{ label: 'Standing Order', value: 'Monthly' }, { label: 'Next Delivery', value: '5 days' }, { label: 'Account Since', value: '4 yrs' }],
    actionItems: [{ title: 'New lot recommendation', detail: 'First-flush Darjeeling, score 94', tone: 'accent' }, { title: 'Confirm next delivery', detail: 'Standard monthly order', tone: 'default' }],
    activity: [{ label: 'New lot recommended', time: '1 day ago' }, { label: 'Monthly order confirmed', time: '1 week ago' }, { label: 'Last delivery received', time: '3 weeks ago' }, { label: 'Sample requested', time: '1 mo ago' }, { label: 'Became a wholesale account', time: '4 yrs ago' }],
    tableColumns: ['Lot', 'Buyer'], filters: ['Available', 'Sample Sent', 'Ordered'],
    itemTypes: ['First-Flush Darjeeling'], details: ['Recommended'],
  },
  {
    name: 'Highridge Observatory — Member App', category: 'Mobile-Lifestyle', paletteId: 'midnight-press-dark',
    description: 'Member app for a private astronomy observatory — session booking and sky conditions.',
    appName: 'Highridge Observatory', navIcon: 'telescope', primaryFeaturePascal: 'Sessions', primaryFeatureLabel: 'My Sessions',
    greetingName: 'Imogen Falk', greetingInsight: 'Tonight’s sky conditions are excellent for your booked session.',
    insightCard: 'Seeing conditions tonight are the clearest this month — the astronomer added Saturn’s rings to tonight’s viewing list.',
    kpis: [{ label: 'Sessions (YTD)', value: 9 }, { label: 'Clear-Sky Rate', value: 68, suffix: '%' }, { label: 'Member Since', value: '2 yrs' }],
    actionItems: [{ title: 'Tonight’s session confirmed', detail: 'Excellent viewing conditions', tone: 'accent' }, { title: 'Book next month’s meteor shower', detail: 'Spots filling fast', tone: 'default' }],
    activity: [{ label: 'Session confirmed for tonight', time: '2h ago' }, { label: 'Previous session completed', time: '3 weeks ago' }, { label: 'Session rescheduled for weather', time: '1 mo ago' }, { label: 'Astrophotography session booked', time: '2 mo ago' }, { label: 'Became a member', time: '2 yrs ago' }],
    tableColumns: ['Session', 'Astronomer'], filters: ['Confirmed', 'Weather Watch', 'Completed'],
    itemTypes: ['Private Viewing Session'], details: ['Confirmed'],
  },
  {
    name: 'Ashgrove Forgeworks — Client App', category: 'Mobile-Creative', paletteId: 'midnight-press-dark',
    description: 'Client app for a bladesmith workshop — commission status and forge updates.',
    appName: 'Ashgrove Forgeworks', navIcon: 'hammer', primaryFeaturePascal: 'Commission', primaryFeatureLabel: 'My Commission',
    greetingName: 'Soren Dahl', greetingInsight: 'Your blade cleared heat treatment — finishing begins this week.',
    insightCard: 'The Damascus pattern came out cleaner than the test billet — the bladesmith says finishing should take about a week.',
    kpis: [{ label: 'Commission Progress', value: 71, suffix: '%' }, { label: 'Est. Completion', value: '2 wks' }, { label: 'Commission Value', value: '1.8K' }],
    actionItems: [{ title: 'Finishing begins this week', detail: 'Handle and sheath work', tone: 'accent' }, { title: 'Approve handle material', detail: 'Awaiting your selection', tone: 'default' }],
    activity: [{ label: 'Heat treatment completed', time: '2 days ago' }, { label: 'Forge welding completed', time: '1 week ago' }, { label: 'Steel selected', time: '3 weeks ago' }, { label: 'Commission started', time: '1 mo ago' }, { label: 'Deposit paid', time: '1 mo ago' }],
    tableColumns: ['Milestone', 'Bladesmith'], filters: ['Complete', 'In Progress', 'Upcoming'],
    itemTypes: ['Heat Treatment', 'Finishing'], details: ['Complete', 'Starts this week'],
  },
  {
    name: 'Aldercroft Pen Atelier — Client App', category: 'Mobile-Creative', paletteId: 'ledger-ivory-light',
    description: 'Client app for a luxury pen atelier — order status and engraving proofs.',
    appName: 'Aldercroft Pen Atelier', navIcon: 'create', primaryFeaturePascal: 'Order', primaryFeatureLabel: 'My Order',
    greetingName: 'Cordelia Ashworth', greetingInsight: 'Your engraving proof is ready for approval.',
    insightCard: 'The engraver finished your monogram proof a day early — nib fitting is the only step remaining before shipping.',
    kpis: [{ label: 'Order Progress', value: 82, suffix: '%' }, { label: 'Est. Shipping', value: '1 wk' }, { label: 'Order Value', value: '620' }],
    actionItems: [{ title: 'Approve engraving proof', detail: 'Monogram design ready', tone: 'accent' }, { title: 'Nib fitting scheduled', detail: 'Final step before shipping', tone: 'default' }],
    activity: [{ label: 'Engraving proof sent', time: '4h ago' }, { label: 'Lacquer finish cured', time: '3 days ago' }, { label: 'Body turned', time: '1 week ago' }, { label: 'Order placed', time: '2 weeks ago' }, { label: 'Became a client', time: '1 yr ago' }],
    tableColumns: ['Item', 'Turner'], filters: ['Turning', 'Finishing', 'Engraving'],
    itemTypes: ['Custom Fountain Pen'], details: ['Proof ready'],
  },
  {
    name: 'Aerolume Helicopter Charter — Client App', category: 'Mobile-Logistics', paletteId: 'precision-sky-dark',
    description: 'Client app for a private helicopter charter service — flight status and booking.',
    appName: 'Aerolume Helicopter', navIcon: 'airplane', primaryFeaturePascal: 'Flights', primaryFeatureLabel: 'My Flights',
    greetingName: 'Wren Castellane', greetingInsight: 'Your airport transfer is confirmed for tomorrow.',
    insightCard: 'Your pilot flagged a favorable weather window an hour earlier than scheduled — you can move up if that works better.',
    kpis: [{ label: 'Upcoming Flights', value: 1 }, { label: 'Flights Completed', value: 6 }, { label: 'On-Time Rate', value: 97, suffix: '%' }],
    actionItems: [{ title: 'Earlier departure available', detail: 'Weather window opened up', tone: 'accent' }, { title: 'Confirm ground transport', detail: 'Pickup at landing zone', tone: 'default' }],
    activity: [{ label: 'Flight confirmed for tomorrow', time: '3h ago' }, { label: 'Previous flight completed', time: '2 weeks ago' }, { label: 'Booking made', time: '3 weeks ago' }, { label: 'Corporate account activated', time: '6 mo ago' }, { label: 'First flight booked', time: '1 yr ago' }],
    tableColumns: ['Flight', 'Pilot'], filters: ['Scheduled', 'In Flight', 'Completed'],
    itemTypes: ['Airport Transfer'], details: ['Confirmed'],
  },
  {
    name: 'Ashgrove Stoneworks — Client App', category: 'Mobile-RealEstate', paletteId: 'clay-sand-light',
    description: 'Client app for a stone and masonry restoration firm — project status and photos.',
    appName: 'Ashgrove Stoneworks', navIcon: 'construct', primaryFeaturePascal: 'Project', primaryFeatureLabel: 'My Project',
    greetingName: 'Percival Landry', greetingInsight: 'Stone matching is complete — repointing begins this week.',
    insightCard: 'The mason sourced a near-perfect match for your original limestone — repointing starts Wednesday, weather permitting.',
    kpis: [{ label: 'Project Progress', value: 44, suffix: '%' }, { label: 'Est. Completion', value: '4 mo' }, { label: 'Stone Sourced', value: '3 tons' }],
    actionItems: [{ title: 'Repointing begins Wednesday', detail: 'Weather permitting', tone: 'accent' }, { title: 'Review stone match samples', detail: 'Final approval needed', tone: 'default' }],
    activity: [{ label: 'Stone match sourced', time: '2 days ago' }, { label: 'Structural assessment completed', time: '2 weeks ago' }, { label: 'Permit approved', time: '1 mo ago' }, { label: 'Project scoped', time: '2 mo ago' }, { label: 'Contract signed', time: '2 mo ago' }],
    tableColumns: ['Milestone', 'Mason'], filters: ['Complete', 'In Progress', 'Upcoming'],
    itemTypes: ['Stone Matching', 'Repointing'], details: ['Complete', 'Starts Wednesday'],
  },
  {
    name: 'Corbridge Spirits Auctions — Bidder App', category: 'Mobile-Finance', paletteId: 'supper-club-dark',
    description: 'Bidder app for a rare spirits auction house — live lots and bidding.',
    appName: 'Corbridge Spirits Auctions', navIcon: 'wine', primaryFeaturePascal: 'Lots', primaryFeatureLabel: 'Watching',
    greetingName: 'Thaddeus Renwick', greetingInsight: 'A lot you’re watching just received a competing bid.',
    insightCard: 'The single-cask Macallan you’re watching just passed reserve — three other bidders are active on the same lot.',
    kpis: [{ label: 'Lots Watching', value: 5 }, { label: 'Active Bids', value: 2 }, { label: 'Won This Year', value: 4 }],
    actionItems: [{ title: 'Competing bid placed', detail: 'Single-cask Macallan, reserve met', tone: 'accent' }, { title: 'Auction closes in 2 hours', detail: 'Autumn auction', tone: 'warning' }],
    activity: [{ label: 'Competing bid received', time: '20m ago' }, { label: 'Bid placed on Macallan lot', time: '2h ago' }, { label: 'Won a previous lot', time: '2 mo ago' }, { label: 'Registered for autumn auction', time: '3 mo ago' }, { label: 'Became a registered bidder', time: '2 yrs ago' }],
    tableColumns: ['Lot', 'Current Bid'], filters: ['Watching', 'Bidding', 'Won'],
    itemTypes: ['Single-Cask Macallan'], details: ['Reserve met'],
  },
]

export const mobileBatch7 = specs.map((spec) => ({
  name: spec.name,
  category: spec.category,
  paletteId: spec.paletteId,
  config: {
    description: spec.description,
    appName: spec.appName,
    navIcon: spec.navIcon,
    primaryFeaturePascal: spec.primaryFeaturePascal,
    primaryFeatureLabel: spec.primaryFeatureLabel,
    greetingName: spec.greetingName,
    greetingInsight: spec.greetingInsight,
    insightCard: spec.insightCard,
    kpis: spec.kpis,
    actionItems: spec.actionItems,
    activity: spec.activity,
    primaryTable: {
      columns: spec.tableColumns,
      filters: spec.filters,
      rows: spec.itemTypes.map((item, i) => ({
        cells: [item, spec.details[i % spec.details.length]],
        status: spec.filters[i % spec.filters.length],
      })),
    },
  },
}))
