export const privateEquity = {
  name: 'Private Equity Firm — Deal & Portfolio Suite',
  category: 'Finance',
  paletteId: 'fintech-emerald-dark',
  config: {
    description: 'Deal pipeline, portfolio company tracking, and LP reporting for a private equity firm.',
    appName: 'Kestrel Ridge Capital',
    tagline: 'Disciplined capital for founders who have already done the hard part.',
    loginQuote: 'Every deal, every portfolio company, one pipeline.',
    navIcon: 'Landmark',
    primaryFeatureRoute: 'deals',
    primaryFeaturePascal: 'Deals',
    primaryFeatureLabel: 'Deal Pipeline',
    primaryFeatureSingular: 'Deal',
    greetingName: 'Marcus Ellison',
    greetingInsight: 'Fund III is 68% deployed — the Redshaw Logistics term sheet is due back Friday.',
    dashboardVariant: 'activity',
    kpis: [
      { label: 'AUM (Fund III)', value: 640, suffix: 'M', delta: 4, spark: [560, 580, 595, 605, 615, 625, 632, 640] },
      { label: 'Deployed Capital', value: 68, suffix: '%', delta: 9, spark: [42, 47, 52, 56, 59, 62, 65, 68] },
      { label: 'Active Deals', value: 9, delta: 12, spark: [5, 6, 6, 7, 7, 8, 8, 9] },
      { label: 'Portfolio Companies', value: 14, spark: [11, 11, 12, 12, 13, 13, 14, 14] },
    ],
    weeklyBars: [
      { label: 'W1', value: 3 }, { label: 'W2', value: 4 }, { label: 'W3', value: 2 },
      { label: 'W4', value: 5 }, { label: 'W5', value: 4 }, { label: 'W6', value: 6 },
      { label: 'W7', value: 5 }, { label: 'W8', value: 7 },
    ],
    activity: [
      { label: 'Term sheet issued to Redshaw Logistics — $42M growth round', time: '1 hour ago' },
      { label: 'Due diligence completed on Vantage Materials', time: '3 hours ago' },
      { label: 'Board seat confirmed at Northfield Robotics', time: 'yesterday' },
      { label: 'Q1 LP report distributed to 38 limited partners', time: 'yesterday' },
      { label: 'Add-on acquisition closed for portfolio co. Brightwell Health', time: '2 days ago' },
    ],
    primaryTable: {
      columns: ['Target', 'Sector', 'Deal Size', 'Deal Lead'],
      filters: ['Active', 'Due Diligence', 'Closed'],
      rows: [
        { cells: ['Redshaw Logistics', 'Logistics & Supply Chain', '$42M', 'M. Ellison'], status: 'Active' },
        { cells: ['Vantage Materials', 'Industrial Manufacturing', '$28M', 'C. Whitford'], status: 'Due Diligence' },
        { cells: ['Northfield Robotics', 'Industrial Automation', '$55M', 'M. Ellison'], status: 'Closed' },
        { cells: ['Brightwell Health', 'Healthcare Services', '$19M', 'S. Adeyemi'], status: 'Closed' },
        { cells: ['Coppermill Foods', 'Consumer & Retail', '$31M', 'C. Whitford'], status: 'Due Diligence' },
        { cells: ['Ashgrove Insurance Services', 'Financial Services', '$47M', 'S. Adeyemi'], status: 'Active' },
        { cells: ['Palladium Data Systems', 'Enterprise Software', '$63M', 'M. Ellison'], status: 'Active' },
        { cells: ['Ferrous & Kin Metalworks', 'Industrial Manufacturing', '$22M', 'C. Whitford'], status: 'Closed' },
      ],
    },
    analyticsKpis: [
      { label: 'Capital Deployed (Q)', value: 84, suffix: 'M', delta: 15 },
      { label: 'Gross IRR', value: 24, suffix: '%', delta: 3 },
      { label: 'Portfolio EBITDA Growth', value: 18, suffix: '%', delta: 5 },
      { label: 'Realized Exits', value: 2, delta: 100 },
    ],
    trend: [
      { label: 'Jan', value: 560 }, { label: 'Feb', value: 595 }, { label: 'Mar', value: 615 },
      { label: 'Apr', value: 632 }, { label: 'May', value: 640 },
    ],
    sources: [
      { label: 'Banker referral', value: 4 }, { label: 'Sponsor network', value: 3 },
      { label: 'Direct outreach', value: 1 }, { label: 'Portfolio add-on', value: 1 },
    ],
    rankedTable: {
      label: 'Deal value by lead',
      rows: [
        { name: 'M. Ellison', value: 160 },
        { name: 'S. Adeyemi', value: 66 },
        { name: 'C. Whitford', value: 81 },
      ],
    },
    notifications: [
      { title: 'Term sheet issued', description: 'Redshaw Logistics — $42M growth round, response due Friday.', time: '1 hour ago', unread: true, tone: 'default' },
      { title: 'LP report distributed', description: 'Q1 report sent to all 38 limited partners.', time: 'yesterday', unread: true, tone: 'outline' },
      { title: 'Board seat confirmed', description: 'M. Ellison joins the Northfield Robotics board effective this week.', time: 'yesterday', unread: false, tone: 'solid' },
      { title: 'Add-on acquisition closed', description: 'Brightwell Health completed a bolt-on acquisition.', time: '2 days ago', unread: false, tone: 'default' },
    ],
    team: [
      { name: 'Marcus Ellison', email: 'm.ellison@kestrelridge.com', role: 'Managing Partner' },
      { name: 'Sade Adeyemi', email: 's.adeyemi@kestrelridge.com', role: 'Partner' },
      { name: 'Colin Whitford', email: 'c.whitford@kestrelridge.com', role: 'Principal' },
      { name: 'Renata Silva', email: 'r.silva@kestrelridge.com', role: 'Investor Relations' },
    ],
  },
}
