const specs = [
  {
    name: 'Private Equestrian Center — Marketing Site', category: 'Website-RealEstate', paletteId: 'clay-sand-light',
    spec: {
      description: 'Marketing site for a private equestrian boarding and training facility.',
      brand: 'Birchwood Equestrian Center', tagline: 'EQUESTRIAN BOARDING & TRAINING',
      heroTitle: 'Horses boarded and trained to the standard the owner actually expects.',
      heroDescription: 'Full boarding, training, and lesson programs on 80 acres, with a barn team that treats every horse like their own.',
      heroCta: 'Schedule a facility tour',
      navLinks: [{ label: 'Boarding', href: '#' }, { label: 'Training', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Full Boarding', description: 'Individualized turnout, feeding, and care plans for every horse.' },
        { title: 'Training Programs', description: 'Trainers who compete themselves, not just teach from the rail.' },
        { title: 'Lesson Program', description: 'Riders developed from first lesson through competition.' },
      ],
      stats: [{ value: 34, label: 'Horses Boarded' }, { value: 42, label: 'Lesson Students' }, { value: 89, suffix: '%', label: 'Stall Occupancy' }],
      testimonials: [
        { quote: 'They treat my horse better than most people treat their pets.', name: 'Boarder', role: 'Client', rating: 5 },
        { quote: 'My daughter’s riding has come further in a year than in three years elsewhere.', name: 'Parent', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Looking for the right barn?', ctaDescription: 'Schedule a tour and meet the training team.',
      footerColumns: [{ title: 'Programs', links: [{ label: 'Boarding', href: '#' }, { label: 'Training', href: '#' }] }, { title: 'Facility', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Vineyard Management — Marketing Site', category: 'Website-Food', paletteId: 'forest-market-light',
    spec: {
      description: 'Marketing site for a private vineyard management firm.',
      brand: 'Fernbrook Vineyard Management', tagline: 'VINEYARD MANAGEMENT',
      heroTitle: 'Managing other people’s vineyards like they were our own.',
      heroDescription: 'Full vineyard management for estate owners — canopy management, spray programs, and harvest planning.',
      heroCta: 'Discuss your estate',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Estates', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Canopy Management', description: 'Season-long canopy work tuned to your varietal and site.' },
        { title: 'Spray Program', description: 'A spray schedule built around your actual disease pressure, not a calendar.' },
        { title: 'Harvest Planning', description: 'Brix monitoring and harvest timing coordinated with your winemaker.' },
      ],
      stats: [{ value: 11, label: 'Managed Estates' }, { value: 420, label: 'Acres Under Management' }, { value: 3.8, label: 'Avg. Yield (tons/acre)' }],
      testimonials: [
        { quote: 'Our yield and quality both improved the first season they took over.', name: 'Estate Owner', role: 'Client', rating: 5 },
        { quote: 'They manage the vineyard like it’s their own reputation on the label.', name: 'Winemaker', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Own a vineyard that needs real management?', ctaDescription: 'Discuss your estate with our vineyard management team.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Canopy Management', href: '#' }, { label: 'Harvest Planning', href: '#' }] }, { title: 'Firm', links: [{ label: 'Estates', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Corporate Art Advisory — Marketing Site', category: 'Website-Creative', paletteId: 'gallery-red-light',
    spec: {
      description: 'Marketing site for a corporate art advisory and curation firm.',
      brand: 'Verrier Corporate Art Advisory', tagline: 'CORPORATE ART ADVISORY',
      heroTitle: 'Corporate art collections curated with the same rigor as a museum.',
      heroDescription: 'Acquisition, curation, and installation for corporate collections — lobby, executive floor, and rotating exhibitions.',
      heroCta: 'Discuss your collection',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Portfolio', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Collection Acquisition', description: 'Works sourced and vetted by advisors with real curatorial backgrounds.' },
        { title: 'Curatorial Planning', description: 'A collection that tells a coherent story, not a random assortment.' },
        { title: 'Installation & Rotation', description: 'Professional installation and a rotation program that keeps the space alive.' },
      ],
      stats: [{ value: 6, label: 'Active Collections' }, { value: 340, label: 'Works Under Management' }, { value: '12M', label: 'Collection Value' }],
      testimonials: [
        { quote: 'Our lobby collection is now the first thing clients mention when they visit.', name: 'Corporate Client', role: 'Client', rating: 5 },
        { quote: 'They understood our brand better than most of our own marketing team.', name: 'Corporate Client', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Building a corporate collection?', ctaDescription: 'Discuss your space and budget with our advisory team.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Acquisition', href: '#' }, { label: 'Curation', href: '#' }] }, { title: 'Firm', links: [{ label: 'Portfolio', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Diving Expedition Company — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-sky-dark',
    spec: {
      description: 'Marketing site for a private diving and marine expedition company.',
      brand: 'Meridian Marine Expeditions', tagline: 'PRIVATE DIVE EXPEDITIONS',
      heroTitle: 'Dive expeditions planned by people who have actually done the dive.',
      heroDescription: 'Small-group expeditions to the world’s best dive sites, led by dive masters who know the waters personally.',
      heroCta: 'View upcoming expeditions',
      navLinks: [{ label: 'Expeditions', href: '#' }, { label: 'Dive Masters', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Small-Group Expeditions', description: 'Capped group sizes so every diver gets real attention underwater.' },
        { title: 'Expert Dive Masters', description: 'Guides who have logged thousands of dives at every site we visit.' },
        { title: 'Full Logistics', description: 'Gear, permits, and transport handled so you just show up and dive.' },
      ],
      stats: [{ value: 6, label: 'Active Expeditions' }, { value: 42, label: 'Divers Booked' }, { value: 58, suffix: '%', label: 'Repeat Diver Rate' }],
      testimonials: [
        { quote: 'The dive master knew every reef by name — it showed in every briefing.', name: 'Diver', role: 'Client', rating: 5 },
        { quote: 'The most seamless dive trip logistics I have ever experienced.', name: 'Diver', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready for your next dive?', ctaDescription: 'View upcoming expeditions and reserve your spot.',
      footerColumns: [{ title: 'Expeditions', links: [{ label: 'Upcoming Trips', href: '#' }, { label: 'Dive Masters', href: '#' }] }, { title: 'Company', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'High-End Remodeling Firm — Marketing Site', category: 'Website-Creative', paletteId: 'brutalist-light',
    spec: {
      description: 'Marketing site for a high-end kitchen and bath remodeling firm.',
      brand: 'Aldergate Remodeling', tagline: 'KITCHEN & BATH REMODELING',
      heroTitle: 'Kitchens and baths rebuilt without the six-month horror story.',
      heroDescription: 'Full kitchen and bath remodels managed by one project manager, from design through final walkthrough.',
      heroCta: 'Start a project',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Design-Build', description: 'One team from design through construction, no handoff gaps.' },
        { title: 'Single Point of Contact', description: 'One project manager who actually answers the phone.' },
        { title: 'Real Timelines', description: 'A schedule we actually hit, not a best-case estimate.' },
      ],
      stats: [{ value: 12, label: 'Active Projects' }, { value: 86, suffix: '%', label: 'On-Budget Rate' }, { value: 22, label: 'Subcontractors Active' }],
      testimonials: [
        { quote: 'The only contractor who actually finished on the date they promised.', name: 'Homeowner', role: 'Client', rating: 5 },
        { quote: 'Zero surprises on the invoice, which never happens in a remodel.', name: 'Homeowner', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready to actually finish your remodel?', ctaDescription: 'Tell us about the project — we take on a limited number per quarter.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Kitchens', href: '#' }, { label: 'Baths', href: '#' }] }, { title: 'Firm', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Cigar & Spirits Lounge — Marketing Site', category: 'Website-Food', paletteId: 'supper-club-dark',
    spec: {
      description: 'Marketing and membership site for a private cigar and spirits lounge.',
      brand: 'Ashcombe Lounge', tagline: 'PRIVATE MEMBERS’ LOUNGE',
      heroTitle: 'A members’ lounge run like the club it actually is.',
      heroDescription: 'A private humidor, a curated spirits list, and a room that knows your name — membership by application.',
      heroCta: 'Apply for membership',
      navLinks: [{ label: 'Membership', href: '#' }, { label: 'Humidor', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Private Humidor', description: 'Climate-controlled personal lockers for members’ own collections.' },
        { title: 'Curated Spirits', description: 'A whiskey and cognac list built by people who actually collect it.' },
        { title: 'Members-Only Events', description: 'Tastings and pairings held exclusively for the membership.' },
      ],
      stats: [{ value: 210, label: 'Active Members' }, { value: 88, suffix: '%', label: 'Locker Occupancy' }, { value: 91, suffix: '%', label: 'Member Retention' }],
      testimonials: [
        { quote: 'The staff remembers my usual pour before I sit down.', name: 'Member', role: 'Client', rating: 5 },
        { quote: 'The most comfortable room in the city to close a real conversation.', name: 'Member', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Membership is by application.', ctaDescription: 'Apply for membership — current wait is approximately 6 weeks.',
      footerColumns: [{ title: 'Membership', links: [{ label: 'Apply', href: '#' }, { label: 'Tiers', href: '#' }] }, { title: 'Lounge', links: [{ label: 'Humidor', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Museum Collection — Marketing Site', category: 'Website-Creative', paletteId: 'paper-oxblood-light',
    spec: {
      description: 'Marketing site for a private museum-quality estate collection.',
      brand: 'Aldergate Estate Collection', tagline: 'PRIVATE COLLECTION',
      heroTitle: 'A private collection catalogued to museum standard.',
      heroDescription: 'A curated collection of 18th and 19th century fine and decorative arts, available for scholarly loan and private viewing.',
      heroCta: 'Request a viewing',
      navLinks: [{ label: 'Collection', href: '#' }, { label: 'Loans', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Museum-Standard Cataloging', description: 'Every object documented with full provenance and condition history.' },
        { title: 'Scholarly Loans', description: 'Works available for loan to qualifying institutions and exhibitions.' },
        { title: 'Private Viewings', description: 'By-appointment viewings for scholars, collectors, and institutions.' },
      ],
      stats: [{ value: 420, label: 'Cataloged Objects' }, { value: '18M', label: 'Collection Value' }, { value: 6, label: 'Objects on Loan' }],
      testimonials: [
        { quote: 'The documentation on every piece was more thorough than our own museum’s archive.', name: 'Museum Curator', role: 'Institutional Partner', rating: 5 },
        { quote: 'A rare private collection actually maintained to institutional standard.', name: 'Scholar', role: 'Researcher', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Researching or curating an exhibition?', ctaDescription: 'Request a private viewing or discuss a loan.',
      footerColumns: [{ title: 'Collection', links: [{ label: 'Objects', href: '#' }, { label: 'Loans', href: '#' }] }, { title: 'Estate', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Boutique Watch Dealer — Marketing Site', category: 'Website-Creative', paletteId: 'gallery-red-light',
    spec: {
      description: 'Marketing site for a boutique watch and timepiece dealer.',
      brand: 'Aldercroft Timepieces', tagline: 'AUTHENTICATED FINE TIMEPIECES',
      heroTitle: 'Watches sourced, authenticated, and sold with real paperwork.',
      heroDescription: 'Vintage and limited-edition timepieces, every piece verified by our in-house authentication team before it is listed.',
      heroCta: 'View the collection',
      navLinks: [{ label: 'Collection', href: '#' }, { label: 'Authentication', href: '#' }, { label: 'Sell a Watch', href: '#' }],
      features: [
        { title: 'In-House Authentication', description: 'Every movement inspected before a piece is ever listed for sale.' },
        { title: 'Verified Provenance', description: 'Documentation and papers cross-checked, not just taken on faith.' },
        { title: 'Consignment Program', description: 'Sell through a dealer who authenticates before they list, not after.' },
      ],
      stats: [{ value: 68, label: 'Pieces in Inventory' }, { value: '3.4M', label: 'Inventory Value' }, { value: 34, label: 'Avg. Days to Sale' }],
      testimonials: [
        { quote: 'The authentication process alone was worth buying through them.', name: 'Collector', role: 'Client', rating: 5 },
        { quote: 'They caught an inconsistency in the papers that another dealer had missed.', name: 'Collector', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Buying or selling a fine timepiece?', ctaDescription: 'View the current collection or inquire about consignment.',
      footerColumns: [{ title: 'Collection', links: [{ label: 'Current Inventory', href: '#' }, { label: 'Consignment', href: '#' }] }, { title: 'Dealer', links: [{ label: 'Authentication', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Golf Club — Marketing Site', category: 'Website-RealEstate', paletteId: 'forest-market-light',
    spec: {
      description: 'Marketing and membership site for a private golf club.',
      brand: 'Birchwood Golf Club', tagline: 'PRIVATE GOLF CLUB',
      heroTitle: 'A course, and a club, worth actually joining.',
      heroDescription: 'A championship course, a members’ dining program, and a waitlist that moves — membership by referral.',
      heroCta: 'Request membership info',
      navLinks: [{ label: 'Course', href: '#' }, { label: 'Membership', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Championship Course', description: 'A course maintained to tournament standard, every day of the season.' },
        { title: 'Members’ Dining', description: 'A dining program run by a real culinary team, not a snack bar.' },
        { title: 'Member Events', description: 'Tournaments and social events built around an active membership.' },
      ],
      stats: [{ value: 340, label: 'Active Members' }, { value: 76, suffix: '%', label: 'Course Utilization' }, { value: 92, suffix: '%', label: 'Member Retention' }],
      testimonials: [
        { quote: 'The course conditions here rival clubs twice the initiation fee.', name: 'Member', role: 'Client', rating: 5 },
        { quote: 'The membership actually feels like a community, not just a tee sheet.', name: 'Member', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Membership is by referral.', ctaDescription: 'Request information and we will connect you with a sponsoring member.',
      footerColumns: [{ title: 'Club', links: [{ label: 'Course', href: '#' }, { label: 'Membership', href: '#' }] }, { title: 'Info', links: [{ label: 'Events', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Corporate Flight Department — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-ember-dark',
    spec: {
      description: 'Marketing site for an in-house corporate flight department (recruiting / vendor-facing).',
      brand: 'Halden Industries Flight Department', tagline: 'CORPORATE FLIGHT OPERATIONS',
      heroTitle: 'A corporate flight department run to airline-grade standards.',
      heroDescription: 'Our in-house flight operations team — safety record, crew standards, and the fleet we operate.',
      heroCta: 'Contact flight operations',
      navLinks: [{ label: 'Fleet', href: '#' }, { label: 'Safety', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Dispatch Reliability', description: '99% dispatch reliability across the fleet, audited annually.' },
        { title: 'Crew Standards', description: 'Duty and rest compliance tracked to the same standard as commercial carriers.' },
        { title: 'Safety Management System', description: 'A formal SMS program reviewed quarterly by an independent auditor.' },
      ],
      stats: [{ value: 24, label: 'Flights (MTD)' }, { value: 99, suffix: '%', label: 'Dispatch Reliability' }, { value: 100, suffix: '%', label: 'Crew Duty Compliance' }],
      testimonials: [
        { quote: 'The most disciplined flight department I have worked with in twenty years.', name: 'Contract Pilot', role: 'Crew', rating: 5 },
        { quote: 'Safety culture here is not a poster on the wall, it is how they actually operate.', name: 'Contract Pilot', role: 'Crew', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Vendor or crew inquiry?', ctaDescription: 'Contact our flight operations team directly.',
      footerColumns: [{ title: 'Operations', links: [{ label: 'Fleet', href: '#' }, { label: 'Safety', href: '#' }] }, { title: 'Department', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
]

export const websiteBatch5 = specs
