const specs = [
  {
    name: 'Boutique Law Firm — Marketing Site', category: 'Website-Legal', paletteId: 'counsel-navy-light',
    spec: {
      description: 'Marketing site for a boutique law firm — practice areas, credibility signals, consultation CTA.',
      brand: 'Harrow & Voss', tagline: 'BOUTIQUE PRACTICE',
      heroTitle: 'Counsel that reads the fine print before you have to.',
      heroDescription: 'Corporate formation, estate planning, and litigation for clients who expect a partner to actually answer the phone.',
      heroCta: 'Book a consultation',
      navLinks: [{ label: 'Practice Areas', href: '#' }, { label: 'Attorneys', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Corporate Formation', description: 'Entity structuring, financing rounds, and governance built to survive due diligence.' },
        { title: 'Estate Planning', description: 'Trusts, wills, and succession plans drafted for families with real complexity.' },
        { title: 'Civil Litigation', description: 'Representation from filing through trial, handled by the partner you actually meet.' },
      ],
      stats: [{ value: 34, label: 'Active Matters' }, { value: 18, suffix: ' yrs', label: 'In Practice' }, { value: 96, suffix: '%', label: 'Client Satisfaction' }],
      testimonials: [
        { quote: 'They handled our acquisition with more care than firms twice their size.', name: 'Marcus Rivera', role: 'CEO, Vantage Materials', rating: 5 },
        { quote: 'Elena walked us through the estate plan like it was the only matter on her desk.', name: 'Priya Sharma', role: 'Private Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Every matter starts with a conversation.', ctaDescription: 'Book a 30-minute consultation — no obligation, no billable clock running.',
      footerColumns: [{ title: 'Practice Areas', links: [{ label: 'Corporate', href: '#' }, { label: 'Estate Planning', href: '#' }, { label: 'Litigation', href: '#' }] }, { title: 'Firm', links: [{ label: 'Attorneys', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Architecture Studio — Portfolio Site', category: 'Website-Creative', paletteId: 'brutalist-light',
    spec: {
      description: 'Portfolio and inquiry site for an architecture studio.',
      brand: 'Ferro & Lund', tagline: 'ARCHITECTURE STUDIO',
      heroTitle: 'Structures built to outlast the trend that inspired them.',
      heroDescription: 'Residential, commercial, and public projects — from concept sketch through occupancy permit.',
      heroCta: 'Start a project',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Studio', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Residential', description: 'Custom homes and additions designed around how a family actually lives.' },
        { title: 'Commercial', description: 'Office and retail spaces built for the business, not the rendering.' },
        { title: 'Public & Civic', description: 'Community spaces designed to hold up under real daily use.' },
      ],
      stats: [{ value: 18, label: 'Active Projects' }, { value: 12, suffix: ' yrs', label: 'Studio Founded' }, { value: 88, suffix: '%', label: 'On-Budget Rate' }],
      testimonials: [
        { quote: 'They designed for how we actually live, not how a magazine would photograph it.', name: 'Elin Torvald', role: 'Homeowner', rating: 5 },
        { quote: 'The only studio that hit both budget and permit timeline on our first try.', name: 'James O’Brien', role: 'Developer, Alder Street Partners', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a site and a problem to solve?', ctaDescription: 'Tell us about the project — we respond to every serious inquiry within 48 hours.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Residential', href: '#' }, { label: 'Commercial', href: '#' }, { label: 'Civic', href: '#' }] }, { title: 'Studio', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Wealth Advisory — Marketing Site', category: 'Website-Finance', paletteId: 'ledger-ivory-light',
    spec: {
      description: 'Marketing site for a private wealth advisory firm.',
      brand: 'Meridian Capital Partners', tagline: 'DISCRETIONARY WEALTH MANAGEMENT',
      heroTitle: 'Wealth managed the way it should have been from the start.',
      heroDescription: 'Discretionary portfolio management, tax-aware planning, and a fiduciary standard for families who have outgrown a generalist advisor.',
      heroCta: 'Schedule a conversation',
      navLinks: [{ label: 'Approach', href: '#' }, { label: 'Team', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Discretionary Management', description: 'Portfolios built to your risk profile, rebalanced without waiting for your sign-off.' },
        { title: 'Tax-Aware Planning', description: 'Loss harvesting and asset location that actually shows up on the return.' },
        { title: 'Multi-Generational Planning', description: 'Trust and estate coordination built for the next generation, not just this one.' },
      ],
      stats: [{ value: 482, suffix: 'M', label: 'Assets Under Mgmt' }, { value: 156, label: 'Client Families' }, { value: 14, suffix: '%', label: 'Avg. Annual Return' }],
      testimonials: [
        { quote: 'The first advisor who explained the fee structure before we asked.', name: 'David Reyes', role: 'Client since 2019', rating: 5 },
        { quote: 'They rebalanced through the downturn without a single anxious phone call from us.', name: 'Grace Whitfield', role: 'Client since 2015', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'A fiduciary standard, in writing.', ctaDescription: 'Schedule a no-obligation portfolio review with a senior advisor.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Wealth Management', href: '#' }, { label: 'Tax Planning', href: '#' }, { label: 'Estate Planning', href: '#' }] }, { title: 'Firm', links: [{ label: 'Team', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Luxury Real Estate Brokerage — Marketing Site', category: 'Website-RealEstate', paletteId: 'luxury-gold-dark',
    spec: {
      description: 'Marketing site for a luxury real estate brokerage.',
      brand: 'Ashcombe & Vale', tagline: 'PRIVATE REAL ESTATE',
      heroTitle: 'The properties that never touch the open market.',
      heroDescription: 'Discreet representation for buyers and sellers of exceptional homes — off-market access, not a listing feed.',
      heroCta: 'Request private access',
      navLinks: [{ label: 'Listings', href: '#' }, { label: 'Sell', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Off-Market Access', description: 'A private network of listings that never reach a public search.' },
        { title: 'Discreet Representation', description: 'Every transaction handled with the confidentiality our clients expect.' },
        { title: 'Global Reach', description: 'A referral network spanning the markets our clients actually buy in.' },
      ],
      stats: [{ value: 27, label: 'Active Listings' }, { value: 340, suffix: 'M', label: 'Portfolio Value' }, { value: 41, label: 'Avg. Days on Market' }],
      testimonials: [
        { quote: 'They found us a property that was never publicly listed, and closed in three weeks.', name: 'Rupert Ashcombe', role: 'Private Buyer', rating: 5 },
        { quote: 'Discretion was non-negotiable for us. They delivered it without being asked twice.', name: 'Noelle Devereux', role: 'Seller', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Discretion, by design.', ctaDescription: 'Request private access to our current off-market portfolio.',
      footerColumns: [{ title: 'Properties', links: [{ label: 'Buy', href: '#' }, { label: 'Sell', href: '#' }] }, { title: 'Firm', links: [{ label: 'Agents', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Med Spa & Aesthetics Clinic — Marketing Site', category: 'Website-Healthcare', paletteId: 'wellness-sage-light',
    spec: {
      description: 'Marketing site for a medical aesthetics clinic.',
      brand: 'Willowmere Aesthetics', tagline: 'MEDICAL AESTHETICS',
      heroTitle: 'Aesthetic medicine, practiced like medicine.',
      heroDescription: 'Physician-led injectables, laser treatments, and skin health — no upselling, no rushed consultations.',
      heroCta: 'Book a consultation',
      navLinks: [{ label: 'Treatments', href: '#' }, { label: 'Providers', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Injectables', description: 'Neuromodulators and fillers administered by board-certified physicians only.' },
        { title: 'Laser & Skin Health', description: 'Resurfacing and rejuvenation treatments backed by real clinical evidence.' },
        { title: 'Personalized Plans', description: 'A treatment plan built around your skin, not a package menu.' },
      ],
      stats: [{ value: 412, label: 'Active Patients' }, { value: 98, suffix: '%', label: 'Patient Satisfaction' }, { value: 11, suffix: ' yrs', label: 'In Practice' }],
      testimonials: [
        { quote: 'The consultation felt like a medical appointment, not a sales pitch.', name: 'Marguerite Boone', role: 'Patient', rating: 5 },
        { quote: 'Subtle results, exactly what I asked for the first time.', name: 'Dana Kessler', role: 'Patient', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Start with a real consultation.', ctaDescription: 'Book a private consultation with one of our physicians.',
      footerColumns: [{ title: 'Treatments', links: [{ label: 'Injectables', href: '#' }, { label: 'Laser', href: '#' }, { label: 'Skin Health', href: '#' }] }, { title: 'Clinic', links: [{ label: 'Providers', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Boutique Hotel Group — Marketing Site', category: 'Website-Food', paletteId: 'crema-fraunces-light',
    spec: {
      description: 'Marketing site for a small boutique hotel group.',
      brand: 'Larkspur & Stone', tagline: 'BOUTIQUE HOSPITALITY',
      heroTitle: 'Three properties, one standard: remembered, not just booked.',
      heroDescription: 'Coastal suites, garden rooms, and vineyard views — every stay considered before the guest arrives.',
      heroCta: 'Check availability',
      navLinks: [{ label: 'Properties', href: '#' }, { label: 'Experiences', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Larkspur House', description: 'Coastal suites with private terraces overlooking the bay.' },
        { title: 'The Stonecroft', description: 'A restored manor house with garden and loft rooms.' },
        { title: 'Millbrook Inn', description: 'Full-property buyouts for reunions and private events.' },
      ],
      stats: [{ value: 91, suffix: '%', label: 'Occupancy Rate' }, { value: 47, suffix: '%', label: 'Repeat Guest Rate' }, { value: 3, label: 'Properties' }],
      testimonials: [
        { quote: 'They remembered our anniversary from three years ago without being asked.', name: 'Elena Beaumont', role: 'Guest', rating: 5 },
        { quote: 'The kind of stay you plan your whole trip around.', name: 'Andres Ibarra', role: 'Guest', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Every stay, considered.', ctaDescription: 'Check availability across all three properties.',
      footerColumns: [{ title: 'Properties', links: [{ label: 'Larkspur House', href: '#' }, { label: 'The Stonecroft', href: '#' }, { label: 'Millbrook Inn', href: '#' }] }, { title: 'Guest Info', links: [{ label: 'Experiences', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Creative & Branding Agency — Portfolio Site', category: 'Website-Creative', paletteId: 'creative-violet-dark',
    spec: {
      description: 'Portfolio and pitch site for a branding agency.',
      brand: 'Nocturne & Bloom', tagline: 'BRAND & IDENTITY',
      heroTitle: 'Brand systems for companies that refuse to look like everyone else.',
      heroDescription: 'Identity, packaging, and campaign work for founders who already know what generic looks like.',
      heroCta: 'Start a project',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Studio', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Identity Systems', description: 'Full visual identity, built to hold up across every touchpoint.' },
        { title: 'Packaging', description: 'Packaging design that earns the shelf space it takes up.' },
        { title: 'Campaign Creative', description: 'Concepts built to survive contact with a real media budget.' },
      ],
      stats: [{ value: 14, label: 'Active Engagements' }, { value: 92, suffix: '%', label: 'On-Brief Approval' }, { value: 9, suffix: ' yrs', label: 'Studio Founded' }],
      testimonials: [
        { quote: 'They pushed back on our first brief and were right to.', name: 'Liv Bergström', role: 'Founder, Solace Skincare', rating: 5 },
        { quote: 'The rebrand doubled our retail conversion inside two months.', name: 'Dara Okonkwo', role: 'CEO, Ferrous Coffee', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a brand that needs a point of view?', ctaDescription: 'Tell us about the project — we take on a limited number of engagements per quarter.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Identity', href: '#' }, { label: 'Packaging', href: '#' }, { label: 'Campaigns', href: '#' }] }, { title: 'Studio', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Fine Dining Restaurant — Marketing Site', category: 'Website-Food', paletteId: 'supper-club-dark',
    spec: {
      description: 'Marketing and reservation site for a fine dining restaurant.',
      brand: 'Marrow & Ash', tagline: 'FINE DINING',
      heroTitle: 'A tasting menu built around what the market actually had this morning.',
      heroDescription: 'Seasonal, ingredient-led fine dining — one seating a night, reservations open six weeks out.',
      heroCta: 'Reserve a table',
      navLinks: [{ label: 'Menu', href: '#' }, { label: 'Chef', href: '#' }, { label: 'Reservations', href: '#' }],
      features: [
        { title: 'Tasting Menu', description: 'A nine-course menu that changes weekly with what the market delivers.' },
        { title: 'Wine Pairing', description: 'A cellar-driven pairing program curated by our in-house sommelier.' },
        { title: "Chef's Table", description: 'Six seats at the pass, for guests who want to watch the whole service.' },
      ],
      stats: [{ value: 5, label: 'Years Open' }, { value: 4.9, label: 'Avg. Rating' }, { value: 340, label: 'Covers per Week' }],
      testimonials: [
        { quote: 'The best tasting menu in the city, and I say that having tried most of them.', name: 'Kofi Mensah', role: 'Guest', rating: 5 },
        { quote: 'Book six weeks out. It is worth every day of the wait.', name: 'Ines Duarte', role: 'Guest', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'One seating a night.', ctaDescription: 'Reservations open six weeks in advance — book before the calendar fills.',
      footerColumns: [{ title: 'Dining', links: [{ label: 'Menu', href: '#' }, { label: 'Wine List', href: '#' }] }, { title: 'Info', links: [{ label: 'Chef', href: '#' }, { label: 'Reservations', href: '#' }] }],
    },
  },
  {
    name: 'Wedding & Event Planning — Marketing Site', category: 'Website-Events', paletteId: 'gallery-red-light',
    spec: {
      description: 'Marketing and inquiry site for a wedding and event planning company.',
      brand: 'Bellcourt Events', tagline: 'WEDDING & EVENT DESIGN',
      heroTitle: 'The day you have been picturing, run by someone who has actually run one.',
      heroDescription: 'Full-service wedding and event design — from the first venue tour to the last dance.',
      heroCta: 'Inquire about your date',
      navLinks: [{ label: 'Weddings', href: '#' }, { label: 'Events', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Full Planning', description: 'Every vendor, every timeline detail, handled from booking to breakdown.' },
        { title: 'Design & Styling', description: 'A design concept built around you, not a pre-set aesthetic package.' },
        { title: 'Day-Of Coordination', description: 'For the couple who has planned everything and just needs someone else running it.' },
      ],
      stats: [{ value: 84, label: 'Events per Year' }, { value: 98, suffix: '%', label: 'Client Satisfaction' }, { value: 12, suffix: ' yrs', label: 'In Business' }],
      testimonials: [
        { quote: 'She handled a venue cancellation four days out and we never even found out until after.', name: 'Corinne Voss', role: 'Bride', rating: 5 },
        { quote: 'The only planner our families actually agreed on.', name: 'Julian Marsh', role: 'Groom', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Dates book up to 18 months out.', ctaDescription: 'Tell us about your date — we respond within 48 hours.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Full Planning', href: '#' }, { label: 'Day-Of', href: '#' }] }, { title: 'Company', links: [{ label: 'Portfolio', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Yoga & Wellness Studio — Marketing Site', category: 'Website-Healthcare', paletteId: 'wellness-teal-dark',
    spec: {
      description: 'Marketing and membership site for a private yoga and wellness studio.',
      brand: 'Fernbrook Studio', tagline: 'PRIVATE PRACTICE',
      heroTitle: 'A practice, not a class schedule.',
      heroDescription: 'Small-group and private yoga, breathwork, and recovery sessions — capped at eight per room.',
      heroCta: 'Book your first session',
      navLinks: [{ label: 'Classes', href: '#' }, { label: 'Teachers', href: '#' }, { label: 'Membership', href: '#' }],
      features: [
        { title: 'Small-Group Practice', description: 'Capped at eight students so every teacher can actually see you.' },
        { title: 'Private Sessions', description: 'One-on-one sessions built around an injury, a goal, or just a busy week.' },
        { title: 'Breathwork & Recovery', description: 'Guided breathwork and recovery sessions for the days you cannot make it to the mat.' },
      ],
      stats: [{ value: 8, label: 'Max Class Size' }, { value: 91, suffix: '%', label: 'Member Retention' }, { value: 6, suffix: ' yrs', label: 'Studio Open' }],
      testimonials: [
        { quote: 'The first studio where the teacher actually knew my name by week two.', name: 'Naomi Sato', role: 'Member', rating: 5 },
        { quote: 'Small enough that it never feels like just another class.', name: 'Owen Fairbanks', role: 'Member', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Your first session is on us.', ctaDescription: 'Book a complimentary first class — no membership required.',
      footerColumns: [{ title: 'Practice', links: [{ label: 'Classes', href: '#' }, { label: 'Private Sessions', href: '#' }] }, { title: 'Studio', links: [{ label: 'Teachers', href: '#' }, { label: 'Membership', href: '#' }] }],
    },
  },
]

export const websiteBatch1 = specs
