const specs = [
  {
    name: 'Boutique Chocolate House — Marketing Site', category: 'Website-Food', paletteId: 'food-amber-light',
    spec: {
      description: 'Marketing and wholesale inquiry site for a boutique chocolate house.',
      brand: 'Ferrous & Cacao Confectionery', tagline: 'HANDCRAFTED CHOCOLATE',
      heroTitle: 'Chocolate made in small batches, not mass-tempered.',
      heroDescription: 'Single-origin bean-to-bar chocolate, custom corporate gifts, and wedding favors, tempered by hand.',
      heroCta: 'Shop the collection',
      navLinks: [{ label: 'Shop', href: '#' }, { label: 'Corporate Gifts', href: '#' }, { label: 'Wholesale', href: '#' }],
      features: [
        { title: 'Bean-to-Bar', description: 'Single-origin cacao, roasted and tempered entirely in-house.' },
        { title: 'Custom Corporate Gifts', description: 'Branded chocolate gifts that actually get eaten, not regifted.' },
        { title: 'Wholesale Program', description: 'Restaurant and retail accounts supplied with real batch consistency.' },
      ],
      stats: [{ value: 24, label: 'Active Orders' }, { value: 18, label: 'Wholesale Accounts' }, { value: 640, label: 'Avg. Order Value' }],
      testimonials: [
        { quote: 'Our clients still mention the holiday gift box a year later.', name: 'Corporate Client', role: 'Client', rating: 5 },
        { quote: 'The best chocolate I have found outside of Europe.', name: 'Retail Customer', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Planning a corporate gift order?', ctaDescription: 'Talk to us about custom molds and bulk pricing.',
      footerColumns: [{ title: 'Shop', links: [{ label: 'Collection', href: '#' }, { label: 'Corporate Gifts', href: '#' }] }, { title: 'Company', links: [{ label: 'Wholesale', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Genealogy Research Firm — Marketing Site', category: 'Website-Legal', paletteId: 'paper-oxblood-light',
    spec: {
      description: 'Marketing site for a private genealogy and family history research firm.',
      brand: 'Aldergate Genealogy Research', tagline: 'FAMILY HISTORY RESEARCH',
      heroTitle: 'Family history researched with the rigor of a legal case, not a hobby.',
      heroDescription: 'Professional lineage research, immigration records, and estate documentation — archival-grade, fully cited.',
      heroCta: 'Start a research project',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Lineage Research', description: 'Multi-generational family trees built on verified primary sources.' },
        { title: 'Immigration Records', description: 'Ship manifests, naturalization papers, and border records, tracked down and verified.' },
        { title: 'Estate Documentation', description: 'Heir research built to hold up in a probate court, not just a family reunion.' },
      ],
      stats: [{ value: 11, label: 'Active Projects' }, { value: 340, label: 'Records Verified (MTD)' }, { value: 96, suffix: '%', label: 'Client Satisfaction' }],
      testimonials: [
        { quote: 'They found records our own family had been searching for over twenty years.', name: 'Client', role: 'Client', rating: 5 },
        { quote: 'Every claim in the report was cited and verifiable.', name: 'Estate Attorney', role: 'Referral Partner', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a family history worth documenting?', ctaDescription: 'Start with a free scoping consultation.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Lineage Research', href: '#' }, { label: 'Estate Documentation', href: '#' }] }, { title: 'Firm', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Home Theater & Screening Room Design — Marketing Site', category: 'Website-Creative', paletteId: 'midnight-press-dark',
    spec: {
      description: 'Marketing site for a high-end home theater and screening room design firm.',
      brand: 'Blackwood Screening Room Design', tagline: 'PRIVATE SCREENING ROOMS',
      heroTitle: 'Screening rooms calibrated the way a real theater is calibrated.',
      heroDescription: 'Acoustic design, projection calibration, and full theater builds for clients who can hear the difference.',
      heroCta: 'Start a project',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Acoustic Design', description: 'Room treatment engineered around your space, not a generic kit.' },
        { title: 'Projection Calibration', description: 'Color and contrast calibrated to reference standard, not eyeballed.' },
        { title: 'Full Theater Builds', description: 'From empty room to premiere-ready, managed by one design team.' },
      ],
      stats: [{ value: 8, label: 'Active Projects' }, { value: 90, suffix: '%', label: 'On-Time Completion' }, { value: 14, label: 'Calibration Sessions (MTD)' }],
      testimonials: [
        { quote: 'It sounds and looks better than most commercial theaters I have been in.', name: 'Homeowner', role: 'Client', rating: 5 },
        { quote: 'The calibration alone was worth the investment.', name: 'Homeowner', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Building a room worth the investment?', ctaDescription: 'Tell us about the space — we take on a limited number of builds per year.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Theater Rooms', href: '#' }, { label: 'Media Rooms', href: '#' }] }, { title: 'Firm', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Raptor Rescue & Education Sanctuary — Marketing Site', category: 'Website-NonProfit', paletteId: 'moss-archive-light',
    spec: {
      description: 'Marketing and membership site for a raptor rescue and education sanctuary.',
      brand: 'Fernbrook Raptor Sanctuary', tagline: 'RAPTOR RESCUE & EDUCATION',
      heroTitle: 'A sanctuary funded by members who actually visit.',
      heroDescription: 'Rehabilitating injured raptors and teaching the next generation why they matter — membership funds every release.',
      heroCta: 'Become a member',
      navLinks: [{ label: 'Visit', href: '#' }, { label: 'Education', href: '#' }, { label: 'Membership', href: '#' }],
      features: [
        { title: 'Rehabilitation Program', description: 'Injured raptors rehabilitated and released back to the wild.' },
        { title: 'Education Program', description: 'School visits that put a real hawk in front of a real classroom.' },
        { title: 'Member Visits', description: 'Unlimited visits, behind-the-scenes access, and release-day invitations.' },
      ],
      stats: [{ value: 420, label: 'Active Members' }, { value: 34, label: 'Birds in Care' }, { value: 62, label: 'Rehabilitations (YTD)' }],
      testimonials: [
        { quote: 'Watching a release with my kids is the best membership I have ever had.', name: 'Member', role: 'Family Member', rating: 5 },
        { quote: 'The education program changed how my students see wildlife.', name: 'Teacher', role: 'Educator Member', rating: 5 },
      ],
      pricing: [
        { name: 'Individual', price: '$45', period: '/year', description: 'Unlimited visits for one', features: ['Unlimited visits', 'Member newsletter'], cta: 'Join' },
        { name: 'Family', price: '$75', period: '/year', description: 'Unlimited visits for your household', features: ['Unlimited visits', 'Release-day invites', 'Up to 5 members'], featured: true, cta: 'Join' },
        { name: 'Sponsor', price: '$250', period: '/year', description: 'Sponsor a bird in care', features: ['All family benefits', 'Sponsor a specific bird', 'Behind-the-scenes tour'], cta: 'Join' },
      ],
      ctaTitle: 'Every membership funds a release.', ctaDescription: 'Become a member and support the rehabilitation program directly.',
      footerColumns: [{ title: 'Visit', links: [{ label: 'Hours', href: '#' }, { label: 'Education', href: '#' }] }, { title: 'Support', links: [{ label: 'Membership', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Cellar & Wine Storage — Marketing Site', category: 'Website-Food', paletteId: 'supper-club-dark',
    spec: {
      description: 'Marketing site for a private wine cellar and storage facility.',
      brand: 'Meridian Private Cellars', tagline: 'PRIVATE WINE STORAGE',
      heroTitle: 'Wine storage run to the standard a real collection deserves.',
      heroDescription: 'Climate-controlled private cellar storage with full cataloging, insurance support, and white-glove pull-and-ship.',
      heroCta: 'Reserve a cellar space',
      navLinks: [{ label: 'Storage', href: '#' }, { label: 'Cataloging', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Climate-Controlled Storage', description: 'Temperature and humidity monitored and logged around the clock.' },
        { title: 'Full Cataloging', description: 'Every bottle documented, searchable, and ready for insurance appraisal.' },
        { title: 'Pull & Ship', description: 'White-glove delivery for the bottle you want, whenever you want it.' },
      ],
      stats: [{ value: 84, label: 'Active Collectors' }, { value: 12400, label: 'Bottles Stored' }, { value: 84, suffix: '%', label: 'Cellar Occupancy' }],
      testimonials: [
        { quote: 'My collection has never been better documented or better protected.', name: 'Collector', role: 'Client', rating: 5 },
        { quote: 'The pull-and-ship service means I never have to think about logistics.', name: 'Collector', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Outgrown your home cellar?', ctaDescription: 'Reserve a private storage space with full cataloging included.',
      footerColumns: [{ title: 'Storage', links: [{ label: 'Cellar Space', href: '#' }, { label: 'Cataloging', href: '#' }] }, { title: 'Company', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Executive Home Staging Firm — Marketing Site', category: 'Website-RealEstate', paletteId: 'gallery-red-light',
    spec: {
      description: 'Marketing site for an executive home staging firm.',
      brand: 'Marchetti Home Staging', tagline: 'PROFESSIONAL HOME STAGING',
      heroTitle: 'Homes staged to sell, not just to photograph well.',
      heroDescription: 'Full-service staging for listings that need to move — a curated inventory, not rental furniture off a truck.',
      heroCta: 'Request a consultation',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Portfolio', href: '#' }, { label: 'For Realtors', href: '#' }],
      features: [
        { title: 'Full Home Staging', description: 'Every room staged with furniture curated for the property, not generic.' },
        { title: 'Vacant Home Staging', description: 'Empty listings transformed into homes buyers can picture living in.' },
        { title: 'Realtor Partnership Program', description: 'Priority scheduling and preferred rates for our realtor partners.' },
      ],
      stats: [{ value: 16, label: 'Active Projects' }, { value: 34, suffix: '%', label: 'Avg. DOM Reduction' }, { value: 22, label: 'Realtor Partners' }],
      testimonials: [
        { quote: 'The staged listing sold in four days, at asking price.', name: 'Realtor', role: 'Partner', rating: 5 },
        { quote: 'Buyers could not stop talking about how the home felt, not just looked.', name: 'Seller', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Listing a property soon?', ctaDescription: 'Request a staging consultation before your listing photos.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Full Staging', href: '#' }, { label: 'Vacant Staging', href: '#' }] }, { title: 'Partners', links: [{ label: 'For Realtors', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Aerial Infrastructure Inspection Firm — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-acid-dark',
    spec: {
      description: 'Marketing site for a drone-based infrastructure inspection company.',
      brand: 'Blackridge Aerial Inspections', tagline: 'AERIAL INFRASTRUCTURE INSPECTION',
      heroTitle: 'Infrastructure inspected from the air, documented like it matters.',
      heroDescription: 'FAA-certified drone inspection for cell towers, wind turbines, solar farms, and bridges — full reports, not just footage.',
      heroCta: 'Request an inspection',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Certifications', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Cell Tower Inspection', description: 'Detailed structural surveys without the fall-protection risk of a climb.' },
        { title: 'Wind Turbine Inspection', description: 'Blade and nacelle inspection that catches damage before it grounds the turbine.' },
        { title: 'Full Reporting', description: 'A real defect report with imagery and severity ratings, not a raw footage dump.' },
      ],
      stats: [{ value: 12, label: 'Active Contracts' }, { value: 34, label: 'Inspections (MTD)' }, { value: '2 days', label: 'Avg. Report Turnaround' }],
      testimonials: [
        { quote: 'They found a crack our ground inspection had missed for two years.', name: 'Utility Client', role: 'Client', rating: 5 },
        { quote: 'The report quality alone justified switching from our previous vendor.', name: 'Infrastructure Manager', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Need an asset inspected safely?', ctaDescription: 'Request a quote for your next inspection.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Cell Towers', href: '#' }, { label: 'Wind Turbines', href: '#' }] }, { title: 'Company', links: [{ label: 'Certifications', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Specialty Cheese Affinage House — Marketing Site', category: 'Website-Food', paletteId: 'food-amber-light',
    spec: {
      description: 'Marketing site for a specialty cheese affinage and import house.',
      brand: 'Aldergate Cheese Cellars', tagline: 'CHEESE AFFINAGE & IMPORT',
      heroTitle: 'Cheese aged in-house, not just imported and resold.',
      heroDescription: 'Imported wheels aged to peak in our own caves, supplied to restaurants and specialty retailers who care about the difference.',
      heroCta: 'Inquire about wholesale',
      navLinks: [{ label: 'Program', href: '#' }, { label: 'Caves', href: '#' }, { label: 'Wholesale', href: '#' }],
      features: [
        { title: 'In-House Affinage', description: 'Wheels aged in our own caves, not shipped pre-aged from overseas.' },
        { title: 'Restaurant Program', description: 'Standing weekly orders built around your actual menu.' },
        { title: 'Specialty Retail Supply', description: 'Curated selections for retailers who want a real cheese program.' },
      ],
      stats: [{ value: 46, label: 'Wholesale Accounts' }, { value: 82, suffix: '%', label: 'Cave Occupancy' }, { value: 340, label: 'Wheels Aging' }],
      testimonials: [
        { quote: 'The best cheese program we have ever put on a menu.', name: 'Restaurant Chef', role: 'Wholesale Client', rating: 5 },
        { quote: 'Consistency is the reason we have stayed with them for six years.', name: 'Retail Buyer', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Building a real cheese program?', ctaDescription: 'Inquire about wholesale accounts and custom aging requests.',
      footerColumns: [{ title: 'Program', links: [{ label: 'Restaurant', href: '#' }, { label: 'Retail', href: '#' }] }, { title: 'Company', links: [{ label: 'Caves', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Boutique Architecture Photography Studio — Marketing Site', category: 'Website-Creative', paletteId: 'gallery-red-light',
    spec: {
      description: 'Marketing site for an architecture and interior photography studio.',
      brand: 'Aldergate Photography Studio', tagline: 'ARCHITECTURAL PHOTOGRAPHY',
      heroTitle: 'Architectural photography that survives the redesign trend cycle.',
      heroDescription: 'Exterior, interior, and commercial space photography for architects and designers who need it to actually sell the work.',
      heroCta: 'Book a shoot',
      navLinks: [{ label: 'Portfolio', href: '#' }, { label: 'Services', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Architecture Exterior', description: 'Golden-hour and blue-hour shoots that show the building at its best.' },
        { title: 'Interior Design', description: 'Interiors shot to show scale and light the way the designer intended.' },
        { title: 'Fast Turnaround', description: 'A 5-day average turnaround, not the two-week industry standard.' },
      ],
      stats: [{ value: 9, label: 'Active Shoots' }, { value: '5 days', label: 'Avg. Turnaround' }, { value: 88, suffix: '%', label: 'Client Retention' }],
      testimonials: [
        { quote: 'These photos are the reason the project got published.', name: 'Architect', role: 'Client', rating: 5 },
        { quote: 'The fastest turnaround I have ever gotten from an architecture photographer.', name: 'Interior Designer', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a project worth photographing well?', ctaDescription: 'Book a shoot — we schedule 2-3 weeks out during peak season.',
      footerColumns: [{ title: 'Portfolio', links: [{ label: 'Architecture', href: '#' }, { label: 'Interiors', href: '#' }] }, { title: 'Studio', links: [{ label: 'Services', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
]

export const websiteBatch6 = specs
