const specs = [
  {
    name: 'Private Wine Importer & Distributor — Marketing Site', category: 'Website-Food', paletteId: 'supper-club-dark',
    spec: {
      description: 'Marketing site for a private wine importer and distributor.',
      brand: 'Meridian Wine Imports', tagline: 'DIRECT-IMPORT WINE',
      heroTitle: 'Wine imported direct from the estate, not bought through a broker chain.',
      heroDescription: 'Burgundy, Bordeaux, and natural wine allocations, imported and distributed directly to restaurant accounts.',
      heroCta: 'Set up an account',
      navLinks: [{ label: 'Portfolio', href: '#' }, { label: 'Restaurants', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Direct Estate Relationships', description: 'Allocations sourced directly from growers, not resold from a broker.' },
        { title: 'Restaurant Accounts', description: 'Standing allocations built around your actual list.' },
        { title: 'Futures Program', description: 'En primeur access most importers can’t offer.' },
      ],
      stats: [{ value: 62, label: 'Restaurant Accounts' }, { value: 340, label: 'Cases in Transit' }, { value: 92, suffix: '%', label: 'On-Time Customs Rate' }],
      testimonials: [
        { quote: 'The allocation quality is a different tier from our previous importer.', name: 'Wine Director', role: 'Client', rating: 5 },
        { quote: 'Direct access to allocations we could never get elsewhere.', name: 'Sommelier', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Building a real wine program?', ctaDescription: 'Set up a restaurant account to access current allocations.',
      footerColumns: [{ title: 'Portfolio', links: [{ label: 'Burgundy', href: '#' }, { label: 'Bordeaux', href: '#' }] }, { title: 'Company', links: [{ label: 'Restaurants', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'High-End Security Installation Firm — Marketing Site', category: 'Website-RealEstate', paletteId: 'mono-dev-dark',
    spec: {
      description: 'Marketing site for a high-end residential security installation firm.',
      brand: 'Blackridge Security', tagline: 'DISCREET RESIDENTIAL SECURITY',
      heroTitle: 'Security installed to protect a home, not just satisfy insurance.',
      heroDescription: 'Access control, perimeter systems, and safe rooms, designed and installed by a team estates actually trust.',
      heroCta: 'Request a site survey',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Discretion', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Access Control Systems', description: 'Full estate access managed from a single, secure platform.' },
        { title: 'Perimeter Security', description: 'Detection systems that don’t compromise the property’s look.' },
        { title: 'Safe Room Installation', description: 'Hardened rooms designed and built into the existing architecture.' },
      ],
      stats: [{ value: 9, label: 'Active Jobs' }, { value: 91, suffix: '%', label: 'On-Time Completion' }, { value: 42, label: 'Service Contracts' }],
      testimonials: [
        { quote: 'Discreet, professional, and it actually works when tested.', name: 'Estate Manager', role: 'Client', rating: 5 },
        { quote: 'The only firm we trust with our clients’ security.', name: 'Family Office', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready for a real security assessment?', ctaDescription: 'Request a confidential site survey.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Access Control', href: '#' }, { label: 'Perimeter Security', href: '#' }] }, { title: 'Firm', links: [{ label: 'Discretion', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Custom Boat Building Yard — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-sky-dark',
    spec: {
      description: 'Marketing site for a custom boat building yard.',
      brand: 'Meridian Boat Works', tagline: 'CUSTOM VESSEL BUILDS',
      heroTitle: 'Hulls built to the client’s spec, not off a mold catalog.',
      heroDescription: 'Custom sportfishers, sailing yachts, and center consoles, built one vessel at a time by a dedicated crew.',
      heroCta: 'Start a build',
      navLinks: [{ label: 'Builds', href: '#' }, { label: 'Yard', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Custom Hull Design', description: 'Naval architecture built around how you actually use the water.' },
        { title: 'Full Fit-Out', description: 'Interior joinery and systems built to your exact specification.' },
        { title: 'Sea Trial Guarantee', description: 'Every build proven on the water before handover.' },
      ],
      stats: [{ value: 4, label: 'Active Builds' }, { value: '9 mo', label: 'Avg. Build Time' }, { value: 6, label: 'Waitlist' }],
      testimonials: [
        { quote: 'The sea trial confirmed everything we designed on paper.', name: 'Owner', role: 'Client', rating: 5 },
        { quote: 'A build process more organized than any yard I have used.', name: 'Captain', role: 'Client Representative', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Planning a custom build?', ctaDescription: 'Slots are limited — inquire early to reserve build capacity.',
      footerColumns: [{ title: 'Builds', links: [{ label: 'Sportfishers', href: '#' }, { label: 'Sailing Yachts', href: '#' }] }, { title: 'Yard', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Antique Rug & Textile Dealer — Marketing Site', category: 'Website-Creative', paletteId: 'paper-oxblood-light',
    spec: {
      description: 'Marketing site for an antique rug and textile dealer.',
      brand: 'Aldergate Rug & Textile', tagline: 'ANTIQUE RUGS & TEXTILES',
      heroTitle: 'Rugs authenticated, restored, and sold with real provenance.',
      heroDescription: 'Persian, Ottoman, and tribal textiles, sourced from estates and restored by hand before they ever go to sale.',
      heroCta: 'Browse the collection',
      navLinks: [{ label: 'Collection', href: '#' }, { label: 'Restoration', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Authenticated Provenance', description: 'Every piece researched and documented before it goes to sale.' },
        { title: 'In-House Restoration', description: 'Reweaving and cleaning done by hand, not outsourced.' },
        { title: 'Appraisal Services', description: 'Insurance-grade appraisals for collectors and estates.' },
      ],
      stats: [{ value: 220, label: 'Pieces in Inventory' }, { value: '1.8M', label: 'Inventory Value' }, { value: 68, label: 'Avg. Days to Sale' }],
      testimonials: [
        { quote: 'The restoration brought a piece we thought was beyond saving back to life.', name: 'Collector', role: 'Client', rating: 5 },
        { quote: 'The provenance research alone justified the purchase.', name: 'Interior Designer', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a textile worth appraising?', ctaDescription: 'We offer confidential appraisals for estates and private collections.',
      footerColumns: [{ title: 'Collection', links: [{ label: 'Browse', href: '#' }, { label: 'New Acquisitions', href: '#' }] }, { title: 'Company', links: [{ label: 'Restoration', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Custom Neon & Signage Studio — Marketing Site', category: 'Website-Creative', paletteId: 'creative-violet-dark',
    spec: {
      description: 'Marketing site for a custom neon and signage fabrication studio.',
      brand: 'Aldercroft Neon Works', tagline: 'HAND-BENT NEON & SIGNAGE',
      heroTitle: 'Signs bent by hand, not printed from a template.',
      heroDescription: 'Custom storefront signage, rooftop installations, and gallery pieces, fabricated and wired entirely in-house.',
      heroCta: 'Start a commission',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Custom Storefront Signs', description: 'Bent and wired to spec, built to survive years of daily use.' },
        { title: 'Gallery & Art Installations', description: 'Neon as a medium, not just signage.' },
        { title: 'Permit-Ready Installs', description: 'We handle the permitting, not just the fabrication.' },
      ],
      stats: [{ value: 9, label: 'Active Commissions' }, { value: 6, label: 'Installs This Month' }, { value: 54, suffix: '%', label: 'Repeat Client Rate' }],
      testimonials: [
        { quote: 'It’s the first thing people mention about our storefront.', name: 'Restaurant Owner', role: 'Client', rating: 5 },
        { quote: 'The craftsmanship is obvious the moment it’s lit.', name: 'Gallery Owner', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a space that needs real neon?', ctaDescription: 'Commissions typically take about five weeks start to finish.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Storefront Signs', href: '#' }, { label: 'Art Installations', href: '#' }] }, { title: 'Studio', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Stained Glass Studio — Marketing Site', category: 'Website-Creative', paletteId: 'gallery-red-light',
    spec: {
      description: 'Marketing site for a stained glass studio specializing in restoration and commissions.',
      brand: 'Aldergate Glass Studio', tagline: 'LEADED GLASS, HAND-FIRED',
      heroTitle: 'Glass leaded and fired the way it has been done for a century.',
      heroDescription: 'Cathedral window restoration, residential commissions, and gallery pieces, built entirely by hand.',
      heroCta: 'Discuss a commission',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Restoration', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Cathedral Restoration', description: 'Historic windows restored with heritage-approved materials.' },
        { title: 'Residential Commissions', description: 'A panel designed and built around your actual space.' },
        { title: 'Gallery Pieces', description: 'Stained glass as fine art, not just architectural fixture.' },
      ],
      stats: [{ value: 5, label: 'Active Commissions' }, { value: '22k', label: 'Avg. Commission Value' }, { value: 85, suffix: '%', label: 'On-Time Completion' }],
      testimonials: [
        { quote: 'The restoration matched the original craftsmanship perfectly.', name: 'Church Committee', role: 'Client', rating: 5 },
        { quote: 'A genuinely rare level of skill in this craft today.', name: 'Homeowner', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have glass worth restoring or commissioning?', ctaDescription: 'We take on a limited number of commissions each year.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Restoration', href: '#' }, { label: 'Commissions', href: '#' }] }, { title: 'Studio', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Cider House & Orchard — Marketing Site', category: 'Website-Food', paletteId: 'forest-market-light',
    spec: {
      description: 'Marketing site for a private cider house and orchard.',
      brand: 'Fernbrook Cider House', tagline: 'ORCHARD TO BOTTLE CIDER',
      heroTitle: 'Cider pressed from our own orchard, not blended from concentrate.',
      heroDescription: 'Heritage apple varieties, barrel-aged reserves, and wholesale accounts, all supplied from 84 acres we manage ourselves.',
      heroCta: 'Set up a wholesale account',
      navLinks: [{ label: 'Cidery', href: '#' }, { label: 'Orchard', href: '#' }, { label: 'Wholesale', href: '#' }],
      features: [
        { title: 'Heritage Apple Orchard', description: '84 acres of heritage varieties, managed for flavor, not yield.' },
        { title: 'Barrel-Aged Reserves', description: 'Small-batch cider aged in oak for real depth.' },
        { title: 'Wholesale Program', description: 'Restaurant and retail accounts supplied direct from the press.' },
      ],
      stats: [{ value: 28, label: 'Wholesale Accounts' }, { value: 84, label: 'Orchard Acres' }, { value: '420 gal', label: 'Weekly Press Yield' }],
      testimonials: [
        { quote: 'You can genuinely taste the difference from a concentrate cider.', name: 'Restaurant Buyer', role: 'Client', rating: 5 },
        { quote: 'The barrel-aged reserve is the best cider on our list.', name: 'Beverage Director', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Building a real cider program?', ctaDescription: 'Set up a wholesale account for the current season.',
      footerColumns: [{ title: 'Cidery', links: [{ label: 'Our Cider', href: '#' }, { label: 'Orchard', href: '#' }] }, { title: 'Company', links: [{ label: 'Wholesale', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Fine Fur Restoration Atelier — Marketing Site', category: 'Website-Creative', paletteId: 'luxury-gold-dark',
    spec: {
      description: 'Marketing site for a fur restoration and cold storage atelier.',
      brand: 'Aldercroft Fur Atelier', tagline: 'FUR RESTORATION & STORAGE',
      heroTitle: 'Heirloom furs restored by a master furrier, not a dry cleaner.',
      heroDescription: 'Restoration, remodeling, and climate-controlled cold storage for garments that deserve real care.',
      heroCta: 'Request an assessment',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Storage', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Restoration & Relining', description: 'Vintage garments brought back to their original condition.' },
        { title: 'Custom Remodeling', description: 'A dated piece remade into something you’ll actually wear.' },
        { title: 'Climate-Controlled Storage', description: 'Cold storage that actually protects the garment year-round.' },
      ],
      stats: [{ value: 6, label: 'Active Commissions' }, { value: 84, label: 'Cold Storage Clients' }, { value: 68, suffix: '%', label: 'Repeat Client Rate' }],
      testimonials: [
        { quote: 'My grandmother’s coat looks better now than in her old photos.', name: 'Client', role: 'Client', rating: 5 },
        { quote: 'The remodel gave the piece a completely new life.', name: 'Client', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a piece worth restoring?', ctaDescription: 'Request a confidential condition assessment.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Restoration', href: '#' }, { label: 'Remodeling', href: '#' }] }, { title: 'Atelier', links: [{ label: 'Storage', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Embroidery & Regalia House — Marketing Site', category: 'Website-Creative', paletteId: 'midnight-press-dark',
    spec: {
      description: 'Marketing site for an embroidery and ceremonial regalia house.',
      brand: 'Aldergate Regalia House', tagline: 'HAND-EMBROIDERED REGALIA',
      heroTitle: 'Regalia embroidered to a standard institutions actually require.',
      heroDescription: 'Regimental badges, academic regalia, and ceremonial commissions, hand-stitched with real gold thread work.',
      heroCta: 'Discuss a commission',
      navLinks: [{ label: 'Commissions', href: '#' }, { label: 'Institutions', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Regimental Badges', description: 'Precise, regulation-accurate badge work for military and honor units.' },
        { title: 'Academic Regalia', description: 'Ceremonial pieces built to an institution’s exact heraldry.' },
        { title: 'Gold Thread Work', description: 'Traditional goldwork embroidery, done entirely by hand.' },
      ],
      stats: [{ value: 12, label: 'Active Commissions' }, { value: 34, label: 'Institutional Clients' }, { value: 62, suffix: '%', label: 'Repeat Client Rate' }],
      testimonials: [
        { quote: 'The heraldic accuracy was exactly what our institution required.', name: 'Institution Representative', role: 'Client', rating: 5 },
        { quote: 'Craftsmanship you genuinely can’t find elsewhere anymore.', name: 'Livery Company', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a regalia commission in mind?', ctaDescription: 'Institutional orders typically take about five weeks.',
      footerColumns: [{ title: 'Commissions', links: [{ label: 'Badges', href: '#' }, { label: 'Regalia', href: '#' }] }, { title: 'House', links: [{ label: 'Institutions', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Concours Car Detailing Studio — Marketing Site', category: 'Website-Logistics', paletteId: 'mono-dev-dark',
    spec: {
      description: 'Marketing site for a concours-level car detailing and paint correction studio.',
      brand: 'Ferrous Detailing Studio', tagline: 'CONCOURS-LEVEL DETAILING',
      heroTitle: 'Paint corrected to a standard judges actually score.',
      heroDescription: 'Multi-stage paint correction, ceramic coating, and show prep, done in a climate-controlled bay.',
      heroCta: 'Book a detail',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Show Prep', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Multi-Stage Correction', description: 'Paint corrected to a mirror finish, not a quick buff.' },
        { title: 'Ceramic Coating', description: 'Long-term protection applied to a genuinely corrected surface.' },
        { title: 'Concours Show Prep', description: 'Full prep for collectors who actually show their cars.' },
      ],
      stats: [{ value: 6, label: 'Active Jobs' }, { value: 88, suffix: '%', label: 'Bay Utilization' }, { value: 72, suffix: '%', label: 'Repeat Client Rate' }],
      testimonials: [
        { quote: 'The car placed at concours the same week it left their bay.', name: 'Collector', role: 'Client', rating: 5 },
        { quote: 'The correction work is the best I have seen at this level.', name: 'Collector', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Prepping for a show or just want it done right?', ctaDescription: 'Book a bay slot — appointments run 3-4 weeks out.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Correction', href: '#' }, { label: 'Ceramic Coating', href: '#' }] }, { title: 'Studio', links: [{ label: 'Show Prep', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
]

export const websiteBatch9 = specs
