const specs = [
  {
    name: 'Boutique Ski Chalet Group — Marketing Site', category: 'Website-RealEstate', paletteId: 'open-air-light',
    spec: {
      description: 'Marketing site for a boutique ski chalet rental group.',
      brand: 'Ridgeline Alpine Chalets', tagline: 'ALPINE HOSPITALITY',
      heroTitle: 'Chalets managed to hotel standard, without the hotel.',
      heroDescription: 'Private mountain chalets with dedicated property management — ski-in access, full concierge, zero compromises.',
      heroCta: 'Check availability',
      navLinks: [{ label: 'Chalets', href: '#' }, { label: 'Concierge', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Ski-In Chalets', description: 'Private mountain properties within steps of the lift.' },
        { title: 'Full Concierge', description: 'Private chef, ski instruction, and transport arranged before you land.' },
        { title: 'Hotel-Standard Service', description: 'Daily housekeeping and a dedicated property manager on call.' },
      ],
      stats: [{ value: 18, label: 'Managed Chalets' }, { value: 94, suffix: '%', label: 'Occupancy Rate' }, { value: 51, suffix: '%', label: 'Repeat Guest Rate' }],
      testimonials: [
        { quote: 'It felt like our own home, run by someone else’s staff.', name: 'Grace Whitfield', role: 'Guest', rating: 5 },
        { quote: 'The concierge had our ski instructor booked before we even landed.', name: 'James O’Brien', role: 'Guest', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Peak season books out early.', ctaDescription: 'Check availability for the upcoming season.',
      footerColumns: [{ title: 'Stay', links: [{ label: 'Chalets', href: '#' }, { label: 'Concierge', href: '#' }] }, { title: 'Company', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Fine Jewelry Atelier — Marketing Site', category: 'Website-Creative', paletteId: 'luxury-gold-dark',
    spec: {
      description: 'Marketing site for a fine jewelry atelier.',
      brand: 'Aldercroft Jewelers', tagline: 'FINE JEWELRY ATELIER',
      heroTitle: 'Jewelry made once, for the person it is made for.',
      heroDescription: 'Bespoke engagement rings, custom pieces, and heirloom redesigns, made entirely by hand in our atelier.',
      heroCta: 'Book a design consultation',
      navLinks: [{ label: 'Bespoke', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Bespoke Design', description: 'A piece designed from a blank page, not adapted from a catalog.' },
        { title: 'Ethically Sourced Stones', description: 'Every stone traced and verified before it reaches your setting.' },
        { title: 'Hand Fabrication', description: 'Cast, set, and finished by hand in our own atelier, not outsourced.' },
      ],
      stats: [{ value: 14, label: 'Active Commissions' }, { value: 90, suffix: '%', label: 'On-Time Delivery' }, { value: 22, suffix: ' yrs', label: 'Atelier Founded' }],
      testimonials: [
        { quote: 'They designed a ring that was somehow exactly what I didn’t know I wanted.', name: 'Priya Sharma', role: 'Client', rating: 5 },
        { quote: 'Watching them redesign my grandmother’s ring was worth the wait alone.', name: 'Elena Vasquez', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Designing something that matters?', ctaDescription: 'Book a private design consultation with our lead jeweler.',
      footerColumns: [{ title: 'Bespoke', links: [{ label: 'Engagement Rings', href: '#' }, { label: 'Custom Pieces', href: '#' }] }, { title: 'Atelier', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Boutique Ceramics Studio — Marketing Site', category: 'Website-Creative', paletteId: 'clay-sand-light',
    spec: {
      description: 'Marketing site for a boutique ceramics and pottery studio.',
      brand: 'Fernbrook Ceramics Studio', tagline: 'HANDMADE CERAMICS',
      heroTitle: 'Tableware thrown one piece at a time, not molded a thousand.',
      heroDescription: 'Wheel-thrown dinnerware, custom sets, and wholesale collections, fired in a small studio kiln.',
      heroCta: 'Shop the collection',
      navLinks: [{ label: 'Shop', href: '#' }, { label: 'Custom Orders', href: '#' }, { label: 'Wholesale', href: '#' }],
      features: [
        { title: 'Wheel-Thrown', description: 'Every piece thrown by hand, no two exactly alike.' },
        { title: 'Custom Dinnerware', description: 'Sets designed around your table, your glaze, your quantity.' },
        { title: 'Wholesale Program', description: 'Restaurant-grade tableware for kitchens that care what it looks like.' },
      ],
      stats: [{ value: 19, label: 'Active Orders' }, { value: 14, label: 'Wholesale Accounts' }, { value: 12, suffix: ' yrs', label: 'Studio Founded' }],
      testimonials: [
        { quote: 'Our restaurant’s plates get commented on more than the food some nights.', name: 'Coppermill Café', role: 'Wholesale Client', rating: 5 },
        { quote: 'The custom set for our wedding registry was worth every week of the wait.', name: 'Priya & James', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Outfitting a kitchen or a table?', ctaDescription: 'Shop the current collection or inquire about a custom order.',
      footerColumns: [{ title: 'Shop', links: [{ label: 'Collection', href: '#' }, { label: 'Custom Orders', href: '#' }] }, { title: 'Studio', links: [{ label: 'Wholesale', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Aviation Maintenance — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-ember-dark',
    spec: {
      description: 'Marketing site for a private aviation maintenance facility.',
      brand: 'Kestrel Ridge MRO', tagline: 'AIRCRAFT MAINTENANCE',
      heroTitle: 'Aircraft maintenance for owners who read the logbook.',
      heroDescription: 'Annual inspections, engine overhauls, and avionics upgrades — FAA-certified, owner-transparent.',
      heroCta: 'Schedule an inspection',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Certifications', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Annual Inspections', description: 'A thorough inspection with a real, itemized report — nothing hidden in the invoice.' },
        { title: 'Engine Overhaul', description: 'Factory-trained technicians on every major engine platform we service.' },
        { title: 'Avionics Upgrades', description: 'Panel upgrades installed and certified without grounding your aircraft for a season.' },
      ],
      stats: [{ value: 11, label: 'Active Service Orders' }, { value: 94, suffix: '%', label: 'On-Time Completion' }, { value: '9 days', label: 'Avg. Turnaround' }],
      testimonials: [
        { quote: 'The only shop that has ever shown me the actual part before replacing it.', name: 'Aircraft Owner', role: 'Client', rating: 5 },
        { quote: 'Turnaround was faster than they quoted, which never happens in aviation.', name: 'Fleet Manager', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Due for an inspection?', ctaDescription: 'Schedule your annual inspection before your window closes.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Inspections', href: '#' }, { label: 'Engine Overhaul', href: '#' }] }, { title: 'Facility', links: [{ label: 'Certifications', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Executive Office Suites — Marketing Site', category: 'Website-RealEstate', paletteId: 'saas-indigo-dark',
    spec: {
      description: 'Marketing site for an executive office and workspace provider.',
      brand: 'Aldergate Executive Suites', tagline: 'EXECUTIVE WORKSPACE',
      heroTitle: 'Office space run to the standard our members expect, every floor.',
      heroDescription: 'Private offices, dedicated desks, and virtual memberships in a building run like a private club, not a co-working chain.',
      heroCta: 'Tour a suite',
      navLinks: [{ label: 'Suites', href: '#' }, { label: 'Membership', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Private Office Suites', description: 'Fully furnished, private offices with your firm’s name on the door.' },
        { title: 'Member Amenities', description: 'Conference rooms, a members’ lounge, and concierge reception.' },
        { title: 'Flexible Terms', description: 'Month-to-month or multi-year, without a co-working chain’s fine print.' },
      ],
      stats: [{ value: 84, label: 'Active Members' }, { value: 89, suffix: '%', label: 'Occupancy Rate' }, { value: 86, suffix: '%', label: 'Renewal Rate' }],
      testimonials: [
        { quote: 'Clients assume we own the building, which is exactly the point.', name: 'Member Firm', role: 'Client', rating: 5 },
        { quote: 'The only workspace that has never once felt like a co-working space.', name: 'Member Firm', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'See the space before you sign.', ctaDescription: 'Book a private tour of an available suite.',
      footerColumns: [{ title: 'Space', links: [{ label: 'Suites', href: '#' }, { label: 'Membership', href: '#' }] }, { title: 'Company', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Luxury Motorcar Dealership — Marketing Site', category: 'Website-RealEstate', paletteId: 'luxury-gold-dark',
    spec: {
      description: 'Marketing site for a luxury and classic car dealership.',
      brand: 'Ashcombe Motorcars', tagline: 'CURATED MOTORCARS',
      heroTitle: 'Vehicles sourced for the client, not off the lot.',
      heroDescription: 'Vintage, limited-edition, and performance vehicles sourced globally on your behalf — discreet, unhurried, exact.',
      heroCta: 'Start a search',
      navLinks: [{ label: 'Inventory', href: '#' }, { label: 'Sourcing', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Global Sourcing', description: 'A network spanning auctions and private collections most buyers never reach.' },
        { title: 'Full Provenance', description: 'Every vehicle verified and documented before it ever reaches you.' },
        { title: 'White-Glove Delivery', description: 'Inspection, transport, and delivery handled without you lifting a finger.' },
      ],
      stats: [{ value: 22, label: 'Active Clients' }, { value: 88, suffix: '%', label: 'Sourcing Success Rate' }, { value: 6, label: 'Deliveries This Month' }],
      testimonials: [
        { quote: 'They found the exact car I had been searching for on my own for three years.', name: 'Collector', role: 'Client', rating: 5 },
        { quote: 'The sourcing process alone was worth the fee.', name: 'Collector', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Looking for a specific vehicle?', ctaDescription: 'Tell us what you are searching for — we source across the global market.',
      footerColumns: [{ title: 'Vehicles', links: [{ label: 'Inventory', href: '#' }, { label: 'Sourcing', href: '#' }] }, { title: 'Dealership', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Culinary Academy — Marketing Site', category: 'Website-Education', paletteId: 'food-amber-light',
    spec: {
      description: 'Marketing and admissions site for a private culinary academy.',
      brand: 'Ferrous Culinary Academy', tagline: 'PROFESSIONAL CULINARY TRAINING',
      heroTitle: 'Culinary training for people who intend to actually run a kitchen.',
      heroDescription: 'Certificate programs in culinary arts, pastry, and restaurant management, with real externship placements.',
      heroCta: 'Apply now',
      navLinks: [{ label: 'Programs', href: '#' }, { label: 'Placements', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Culinary Arts Certificate', description: 'A full culinary foundation taught by working chef instructors.' },
        { title: 'Real Externships', description: 'Placements at partner restaurants, not a mock kitchen exercise.' },
        { title: 'Job Placement', description: 'A placement team that actually knows the hiring chefs in the city.' },
      ],
      stats: [{ value: 42, label: 'Active Students' }, { value: 91, suffix: '%', label: 'Job Placement Rate' }, { value: 22, label: 'Externship Partners' }],
      testimonials: [
        { quote: 'The externship placement got me hired before I even graduated.', name: 'Alumnus', role: 'Graduate', rating: 5 },
        { quote: 'The only program that treated us like future line cooks, not students.', name: 'Alumnus', role: 'Graduate', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready to actually work in a kitchen?', ctaDescription: 'Apply for the next cohort — enrollment is limited.',
      footerColumns: [{ title: 'Programs', links: [{ label: 'Culinary Arts', href: '#' }, { label: 'Pastry', href: '#' }] }, { title: 'Academy', links: [{ label: 'Placements', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Racquet Club — Marketing Site', category: 'Website-Productivity', paletteId: 'track-red-light',
    spec: {
      description: 'Marketing and membership site for a private racquet club.',
      brand: 'Ironclad Racquet Club', tagline: 'PRIVATE RACQUET CLUB',
      heroTitle: 'Courts you can actually book, leagues you can actually win.',
      heroDescription: 'Indoor and outdoor tennis and pickleball, member leagues, and a pro shop staffed by real teaching pros.',
      heroCta: 'Tour the club',
      navLinks: [{ label: 'Courts', href: '#' }, { label: 'Leagues', href: '#' }, { label: 'Membership', href: '#' }],
      features: [
        { title: 'Indoor & Outdoor Courts', description: 'Year-round play across tennis and pickleball courts.' },
        { title: 'Member Leagues', description: 'Competitive leagues at every level, run by our teaching pros.' },
        { title: 'Pro Shop & Lessons', description: 'Private lessons and a fully stocked pro shop on-site.' },
      ],
      stats: [{ value: 420, label: 'Active Members' }, { value: 84, suffix: '%', label: 'Court Utilization' }, { value: 96, label: 'League Players' }],
      testimonials: [
        { quote: 'The league play here is the most competitive I have found in the city.', name: 'Member', role: 'Client', rating: 5 },
        { quote: 'I have never once failed to book a court when I wanted one.', name: 'Member', role: 'Client', rating: 5 },
      ],
      pricing: [
        { name: 'Individual', price: '$180', period: '/month', description: 'Full court access', features: ['Unlimited court time', 'League eligibility'], cta: 'Join now' },
        { name: 'Family', price: '$280', period: '/month', description: 'Full household access', features: ['Unlimited court time', 'League eligibility', 'Up to 4 members'], featured: true, cta: 'Join now' },
        { name: 'Corporate', price: 'Custom', description: 'For teams and companies', features: ['Bulk memberships', 'Event hosting'], cta: 'Contact us' },
      ],
      ctaTitle: 'Ready to actually get on a court?', ctaDescription: 'Tour the club and see what membership includes.',
      footerColumns: [{ title: 'Play', links: [{ label: 'Courts', href: '#' }, { label: 'Leagues', href: '#' }] }, { title: 'Club', links: [{ label: 'Membership', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Assisted Living Community — Marketing Site', category: 'Website-Healthcare', paletteId: 'wellness-teal-dark',
    spec: {
      description: 'Marketing and family-inquiry site for an assisted living community.',
      brand: 'Willowmere Senior Living', tagline: 'SENIOR LIVING COMMUNITY',
      heroTitle: 'Care coordinated across every shift, without a gap.',
      heroDescription: 'Independent living, assisted living, and memory care, with a care plan built around the resident, not a floor plan.',
      heroCta: 'Schedule a tour',
      navLinks: [{ label: 'Care Levels', href: '#' }, { label: 'Community', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Assisted Living', description: 'Daily support built around the resident’s actual routine, not ours.' },
        { title: 'Memory Care', description: 'A dedicated, secure community with staff trained specifically for memory care.' },
        { title: 'Family Communication', description: 'Real-time updates for families, not a monthly newsletter.' },
      ],
      stats: [{ value: 84, label: 'Residents' }, { value: 92, suffix: '%', label: 'Occupancy Rate' }, { value: 96, suffix: '%', label: 'Family Satisfaction' }],
      testimonials: [
        { quote: 'The care coordinator calls us before we even think to ask a question.', name: 'Family Member', role: 'Resident’s Daughter', rating: 5 },
        { quote: 'My father has never once felt like a room number here.', name: 'Family Member', role: 'Resident’s Son', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Considering a move for a loved one?', ctaDescription: 'Schedule a private tour and speak with our care team.',
      footerColumns: [{ title: 'Care', links: [{ label: 'Assisted Living', href: '#' }, { label: 'Memory Care', href: '#' }] }, { title: 'Community', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Boutique Perfumery — Marketing Site', category: 'Website-Creative', paletteId: 'creative-coral-light',
    spec: {
      description: 'Marketing site for a boutique bespoke perfumery.',
      brand: 'Ferrous & Bloom Perfumery', tagline: 'BESPOKE FRAGRANCE',
      heroTitle: 'Fragrance composed to the client, not blended off a shelf.',
      heroDescription: 'One-on-one fragrance composition sessions, resulting in a scent that exists nowhere else.',
      heroCta: 'Book a composition session',
      navLinks: [{ label: 'Bespoke', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Composition Sessions', description: 'A guided session that translates memory and preference into raw materials.' },
        { title: 'Rare Materials', description: 'A library of 340+ formulas built from ingredients most houses never touch.' },
        { title: 'Exclusive Formula', description: 'Your final scent belongs to you alone, never sold to another client.' },
      ],
      stats: [{ value: 8, label: 'Active Commissions' }, { value: 340, label: 'Formulas in Library' }, { value: 82, suffix: '%', label: 'Client Retention' }],
      testimonials: [
        { quote: 'It smells like a memory I didn’t know I could bottle.', name: 'Client', role: 'Client', rating: 5 },
        { quote: 'The most personal luxury purchase I have ever made.', name: 'Client', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a scent memory worth composing?', ctaDescription: 'Book a private composition session with our perfumer.',
      footerColumns: [{ title: 'Bespoke', links: [{ label: 'Composition', href: '#' }, { label: 'Process', href: '#' }] }, { title: 'House', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
]

export const websiteBatch4 = specs
