const specs = [
  {
    name: 'Private Falconry Academy — Marketing Site', category: 'Website-Education', paletteId: 'precision-ember-dark',
    spec: {
      description: 'Marketing and enrollment site for a licensed falconry academy.',
      brand: 'Blackwood Falconry Academy', tagline: 'LICENSED FALCONRY TRAINING',
      heroTitle: 'Falconry taught by licensed master falconers, not a weekend workshop.',
      heroDescription: 'A real apprenticeship path — general falconer through master falconer — with birds, mentors, and field hours that count.',
      heroCta: 'Apply to the program',
      navLinks: [{ label: 'Program', href: '#' }, { label: 'Faculty', href: '#' }, { label: 'Apply', href: '#' }],
      features: [
        { title: 'Licensed Apprenticeship', description: 'A state-recognized path from apprentice to general falconer.' },
        { title: 'Mentor-Led Field Hours', description: 'Real hunting hours logged with a sponsoring master falconer.' },
        { title: 'Raptor Handling Certificate', description: 'A credential recognized by wildlife rehabilitation programs.' },
      ],
      stats: [{ value: 14, label: 'Active Apprentices' }, { value: 88, suffix: '%', label: 'Certification Rate' }, { value: 22, label: 'Birds in Program' }],
      testimonials: [
        { quote: 'The mentorship was more rigorous than I expected, in the best way.', name: 'Apprentice', role: 'Graduate', rating: 5 },
        { quote: 'A real credential, not a certificate you print at home.', name: 'Apprentice', role: 'Current Student', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready to start an apprenticeship?', ctaDescription: 'Applications open twice a year — spring and fall cohorts.',
      footerColumns: [{ title: 'Program', links: [{ label: 'Curriculum', href: '#' }, { label: 'Faculty', href: '#' }] }, { title: 'Academy', links: [{ label: 'Apply', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Rare Book & Manuscript Dealer — Marketing Site', category: 'Website-Creative', paletteId: 'paper-oxblood-light',
    spec: {
      description: 'Marketing site for a rare book and manuscript dealer.',
      brand: 'Aldergate Rare Books', tagline: 'RARE BOOKS & MANUSCRIPTS',
      heroTitle: 'Rare books sourced, authenticated, and sold with real provenance.',
      heroDescription: 'First editions, illuminated manuscripts, and signed copies — every volume backed by a documented chain of ownership.',
      heroCta: 'Browse the collection',
      navLinks: [{ label: 'Collection', href: '#' }, { label: 'Authentication', href: '#' }, { label: 'Sell to Us', href: '#' }],
      features: [
        { title: 'Authenticated Provenance', description: 'Every volume researched and documented before it goes to sale.' },
        { title: 'Estate Acquisitions', description: 'Private and estate libraries acquired with discretion.' },
        { title: 'Appraisal Services', description: 'Insurance-grade appraisals for collectors and estates.' },
      ],
      stats: [{ value: 340, label: 'Volumes in Inventory' }, { value: '2.4M', label: 'Inventory Value' }, { value: 62, label: 'Avg. Days to Sale' }],
      testimonials: [
        { quote: 'The provenance research alone was worth the price.', name: 'Collector', role: 'Client', rating: 5 },
        { quote: 'They handled our family library with real care and discretion.', name: 'Estate Executor', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a library worth appraising?', ctaDescription: 'We offer confidential appraisals for estates and private collections.',
      footerColumns: [{ title: 'Collection', links: [{ label: 'Browse', href: '#' }, { label: 'New Acquisitions', href: '#' }] }, { title: 'Services', links: [{ label: 'Appraisal', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Pipe Organ Restoration Firm — Marketing Site', category: 'Website-Creative', paletteId: 'midnight-press-dark',
    spec: {
      description: 'Marketing site for a boutique pipe organ restoration firm.',
      brand: 'Aldergate Organ Works', tagline: 'PIPE ORGAN RESTORATION',
      heroTitle: 'Pipe organs restored to play in the room they were built for.',
      heroDescription: 'Full mechanical and tonal restoration for cathedral, church, and concert hall instruments — voiced on site, not in a shop.',
      heroCta: 'Discuss a restoration',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Full Mechanical Restoration', description: 'Wind chests, action, and console rebuilt to original spec.' },
        { title: 'On-Site Voicing', description: 'Every pipe voiced in the room it will actually be heard in.' },
        { title: 'Historic Preservation', description: 'Restoration that respects the instrument’s original character.' },
      ],
      stats: [{ value: 4, label: 'Active Restorations' }, { value: '120k', label: 'Avg. Project Value' }, { value: 82, suffix: '%', label: 'On-Time Completion' }],
      testimonials: [
        { quote: 'The organ sounds better than it has in fifty years.', name: 'Music Director', role: 'Client', rating: 5 },
        { quote: 'A genuinely rare level of craftsmanship.', name: 'Diocese Representative', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have an instrument that needs real restoration?', ctaDescription: 'We take on a limited number of restorations each year.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Restorations', href: '#' }, { label: 'Process', href: '#' }] }, { title: 'Firm', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Truffle Foraging Co. — Marketing Site', category: 'Website-Food', paletteId: 'forest-market-light',
    spec: {
      description: 'Marketing and wholesale site for a private truffle foraging and distribution company.',
      brand: 'Fernbrook Truffle Co.', tagline: 'FORAGED TRUFFLES, DELIVERED FRESH',
      heroTitle: 'Truffles foraged and delivered the same day, not flown in stale.',
      heroDescription: 'Black and white truffles hunted with trained dogs and delivered directly to restaurant kitchens within hours.',
      heroCta: 'Set up a standing order',
      navLinks: [{ label: 'Restaurants', href: '#' }, { label: 'Season', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Same-Day Delivery', description: 'Harvested at dawn, delivered before service.' },
        { title: 'Trained Foraging Dogs', description: 'Four working dogs, each with a dedicated handler.' },
        { title: 'Standing Restaurant Orders', description: 'Daily supply built around your actual menu volume.' },
      ],
      stats: [{ value: 22, label: 'Restaurant Accounts' }, { value: '4.2 lbs', label: "Today's Harvest" }, { value: 4, label: 'Foraging Dogs Active' }],
      testimonials: [
        { quote: 'The freshness difference is obvious the moment it hits the pan.', name: 'Executive Chef', role: 'Client', rating: 5 },
        { quote: 'Reliable supply through the whole season, which is rare.', name: 'Chef', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Running a kitchen that needs real truffles?', ctaDescription: 'Set up a standing order for the season.',
      footerColumns: [{ title: 'Restaurants', links: [{ label: 'Standing Orders', href: '#' }, { label: 'Special Orders', href: '#' }] }, { title: 'Company', links: [{ label: 'Season', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Hot Air Balloon Adventures — Marketing Site', category: 'Website-Travel', paletteId: 'open-air-light',
    spec: {
      description: 'Marketing and booking site for a private hot air balloon tour company.',
      brand: 'Ridgeline Balloon Adventures', tagline: 'SUNRISE BALLOON FLIGHTS',
      heroTitle: 'Sunrise flights planned around the weather, not the calendar.',
      heroDescription: 'Private charters, proposal flights, and group tours flown by FAA-certified pilots — champagne toast included.',
      heroCta: 'Book a flight',
      navLinks: [{ label: 'Flights', href: '#' }, { label: 'Private Charters', href: '#' }, { label: 'Book Now', href: '#' }],
      features: [
        { title: 'Sunrise Flights', description: 'The calmest air of the day, over some of the best scenery in the region.' },
        { title: 'Private Charters', description: 'A balloon reserved entirely for your group, no strangers aboard.' },
        { title: 'Weather-First Scheduling', description: 'We fly when it is safe, and rebook instantly when it is not.' },
      ],
      stats: [{ value: 18, label: 'Flights (MTD)' }, { value: 12, suffix: '%', label: 'Weather Cancellation Rate' }, { value: 6, label: 'Avg. Passengers/Flight' }],
      testimonials: [
        { quote: 'The proposal flight was more beautiful than we could have planned ourselves.', name: 'Passenger', role: 'Guest', rating: 5 },
        { quote: 'They rebooked us with zero hassle when the weather turned.', name: 'Passenger', role: 'Guest', rating: 5 },
      ],
      pricing: [
        { name: 'Shared Flight', price: '$249', period: '/person', description: 'Join a small group sunrise flight', features: ['Sunrise flight', 'Champagne toast', 'Flight certificate'], cta: 'Book' },
        { name: 'Private Charter', price: '$1,400', period: '/flight', description: 'The whole balloon, just for your group', features: ['Up to 4 passengers', 'Champagne toast', 'Custom flight path'], featured: true, cta: 'Book' },
        { name: 'Proposal Flight', price: '$1,800', period: '/flight', description: 'A flight built around the moment', features: ['Private charter', 'Photographer add-on', 'Champagne toast'], cta: 'Book' },
      ],
      ctaTitle: 'Ready to see sunrise from above?', ctaDescription: 'Flights book out weeks ahead in peak season — reserve early.',
      footerColumns: [{ title: 'Flights', links: [{ label: 'Shared Flights', href: '#' }, { label: 'Private Charters', href: '#' }] }, { title: 'Company', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Custom Cigar House — Marketing Site', category: 'Website-Food', paletteId: 'supper-club-dark',
    spec: {
      description: 'Marketing site for a private cigar blending and rolling house.',
      brand: 'Aldercroft Cigar House', tagline: 'CIGARS ROLLED TO ORDER',
      heroTitle: 'Cigars rolled to order, not stocked off a shelf.',
      heroDescription: 'Custom blends, hand-rolled to order, for weddings, corporate gifts, and private collectors who know the difference.',
      heroCta: 'Start a custom order',
      navLinks: [{ label: 'Custom Blends', href: '#' }, { label: 'Corporate Gifts', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Custom Blending', description: 'A blend developed and sampled specifically for your palate.' },
        { title: 'Custom Bands', description: 'Personalized bands for weddings and corporate events.' },
        { title: 'Retail Wholesale', description: 'Consistent, hand-rolled inventory for lounge and retail accounts.' },
      ],
      stats: [{ value: 14, label: 'Active Orders' }, { value: '1.8k', label: 'Avg. Order Value' }, { value: 18, label: 'Retail Accounts' }],
      testimonials: [
        { quote: 'Our wedding cigars are still the thing guests talk about.', name: 'Client', role: 'Groom', rating: 5 },
        { quote: 'The blend they built for me is better than anything I can buy.', name: 'Private Collector', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Planning an event or a custom blend?', ctaDescription: 'Talk to us about your order — custom blends take about three weeks.',
      footerColumns: [{ title: 'Orders', links: [{ label: 'Custom Blends', href: '#' }, { label: 'Corporate Gifts', href: '#' }] }, { title: 'Company', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Botanical Garden Design Studio — Marketing Site', category: 'Website-Creative', paletteId: 'forest-market-light',
    spec: {
      description: 'Marketing site for a private botanical garden design firm.',
      brand: 'Fernbrook Botanical Design', tagline: 'BOTANICAL GARDEN DESIGN',
      heroTitle: 'Gardens designed with the same rigor as a botanical collection.',
      heroDescription: 'Rare specimen sourcing, conservatory design, and full estate gardens, built by a team that treats plants like a real collection.',
      heroCta: 'Start a project',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Rare Specimen Sourcing', description: 'Plants sourced from growers most designers never contact.' },
        { title: 'Conservatory Design', description: 'Climate-controlled growing environments engineered around the collection.' },
        { title: 'Full Estate Gardens', description: 'From bare land to a mature-feeling garden, managed start to finish.' },
      ],
      stats: [{ value: 9, label: 'Active Projects' }, { value: '140k', label: 'Avg. Project Value' }, { value: 84, label: 'Rare Specimens Sourced' }],
      testimonials: [
        { quote: 'The garden feels like it has been here for decades already.', name: 'Homeowner', role: 'Client', rating: 5 },
        { quote: 'The specimen sourcing alone justified the entire project.', name: 'Estate Manager', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Planning a garden worth the investment?', ctaDescription: 'We take on a limited number of estate projects each year.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Gardens', href: '#' }, { label: 'Conservatories', href: '#' }] }, { title: 'Studio', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Falconry Equipment Makers — Marketing Site', category: 'Website-Creative', paletteId: 'clay-sand-light',
    spec: {
      description: 'Marketing site for a private falconry equipment maker.',
      brand: 'Aldergate Falconry Goods', tagline: 'HAND-MADE FALCONRY GEAR',
      heroTitle: 'Hoods, jesses, and gauntlets, hand-made to the bird.',
      heroDescription: 'Custom leather falconry equipment, fitted and stitched by hand for falconers who won’t settle for mass-produced gear.',
      heroCta: 'Order custom gear',
      navLinks: [{ label: 'Custom Gear', href: '#' }, { label: 'Fitting', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Custom Gauntlets', description: 'Fitted to your hand and your bird, not a standard size.' },
        { title: 'Hand-Stitched Hoods', description: 'Hoods built for a precise, comfortable fit on the exact species.' },
        { title: 'Falconry Club Supply', description: 'Wholesale gear for clubs and equipment suppliers.' },
      ],
      stats: [{ value: 16, label: 'Active Orders' }, { value: 340, label: 'Avg. Order Value' }, { value: 68, suffix: '%', label: 'Repeat Customer Rate' }],
      testimonials: [
        { quote: 'The fit is completely different from anything I bought off the shelf.', name: 'Falconer', role: 'Client', rating: 5 },
        { quote: 'This is the gear I recommend to every apprentice I sponsor.', name: 'Master Falconer', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Need gear fitted to your bird?', ctaDescription: 'Custom orders take about three weeks from measurement to ship.',
      footerColumns: [{ title: 'Gear', links: [{ label: 'Gauntlets', href: '#' }, { label: 'Hoods', href: '#' }] }, { title: 'Company', links: [{ label: 'Fitting', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Apiary Management — Marketing Site', category: 'Website-Food', paletteId: 'food-amber-light',
    spec: {
      description: 'Marketing site for a private beekeeping and apiary management firm.',
      brand: 'Fernbrook Apiary Management', tagline: 'MANAGED HIVES, REAL YIELD',
      heroTitle: 'Hives managed like a real agricultural operation, not a hobby.',
      heroDescription: 'Full-service apiary management for estates, farms, and vineyards — inspections, treatment, and honey extraction handled end to end.',
      heroCta: 'Request a hive assessment',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Pollination', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Managed Hive Program', description: 'Regular inspections, treatment, and reporting on every hive.' },
        { title: 'Pollination Contracts', description: 'Managed pollination for orchards and vineyards during bloom.' },
        { title: 'Honey Extraction & Sale', description: 'We extract, bottle, and can help sell your own estate honey.' },
      ],
      stats: [{ value: 84, label: 'Managed Hives' }, { value: 92, suffix: '%', label: 'Hive Health Rate' }, { value: 22, label: 'Client Apiaries' }],
      testimonials: [
        { quote: 'Our orchard yield improved noticeably after their first season managing pollination.', name: 'Orchard Owner', role: 'Client', rating: 5 },
        { quote: 'Professional, reliable, and our hives have never been healthier.', name: 'Estate Manager', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have land that could use managed hives?', ctaDescription: 'Request a free hive-site assessment.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Hive Management', href: '#' }, { label: 'Pollination', href: '#' }] }, { title: 'Company', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Antique Clock & Automata Restoration — Marketing Site', category: 'Website-Creative', paletteId: 'paper-oxblood-light',
    spec: {
      description: 'Marketing site for an antique clock and automata restoration workshop.',
      brand: 'Aldergate Clockworks', tagline: 'MECHANISMS RESTORED TO RUN',
      heroTitle: 'Mechanisms restored to run, not just to display.',
      heroDescription: 'Grandfather clocks, automata, and pocket watches restored by hand — every gear train rebuilt to keep real time.',
      heroCta: 'Discuss a restoration',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Automata Restoration', description: 'Musical and mechanical automata restored to their original motion.' },
        { title: 'Grandfather Clock Restoration', description: 'Full movement rebuild and case refinishing.' },
        { title: 'Pocket Watch Service', description: 'Escapement adjustment and full servicing for heirloom watches.' },
      ],
      stats: [{ value: 7, label: 'Active Restorations' }, { value: '8.4k', label: 'Avg. Restoration Value' }, { value: 86, suffix: '%', label: 'On-Time Completion' }],
      testimonials: [
        { quote: 'My grandfather’s clock runs better now than it did fifty years ago.', name: 'Client', role: 'Collector', rating: 5 },
        { quote: 'The automaton moves exactly as it did the day it was built.', name: 'Museum Curator', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a mechanism worth restoring?', ctaDescription: 'We take a limited number of restorations each season.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Restorations', href: '#' }, { label: 'Process', href: '#' }] }, { title: 'Workshop', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
]

export const websiteBatch7 = specs
