const specs = [
  {
    name: 'Private Equity Firm — Marketing Site', category: 'Website-Finance', paletteId: 'fintech-emerald-dark',
    spec: {
      description: 'Marketing site for a private equity firm.',
      brand: 'Kestrel Ridge Capital', tagline: 'PRIVATE EQUITY',
      heroTitle: 'Disciplined capital for founders who have already done the hard part.',
      heroDescription: 'Growth equity and buyout investments in founder-led businesses ready to scale past their first act.',
      heroCta: 'Discuss a partnership',
      navLinks: [{ label: 'Approach', href: '#' }, { label: 'Portfolio', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Growth Equity', description: 'Capital and operating support for companies with product-market fit already proven.' },
        { title: 'Buyout Investments', description: 'Full or majority acquisitions of established, profitable businesses.' },
        { title: 'Operating Support', description: 'A bench of operating partners, not just a board seat and a check.' },
      ],
      stats: [{ value: 640, suffix: 'M', label: 'AUM (Fund III)' }, { value: 14, label: 'Portfolio Companies' }, { value: 24, suffix: '%', label: 'Gross IRR' }],
      testimonials: [
        { quote: 'They brought operating help, not just capital and a quarterly call.', name: 'Colin Whitford', role: 'CEO, Portfolio Company', rating: 5 },
        { quote: 'The only fund that actually understood our industry before the first meeting.', name: 'Sade Adeyemi', role: 'Founder, Portfolio Company', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Building something worth backing?', ctaDescription: 'We meet founders well before a formal process begins.',
      footerColumns: [{ title: 'Invest', links: [{ label: 'Growth Equity', href: '#' }, { label: 'Buyouts', href: '#' }] }, { title: 'Firm', links: [{ label: 'Portfolio', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Environmental Foundation — Marketing Site', category: 'Website-NonProfit', paletteId: 'moss-archive-light',
    spec: {
      description: 'Marketing and donor site for an environmental foundation.',
      brand: 'Fernbrook Foundation', tagline: 'ENVIRONMENTAL FOUNDATION',
      heroTitle: 'Funding the land stewardship work that outlasts a single grant cycle.',
      heroDescription: 'Watershed restoration, wetlands protection, and grassland conservation, funded through multi-year grants.',
      heroCta: 'Support our work',
      navLinks: [{ label: 'Our Work', href: '#' }, { label: 'Grantees', href: '#' }, { label: 'Give', href: '#' }],
      features: [
        { title: 'Watershed Restoration', description: 'Multi-year grants for the restoration work that takes longer than one budget cycle.' },
        { title: 'Wetlands Protection', description: 'Direct funding for land trusts protecting critical wetland habitat.' },
        { title: 'Grassland Conservation', description: 'Partnering with ranchers and land trusts on working-land conservation.' },
      ],
      stats: [{ value: 4.8, suffix: 'M', label: 'Grants Disbursed (YTD)' }, { value: 46, label: 'Active Grantees' }, { value: 12400, label: 'Acres Under Stewardship' }],
      testimonials: [
        { quote: 'They fund the multi-year work other foundations won’t commit to.', name: 'Diego Álvarez', role: 'Executive Director, Grantee' },
        { quote: 'A true partner, not just a check that shows up once a year.', name: 'Helga Berg', role: 'Program Director, Grantee' },
      ],
      pricing: null,
      ctaTitle: 'Land stewardship takes more than one season.', ctaDescription: 'Support multi-year conservation work with a gift today.',
      footerColumns: [{ title: 'Our Work', links: [{ label: 'Watershed', href: '#' }, { label: 'Wetlands', href: '#' }] }, { title: 'Foundation', links: [{ label: 'Grantees', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Fine Art Gallery — Marketing Site', category: 'Website-Creative', paletteId: 'gallery-red-light',
    spec: {
      description: 'Marketing site for a fine art gallery and auction house.',
      brand: 'Verrier & Cass', tagline: 'FINE ART GALLERY',
      heroTitle: 'Representing artists whose work outlives the market cycle.',
      heroDescription: 'Contemporary painting, sculpture, and works on paper — private sales, exhibitions, and collection advisory.',
      heroCta: 'Inquire about a work',
      navLinks: [{ label: 'Artists', href: '#' }, { label: 'Exhibitions', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Represented Artists', description: 'A roster built on conviction, not just what sells this season.' },
        { title: 'Private Sales', description: 'Discreet acquisitions for collectors who prefer not to bid at auction.' },
        { title: 'Collection Advisory', description: 'Guidance for collectors building toward something with real coherence.' },
      ],
      stats: [{ value: 84, label: 'Works in Collection' }, { value: 6.4, suffix: 'M', label: 'Collection Value' }, { value: 112, label: 'Private Clients' }],
      testimonials: [
        { quote: 'They understood exactly what belonged in our collection, and what didn’t.', name: 'Beatrix Ondo', role: 'Private Collector', rating: 5 },
        { quote: 'The only gallery that never once tried to sell me something wrong for the collection.', name: 'Felix Marchetti', role: 'Private Collector', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Building a collection?', ctaDescription: 'Speak with our advisory team about acquisitions and representation.',
      footerColumns: [{ title: 'Collect', links: [{ label: 'Artists', href: '#' }, { label: 'Exhibitions', href: '#' }] }, { title: 'Gallery', links: [{ label: 'Advisory', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Boutique Investment Bank — Advisory Site', category: 'Website-Finance', paletteId: 'saas-indigo-light',
    spec: {
      description: 'Marketing site for a boutique fund administration firm.',
      brand: 'Ledgerstone Fund Services', tagline: 'FUND ADMINISTRATION',
      heroTitle: 'Fund administration that closes the books on time, every time.',
      heroDescription: 'NAV calculation, investor reporting, and fund accounting for managers who need a partner, not a vendor.',
      heroCta: 'Talk to our team',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Fund Types', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'NAV Calculation', description: 'On-time NAVs, verified twice before they ever reach an investor.' },
        { title: 'Investor Reporting', description: 'Reports built to satisfy your most detail-oriented LP.' },
        { title: 'Fund Accounting', description: 'A dedicated fund accountant who actually knows your structure.' },
      ],
      stats: [{ value: 22, label: 'Funds Administered' }, { value: '1.8B', label: 'AUA' }, { value: 98, suffix: '%', label: 'On-Time NAV Rate' }],
      testimonials: [
        { quote: 'The first administrator that never once missed a close date.', name: 'Renata Silva', role: 'CFO, Fund Manager', rating: 5 },
        { quote: 'Our LPs stopped asking us questions once Ledgerstone took over reporting.', name: 'Marcus Ellison', role: 'Managing Partner', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Tired of chasing your administrator?', ctaDescription: 'Talk to our team about switching funds without missing a close.',
      footerColumns: [{ title: 'Services', links: [{ label: 'NAV', href: '#' }, { label: 'Reporting', href: '#' }] }, { title: 'Firm', links: [{ label: 'Fund Types', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'High-End Landscape Design Studio — Marketing Site', category: 'Website-Creative', paletteId: 'forest-market-light',
    spec: {
      description: 'Marketing and portfolio site for a landscape design studio.',
      brand: 'Fernbrook Landscape Studio', tagline: 'LANDSCAPE DESIGN',
      heroTitle: 'Gardens designed to look established the day they are planted.',
      heroDescription: 'Full-property landscape design, native plant restoration, and courtyard design for clients who think in decades, not seasons.',
      heroCta: 'Start a project',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Full Property Design', description: 'A landscape master plan built around how the property is actually used.' },
        { title: 'Native Plant Restoration', description: 'Ecologically grounded planting plans that thrive without constant intervention.' },
        { title: 'Courtyard & Outdoor Living', description: 'Outdoor rooms designed with the same rigor as the house itself.' },
      ],
      stats: [{ value: 15, label: 'Active Projects' }, { value: 87, suffix: '%', label: 'On-Schedule Rate' }, { value: 20, suffix: ' yrs', label: 'Studio Founded' }],
      testimonials: [
        { quote: 'The garden looked ten years old the week it was finished.', name: 'Whitmore Estate', role: 'Client', rating: 5 },
        { quote: 'They designed for how we actually use the yard, not how it photographs.', name: 'Alder Street Client', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a property that needs a plan?', ctaDescription: 'Tell us about the site — we take on a limited number of projects per season.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Residential', href: '#' }, { label: 'Native Plant', href: '#' }] }, { title: 'Studio', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Security Consultancy — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-acid-dark',
    spec: {
      description: 'Marketing site for a corporate security consultancy.',
      brand: 'Blackridge Security Advisory', tagline: 'CORPORATE SECURITY ADVISORY',
      heroTitle: 'Risk assessments for organizations that would rather not find out the hard way.',
      heroDescription: 'Physical security assessments, executive protection reviews, and insider threat programs for companies with real exposure.',
      heroCta: 'Request an assessment',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Approach', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Physical Security Assessment', description: 'A real audit of your facilities, not a checklist exercise.' },
        { title: 'Executive Protection Review', description: 'Threat assessments for the people your business actually depends on.' },
        { title: 'Insider Threat Programs', description: 'Programs built around your actual risk, not a generic template.' },
      ],
      stats: [{ value: 12, label: 'Active Engagements' }, { value: 82, suffix: '%', label: 'Findings Remediated' }, { value: 90, suffix: '%', label: 'Client Retention' }],
      testimonials: [
        { quote: 'They found exposure our internal team had missed for years.', name: 'Nina Whitfield', role: 'CISO, Client Company', rating: 5 },
        { quote: 'The most thorough assessment we have had in a decade.', name: 'Owen Fairbanks', role: 'COO, Client Company', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Know your actual exposure.', ctaDescription: 'Request a confidential consultation with our advisory team.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Assessments', href: '#' }, { label: 'Executive Protection', href: '#' }] }, { title: 'Firm', links: [{ label: 'Approach', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Bespoke Tailoring House — Marketing Site', category: 'Website-Creative', paletteId: 'gallery-red-light',
    spec: {
      description: 'Marketing site for a bespoke tailoring house.',
      brand: 'Aldergate Bespoke', tagline: 'BESPOKE TAILORING',
      heroTitle: 'Suits built to the client, not the rack.',
      heroDescription: 'Fully bespoke suiting and formal wear, cut and fitted over multiple sessions, made by hand.',
      heroCta: 'Book a consultation',
      navLinks: [{ label: 'Process', href: '#' }, { label: 'Fabrics', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Fully Bespoke', description: 'A pattern cut from scratch, for you, not adjusted from a block.' },
        { title: 'Hand Finishing', description: 'Hand-stitched details that a machine simply cannot replicate.' },
        { title: 'Fabric Selection', description: 'Mills sourced from England and Italy, chosen for how they actually wear.' },
      ],
      stats: [{ value: 21, label: 'Active Orders' }, { value: '6 wks', label: 'Avg. Turnaround' }, { value: 84, suffix: '%', label: 'Client Retention' }],
      testimonials: [
        { quote: 'The first suit that has ever actually fit me.', name: 'James O’Brien', role: 'Client', rating: 5 },
        { quote: 'Worth every one of the three fittings.', name: 'Marcus Rivera', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready for a suit built around you?', ctaDescription: 'Book a consultation to begin your first fitting.',
      footerColumns: [{ title: 'Tailoring', links: [{ label: 'Process', href: '#' }, { label: 'Fabrics', href: '#' }] }, { title: 'House', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Tutoring & Test Prep Firm — Marketing Site', category: 'Website-Education', paletteId: 'cobalt-pop-light',
    spec: {
      description: 'Marketing site for a private tutoring and test prep firm.',
      brand: 'Ashford Scholars Tutoring', tagline: 'PRIVATE TEST PREPARATION',
      heroTitle: 'Test prep for students who need a plan, not just a workbook.',
      heroDescription: 'SAT, ACT, and AP tutoring built around a real diagnostic and a real plan, not a generic curriculum.',
      heroCta: 'Book a diagnostic',
      navLinks: [{ label: 'Programs', href: '#' }, { label: 'Tutors', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'SAT & ACT Prep', description: 'A personalized plan built from a real diagnostic, not a one-size curriculum.' },
        { title: 'AP Subject Tutoring', description: 'Subject-matter tutors who actually taught the AP curriculum.' },
        { title: 'College Essay Coaching', description: 'Essay coaching that finds the student’s actual voice, not a template.' },
      ],
      stats: [{ value: 46, label: 'Active Students' }, { value: 180, label: 'Avg. Score Improvement' }, { value: 96, suffix: '%', label: 'Parent Satisfaction' }],
      testimonials: [
        { quote: 'His score went up 200 points and he actually enjoyed the sessions.', name: 'Parent of a Student', role: 'Parent', rating: 5 },
        { quote: 'The only prep program that treated my daughter like an individual, not a number.', name: 'Parent of a Student', role: 'Parent', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Start with a real diagnostic.', ctaDescription: 'Book a diagnostic assessment to see where your student actually stands.',
      footerColumns: [{ title: 'Programs', links: [{ label: 'SAT/ACT', href: '#' }, { label: 'AP Subjects', href: '#' }] }, { title: 'Firm', links: [{ label: 'Tutors', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Marine Vessel Services — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-sky-dark',
    spec: {
      description: 'Marketing site for a marine vessel maintenance and service company.',
      brand: 'Meridian Yacht Services', tagline: 'VESSEL MAINTENANCE',
      heroTitle: 'Vessel maintenance scheduled before the season, not during it.',
      heroDescription: 'Engine service, hull maintenance, and spring commissioning for owners who would rather not think about it.',
      heroCta: 'Schedule service',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Fleet Contracts', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Engine Service', description: 'Full-service engine maintenance from technicians who know your make.' },
        { title: 'Hull Maintenance', description: 'Cleaning and inspection that catches issues before they cost real money.' },
        { title: 'Spring Commissioning', description: 'Your vessel ready for launch day, not launch week.' },
      ],
      stats: [{ value: 24, label: 'Vessels Serviced (MTD)' }, { value: 62, label: 'Fleet Under Contract' }, { value: 90, suffix: '%', label: 'Client Retention' }],
      testimonials: [
        { quote: 'They caught an issue our previous yard missed for two seasons.', name: 'Marina Client', role: 'Vessel Owner', rating: 5 },
        { quote: 'Our boat has never been ready for launch day this early before.', name: 'Fleet Owner', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Get ahead of the season.', ctaDescription: 'Schedule your spring commissioning before the rush.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Engine', href: '#' }, { label: 'Hull', href: '#' }] }, { title: 'Company', links: [{ label: 'Fleet Contracts', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Antique & Fine Furnishings Dealer — Marketing Site', category: 'Website-Creative', paletteId: 'paper-oxblood-light',
    spec: {
      description: 'Marketing site for an antique and fine furnishings dealer.',
      brand: 'Aldergate Antiques', tagline: 'FINE ANTIQUES & FURNISHINGS',
      heroTitle: 'Provenance documented as carefully as the piece itself.',
      heroDescription: 'Curated 18th and 19th century furniture and decorative arts, sourced from estates and verified before sale.',
      heroCta: 'View the collection',
      navLinks: [{ label: 'Collection', href: '#' }, { label: 'Sourcing', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Verified Provenance', description: 'Every piece documented with real provenance, not a hopeful guess.' },
        { title: 'Estate Sourcing', description: 'A network of estate relationships most dealers never access.' },
        { title: 'Restoration Guidance', description: 'Advice on what to restore and what to leave exactly as found.' },
      ],
      stats: [{ value: 140, label: 'Pieces in Collection' }, { value: 2.8, suffix: 'M', label: 'Collection Value' }, { value: 68, suffix: ' days', label: 'Avg. Days to Sale' }],
      testimonials: [
        { quote: 'The provenance documentation alone was worth the price.', name: 'Private Collector', role: 'Client', rating: 5 },
        { quote: 'The only dealer I trust to tell me when a piece isn’t right for my collection.', name: 'Private Collector', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Building a collection with real provenance?', ctaDescription: 'View the current collection or inquire about a specific piece.',
      footerColumns: [{ title: 'Collection', links: [{ label: 'Current Pieces', href: '#' }, { label: 'Sourcing', href: '#' }] }, { title: 'Dealer', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
]

export const websiteBatch3 = specs
