const specs = [
  {
    name: 'Private Wealth Advisory — Executive Site', category: 'Website-Finance', paletteId: 'saas-indigo-light',
    spec: {
      description: 'Marketing site for a boutique investment banking / advisory firm.',
      brand: 'Ashworth Capital Advisors', tagline: 'M&A ADVISORY',
      heroTitle: 'Sell-side advisory for founders who sell the company once.',
      heroDescription: 'M&A, growth capital, and recapitalization advisory for founder-led businesses navigating their first real exit.',
      heroCta: 'Discuss a transaction',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Track Record', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Sell-Side M&A', description: 'Full process management from positioning through close.' },
        { title: 'Growth Capital', description: 'Structured raises for companies scaling past their first round.' },
        { title: 'Recapitalization', description: 'Liquidity events that keep founders in control of what happens next.' },
      ],
      stats: [{ value: 7, label: 'Active Mandates' }, { value: 420, suffix: 'M', label: 'Pipeline Value' }, { value: 3, label: 'Closed YTD' }],
      testimonials: [
        { quote: 'They ran a real process, not a rubber stamp on the first offer.', name: 'Colin Whitford', role: 'Founder, Vantage Materials', rating: 5 },
        { quote: 'The only bank that actually understood our cap table before the first call.', name: 'Sade Adeyemi', role: 'CEO, Ashgrove Insurance', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Considering a transaction?', ctaDescription: 'A confidential first conversation, no engagement required.',
      footerColumns: [{ title: 'Services', links: [{ label: 'M&A', href: '#' }, { label: 'Growth Capital', href: '#' }] }, { title: 'Firm', links: [{ label: 'Track Record', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Boutique Winery — Marketing & Club Site', category: 'Website-Food', paletteId: 'supper-club-dark',
    spec: {
      description: 'Marketing and wine club site for a boutique winery.',
      brand: 'Ferrous Hollow Vineyards', tagline: 'SMALL-LOT WINE',
      heroTitle: 'Wine made in lots too small for a grocery store shelf.',
      heroDescription: 'Estate-grown, small-lot wine — join the club or visit the tasting room in the hills above the valley.',
      heroCta: 'Join the wine club',
      navLinks: [{ label: 'Wines', href: '#' }, { label: 'Visit', href: '#' }, { label: 'Club', href: '#' }],
      features: [
        { title: 'Estate Grown', description: 'Every bottle traced back to the block it was grown on.' },
        { title: 'Small-Lot Production', description: 'Under 200 cases per vintage, most wines sell out before release.' },
        { title: 'Tasting Room', description: 'Reservation-only tastings led by the winemaker, not a script.' },
      ],
      stats: [{ value: 680, label: 'Club Members' }, { value: 12, label: 'Wines in Production' }, { value: 18, suffix: ' yrs', label: 'Estate Founded' }],
      testimonials: [
        { quote: 'The only wine club where I actually look forward to the shipment.', name: 'Kofi Mensah', role: 'Club Member', rating: 5 },
        { quote: 'The tasting room visit alone was worth the drive up.', name: 'Ines Duarte', role: 'Visitor', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Most vintages sell out before release.', ctaDescription: 'Join the club to reserve your allocation before the public release.',
      footerColumns: [{ title: 'Wine', links: [{ label: 'Current Releases', href: '#' }, { label: 'Wine Club', href: '#' }] }, { title: 'Visit', links: [{ label: 'Tasting Room', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Executive Search Firm — Marketing Site', category: 'Website-HRPeople', paletteId: 'saas-indigo-dark',
    spec: {
      description: 'Marketing site for an executive search / recruiting firm.',
      brand: 'Harrowgate Search', tagline: 'EXECUTIVE SEARCH',
      heroTitle: 'Placing executives who outlast the org chart that hired them.',
      heroDescription: 'Retained executive search for companies who have been burned by a contingency recruiter before.',
      heroCta: 'Start a search',
      navLinks: [{ label: 'Practice Areas', href: '#' }, { label: 'Approach', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'C-Suite Search', description: 'CEO, CFO, and CTO placements for companies who need it right the first time.' },
        { title: 'Board Search', description: 'Independent director placements built around actual governance gaps.' },
        { title: 'Confidential Search', description: 'Discreet searches run without a public posting anywhere.' },
      ],
      stats: [{ value: 22, label: 'Active Searches' }, { value: 89, suffix: '%', label: 'Placement Rate' }, { value: 48, suffix: ' days', label: 'Avg. Time to Fill' }],
      testimonials: [
        { quote: 'They found our CFO in six weeks after two other firms failed in six months.', name: 'Renata Silva', role: 'Board Chair', rating: 5 },
        { quote: 'The only search firm that actually understood our culture, not just our comp bands.', name: 'Owen Berg', role: 'CEO', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'The right leader changes everything.', ctaDescription: 'Tell us about the role — we respond to every serious inquiry within 48 hours.',
      footerColumns: [{ title: 'Search', links: [{ label: 'C-Suite', href: '#' }, { label: 'Board', href: '#' }] }, { title: 'Firm', links: [{ label: 'Approach', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Veterinary Specialty Hospital — Marketing Site', category: 'Website-Healthcare', paletteId: 'wellness-teal-dark',
    spec: {
      description: 'Marketing site for a veterinary specialty and referral hospital.',
      brand: 'Alderbrook Veterinary Specialists', tagline: 'REFERRAL VETERINARY CARE',
      heroTitle: 'Specialty veterinary care, coordinated with the vet you already trust.',
      heroDescription: 'Orthopedic surgery, oncology, cardiology, and internal medicine — referral-only, coordinated closely with primary care vets.',
      heroCta: 'Refer a patient',
      navLinks: [{ label: 'Specialties', href: '#' }, { label: 'For Vets', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Orthopedic Surgery', description: 'Advanced surgical care for the cases primary care cannot take on.' },
        { title: 'Oncology', description: 'A full oncology service, from diagnosis through treatment planning.' },
        { title: 'Cardiology', description: 'Advanced cardiac diagnostics and ongoing case management.' },
      ],
      stats: [{ value: 38, label: 'Active Cases' }, { value: 61, label: 'Referrals This Month' }, { value: 97, suffix: '%', label: 'Client Satisfaction' }],
      testimonials: [
        { quote: 'They kept us in the loop on every step of our patient’s care.', name: 'Elin Torvald', role: 'Referring Veterinarian', rating: 5 },
        { quote: 'The coordination between their team and ours was seamless.', name: 'Rafael Solis', role: 'Referring Veterinarian', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Referring a patient?', ctaDescription: 'Submit a referral and our team will coordinate directly with your practice.',
      footerColumns: [{ title: 'Specialties', links: [{ label: 'Surgery', href: '#' }, { label: 'Oncology', href: '#' }, { label: 'Cardiology', href: '#' }] }, { title: 'For Vets', links: [{ label: 'Refer a Patient', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Aviation Charter — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-ember-dark',
    spec: {
      description: 'Marketing site for a private jet charter company.',
      brand: 'Aerolume Jet Charter', tagline: 'PRIVATE AVIATION',
      heroTitle: 'Private aviation, coordinated to the minute.',
      heroDescription: 'On-demand and membership private jet charter — a fleet coordinated by people who answer at 2 AM.',
      heroCta: 'Request a quote',
      navLinks: [{ label: 'Fleet', href: '#' }, { label: 'Membership', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'On-Demand Charter', description: 'Book a flight in hours, not days, across our managed fleet.' },
        { title: 'Membership Program', description: 'Guaranteed availability and locked-in rates for frequent flyers.' },
        { title: 'Empty Leg Alerts', description: 'Repositioning flights at a fraction of standard charter cost.' },
      ],
      stats: [{ value: 46, label: 'Flights per Month' }, { value: 96, suffix: '%', label: 'On-Time Departure' }, { value: 78, suffix: '%', label: 'Fleet Utilization' }],
      testimonials: [
        { quote: 'They rerouted our flight around weather without us even having to ask.', name: 'Grace Whitfield', role: 'Member', rating: 5 },
        { quote: 'The only charter company that has never once let us down on timing.', name: 'Julian Marsh', role: 'Member', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Flying in the next 48 hours?', ctaDescription: 'Request a quote — our team responds within the hour.',
      footerColumns: [{ title: 'Fly', links: [{ label: 'On-Demand', href: '#' }, { label: 'Membership', href: '#' }] }, { title: 'Company', links: [{ label: 'Fleet', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Executive Coaching Firm — Marketing Site', category: 'Website-HRPeople', paletteId: 'cobalt-pop-light',
    spec: {
      description: 'Marketing site for an executive coaching and leadership development firm.',
      brand: 'Ashford Leadership Partners', tagline: 'EXECUTIVE COACHING',
      heroTitle: 'Executive coaching for leaders who already know the theory.',
      heroDescription: 'One-on-one and team coaching for executives navigating a promotion, a transition, or a team that has stopped trusting them.',
      heroCta: 'Book a discovery call',
      navLinks: [{ label: 'Programs', href: '#' }, { label: 'Coaches', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Executive Presence', description: 'Coaching built around how you actually show up in the room.' },
        { title: 'New Leader Transition', description: 'The first 100 days, planned instead of survived.' },
        { title: 'Team Effectiveness', description: 'Coaching for the leader whose team has stopped speaking up.' },
      ],
      stats: [{ value: 28, label: 'Active Clients' }, { value: 93, suffix: '%', label: 'Program Completion' }, { value: 74, label: 'Avg. NPS' }],
      testimonials: [
        { quote: 'My coach called out the pattern I had been avoiding for years.', name: 'Dana Kessler', role: 'VP, Client', rating: 5 },
        { quote: 'The only leadership program that actually changed how my team works with me.', name: 'Marcus Webb', role: 'Director, Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready for a real conversation?', ctaDescription: 'Book a complimentary discovery call with one of our coaches.',
      footerColumns: [{ title: 'Programs', links: [{ label: 'Executive Coaching', href: '#' }, { label: 'Team Coaching', href: '#' }] }, { title: 'Firm', links: [{ label: 'Coaches', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Corporate Event Production — Marketing Site', category: 'Website-Events', paletteId: 'midnight-press-dark',
    spec: {
      description: 'Marketing site for a corporate event production company.',
      brand: 'Bellcourt Productions', tagline: 'EVENT PRODUCTION',
      heroTitle: 'Corporate events produced like the client’s reputation depends on it.',
      heroDescription: 'Summits, product launches, and investor days — produced end to end, from concept through load-out.',
      heroCta: 'Discuss your event',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Capabilities', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Full Production', description: 'Venue, AV, staging, and run-of-show, managed as one team.' },
        { title: 'Creative Direction', description: 'An event concept built around the message, not a template.' },
        { title: 'On-Site Management', description: 'A dedicated producer on-site from load-in to load-out.' },
      ],
      stats: [{ value: 8, label: 'Active Productions' }, { value: 91, suffix: '%', label: 'On-Budget Rate' }, { value: 95, suffix: '%', label: 'Attendee Satisfaction' }],
      testimonials: [
        { quote: 'They ran our investor day like they had thirty years in the room.', name: 'Nina Whitfield', role: 'VP Communications', rating: 5 },
        { quote: 'The only production team that never once made us worry about the run of show.', name: 'James O’Brien', role: 'Marketing Director', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Planning something that has to go right?', ctaDescription: 'Tell us about the event — we take on a limited number of productions per quarter.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Summits', href: '#' }, { label: 'Product Launches', href: '#' }] }, { title: 'Company', links: [{ label: 'Capabilities', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Custom Furniture Workshop — Marketing Site', category: 'Website-Creative', paletteId: 'clay-sand-light',
    spec: {
      description: 'Marketing and commission-inquiry site for a custom furniture workshop.',
      brand: 'Ashgrove Woodworks', tagline: 'CUSTOM FURNITURE',
      heroTitle: 'Furniture commissioned once, used for a lifetime.',
      heroDescription: 'Hand-built dining tables, credenzas, and case goods — one commission at a time, in solid domestic hardwood.',
      heroCta: 'Start a commission',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Custom Commissions', description: 'A piece designed around your space, not a catalog you adapt to.' },
        { title: 'Solid Hardwood', description: 'Domestic walnut, white oak, and cherry — no veneer, no particleboard.' },
        { title: 'Lifetime Craftsmanship', description: 'Joinery built to be repaired, not replaced, decades from now.' },
      ],
      stats: [{ value: 9, label: 'Active Commissions' }, { value: 88, suffix: '%', label: 'On-Time Delivery' }, { value: 15, suffix: ' yrs', label: 'Workshop Founded' }],
      testimonials: [
        { quote: 'The dining table is the first thing every guest asks about.', name: 'Priya Nair', role: 'Client', rating: 5 },
        { quote: 'Worth the eight-week wait, twice over.', name: 'Thomas Girard', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a piece in mind?', ctaDescription: 'Tell us about the commission — we take on a limited number of pieces per season.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Dining Tables', href: '#' }, { label: 'Case Goods', href: '#' }] }, { title: 'Workshop', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Talent & Literary Agency — Marketing Site', category: 'Website-Creative', paletteId: 'paper-oxblood-light',
    spec: {
      description: 'Marketing site for a talent and literary representation agency.',
      brand: 'Harcourt Fenwick Agency', tagline: 'TALENT & LITERARY REPRESENTATION',
      heroTitle: 'Representing the work, not just the contract.',
      heroDescription: 'Literary, speaking, and brand representation for authors and public figures who need an advocate, not a rolodex.',
      heroCta: 'Submit an inquiry',
      navLinks: [{ label: 'Roster', href: '#' }, { label: 'Services', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Literary Representation', description: 'Book deals negotiated by agents who read the manuscript first.' },
        { title: 'Speaking Engagements', description: 'Keynote and event bookings matched to the right stage.' },
        { title: 'Brand Partnerships', description: 'Endorsement deals vetted for fit before they ever reach your inbox.' },
      ],
      stats: [{ value: 42, label: 'Roster Size' }, { value: 16, label: 'Active Deals' }, { value: 11, label: 'Closed YTD' }],
      testimonials: [
        { quote: 'They negotiated a deal I would never have gotten on my own.', name: 'Marguerite Fontaine', role: 'Author, Client', rating: 5 },
        { quote: 'The only agency that reads every page before they pitch it.', name: 'Rem Achebe', role: 'Author, Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Represented by someone who has actually read your work?', ctaDescription: 'Submit an inquiry — we respond to every serious submission.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Literary', href: '#' }, { label: 'Speaking', href: '#' }] }, { title: 'Agency', links: [{ label: 'Roster', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Boutique Fitness Studio — Marketing Site', category: 'Website-Productivity', paletteId: 'track-red-light',
    spec: {
      description: 'Marketing and membership site for a boutique fitness studio.',
      brand: 'Ironclad Performance Studio', tagline: 'SMALL-GROUP TRAINING',
      heroTitle: 'Small-group training, capped at eight, every single class.',
      heroDescription: 'Strength, conditioning, and mobility classes led by coaches who know your name and your last set.',
      heroCta: 'Book your first class',
      navLinks: [{ label: 'Classes', href: '#' }, { label: 'Coaches', href: '#' }, { label: 'Membership', href: '#' }],
      features: [
        { title: 'Small-Group Strength', description: 'Capped at eight athletes so every rep actually gets coached.' },
        { title: 'Conditioning', description: 'Programming built around real strength gains, not just a sweat.' },
        { title: 'Mobility & Recovery', description: 'Dedicated recovery sessions built into every membership.' },
      ],
      stats: [{ value: 380, label: 'Active Members' }, { value: 94, suffix: '%', label: 'Class Capacity' }, { value: 8, label: 'Max Class Size' }],
      testimonials: [
        { quote: 'The first gym where the coach actually corrected my form every single class.', name: 'Marcus Rivera', role: 'Member', rating: 5 },
        { quote: 'Small enough that skipping a class actually gets noticed.', name: 'Aisha Patel', role: 'Member', rating: 5 },
      ],
      pricing: [
        { name: 'Trial Week', price: '$0', description: 'Unlimited classes for 7 days', features: ['All class types', 'No commitment'], cta: 'Start free' },
        { name: 'Unlimited', price: '$220', period: '/month', description: 'Full access, every class', features: ['Unlimited classes', 'Recovery sessions', 'Nutrition guidance'], featured: true, cta: 'Join now' },
        { name: 'Founding Member', price: '$180', period: '/month', description: 'Locked-in rate for early members', features: ['Unlimited classes', 'Priority booking', 'Founding member perks'], cta: 'Join now' },
      ],
      ctaTitle: 'Your first class is free.', ctaDescription: 'No commitment, no pressure — just show up and see if it fits.',
      footerColumns: [{ title: 'Train', links: [{ label: 'Classes', href: '#' }, { label: 'Membership', href: '#' }] }, { title: 'Studio', links: [{ label: 'Coaches', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
]

export const websiteBatch2 = specs
