const specs = [
  {
    name: 'Private Art Conservation Studio — Marketing Site', category: 'Website-Creative', paletteId: 'paper-oxblood-light',
    spec: {
      description: 'Marketing site for a private fine art conservation studio.',
      brand: 'Aldergate Conservation Studio', tagline: 'FINE ART CONSERVATION',
      heroTitle: 'Objects conserved to a standard museums actually trust.',
      heroDescription: 'Painting, textile, sculpture, and works-on-paper conservation for collectors, museums, and estates.',
      heroCta: 'Request a condition assessment',
      navLinks: [{ label: 'Services', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Painting Conservation', description: 'Cleaning, structural repair, and varnish work done reversibly, the way a museum requires.' },
        { title: 'Condition Reporting', description: 'Insurance-grade documentation for every treatment.' },
        { title: 'Museum Loan Prep', description: 'Objects prepared and documented to loan-ready standard.' },
      ],
      stats: [{ value: 11, label: 'Objects in Treatment' }, { value: 14, label: 'Museum Clients' }, { value: '6 wks', label: 'Avg. Treatment Time' }],
      testimonials: [
        { quote: 'The condition report alone was worth the commission.', name: 'Private Collector', role: 'Client', rating: 5 },
        { quote: 'The only studio we trust with loan-bound pieces.', name: 'Museum Registrar', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a piece that needs real conservation?', ctaDescription: 'Request a condition assessment before your next move or loan.',
      footerColumns: [{ title: 'Services', links: [{ label: 'Paintings', href: '#' }, { label: 'Sculpture', href: '#' }] }, { title: 'Studio', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Boutique Perfumery House — Marketing Site', category: 'Website-Creative', paletteId: 'creative-coral-light',
    spec: {
      description: 'Marketing site for a boutique fragrance house.',
      brand: 'Aldercroft Perfumery', tagline: 'BENCH-BLENDED FRAGRANCE',
      heroTitle: 'Fragrance blended on a bench, not mixed in a factory.',
      heroDescription: 'Signature scents, custom commissions, and wholesale collections, formulated and macerated in-house.',
      heroCta: 'Explore the collection',
      navLinks: [{ label: 'Collection', href: '#' }, { label: 'Custom Commission', href: '#' }, { label: 'Wholesale', href: '#' }],
      features: [
        { title: 'Signature Collection', description: 'A permanent line built and refined over a decade of formulation.' },
        { title: 'Custom Commission', description: 'A fragrance built entirely around you, from raw materials up.' },
        { title: 'Wholesale Program', description: 'Boutique retailers supplied with consistent, hand-batched stock.' },
      ],
      stats: [{ value: 9, label: 'Active Batches' }, { value: 18, label: 'Wholesale Accounts' }, { value: 62, label: 'Formulas in Library' }],
      testimonials: [
        { quote: 'My custom scent is genuinely unlike anything on a shelf.', name: 'Client', role: 'Commission Client', rating: 5 },
        { quote: 'Consistent quality, batch after batch — rare at this scale.', name: 'Boutique Buyer', role: 'Wholesale Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Want a fragrance built just for you?', ctaDescription: 'Custom commissions begin with a scent consultation.',
      footerColumns: [{ title: 'Collection', links: [{ label: 'Signature Line', href: '#' }, { label: 'Custom', href: '#' }] }, { title: 'House', links: [{ label: 'Wholesale', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Yacht Refit & Restoration — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-sky-dark',
    spec: {
      description: 'Marketing site for a yacht refit and restoration yard.',
      brand: 'Meridian Refit Yard', tagline: 'YACHT REFIT & RESTORATION',
      heroTitle: 'Refits finished to the standard of the sea trial that follows.',
      heroDescription: 'Full interior refits, engine overhauls, and hull work — every project managed by one team from haul-out to relaunch.',
      heroCta: 'Discuss a refit',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Yard', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Full Interior Refits', description: 'Joinery, upholstery, and systems, rebuilt to your specification.' },
        { title: 'Engine Room Overhauls', description: 'Full mechanical service by certified marine engineers.' },
        { title: 'Hull & Paint', description: 'Fairing and finish work to a show-quality standard.' },
      ],
      stats: [{ value: 5, label: 'Active Refits' }, { value: 84, suffix: '%', label: 'Berth Utilization' }, { value: '5 mo', label: 'Avg. Refit Timeline' }],
      testimonials: [
        { quote: 'The sea trial went perfectly — no punch list at all.', name: 'Yacht Owner', role: 'Client', rating: 5 },
        { quote: 'The most organized refit project I have been part of.', name: 'Captain', role: 'Client Representative', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Planning a refit before next season?', ctaDescription: 'Berths book out early — reach out to reserve your slot.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Refits', href: '#' }, { label: 'Restorations', href: '#' }] }, { title: 'Yard', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Bespoke Millinery House — Marketing Site', category: 'Website-Creative', paletteId: 'clay-sand-light',
    spec: {
      description: 'Marketing site for a bespoke millinery house.',
      brand: 'Aldergate Millinery', tagline: 'HAND-BLOCKED MILLINERY',
      heroTitle: 'Hats blocked by hand for the occasion that actually needs one.',
      heroDescription: 'Custom occasion hats, bridal headpieces, and racing-season commissions, built in a working atelier.',
      heroCta: 'Book a fitting',
      navLinks: [{ label: 'Commissions', href: '#' }, { label: 'Atelier', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Custom Occasion Hats', description: 'Blocked and trimmed for the exact event and outfit.' },
        { title: 'Bridal Headpieces', description: 'Built to match a gown, not adapted from a catalog piece.' },
        { title: 'Racing Season Commissions', description: 'The commissions that make an entrance at the enclosure.' },
      ],
      stats: [{ value: 14, label: 'Active Orders' }, { value: 92, suffix: '%', label: 'Atelier Utilization' }, { value: 58, suffix: '%', label: 'Repeat Client Rate' }],
      testimonials: [
        { quote: 'People still ask where I got my hat, a year later.', name: 'Client', role: 'Client', rating: 5 },
        { quote: 'The fitting process alone is worth the commission.', name: 'Bride', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have an occasion worth a real hat?', ctaDescription: 'Book a fitting — season slots fill quickly.',
      footerColumns: [{ title: 'Commissions', links: [{ label: 'Occasion Hats', href: '#' }, { label: 'Bridal', href: '#' }] }, { title: 'Atelier', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Private Aviation Concierge — Marketing Site', category: 'Website-Logistics', paletteId: 'precision-ember-dark',
    spec: {
      description: 'Marketing site for a private aviation concierge and charter membership.',
      brand: 'Aerolume Concierge', tagline: 'PRIVATE AVIATION, HANDLED',
      heroTitle: 'Every leg coordinated by a team that answers the phone.',
      heroDescription: 'Charter booking, fleet coordination, and full trip concierge for members who fly on their own schedule.',
      heroCta: 'Request membership info',
      navLinks: [{ label: 'Membership', href: '#' }, { label: 'Fleet', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'On-Demand Charter', description: 'A trip booked and confirmed in minutes, not hours.' },
        { title: 'Fleet Coordination', description: 'The right aircraft for the route, every time.' },
        { title: 'Full Trip Concierge', description: 'Ground transport and catering handled without a second call.' },
      ],
      stats: [{ value: 6, label: 'Trips This Week' }, { value: 96, suffix: '%', label: 'On-Time Departure' }, { value: 42, label: 'Active Members' }],
      testimonials: [
        { quote: 'They rebooked our aircraft mid-storm without us even calling.', name: 'Member', role: 'Client', rating: 5 },
        { quote: 'The most responsive concierge team I have used.', name: 'Member', role: 'Client', rating: 5 },
      ],
      pricing: [
        { name: 'On-Demand', price: 'Custom', period: '', description: 'Pay-as-you-fly charter access', features: ['Priority booking', 'Fleet-wide access', '24/7 concierge'], cta: 'Inquire' },
        { name: 'Jet Card', price: '$150k', period: '/year', description: '25 hours of guaranteed availability', features: ['Guaranteed availability', 'Fixed hourly rate', 'Full concierge'], featured: true, cta: 'Inquire' },
        { name: 'Fractional', price: 'Custom', period: '', description: 'Shared ownership of a dedicated aircraft', features: ['Dedicated aircraft', 'Full concierge', 'Priority scheduling'], cta: 'Inquire' },
      ],
      ctaTitle: 'Ready to fly on your own schedule?', ctaDescription: 'Speak with a membership advisor about the right tier for you.',
      footerColumns: [{ title: 'Membership', links: [{ label: 'Jet Card', href: '#' }, { label: 'Fractional', href: '#' }] }, { title: 'Company', links: [{ label: 'Fleet', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Violin Making Workshop — Marketing Site', category: 'Website-Creative', paletteId: 'midnight-press-dark',
    spec: {
      description: 'Marketing site for a fine violin making and lutherie workshop.',
      brand: 'Aldergate Lutherie', tagline: 'HAND-BUILT STRING INSTRUMENTS',
      heroTitle: 'Instruments built by hand for the players who can hear the difference.',
      heroDescription: 'Solo violins, chamber violas, and concert cellos, carved and voiced one at a time in a working workshop.',
      heroCta: 'Join the waitlist',
      navLinks: [{ label: 'Instruments', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Solo Instruments', description: 'Built to project in a concert hall, not just sound good in a room.' },
        { title: 'Chamber Instruments', description: 'Voiced for ensemble balance, not solo projection alone.' },
        { title: 'Restoration & Setup', description: 'Vintage instruments brought back to full voice.' },
      ],
      stats: [{ value: 4, label: 'Active Commissions' }, { value: '11 mo', label: 'Avg. Build Time' }, { value: 8, label: 'Waitlist' }],
      testimonials: [
        { quote: 'The instrument projects like nothing I have played before.', name: 'Concertmaster', role: 'Client', rating: 5 },
        { quote: 'Worth every month of the wait.', name: 'Soloist', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready to commission an instrument?', ctaDescription: 'The waitlist typically runs 8-12 months — inquire early.',
      footerColumns: [{ title: 'Instruments', links: [{ label: 'Violins', href: '#' }, { label: 'Violas & Cellos', href: '#' }] }, { title: 'Workshop', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Luxury Handbag Atelier — Marketing Site', category: 'Website-Creative', paletteId: 'luxury-gold-dark',
    spec: {
      description: 'Marketing site for a luxury handbag and leather goods atelier.',
      brand: 'Aldercroft Leather Atelier', tagline: 'HAND-CUT LEATHER GOODS',
      heroTitle: 'Bags cut and stitched by hand, not stamped from a mold.',
      heroDescription: 'Exotic leather totes, structured commissions, and travel sets, built one piece at a time.',
      heroCta: 'Start a commission',
      navLinks: [{ label: 'Commissions', href: '#' }, { label: 'Atelier', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Exotic Leather Pieces', description: 'Fully documented, CITES-compliant exotic leather commissions.' },
        { title: 'Structured Classics', description: 'Timeless silhouettes built to outlast a trend cycle.' },
        { title: 'Monogram & Travel Sets', description: 'Matched sets built around how you actually travel.' },
      ],
      stats: [{ value: 12, label: 'Active Commissions' }, { value: 24, label: 'Waitlist' }, { value: 71, suffix: '%', label: 'Repeat Client Rate' }],
      testimonials: [
        { quote: 'The craftsmanship is on another level entirely.', name: 'Client', role: 'Client', rating: 5 },
        { quote: 'Worth the wait — nothing compares off a shelf.', name: 'Client', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready to commission a piece?', ctaDescription: 'Commissions typically take 8 weeks from consultation to delivery.',
      footerColumns: [{ title: 'Commissions', links: [{ label: 'Exotic Leather', href: '#' }, { label: 'Classics', href: '#' }] }, { title: 'Atelier', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Whisky Cask Investment Firm — Marketing Site', category: 'Website-Finance', paletteId: 'ledger-ivory-light',
    spec: {
      description: 'Marketing site for a whisky cask investment and portfolio management firm.',
      brand: 'Corbridge Cask Capital', tagline: 'WHISKY CASK INVESTMENT',
      heroTitle: 'Cask investment managed like a real asset class, not a novelty.',
      heroDescription: 'Sourced casks, warehouse-verified valuations, and a bottling strategy built around your investment horizon.',
      heroCta: 'Request a portfolio consultation',
      navLinks: [{ label: 'Portfolio', href: '#' }, { label: 'Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Sourced Casks', description: 'Access to distillery relationships most investors never reach.' },
        { title: 'Warehouse-Verified Valuation', description: 'Every cask independently verified, not marked to a guess.' },
        { title: 'Bottling Strategy', description: 'A clear exit plan, whether you bottle or resell the cask.' },
      ],
      stats: [{ value: 340, label: 'Casks Under Management' }, { value: '4.2M', label: 'Portfolio Value' }, { value: 68, label: 'Active Investors' }],
      testimonials: [
        { quote: 'The transparency on valuation is what won me over.', name: 'Investor', role: 'Client', rating: 5 },
        { quote: 'A genuinely different class of advisor than the typical cask reseller.', name: 'Investor', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Considering cask as an asset class?', ctaDescription: 'Request a portfolio consultation with our investment team.',
      footerColumns: [{ title: 'Portfolio', links: [{ label: 'Sourced Casks', href: '#' }, { label: 'Valuation', href: '#' }] }, { title: 'Firm', links: [{ label: 'Process', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Museum-Grade Taxidermy Studio — Marketing Site', category: 'Website-Creative', paletteId: 'moss-archive-light',
    spec: {
      description: 'Marketing site for a museum-grade taxidermy and natural history studio.',
      brand: 'Fernbrook Naturalist Studio', tagline: 'MUSEUM-GRADE PREPARATION',
      heroTitle: 'Specimens prepared to a standard museums actually commission.',
      heroDescription: 'Diorama pieces, sporting mounts, and private collection work, prepared with full permit compliance.',
      heroCta: 'Discuss a commission',
      navLinks: [{ label: 'Work', href: '#' }, { label: 'Compliance', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Museum Diorama Work', description: 'Full habitat pieces prepared for permanent exhibition.' },
        { title: 'Sporting Mounts', description: 'Trophy work prepared to a natural, lifelike standard.' },
        { title: 'Full Permit Compliance', description: 'Every commission documented to wildlife regulation standard.' },
      ],
      stats: [{ value: 7, label: 'Active Commissions' }, { value: 3, label: 'Museum Contracts' }, { value: 100, suffix: '%', label: 'Permit Compliance' }],
      testimonials: [
        { quote: 'The lifelike quality is what sets this studio apart.', name: 'Museum Curator', role: 'Client', rating: 5 },
        { quote: 'Meticulous about compliance, and it shows in the work.', name: 'Private Collector', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Have a specimen that deserves real preparation?', ctaDescription: 'We take on a limited number of commissions each season.',
      footerColumns: [{ title: 'Work', links: [{ label: 'Diorama Pieces', href: '#' }, { label: 'Mounts', href: '#' }] }, { title: 'Studio', links: [{ label: 'Compliance', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
  {
    name: 'Custom Saddlery & Leatherworks — Marketing Site', category: 'Website-Creative', paletteId: 'clay-sand-light',
    spec: {
      description: 'Marketing site for a custom saddlery and equestrian leatherworks.',
      brand: 'Ashgrove Saddlery', tagline: 'HAND-BUILT SADDLERY',
      heroTitle: 'Saddles fitted to horse and rider, not sized off a rack.',
      heroDescription: 'Custom dressage, jumping, and western saddles, tree-fitted and hand-stitched by working saddlers.',
      heroCta: 'Book a fitting',
      navLinks: [{ label: 'Commissions', href: '#' }, { label: 'Fitting Process', href: '#' }, { label: 'Contact', href: '#' }],
      features: [
        { title: 'Custom Tree Fitting', description: 'A saddle tree fitted to your horse’s actual back, not a standard size.' },
        { title: 'Hand-Stitched Leatherwork', description: 'Full leatherwork done entirely by hand, panel by panel.' },
        { title: 'Tack & Harness Commissions', description: 'Matching tack sets built to the same standard as the saddle.' },
      ],
      stats: [{ value: 8, label: 'Active Commissions' }, { value: 16, label: 'Waitlist' }, { value: 64, suffix: '%', label: 'Repeat Client Rate' }],
      testimonials: [
        { quote: 'My horse moves completely differently in a saddle that actually fits.', name: 'Rider', role: 'Client', rating: 5 },
        { quote: 'Worth every week of the wait — the fit is unmatched.', name: 'Trainer', role: 'Client', rating: 5 },
      ],
      pricing: null,
      ctaTitle: 'Ready for a saddle that actually fits?', ctaDescription: 'Book a fitting — we travel to your stable for the initial measurement.',
      footerColumns: [{ title: 'Commissions', links: [{ label: 'Saddles', href: '#' }, { label: 'Tack Sets', href: '#' }] }, { title: 'Saddlery', links: [{ label: 'About', href: '#' }, { label: 'Contact', href: '#' }] }],
    },
  },
]

export const websiteBatch8 = specs
