import Link from 'next/link';
export default function TermsPage() {
  return (
    <div style={{ minHeight:'100vh', background:'var(--bg-base)', color:'var(--text-primary)', maxWidth:720, margin:'0 auto', padding:'80px 24px' }}>
      <Link href="/" style={{ fontSize:13, color:'var(--text-muted)', textDecoration:'none' }}>← Back</Link>
      <h1 style={{ fontSize:32, fontWeight:700, letterSpacing:'-0.03em', margin:'32px 0 8px' }}>Terms of Service</h1>
      <p style={{ color:'var(--text-muted)', fontSize:13, marginBottom:40 }}>Last updated: May 2025 · Wyber AI · wyberai.com</p>
      {[
        ['Acceptance', 'By using Wyber AI (wyberai.com), you agree to these terms. If you do not agree, do not use the service.'],
        ['What you own', 'All code generated by Wyber AI belongs to you. We claim no ownership over projects you create. Export, modify, sell, or open-source your code freely.'],
        ['What we own', 'The Wyber AI platform, brand, system prompts, and infrastructure are our intellectual property. "Wyber AI" and the Wyber AI logo are trademarks.'],
        ['Acceptable use', 'Do not use Wyber AI to generate malware, phishing pages, spam, illegal content, or anything violating applicable law. Violations result in immediate account termination and may be reported to authorities.'],
        ['Credits and billing', 'Credits are consumed on successful AI generations. Error-fixing mode (Fix Error tab) does not consume credits. Unused monthly credits on paid plans roll over for one billing cycle. Refunds available within 7 days of purchase at hello@wyberai.com.'],
        ['AI-generated content', 'Wyber AI uses Claude Sonnet 4 by Anthropic for code generation. We do not guarantee the accuracy, security, or fitness of AI-generated code. Always review code before deploying to production.'],
        ['Limitation of liability', 'Wyber AI is provided "as is". We are not liable for data loss, security vulnerabilities in generated code, or business losses arising from use of the platform.'],
        ['Contact', 'hello@wyberai.com · wyberai.com'],
      ].map(([title, body]) => (
        <div key={title as string} style={{ marginBottom:32 }}>
          <h2 style={{ fontSize:18, fontWeight:600, margin:'0 0 10px' }}>{title}</h2>
          <p style={{ color:'var(--text-secondary)', lineHeight:1.7, margin:0 }}>{body}</p>
        </div>
      ))}
    </div>
  );
}
