'use client';
import { NavbarClient as Navbar } from '@/components/shared/NavbarClient';
import { Footer } from '@/components/shared/FooterClient';

export default function TermsPage() {
  const SECTIONS = [
    ['Acceptance', 'By using WyberAi, you agree to these terms. If you don\'t agree, don\'t use the service. These terms apply to all users including free and paid accounts.'],
    ['Your account', 'You\'re responsible for your account and everything that happens under it. Use a real email address. Don\'t share your credentials. You must be 18+ to use WyberAi.'],
    ['Your code', 'All code generated by WyberAi belongs to you. You can use it for any purpose — commercial, open source, client work. We claim no ownership over your generated code.'],
    ['Credits & billing', 'Credits are consumed on successful generations. AI error fixes are always free. Unused credits roll over on paid plans. Refunds available within 7 days of purchase — email hello@wyberai.com.'],
    ['Acceptable use', 'Don\'t use WyberAi to generate malware, spam, illegal content, or anything that violates others\' rights. We may suspend accounts that abuse the service.'],
    ['Availability', 'We aim for 99.9% uptime but don\'t guarantee it. We\'re not liable for losses caused by downtime. Check status.wyberai.com for live status.'],
    ['Changes', 'We may update these terms. We\'ll notify you by email if changes are significant. Continued use after changes means acceptance.'],
    ['Contact', 'Questions? hello@wyberai.com · SignalPulse Technologies, Wyoming, USA · © 2026'],
  ];

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', fontFamily: 'var(--font-sans)' }}>
      <Navbar />
      <div style={{ maxWidth: 720, margin: '0 auto', padding: 'clamp(48px,8vw,80px) clamp(16px,4vw,40px)' }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--sky)', letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: 12 }}>Legal</div>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(32px,5vw,48px)', fontWeight: 700, letterSpacing: '-0.025em', color: 'var(--text)', margin: '0 0 8px' }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: 'var(--text3)', marginBottom: 56 }}>Last updated: May 2026 · WyberAi · wyberai.com</p>
        {SECTIONS.map(([title, body]) => (
          <div key={title} style={{ marginBottom: 36, paddingBottom: 36, borderBottom: '1px solid var(--border)' }}>
            <h2 style={{ fontSize: 17, fontWeight: 700, letterSpacing: '-0.03em', color: 'var(--text)', margin: '0 0 10px' }}>{title}</h2>
            <p style={{ fontSize: 14, color: 'var(--text2)', lineHeight: 1.75, margin: 0 }}>{body}</p>
          </div>
        ))}
      </div>
      <Footer />
    </div>
  );
}
