export interface Template {
  id: string;
  name: string;
  description: string;
  category: string;
  framework: string;
  emoji: string;
  prompt: string;
  tags: string[];
}

export const TEMPLATE_GALLERY: Template[] = [
  // SaaS & Business
  { id: 'saas-dashboard', name: 'SaaS Dashboard', description: 'Full admin dashboard with charts, metrics, user table, and sidebar nav', category: 'SaaS', framework: 'react-vite', emoji: '📊', tags: ['dashboard', 'charts', 'admin'], prompt: 'Build a full SaaS admin dashboard with: a sidebar with navigation items (Dashboard, Users, Analytics, Settings, Billing), top stats cards showing MRR, active users, churn rate, NPS, a line chart for revenue over 12 months, a bar chart for user growth, a recent users table with avatar, email, plan, status, and a dark/light mode toggle. Make it look like a premium B2B product.' },
  { id: 'landing-page', name: 'SaaS Landing Page', description: 'Modern landing page with hero, features, pricing, testimonials, FAQ', category: 'Marketing', framework: 'react-vite', emoji: '🚀', tags: ['landing', 'marketing', 'pricing'], prompt: 'Build a complete SaaS landing page with: hero section with headline, subheadline, CTA buttons and a product screenshot mockup, feature grid (6 features with icons), pricing table (3 tiers: Free/Pro/Enterprise), testimonials carousel, FAQ accordion, email waitlist signup form, and sticky navigation. Make it look like a modern YC startup.' },
  { id: 'kanban-board', name: 'Kanban Board', description: 'Drag-and-drop task board with columns, cards, and labels', category: 'Productivity', framework: 'react-vite', emoji: '🗂', tags: ['kanban', 'tasks', 'project management'], prompt: 'Build a Kanban board app with: 4 columns (Backlog, In Progress, Review, Done), draggable task cards with title, description, assignee avatar, priority label (urgent/high/medium/low) and due date, ability to add new cards, column task counts, card color-coding by priority, and a clean header with project name and member avatars.' },
  { id: 'crm', name: 'CRM System', description: 'Contact management with deals pipeline and activity timeline', category: 'SaaS', framework: 'react-vite', emoji: '🤝', tags: ['crm', 'sales', 'contacts'], prompt: 'Build a lightweight CRM with: contacts list with search and filter, contact detail view with name/company/email/phone/stage, deals pipeline with stages (Lead/Qualified/Proposal/Closed), deal cards with value and probability, activity timeline for each contact, and a dashboard with total pipeline value and deals by stage chart.' },
  { id: 'invoice-generator', name: 'Invoice Generator', description: 'Professional invoice builder with PDF export', category: 'Business', framework: 'react-vite', emoji: '🧾', tags: ['invoice', 'billing', 'finance'], prompt: 'Build an invoice generator with: company name and logo upload, client details form, line items table (description, qty, unit price, total), automatic subtotal/tax/total calculation, invoice number and date, due date picker, payment terms, notes section, and a print/PDF button. Style it to look like a real professional invoice.' },
  { id: 'analytics-dashboard', name: 'Analytics Dashboard', description: 'Real-time analytics with multiple chart types and date filtering', category: 'SaaS', framework: 'react-vite', emoji: '📈', tags: ['analytics', 'charts', 'data'], prompt: 'Build an analytics dashboard with: date range picker (7d/30d/90d/custom), key metrics cards (pageviews, sessions, bounce rate, avg session duration), area chart for traffic over time, pie chart for traffic sources, bar chart for top pages, world map for geo data, device breakdown (desktop/mobile/tablet), and a real-time users counter.' },

  // Apps & Tools
  { id: 'todo-app', name: 'Todo App', description: 'Clean task manager with priorities, tags, and filters', category: 'Productivity', framework: 'react-vite', emoji: '✅', tags: ['todo', 'tasks', 'productivity'], prompt: 'Build a polished todo app with: task list with checkboxes, priority levels (high/medium/low) with color coding, tag system with color-coded badges, filter by status/priority/tag, due date with overdue highlighting, task count by status, bulk actions (complete all, delete completed), and smooth animations on add/complete/delete.' },
  { id: 'chat-app', name: 'Chat Interface', description: 'Real-time chat UI with channels, DMs, and message threads', category: 'Communication', framework: 'react-vite', emoji: '💬', tags: ['chat', 'messaging', 'realtime'], prompt: 'Build a Slack-like chat interface with: left sidebar with workspace name, channel list (#general, #random, etc.) and DM list with online indicators, main chat area with message bubbles, timestamps, sender avatars, emoji reactions, message input with formatting toolbar (bold, italic, code, emoji picker button), and an unread message badge on channels.' },
  { id: 'recipe-app', name: 'Recipe App', description: 'Recipe browser with search, filters, and ingredient scaling', category: 'Lifestyle', framework: 'react-vite', emoji: '🍳', tags: ['recipes', 'food', 'cooking'], prompt: 'Build a recipe app with: recipe card grid with photo, name, prep time, difficulty and cuisine tag, search bar, filter by cuisine and diet (vegan/vegetarian/keto/etc.), recipe detail page with ingredients list, step-by-step instructions, serving size adjuster that scales ingredients, nutrition info, and a favorites/save feature.' },
  { id: 'expense-tracker', name: 'Expense Tracker', description: 'Personal finance tracker with categories, budget, and charts', category: 'Finance', framework: 'react-vite', emoji: '💰', tags: ['finance', 'budget', 'expenses'], prompt: 'Build an expense tracker with: add expense form (amount, category, date, note), category breakdown pie chart, monthly spending bar chart, budget vs actual comparison, transaction list with category icons and color coding, monthly summary cards (total spent, top category, vs last month), and spending by category table.' },
  { id: 'portfolio', name: 'Developer Portfolio', description: 'Clean personal portfolio with projects, skills, and contact', category: 'Personal', framework: 'react-vite', emoji: '👨‍💻', tags: ['portfolio', 'personal', 'showcase'], prompt: 'Build a clean developer portfolio with: hero section with name, title, brief bio and social links, skills grid with proficiency indicators, projects section with cards (screenshot mockup, tech stack badges, GitHub and live links), work experience timeline, education section, and contact form. Make it dark-themed and modern.' },

  // E-commerce
  { id: 'product-catalog', name: 'Product Catalog', description: 'E-commerce product listing with cart, filters, and search', category: 'E-commerce', framework: 'react-vite', emoji: '🛍', tags: ['ecommerce', 'shop', 'products'], prompt: 'Build an e-commerce product catalog with: product grid with image, name, price, rating stars and add-to-cart button, search bar, filter sidebar (category, price range, rating, in stock), sort options (price, rating, newest), product detail page with image gallery, description, size/color selector, quantity picker, and a sliding cart drawer with items and checkout total.' },

  // Landing pages (Vue)
  { id: 'vue-landing', name: 'Vue Landing Page', description: 'Animated landing page built with Vue 3', category: 'Marketing', framework: 'vue', emoji: '💚', tags: ['landing', 'vue', 'animated'], prompt: 'Build a modern landing page in Vue 3 with: animated hero with typewriter effect headline, scroll-triggered feature cards that slide in, an interactive pricing toggle (monthly/annual), a testimonial slider, and a gradient CTA section. Use Vue transitions and scroll animations.' },

  // Vanilla JS
  { id: 'vanilla-game', name: 'Browser Game', description: 'A fully playable browser game in vanilla JS', category: 'Fun', framework: 'vanilla', emoji: '🎮', tags: ['game', 'canvas', 'javascript'], prompt: 'Build a snake game in vanilla JavaScript using the HTML5 Canvas API with: smooth snake movement, food that appears randomly, score counter, speed that increases as score goes up, game over screen with final score and restart button, responsive canvas sizing, and keyboard controls. Make the UI look polished with a dark background and neon colors.' },
];

export const CATEGORIES = [...new Set(TEMPLATE_GALLERY.map(t => t.category))];
