export interface Template {
  id: string;
  name: string;
  description: string;
  category: string;
  framework: string;
  emoji: string;
  prompt: string;
  tags: string[];
  complexity?: 'starter' | 'advanced' | 'complex';
}

export const TEMPLATE_GALLERY: Template[] = [

  // ─── SaaS & Business ───
  { id: 'saas-dashboard', name: 'SaaS Admin Dashboard', description: 'Full admin dashboard with charts, metrics, user table, and sidebar nav', category: 'SaaS', framework: 'react-vite', emoji: '📊', complexity: 'advanced', tags: ['dashboard', 'charts', 'admin'], prompt: 'Build a full SaaS admin dashboard with: a sidebar with navigation items (Dashboard, Users, Analytics, Settings, Billing), top stats cards showing MRR, active users, churn rate, NPS, a line chart for revenue over 12 months, a bar chart for user growth, a recent users table with avatar, email, plan, status, and a dark/light mode toggle. Make it look like a premium B2B product.' },
  { id: 'crm', name: 'CRM System', description: 'Contact management with deals pipeline, activity timeline, and email log', category: 'SaaS', framework: 'react-vite', emoji: '🤝', complexity: 'complex', tags: ['crm', 'sales', 'contacts'], prompt: 'Build a full CRM system with: contacts list with search, filter by stage, and sort; contact detail view with name/company/email/phone/LinkedIn; deals pipeline kanban with stages (Lead/Qualified/Proposal/Negotiation/Closed Won/Closed Lost); deal cards with value, probability, and close date; activity timeline showing calls, emails, meetings; a dashboard with total pipeline value, win rate, and deals by stage chart; quick-add contact modal.' },
  { id: 'analytics-dashboard', name: 'Analytics Dashboard', description: 'Real-time analytics with multiple chart types, date filtering, and geo data', category: 'SaaS', framework: 'react-vite', emoji: '📈', complexity: 'advanced', tags: ['analytics', 'charts', 'data'], prompt: 'Build an analytics dashboard with: date range picker (7d/30d/90d/custom), key metrics cards (pageviews, unique visitors, bounce rate, avg session duration with trend arrows), area chart for traffic over time, donut chart for traffic sources (organic/paid/social/direct/referral), horizontal bar chart for top pages, device breakdown (desktop/mobile/tablet) with percentages, a data table with sortable columns, and CSV export button.' },
  { id: 'invoice-generator', name: 'Invoice Generator', description: 'Professional invoice builder with line items, tax, and PDF export', category: 'Business', framework: 'react-vite', emoji: '🧾', complexity: 'advanced', tags: ['invoice', 'billing', 'finance'], prompt: 'Build an invoice generator with: company name, address, and logo fields; client details form; dynamic line items table (add/remove rows, description, qty, unit price, auto-calculated total); automatic subtotal, tax rate selector, discount field, and grand total; invoice number, issue date, due date; payment terms dropdown; notes section; preview mode that shows the final invoice; and a print/PDF button. Style it to look like a real professional invoice with clean typography.' },
  { id: 'project-management', name: 'Project Management', description: 'Full PM tool with kanban, list view, and team assignment', category: 'Productivity', framework: 'react-vite', emoji: '📋', complexity: 'complex', tags: ['project', 'kanban', 'tasks', 'team'], prompt: 'Build a project management tool with: sidebar showing projects list; kanban board view with columns (Backlog, Todo, In Progress, In Review, Done) and drag-and-drop cards; list view toggle showing tasks in a table; task cards with title, assignee avatar, priority badge (urgent/high/medium/low), due date, tags, and subtask count; task detail modal with description, comments, activity log; team member filter; progress bar per column; and a project header with completion percentage.' },
  { id: 'hr-dashboard', name: 'HR Dashboard', description: 'HR management with employee directory, leave tracker, and payroll overview', category: 'Business', framework: 'react-vite', emoji: '👥', complexity: 'complex', tags: ['hr', 'employees', 'payroll'], prompt: 'Build an HR dashboard with: employee directory with search, department filter, and card/list view toggle; employee profile card showing photo placeholder, name, role, department, email, start date, and manager; leave management section with leave requests (pending/approved/rejected), calendar view of team leave, and leave balance by type; payroll overview with monthly payroll total, breakdown by department, and recent payslips table; hiring pipeline with open positions and applicant counts.' },
  { id: 'customer-support', name: 'Support Ticket System', description: 'Help desk with ticket inbox, priority queues, and SLA tracking', category: 'SaaS', framework: 'react-vite', emoji: '🎧', complexity: 'complex', tags: ['support', 'tickets', 'helpdesk'], prompt: 'Build a customer support ticket system with: ticket inbox with list of tickets (subject, customer, priority, status, created date); ticket detail view with full conversation thread, reply box, internal notes tab, and ticket metadata (assignee, priority, tags, SLA timer); filter by status (open/pending/resolved/closed), priority, and assignee; bulk actions (assign, close, tag); response templates picker; SLA indicator showing time remaining; and summary stats (open tickets, avg response time, satisfaction score).' },
  { id: 'subscription-billing', name: 'Subscription Billing', description: 'Billing dashboard with plans, usage meters, invoices, and payment methods', category: 'SaaS', framework: 'react-vite', emoji: '💳', complexity: 'advanced', tags: ['billing', 'subscription', 'payments'], prompt: 'Build a subscription billing dashboard with: current plan display with features list and upgrade CTA; usage meters showing API calls, storage, team seats with progress bars and overage warnings; invoices table with date, amount, status, and download button; payment methods section with card display (last 4 digits, expiry) and add card button; plan comparison modal with 3 tiers; billing history chart showing monthly spend; and a cancel subscription flow with reason picker.' },

  // ─── E-commerce ───
  { id: 'product-catalog', name: 'E-commerce Store', description: 'Full shop with product grid, cart, search, filters, and checkout flow', category: 'E-commerce', framework: 'react-vite', emoji: '🛍', complexity: 'complex', tags: ['ecommerce', 'shop', 'products', 'cart'], prompt: 'Build a complete e-commerce store with: product grid with image placeholder, name, price, rating stars, and add-to-cart button; search bar with instant results; filter sidebar (category, price range slider, rating, color, in stock toggle); sort options (price low/high, rating, newest); product detail page with image gallery, size/color selector, quantity picker, stock indicator, related products, and reviews section; sliding cart drawer with items, quantities, and order summary; and a checkout form with shipping and payment steps.' },
  { id: 'restaurant-ordering', name: 'Restaurant Ordering', description: 'Food ordering app with menu, cart, dietary filters, and order tracking', category: 'E-commerce', framework: 'react-vite', emoji: '🍕', complexity: 'advanced', tags: ['food', 'restaurant', 'ordering'], prompt: 'Build a restaurant ordering app with: menu categories sidebar (Starters, Mains, Desserts, Drinks); menu item cards with photo placeholder, name, description, price, and add button; dietary filter badges (vegan, gluten-free, spicy, popular); item customization modal (size, extras, special instructions); cart sidebar with items, quantities, subtotal, delivery fee, and total; order type toggle (delivery/pickup); promo code field; and an order confirmation screen with estimated delivery time and order tracking steps.' },
  { id: 'inventory-management', name: 'Inventory Management', description: 'Stock management with SKU tracking, low stock alerts, and supplier management', category: 'Business', framework: 'react-vite', emoji: '📦', complexity: 'complex', tags: ['inventory', 'stock', 'warehouse'], prompt: 'Build an inventory management system with: products table with SKU, name, category, stock level, reorder point, unit cost, and total value; low stock alert banner; stock level color coding (red=critical, amber=low, green=ok); add/edit product modal; stock adjustment form (receive stock, manual adjustment, write-off with reason); supplier list with contact details; purchase orders table; search and filter by category/stock status; and summary cards (total SKUs, total value, low stock count, out of stock count).' },

  // ─── Productivity ───
  { id: 'kanban-board', name: 'Kanban Board', description: 'Drag-and-drop task board with swimlanes, labels, and filters', category: 'Productivity', framework: 'react-vite', emoji: '🗂', complexity: 'advanced', tags: ['kanban', 'tasks', 'project management'], prompt: 'Build a Kanban board with: 5 columns (Backlog, Todo, In Progress, In Review, Done) with task counts; draggable task cards with title, assignee avatar, priority label (urgent/high/medium/low), due date with overdue highlighting, and tag badges; add card button per column; card detail modal with description editor, checklist, comments, due date picker, assignee selector, and label picker; column WIP limits with visual warning; filter by assignee, label, due date; and a board header with member avatars and search.' },
  { id: 'note-taking', name: 'Note Taking App', description: 'Notion-like notes with rich text, folders, tags, and search', category: 'Productivity', framework: 'react-vite', emoji: '📝', complexity: 'advanced', tags: ['notes', 'writing', 'knowledge'], prompt: 'Build a Notion-like note taking app with: left sidebar with workspace name, folder tree, starred notes, and recent notes; main editor area with rich text formatting toolbar (heading 1/2/3, bold, italic, code, bullet list, numbered list, quote, divider); note title as large heading; tags input at the top; note metadata showing created/modified date; search bar that searches across all notes; trash/archive; and a clean empty state with quick action cards.' },
  { id: 'habit-tracker', name: 'Habit Tracker', description: 'Daily habit tracking with streaks, progress rings, and weekly calendar view', category: 'Productivity', framework: 'react-vite', emoji: '🎯', complexity: 'starter', tags: ['habits', 'tracking', 'wellness'], prompt: 'Build a habit tracker app with: habit list with circular progress rings showing completion percentage; daily check-in for each habit (tap to complete); streak counter with fire emoji and current/best streak; weekly calendar grid showing completion history (colored dots); add habit modal with name, color, icon, frequency (daily/weekdays/custom days), and reminder time; habit categories (health, learning, mindfulness, fitness); overall completion rate for today; and a motivational message based on performance.' },
  { id: 'time-tracker', name: 'Time Tracker', description: 'Work time tracker with projects, timers, reports, and billing rates', category: 'Productivity', framework: 'react-vite', emoji: '⏱', complexity: 'advanced', tags: ['time', 'tracking', 'billing', 'freelance'], prompt: 'Build a time tracking app with: active timer with start/stop/pause and project selector; today\'s time entries list with project, description, duration, and billable toggle; project list with color coding, client name, hourly rate, and total hours logged; weekly timesheet grid view; reports section with charts for time by project (pie chart) and daily hours (bar chart); date range filter; and a summary showing total hours, billable hours, and estimated earnings.' },
  { id: 'todo-app', name: 'Smart Todo App', description: 'Task manager with priorities, subtasks, tags, due dates, and smart filters', category: 'Productivity', framework: 'react-vite', emoji: '✅', complexity: 'starter', tags: ['todo', 'tasks', 'productivity'], prompt: 'Build a polished todo app with: task list with checkboxes and smooth completion animation; priority levels (urgent/high/medium/low) with color coding; subtasks that expand under parent tasks; tag system with color-coded badges; due date with overdue highlighting in red; smart lists (Today, Upcoming, No Date, Completed); filter and sort bar; quick add task; task count per list; bulk actions; and a progress bar showing daily completion.' },

  // ─── Finance ───
  { id: 'expense-tracker', name: 'Personal Finance', description: 'Expense tracker with budgets, categories, trends, and net worth tracker', category: 'Finance', framework: 'react-vite', emoji: '💰', complexity: 'advanced', tags: ['finance', 'budget', 'expenses', 'money'], prompt: 'Build a personal finance app with: monthly overview cards (income, expenses, savings rate, net balance); add transaction form (amount, category, date, note, type income/expense); transaction list with category icons, color coding, and search; budget section with category budgets, progress bars, and overage alerts; spending by category donut chart; monthly spending trend line chart; accounts section (checking, savings, credit card) with balances; and a net worth tracker showing assets minus liabilities over time.' },
  { id: 'crypto-dashboard', name: 'Crypto Portfolio', description: 'Crypto portfolio tracker with price charts, P&L, and allocation view', category: 'Finance', framework: 'react-vite', emoji: '₿', complexity: 'advanced', tags: ['crypto', 'portfolio', 'finance', 'trading'], prompt: 'Build a crypto portfolio dashboard with: portfolio total value with 24h change (green/red); holdings table with coin name/symbol, amount, avg buy price, current price, P&L amount and percentage, and allocation percentage; allocation pie chart; price chart for selected coin (1D/1W/1M/1Y range buttons); add holding modal with coin selector, amount, and purchase price; watchlist sidebar with favorite coins and prices; and market summary cards (BTC dominance, total market cap, fear & greed index).' },

  // ─── Communication ───
  { id: 'chat-app', name: 'Team Chat', description: 'Slack-like chat with channels, DMs, threads, reactions, and file sharing', category: 'Communication', framework: 'react-vite', emoji: '💬', complexity: 'complex', tags: ['chat', 'messaging', 'realtime', 'team'], prompt: 'Build a Slack-like team chat interface with: left sidebar with workspace name, channels section (#general, #random, #dev) with unread badges, DMs section with online status indicators; main chat area with message bubbles showing avatar, username, timestamp, and content; emoji reactions on hover; threaded replies count; message input with formatting toolbar (bold, italic, code block, emoji picker button, send button); channel header with topic and member count; user online/offline indicator; and a right panel for thread view.' },
  { id: 'email-client', name: 'Email Client', description: 'Gmail-like email client with inbox, compose, labels, and search', category: 'Communication', framework: 'react-vite', emoji: '📧', complexity: 'complex', tags: ['email', 'inbox', 'communication'], prompt: 'Build a Gmail-like email client with: left sidebar with compose button, folder list (Inbox with unread count, Sent, Drafts, Starred, Spam, Trash), and labels section; email list showing sender avatar, name, subject preview, date, and star/read status; email detail view with full message, reply/forward/delete actions; compose modal with To/CC/BCC/Subject fields, rich text editor, and send button; search bar with filter chips; select all and bulk actions (delete, mark read, label); and empty states for each folder.' },

  // ─── Health & Lifestyle ───
  { id: 'fitness-tracker', name: 'Fitness Tracker', description: 'Workout logger with exercise library, progress charts, and body metrics', category: 'Health', framework: 'react-vite', emoji: '💪', complexity: 'advanced', tags: ['fitness', 'workout', 'health', 'gym'], prompt: 'Build a fitness tracker app with: workout log showing recent workouts with date, name, duration, and exercises completed; start workout flow with exercise selector from a library categorized by muscle group, sets/reps/weight input per exercise, and rest timer; progress charts for key lifts (bench press, squat, deadlift) showing weight over time; body metrics tracker (weight, body fat%) with trend chart; workout streak and weekly goal progress; personal records board; and a workout plan section with predefined programs.' },
  { id: 'recipe-app', name: 'Recipe App', description: 'Recipe browser with search, dietary filters, ingredient scaling, and meal planner', category: 'Health', framework: 'react-vite', emoji: '🍳', complexity: 'advanced', tags: ['recipes', 'food', 'cooking', 'meal planning'], prompt: 'Build a recipe app with: recipe card grid with photo placeholder, name, prep time, difficulty stars, and cuisine tag; search bar; filter by cuisine and diet (vegan/vegetarian/gluten-free/keto); recipe detail page with serving adjuster that scales all ingredients proportionally, ingredient list with checkboxes, step-by-step instructions, nutrition facts table, and save button; favorites collection; weekly meal planner grid; and a shopping list that aggregates ingredients from planned meals.' },

  // ─── Developer Tools ───
  { id: 'api-explorer', name: 'API Explorer', description: 'Postman-like REST client with collections, history, and response viewer', category: 'Dev Tools', framework: 'react-vite', emoji: '🔌', complexity: 'complex', tags: ['api', 'rest', 'developer', 'testing'], prompt: 'Build a Postman-like API explorer with: left sidebar with collections (grouped requests) and history; request panel with method selector (GET/POST/PUT/PATCH/DELETE with color coding), URL input, and send button; tabs for Params (key-value table), Headers (key-value table), Body (JSON editor), and Auth (Bearer token, Basic auth); response panel with status code badge (color coded), response time, body with pretty JSON viewer, headers tab; environment variables selector; and save request to collection button.' },
  { id: 'code-snippet-manager', name: 'Code Snippet Manager', description: 'Snippet library with syntax highlighting, tags, search, and copy button', category: 'Dev Tools', framework: 'react-vite', emoji: '🗂', complexity: 'starter', tags: ['code', 'snippets', 'developer'], prompt: 'Build a code snippet manager with: snippet list in left sidebar showing name, language badge, and tags; main view with snippet title, description, language selector, and code block with syntax highlighting; copy to clipboard button with success animation; tag system with color-coded badges; search that searches title, description, and code; filter by language; add/edit snippet modal; favorites; and keyboard shortcut hint to copy.' },
  { id: 'json-formatter', name: 'JSON Formatter', description: 'JSON tool with format, minify, validate, diff, and tree view', category: 'Dev Tools', framework: 'react-vite', emoji: '{}', complexity: 'starter', tags: ['json', 'formatter', 'developer', 'tool'], prompt: 'Build a JSON formatter tool with: large textarea for JSON input; action buttons (Format/Prettify, Minify, Validate, Copy); error message display with line number for invalid JSON; formatted output with syntax highlighting (strings in green, numbers in blue, booleans in orange, null in red); collapsible tree view of the JSON structure; JSON path display when clicking a value; character/line count; and a split view with input on left, formatted output on right.' },

  // ─── Landing Pages ───
  { id: 'landing-page', name: 'SaaS Landing Page', description: 'Modern landing page with hero, features, pricing, testimonials, and FAQ', category: 'Marketing', framework: 'react-vite', emoji: '🚀', complexity: 'advanced', tags: ['landing', 'marketing', 'pricing'], prompt: 'Build a complete SaaS landing page with: sticky nav with logo, links, and CTA button; hero section with bold headline, subheadline, CTA buttons, email capture, and product mockup placeholder; social proof logos bar; feature section with alternating image/text rows (3 features); feature grid (6 icons with heading and description); pricing table with monthly/annual toggle (3 tiers: Free/Pro/Enterprise) with feature comparison; testimonials with avatar, name, role, company, and star rating; FAQ accordion; and a full-width CTA section.' },
  { id: 'portfolio', name: 'Developer Portfolio', description: 'Personal portfolio with projects, skills, timeline, and contact', category: 'Personal', framework: 'react-vite', emoji: '👨‍💻', complexity: 'starter', tags: ['portfolio', 'personal', 'showcase'], prompt: 'Build a clean developer portfolio with: sticky nav with name/logo and anchor links; hero section with large name, animated title typewriter (Frontend Developer / React Expert / etc.), brief bio, download resume button, and social links (GitHub, LinkedIn, Twitter); skills section with categorized tags (Languages, Frameworks, Tools) with proficiency indicators; projects grid with name, description, tech stack badges, and GitHub/live links; work experience timeline with company, role, dates, and bullet points; education section; and a contact form.' },
  { id: 'vue-landing', name: 'Vue Landing Page', description: 'Animated landing page built with Vue 3 and scroll animations', category: 'Marketing', framework: 'vue', emoji: '💚', complexity: 'advanced', tags: ['landing', 'vue', 'animated'], prompt: 'Build a modern landing page in Vue 3 with: animated hero section with typewriter effect on the headline, floating gradient orbs, and a CTA button with shimmer effect; scroll-triggered feature cards that slide in from left/right alternating; an interactive pricing toggle (monthly/annual) that animates price changes; a testimonial carousel/slider; statistics counter section that counts up when in view; a gradient CTA section at the bottom; and smooth page transitions. Use Vue 3 Composition API and CSS transitions throughout.' },

  // ─── Real Estate & Booking ───
  { id: 'property-listing', name: 'Property Listings', description: 'Real estate app with map view, filters, property detail, and mortgage calculator', category: 'Real Estate', framework: 'react-vite', emoji: '🏠', complexity: 'complex', tags: ['real estate', 'listings', 'property'], prompt: 'Build a real estate property listing app with: split view (list on left, map placeholder on right) with toggle button; property cards showing photo placeholder, price, beds/baths/sqft, address, and favorite heart icon; filter panel (price range slider, beds/baths, property type checkboxes, min sqft); sort options (price, newest, sqft); property detail page with image gallery placeholder, full details, agent contact card, schedule tour button, neighborhood info, and a mortgage calculator (price, down payment, interest rate, term with monthly payment output).' },
  { id: 'booking-system', name: 'Appointment Booking', description: 'Booking platform with calendar, service selection, provider picker, and confirmations', category: 'Business', framework: 'react-vite', emoji: '📅', complexity: 'advanced', tags: ['booking', 'appointments', 'calendar', 'scheduling'], prompt: 'Build an appointment booking system with: service catalog page with service cards (name, duration, price, description); provider selection step showing available staff with photo placeholder, name, rating, and bio; calendar view showing available dates; time slot grid for selected date; booking form (name, email, phone, notes); confirmation screen with booking summary and add-to-calendar button; admin view showing appointments table with date, client, service, provider, status; and appointment status management (confirm, reschedule, cancel).' },

  // ─── Games & Fun ───
  { id: 'vanilla-game', name: 'Snake Game', description: 'Fully playable snake game with levels, high scores, and power-ups', category: 'Games', framework: 'vanilla', emoji: '🎮', complexity: 'starter', tags: ['game', 'canvas', 'javascript'], prompt: 'Build a polished snake game in vanilla JavaScript with HTML5 Canvas with: smooth snake movement with WASD and arrow key controls; food that appears randomly with bonus food items that disappear after 5 seconds; score counter and high score saved to localStorage; speed that increases every 5 points; level display; game over screen with final score, high score, and restart button; pause on spacebar; a power-up food (blue) that temporarily slows the snake; and a dark neon aesthetic with glowing snake and grid.' },
  { id: 'quiz-app', name: 'Quiz App', description: 'Interactive quiz with categories, timer, scoring, and leaderboard', category: 'Games', framework: 'react-vite', emoji: '🧠', complexity: 'starter', tags: ['quiz', 'trivia', 'game'], prompt: 'Build a quiz app with: home screen with category selector (Science, History, Sports, Technology, Movies) and difficulty picker (Easy/Medium/Hard); quiz screen with progress bar, question number, countdown timer (30 seconds per question), multiple choice options that highlight green/red on selection, and score counter; animated correct/incorrect feedback; results screen with score percentage, time taken, correct/incorrect breakdown, and share button; a leaderboard showing top 10 scores from localStorage; and smooth transitions between screens.' },
];

export const CATEGORIES = [...new Set(TEMPLATE_GALLERY.map(t => t.category))];