-- 100 AI Employee Templates seed
-- Departments: Sales(15) Marketing(12) Support(10) Operations(10) Finance(8) HR(8) Engineering(8) Data(8) Research(6) Legal(5) Executive(5) Admin(5)

insert into public.employee_templates (slug, name, emoji, role, department, tagline, description, default_instructions, default_tools, kpis, popular) values

-- ── SALES (15) ────────────────────────────────────────────────────────────────
('ai-sdr', 'AI SDR', '🎯', 'Sales Development Representative', 'Sales',
 'Qualifies inbound leads and drafts personalized outreach automatically.',
 'Monitors your inbox and CRM for new inbound leads, scores them based on your ICP, drafts personalized outreach emails, and logs all activity to your CRM.',
 'Check Gmail for new inbound leads who mention pricing, demo, or interest. Score each lead 1-10 based on company size and relevance to our ICP. Draft a personalized outreach email for each scored lead and log their details to HubSpot with tag "inbound-sdr". Report: leads found, emails drafted, average score.',
 ARRAY['GMAIL','HUBSPOT','LINKEDIN'],
 '[{"name":"Leads Qualified","description":"Number of leads scored and qualified","unit":"leads","target":20},{"name":"Emails Drafted","description":"Personalized outreach emails created","unit":"emails","target":20},{"name":"Avg Lead Score","description":"Average quality score of qualified leads","unit":"score","target":7}]',
 true),

('ai-follow-up-rep', 'AI Follow-up Rep', '🔁', 'Sales Follow-up Specialist', 'Sales',
 'Chases stale deals so nothing slips through the pipeline.',
 'Scans your CRM for deals that have gone quiet, identifies the right moment to re-engage, and drafts timely follow-up emails that feel human.',
 'Check HubSpot for deals with no activity in 5+ days that are still open. For each stale deal, draft a natural follow-up email referencing the last conversation point. Send via Gmail and log the touchpoint in HubSpot. Report: deals touched, replies received.',
 ARRAY['GMAIL','HUBSPOT','SLACK'],
 '[{"name":"Stale Deals Touched","description":"Deals re-engaged after going cold","unit":"deals","target":10},{"name":"Reply Rate","description":"Percentage of follow-ups that received replies","unit":"%","target":25}]',
 true),

('ai-proposal-writer', 'AI Proposal Writer', '📄', 'Proposal Automation Specialist', 'Sales',
 'Drafts tailored sales proposals from a deal brief in minutes.',
 'Takes deal context from your CRM, pulls relevant case studies and pricing from your knowledge base, and assembles a polished proposal document ready for review.',
 'When a HubSpot deal moves to "Proposal" stage, pull the deal details. Draft a complete proposal in Google Docs using our standard template. Include: executive summary, problem statement, proposed solution, timeline, pricing, and 2 relevant case studies. Notify via Slack when ready.',
 ARRAY['HUBSPOT','GOOGLEDOCS','SLACK'],
 '[{"name":"Proposals Created","description":"Number of proposals drafted","unit":"proposals","target":8},{"name":"Time to Draft","description":"Average minutes from trigger to draft","unit":"minutes","target":15}]',
 false),

('ai-demo-scheduler', 'AI Demo Scheduler', '📅', 'Demo Booking Specialist', 'Sales',
 'Books demos with qualified leads without back-and-forth emails.',
 'Responds to inbound demo requests, checks calendar availability, proposes times, and creates calendar events with video links automatically.',
 'Monitor Gmail for demo requests. Check Google Calendar for available slots in the next 5 business days (Mon-Fri, 9am-5pm EST). Reply with 3 available times and a Calendly-style confirmation. Create the calendar event with a Zoom link once confirmed. Log in HubSpot.',
 ARRAY['GMAIL','GOOGLECALENDAR','HUBSPOT'],
 '[{"name":"Demos Scheduled","description":"Demo calls successfully booked","unit":"demos","target":15},{"name":"Response Time","description":"Average hours to respond to demo request","unit":"hours","target":2}]',
 true),

('ai-deal-analyst', 'AI Deal Analyst', '📊', 'Pipeline Intelligence Analyst', 'Sales',
 'Delivers a weekly pipeline health report so your team never misses a signal.',
 'Analyzes your full pipeline every week, flags at-risk deals, spots trends, and delivers a crisp executive summary to the sales team.',
 'Pull all open deals from HubSpot. Identify deals at risk (no activity 7+ days, close date passed, stage stagnant 14+ days). Identify top 3 deals most likely to close this week. Write a pipeline health summary and post to Slack #sales channel. Include: total pipeline value, at-risk deals, momentum deals, recommended actions.',
 ARRAY['HUBSPOT','SLACK','GOOGLEDOCS'],
 '[{"name":"At-Risk Deals Flagged","description":"Deals identified as at-risk","unit":"deals","target":5},{"name":"Pipeline Accuracy","description":"Forecast accuracy vs actual closes","unit":"%","target":80}]',
 false),

('ai-competitive-intel', 'AI Competitive Intel Agent', '🕵️', 'Competitive Intelligence Specialist', 'Sales',
 'Monitors competitors and briefs the sales team before every battle.',
 'Tracks competitor news, pricing changes, and product launches. Delivers battle cards and win/loss context to reps before key meetings.',
 'Search the web for news about our top 5 competitors in the last 7 days. Check for pricing changes, product launches, or leadership changes. Update the competitive battle cards in Notion. Post a weekly competitive digest to Slack #sales-intel. Flag any urgent changes.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Competitor Updates Tracked","description":"Significant competitor changes identified","unit":"updates","target":10},{"name":"Battle Cards Updated","description":"Competitive battle cards refreshed","unit":"cards","target":5}]',
 false),

('ai-sales-coach', 'AI Sales Coach', '🏆', 'Sales Coaching & Enablement Specialist', 'Sales',
 'Reviews call notes and gives reps actionable coaching feedback.',
 'Analyzes call notes and CRM activity to identify coaching opportunities, share best practices, and recognize top performers.',
 'Review all HubSpot call logs from the past week. Identify common objections, successful talk tracks, and areas where deals stalled. Write a coaching digest with: top 3 objection responses that worked, 3 areas to improve, one rep shoutout. Post to Slack #sales-coaching.',
 ARRAY['HUBSPOT','SLACK','NOTION'],
 '[{"name":"Reps Coached","description":"Sales reps who received personalized feedback","unit":"reps","target":5},{"name":"Objections Catalogued","description":"New objection patterns identified","unit":"patterns","target":10}]',
 false),

('ai-contract-tracker', 'AI Contract Tracker', '📋', 'Contract & Renewal Tracker', 'Sales',
 'Never miss a renewal or contract expiry again.',
 'Monitors contract expiry dates, sends renewal alerts, and prepares renewal summaries 60, 30, and 7 days before expiry.',
 'Check HubSpot for contracts expiring in the next 60 days. Group by: 60-day warning, 30-day warning, 7-day urgent. Draft a renewal email for each account and notify the account owner in Slack. Log all actions in HubSpot with tag "renewal-pipeline".',
 ARRAY['HUBSPOT','GMAIL','SLACK'],
 '[{"name":"Renewals Flagged","description":"Contracts flagged before expiry","unit":"contracts","target":100},{"name":"Renewal Emails Sent","description":"Automated renewal outreach sent","unit":"emails","target":20}]',
 false),

('ai-lead-enricher', 'AI Lead Enricher', '🔍', 'Lead Data Enrichment Specialist', 'Sales',
 'Fills in the blanks on every new lead so reps always have context.',
 'Takes raw lead data (name + email) and enriches it with company info, LinkedIn details, tech stack, and firmographics before reps make contact.',
 'Check HubSpot for new contacts added in the last 24 hours with incomplete profiles. For each, search for their LinkedIn profile, company size, industry, and tech stack. Update the HubSpot contact record with enriched data and set a "Enriched" tag. Report: contacts enriched, fields filled.',
 ARRAY['HUBSPOT','LINKEDIN'],
 '[{"name":"Leads Enriched","description":"Contacts enriched with full profile data","unit":"leads","target":25},{"name":"Fields Filled","description":"Average data fields added per lead","unit":"fields","target":8}]',
 false),

('ai-referral-manager', 'AI Referral Manager', '🤝', 'Referral Program Manager', 'Sales',
 'Tracks referrals, sends thank-you notes, and keeps referrers engaged.',
 'Monitors the referral pipeline, sends timely thank-you messages, updates referrers on deal progress, and manages reward fulfilment.',
 'Check HubSpot for deals tagged "referral". For newly closed referral deals, draft a personal thank-you email to the referrer. For in-progress referral deals, send a weekly update to the referrer. Log all communications. Report: active referrals, closed referral revenue, thank-yous sent.',
 ARRAY['HUBSPOT','GMAIL'],
 '[{"name":"Referral Revenue Tracked","description":"Revenue attributed to referral program","unit":"$","target":10000},{"name":"Referrer Engagement","description":"Thank-you and update emails sent","unit":"emails","target":20}]',
 false),

('ai-outbound-prospector', 'AI Outbound Prospector', '🎣', 'Outbound Prospecting Specialist', 'Sales',
 'Finds ideal prospects and builds personalized sequences daily.',
 'Researches your ICP, finds matching companies and contacts on LinkedIn, builds personalized outreach sequences, and queues them for rep approval.',
 'Search LinkedIn for companies matching our ICP: [company size, industry, keywords]. Find the right contact (role: VP/Director/Head of [department]). Draft a 3-touch personalized sequence for each: (1) connection + brief, (2) value proposition, (3) case study. Add to HubSpot sequences. Report: prospects found, sequences built.',
 ARRAY['LINKEDIN','HUBSPOT','GMAIL'],
 '[{"name":"Prospects Found","description":"New qualified prospects identified","unit":"prospects","target":30},{"name":"Sequences Built","description":"Personalized outreach sequences created","unit":"sequences","target":30}]',
 true),

('ai-win-loss-analyst', 'AI Win/Loss Analyst', '⚖️', 'Win/Loss Intelligence Analyst', 'Sales',
 'Learns why you win and lose so the team can do more of what works.',
 'Analyzes closed won and lost deals each month to find patterns, summarize common decision factors, and recommend strategy adjustments.',
 'Pull all deals closed in the last 30 days from HubSpot, split by won/lost. Analyze: common competitor mentions, deal size, sales cycle length, industry. Write a win/loss report with top 3 win factors and top 3 loss factors. Post in Notion and summarize in Slack.',
 ARRAY['HUBSPOT','NOTION','SLACK'],
 '[{"name":"Win Rate","description":"Percentage of deals won","unit":"%","target":30},{"name":"Avg Deal Cycle","description":"Average days from opportunity to close","unit":"days","target":45}]',
 false),

('ai-account-health', 'AI Account Health Monitor', '❤️', 'Account Health Specialist', 'Sales',
 'Monitors customer health scores and alerts the team before churn happens.',
 'Checks product usage, support ticket trends, NPS scores, and engagement signals to generate account health scores and churn risk alerts.',
 'Pull account data from HubSpot. Score each account on: last login date, support tickets opened, contract renewal date, NPS if available. Flag accounts with health score below 40 as "at-risk". Draft a check-in email for each at-risk account. Alert account owners in Slack.',
 ARRAY['HUBSPOT','SLACK','GMAIL'],
 '[{"name":"At-Risk Accounts Flagged","description":"Accounts identified as churn risk","unit":"accounts","target":5},{"name":"Check-ins Sent","description":"Proactive check-in emails sent","unit":"emails","target":10}]',
 false),

('ai-upsell-agent', 'AI Upsell Agent', '📈', 'Expansion Revenue Specialist', 'Sales',
 'Identifies upsell opportunities in the existing customer base automatically.',
 'Scans existing accounts for expansion signals — high usage, new team members, feature requests — and surfaces the right upsell pitch at the right time.',
 'Check HubSpot for customers on the base plan who have been active for 90+ days. Look for signals: high usage, multiple users, feature requests logged. For each upsell candidate, draft a tailored upgrade email referencing their specific usage. Notify account owner in Slack. Report: opportunities found, emails drafted.',
 ARRAY['HUBSPOT','GMAIL','SLACK'],
 '[{"name":"Upsell Opportunities Found","description":"Expansion candidates identified","unit":"accounts","target":10},{"name":"Expansion Revenue Closed","description":"Revenue from upsell campaigns","unit":"$","target":5000}]',
 false),

('ai-sales-recap', 'AI Sales Recap Agent', '📰', 'Sales Intelligence Briefing Specialist', 'Sales',
 'Delivers a daily sales briefing to the team every morning at 8am.',
 'Compiles yesterday''s wins, today''s demos, pipeline movements, and key tasks into a crisp morning briefing posted to Slack.',
 'Pull HubSpot data for the last 24 hours. Compile: deals moved forward, demos today, new leads, stale deals. Write a concise morning briefing (under 300 words). Post to Slack #sales at 8am. Include: 🏆 Yesterday''s wins, 📅 Today''s demos, ⚠️ Needs attention, 🎯 Team focus.',
 ARRAY['HUBSPOT','SLACK'],
 '[{"name":"Briefings Delivered","description":"Morning briefings sent on time","unit":"briefings","target":20},{"name":"Team Engagement","description":"Briefing reactions and replies","unit":"reactions","target":15}]',
 false),

-- ── MARKETING (12) ────────────────────────────────────────────────────────────
('ai-content-writer', 'AI Content Writer', '✍️', 'Content Marketing Specialist', 'Marketing',
 'Drafts blog posts, social content, and newsletters on a schedule.',
 'Generates SEO-optimized blog posts, social media content, and email newsletters based on your brand voice and content calendar.',
 'Check the Notion content calendar for this week''s scheduled posts. For each item, draft the full piece: blog post (800-1200 words, SEO optimized), LinkedIn post (3 paragraphs), Twitter/X thread (5 tweets). Save drafts to Notion for review. Report: pieces drafted, keywords targeted.',
 ARRAY['NOTION','GOOGLEDOCS','SLACK'],
 '[{"name":"Content Pieces Drafted","description":"Blog posts, social posts, newsletters created","unit":"pieces","target":5},{"name":"Words Written","description":"Total words of content produced","unit":"words","target":5000}]',
 true),

('ai-seo-analyst', 'AI SEO Analyst', '🔎', 'SEO Intelligence Specialist', 'Marketing',
 'Monitors rankings, finds keyword opportunities, and reports weekly.',
 'Tracks your keyword rankings, analyzes competitor content, identifies content gaps, and delivers actionable SEO recommendations every week.',
 'Analyze the top 20 target keywords and their current ranking positions. Find 10 new keyword opportunities based on competitor content gaps. Identify 3 underperforming pages that need optimization. Write a weekly SEO report with priority actions. Save to Notion and post summary to Slack #marketing.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Keywords Tracked","description":"Target keywords monitored","unit":"keywords","target":20},{"name":"New Opportunities Found","description":"New keyword gaps identified","unit":"keywords","target":10}]',
 false),

('ai-social-media-manager', 'AI Social Media Manager', '📱', 'Social Media Content Specialist', 'Marketing',
 'Manages your social presence across LinkedIn, Twitter, and more.',
 'Drafts, schedules, and analyzes social media content across platforms. Monitors brand mentions and engages with the community.',
 'Draft 5 LinkedIn posts and 5 Twitter/X posts for the week based on: recent blog content, industry news, product updates, and engagement bait questions. Write each in brand voice. Save to Notion content calendar with suggested posting times. Report: posts drafted, best time recommendations.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Posts Drafted","description":"Social media posts created per week","unit":"posts","target":10},{"name":"Engagement Rate","description":"Average engagement on published posts","unit":"%","target":3}]',
 true),

('ai-email-marketer', 'AI Email Marketer', '📧', 'Email Marketing Automation Specialist', 'Marketing',
 'Designs and sends targeted email campaigns that convert.',
 'Segments your list, writes personalized email copy, sets up automations, and reports on campaign performance.',
 'Review the email marketing calendar in Notion. Draft this week''s campaign email: subject line (A/B test 2 variants), preview text, body copy (personalized for segment), CTA. Write a re-engagement email for subscribers inactive 60+ days. Save drafts in Google Docs. Report: campaigns drafted, segments targeted.',
 ARRAY['NOTION','GOOGLEDOCS','SLACK'],
 '[{"name":"Campaigns Drafted","description":"Email campaigns written and ready","unit":"campaigns","target":4},{"name":"Open Rate","description":"Average email open rate","unit":"%","target":28}]',
 false),

('ai-paid-ads-analyst', 'AI Paid Ads Analyst', '💰', 'Paid Advertising Intelligence Specialist', 'Marketing',
 'Analyzes ad performance and surfaces budget optimization opportunities.',
 'Reviews campaign performance across Google and Meta, identifies underperforming ads, recommends budget reallocation, and generates weekly reports.',
 'Pull last week''s ad performance data. Identify: best performing ads (CTR, ROAS), underperforming campaigns (CPA > target), keywords to add/negative. Write an optimization report with: spend summary, top performers, recommended changes, budget reallocation suggestions. Post to Slack #marketing.',
 ARRAY['SLACK','GOOGLEDOCS','NOTION'],
 '[{"name":"ROAS","description":"Return on ad spend","unit":"x","target":4},{"name":"CPA Reduction","description":"Week-over-week cost per acquisition improvement","unit":"%","target":10}]',
 false),

('ai-pr-agent', 'AI PR Agent', '📣', 'Public Relations Specialist', 'Marketing',
 'Drafts press releases, pitches journalists, and tracks media mentions.',
 'Monitors brand mentions, drafts press releases, identifies relevant journalists, and manages media outreach.',
 'Search for brand mentions and industry news from the past week. Draft a press release for any major company announcement in Google Docs. Identify 5 relevant journalists covering our industry. Draft personalized pitch emails for each. Log all outreach in Notion. Post media mention summary to Slack.',
 ARRAY['GOOGLEDOCS','NOTION','SLACK','GMAIL'],
 '[{"name":"Press Releases Drafted","description":"Press releases written","unit":"releases","target":2},{"name":"Media Pitches Sent","description":"Journalist outreach emails sent","unit":"pitches","target":10}]',
 false),

('ai-brand-monitor', 'AI Brand Monitor', '👁️', 'Brand Intelligence & Reputation Specialist', 'Marketing',
 'Watches the internet for mentions of your brand and reports daily.',
 'Continuously monitors social media, news, forums, and review sites for brand mentions and sentiment shifts.',
 'Search for brand mentions across news, Reddit, LinkedIn, and review sites in the last 24 hours. Categorize as: positive, neutral, negative. For negative mentions, draft a response for review. Compile a daily brand health report with sentiment score. Post to Slack #brand-monitor.',
 ARRAY['SLACK','NOTION','GMAIL'],
 '[{"name":"Mentions Tracked","description":"Brand mentions monitored daily","unit":"mentions","target":50},{"name":"Sentiment Score","description":"Average positive sentiment percentage","unit":"%","target":75}]',
 false),

('ai-webinar-host', 'AI Webinar Coordinator', '🎙️', 'Webinar & Event Marketing Specialist', 'Marketing',
 'Manages webinar prep, promotion, follow-up, and recap automatically.',
 'Handles end-to-end webinar coordination: promotional emails, reminder sequences, attendee follow-up, and post-event content repurposing.',
 'For the upcoming webinar: draft 3 promotional emails (2 weeks out, 1 week out, 1 day before), a day-of reminder, and a post-event follow-up with recording link. Write a LinkedIn post announcing the webinar. Create a post-event blog post outline. Save all to Notion. Report: emails drafted, registrations projected.',
 ARRAY['GMAIL','NOTION','GOOGLEDOCS','SLACK'],
 '[{"name":"Registrations Generated","description":"Webinar sign-ups from email campaigns","unit":"registrations","target":100},{"name":"Attendance Rate","description":"Percentage of registrants who attend","unit":"%","target":40}]',
 false),

('ai-ab-test-analyst', 'AI A/B Test Analyst', '🧪', 'Conversion Optimization Specialist', 'Marketing',
 'Designs A/B tests, tracks results, and recommends winners.',
 'Proposes A/B test ideas, monitors active tests, calculates statistical significance, and writes experiment summaries.',
 'Review all active A/B tests. For tests with sufficient data, calculate statistical significance and declare a winner. Suggest 3 new A/B test ideas based on current conversion bottlenecks. Write a weekly CRO report with: test results, learnings, next tests. Post to Slack #growth.',
 ARRAY['SLACK','NOTION','GOOGLEDOCS'],
 '[{"name":"Tests Analyzed","description":"A/B tests evaluated and concluded","unit":"tests","target":3},{"name":"Conversion Lift","description":"Average CRO improvement from winning tests","unit":"%","target":15}]',
 false),

('ai-community-manager', 'AI Community Manager', '👥', 'Community Growth Specialist', 'Marketing',
 'Nurtures your online community, sparks discussions, and grows membership.',
 'Monitors community channels, responds to questions, surfaces trending topics, and creates engagement content to keep members active.',
 'Check Slack community channels for unanswered questions older than 4 hours. Draft helpful replies. Identify 3 trending topics in the community this week. Write a weekly community digest post. Welcome new members who joined this week with a personalized message. Report: responses sent, new members welcomed.',
 ARRAY['SLACK','NOTION','GOOGLEDOCS'],
 '[{"name":"Questions Answered","description":"Community questions responded to","unit":"responses","target":20},{"name":"New Members Welcomed","description":"Personalized welcome messages sent","unit":"messages","target":10}]',
 false),

('ai-influencer-manager', 'AI Influencer Relations Manager', '⭐', 'Influencer Partnership Specialist', 'Marketing',
 'Finds relevant influencers, manages outreach, and tracks partnership performance.',
 'Identifies influencers aligned with your brand, drafts partnership proposals, tracks collaborations, and measures ROI.',
 'Search for micro-influencers (5K-100K followers) in our niche who haven''t promoted competitors. For the top 10 matches, draft a personalized partnership proposal email. Log all outreach in Notion. For active partnerships, compile a performance report. Post weekly influencer activity digest to Slack.',
 ARRAY['GMAIL','NOTION','SLACK'],
 '[{"name":"Influencers Contacted","description":"Partnership outreach emails sent","unit":"emails","target":10},{"name":"Partnerships Active","description":"Live influencer collaborations","unit":"partnerships","target":3}]',
 false),

('ai-campaign-reporter', 'AI Campaign Reporter', '📊', 'Marketing Analytics & Reporting Specialist', 'Marketing',
 'Compiles campaign performance reports so the team always has data.',
 'Pulls metrics from all marketing channels, calculates KPIs, identifies trends, and delivers a weekly marketing performance report.',
 'Compile this week''s marketing performance: email open/click rates, social engagement, ad spend and ROAS, website traffic, leads generated. Compare to last week and last month. Write a 1-page marketing performance report. Post executive summary to Slack #marketing, full report in Notion.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Reports Delivered","description":"Weekly marketing reports compiled","unit":"reports","target":4},{"name":"MQLs Generated","description":"Marketing qualified leads delivered to sales","unit":"leads","target":50}]',
 false),

-- ── CUSTOMER SUPPORT (10) ──────────────────────────────────────────────────────
('ai-support-agent', 'AI Support Agent', '🛟', 'Customer Support Specialist', 'Support',
 'Triages tickets, answers routine questions, and escalates what needs a human.',
 'Monitors support inbox, categorizes tickets by urgency, drafts responses to common questions, and routes complex issues to the right team member.',
 'Check the support inbox for new tickets. Categorize by: (1) can auto-resolve, (2) needs human. For auto-resolvable tickets, draft a helpful response using our knowledge base. For human-needed tickets, assign to the right team member with a summary and suggested response. Report: tickets triaged, auto-resolved, escalated.',
 ARRAY['GMAIL','SLACK','NOTION'],
 '[{"name":"Tickets Triaged","description":"Support tickets categorized and actioned","unit":"tickets","target":50},{"name":"Auto-Resolution Rate","description":"Percentage of tickets handled without human","unit":"%","target":40}]',
 true),

('ai-inbox-manager', 'AI Inbox Manager', '📥', 'Email Inbox Zero Specialist', 'Support',
 'Sorts your inbox, drafts replies, and gets you to zero every morning.',
 'Reviews your email inbox, categorizes messages, drafts responses to routine emails, and surfaces only what genuinely needs your attention.',
 'Review all unread emails. Categorize as: needs reply (draft response), FYI only (summarize), newsletter (unsubscribe if irrelevant), spam (delete). Draft replies for emails needing a response. Create a daily inbox summary with: action required list, drafted replies awaiting approval, emails handled. Post summary to Slack.',
 ARRAY['GMAIL','SLACK'],
 '[{"name":"Emails Processed","description":"Emails categorized and actioned daily","unit":"emails","target":50},{"name":"Response Time","description":"Average hours to draft reply","unit":"hours","target":1}]',
 true),

('ai-ticket-analyst', 'AI Support Ticket Analyst', '🔬', 'Support Intelligence Analyst', 'Support',
 'Analyzes support trends and recommends product and documentation fixes.',
 'Reviews support ticket patterns, identifies recurring issues, recommends documentation improvements, and surfaces product bugs to engineering.',
 'Analyze all support tickets from the last 30 days. Group by: recurring topics, product area, resolution time. Identify top 5 recurring issues that documentation could prevent. Draft documentation for each. Identify top 3 product bugs to escalate to engineering. Write a monthly support analysis report.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Ticket Trends Identified","description":"Recurring support patterns discovered","unit":"trends","target":10},{"name":"Docs Created","description":"Self-help articles drafted from ticket data","unit":"articles","target":5}]',
 false),

('ai-nps-manager', 'AI NPS & Feedback Manager', '⭐', 'Customer Feedback Intelligence Specialist', 'Support',
 'Collects, analyzes, and acts on customer feedback automatically.',
 'Monitors NPS responses, categorizes feedback themes, drafts responses to detractors, and generates monthly feedback reports.',
 'Review new NPS survey responses. For detractors (0-6), draft a personal apology email and flag for immediate follow-up. For promoters (9-10), send a thank-you and referral invite. Categorize all feedback themes. Write a monthly NPS report with: score trend, top positive themes, top pain points, recommended actions.',
 ARRAY['GMAIL','NOTION','SLACK'],
 '[{"name":"NPS Score","description":"Net Promoter Score","unit":"score","target":50},{"name":"Detractor Response Rate","description":"Percentage of detractors personally contacted","unit":"%","target":100}]',
 false),

('ai-knowledge-base-manager', 'AI Knowledge Base Manager', '📚', 'Documentation & Self-Service Specialist', 'Support',
 'Keeps your help documentation fresh, accurate, and comprehensive.',
 'Audits existing knowledge base articles, identifies gaps, updates outdated content, and creates new articles based on support trends.',
 'Review all knowledge base articles in Notion. Flag articles not updated in 90+ days for review. Identify top 10 support ticket topics with no existing documentation. Draft new help articles for each gap. Improve the 5 most-viewed articles with better structure and examples. Report: articles updated, new articles created.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Articles Updated","description":"Help docs refreshed this month","unit":"articles","target":10},{"name":"New Articles Created","description":"New knowledge base articles written","unit":"articles","target":5}]',
 false),

('ai-churn-preventer', 'AI Churn Prevention Agent', '🔒', 'Customer Retention Specialist', 'Support',
 'Identifies at-risk customers and triggers proactive save campaigns.',
 'Monitors usage patterns, support history, and engagement signals to identify churn risk and trigger personalized save sequences.',
 'Analyze customer accounts for churn signals: no login in 14+ days, 3+ support tickets in 30 days, payment failed, contract expiry in 30 days. For each at-risk customer, draft a personalized save email and notify their account manager in Slack. Report: at-risk customers identified, save emails sent, accounts recovered.',
 ARRAY['GMAIL','SLACK','HUBSPOT'],
 '[{"name":"At-Risk Accounts Saved","description":"Churning customers retained","unit":"accounts","target":3},{"name":"Churn Rate","description":"Monthly customer churn percentage","unit":"%","target":2}]',
 false),

('ai-onboarding-specialist', 'AI Onboarding Specialist', '🚀', 'Customer Onboarding Automation Specialist', 'Support',
 'Guides new customers through setup with personalized email sequences.',
 'Triggers personalized onboarding email sequences, monitors setup completion, and intervenes when customers get stuck.',
 'Check for new customers who signed up in the last 7 days. Review their onboarding progress. For customers who haven''t completed key setup steps, send a helpful nudge email with specific guidance. For customers who completed onboarding, send a congratulations email with next steps. Report: new customers, completion rate, nudges sent.',
 ARRAY['GMAIL','HUBSPOT','SLACK'],
 '[{"name":"Onboarding Completion Rate","description":"Percentage of new users completing setup","unit":"%","target":70},{"name":"Time to First Value","description":"Average days to complete onboarding","unit":"days","target":3}]',
 true),

('ai-escalation-manager', 'AI Escalation Manager', '🚨', 'Critical Issue Escalation Specialist', 'Support',
 'Detects and escalates critical customer issues before they blow up.',
 'Monitors VIP customer accounts, high-severity tickets, and SLA breaches. Ensures the right people know immediately when something critical happens.',
 'Check support inbox for VIP customer tickets and tickets flagged as urgent. Identify any SLA breaches (no response within promised time). For critical issues, immediately alert the support manager in Slack with full context. Draft an apology and status email to the customer. Log all escalations in Notion.',
 ARRAY['GMAIL','SLACK','NOTION'],
 '[{"name":"SLA Compliance","description":"Percentage of tickets resolved within SLA","unit":"%","target":95},{"name":"Escalations Managed","description":"Critical issues escalated and resolved","unit":"issues","target":5}]',
 false),

('ai-csat-analyst', 'AI CSAT Analyst', '😊', 'Customer Satisfaction Intelligence Specialist', 'Support',
 'Tracks CSAT scores and drives continuous support quality improvement.',
 'Analyzes customer satisfaction surveys, identifies quality gaps, coaches support agents, and tracks improvement over time.',
 'Review all CSAT survey responses from the past week. Identify low-scoring interactions (below 3/5). Analyze common complaint themes. Write a CSAT report with: average score, trend vs last week, top 3 improvement areas, 2 positive examples to share. Post to Slack #support-team.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"CSAT Score","description":"Customer satisfaction score average","unit":"score","target":4.5},{"name":"Low-Score Reviews Analyzed","description":"Poor interactions reviewed for learning","unit":"reviews","target":10}]',
 false),

('ai-refund-manager', 'AI Refund & Billing Manager', '💳', 'Billing & Refund Resolution Specialist', 'Support',
 'Handles billing questions and refund requests efficiently and fairly.',
 'Reviews refund requests, applies the refund policy, drafts resolution emails, and flags edge cases for human review.',
 'Check inbox for billing-related emails and refund requests. For each, review against our refund policy. Draft a resolution email: approve with instructions, deny with explanation, or escalate if edge case. Log all billing interactions in HubSpot. Report: requests processed, approved, denied, escalated.',
 ARRAY['GMAIL','HUBSPOT','SLACK'],
 '[{"name":"Refund Requests Resolved","description":"Billing issues handled end-to-end","unit":"requests","target":20},{"name":"Resolution Time","description":"Average hours to resolve billing issue","unit":"hours","target":4}]',
 false),

-- ── OPERATIONS (10) ──────────────────────────────────────────────────────────
('ai-ops-assistant', 'AI Ops Assistant', '⚙️', 'Operations Automation Specialist', 'Operations',
 'Automates the repetitive operational tasks that eat your team''s day.',
 'Identifies and automates recurring manual workflows across tools, ensuring nothing falls through the cracks.',
 'Review recurring operational tasks logged in Notion. For each manual task, execute it using available tools and log completion. Check for any scheduled reports or updates due today. Move relevant data between systems as needed. Report: tasks completed, time saved, exceptions flagged.',
 ARRAY['NOTION','SLACK','GOOGLESHEETS','AIRTABLE'],
 '[{"name":"Tasks Automated","description":"Manual tasks completed by AI","unit":"tasks","target":20},{"name":"Hours Saved","description":"Estimated human hours saved per week","unit":"hours","target":10}]',
 true),

('ai-data-entry-clerk', 'AI Data Entry Clerk', '📋', 'Data Entry & Sync Automation Specialist', 'Operations',
 'Moves data between your tools so you never copy-paste again.',
 'Syncs data across your tech stack, updates records, fills in missing fields, and maintains data integrity across systems.',
 'Check for data sync tasks in the queue: new CRM contacts to add to Sheets, Airtable records to update in Notion, form submissions to route to the right tool. Execute each sync. Validate data format and flag errors. Report: records synced, errors found, exceptions requiring review.',
 ARRAY['GOOGLESHEETS','AIRTABLE','NOTION','HUBSPOT'],
 '[{"name":"Records Synced","description":"Data records successfully moved between systems","unit":"records","target":200},{"name":"Data Accuracy","description":"Percentage of records with no errors","unit":"%","target":99}]',
 false),

('ai-vendor-manager', 'AI Vendor Manager', '🤝', 'Vendor Relations & Procurement Specialist', 'Operations',
 'Manages vendor relationships, tracks contracts, and handles renewals.',
 'Monitors vendor contracts, tracks SLAs, manages renewal timelines, and maintains vendor communication.',
 'Review the vendor contracts list in Notion. Flag contracts expiring in 60 days. Check vendor SLA reports from the past month. Draft renewal emails for expiring contracts. Log vendor performance notes. Send weekly vendor status update to operations team in Slack.',
 ARRAY['NOTION','GMAIL','SLACK','GOOGLESHEETS'],
 '[{"name":"Contracts Monitored","description":"Active vendor contracts tracked","unit":"contracts","target":20},{"name":"Renewals Managed","description":"Vendor renewals completed on time","unit":"renewals","target":5}]',
 false),

('ai-meeting-coordinator', 'AI Meeting Coordinator', '📅', 'Meeting & Calendar Management Specialist', 'Operations',
 'Schedules, prepares agendas, and sends follow-ups for all team meetings.',
 'Manages the full meeting lifecycle: scheduling, agenda creation, note-taking preparation, action item extraction, and follow-up.',
 'Review upcoming meetings in Google Calendar for the next 7 days. For each meeting with no agenda, create an agenda doc in Google Docs and share with attendees. For meetings from the past week, check if action items were logged. Send follow-up email with meeting recap and action items for any meeting without one. Post weekly meeting schedule to Slack.',
 ARRAY['GOOGLECALENDAR','GOOGLEDOCS','GMAIL','SLACK'],
 '[{"name":"Agendas Created","description":"Meeting agendas prepared in advance","unit":"agendas","target":10},{"name":"Action Items Tracked","description":"Meeting action items logged and followed up","unit":"items","target":20}]',
 false),

('ai-project-tracker', 'AI Project Tracker', '🗂️', 'Project Status & Delivery Specialist', 'Operations',
 'Keeps all projects on track with status updates and deadline alerts.',
 'Monitors project boards, flags overdue tasks, nudges task owners, and delivers weekly project status reports.',
 'Review all active projects in Notion. Identify tasks overdue by 2+ days. Send a friendly nudge to the task owner in Slack. Identify projects at risk (3+ overdue tasks, blocked items). Write a weekly project status report: on track, at risk, blocked. Post to Slack #ops.',
 ARRAY['NOTION','SLACK','GOOGLESHEETS'],
 '[{"name":"Overdue Tasks Flagged","description":"Late tasks identified and owners notified","unit":"tasks","target":10},{"name":"On-Time Delivery Rate","description":"Percentage of projects delivered on schedule","unit":"%","target":80}]',
 false),

('ai-inventory-manager', 'AI Inventory Manager', '📦', 'Inventory & Supply Chain Specialist', 'Operations',
 'Tracks inventory levels and triggers reorder alerts automatically.',
 'Monitors stock levels, forecasts demand, flags low-inventory items, and generates purchase orders.',
 'Check the inventory spreadsheet for items below reorder threshold. For each low-stock item, calculate reorder quantity based on 30-day usage. Draft a purchase order email to the supplier. Update the inventory log. Send daily inventory status to the ops team in Slack. Flag any out-of-stock items as urgent.',
 ARRAY['GOOGLESHEETS','GMAIL','SLACK'],
 '[{"name":"Stockouts Prevented","description":"Low-stock alerts sent before stockout","unit":"alerts","target":5},{"name":"Reorder Accuracy","description":"Percentage of reorders that avoided overstock","unit":"%","target":90}]',
 false),

('ai-compliance-checker', 'AI Compliance Monitor', '✅', 'Compliance & Audit Readiness Specialist', 'Operations',
 'Monitors compliance requirements and keeps the team audit-ready.',
 'Tracks regulatory requirements, monitors policy adherence, flags compliance risks, and maintains audit documentation.',
 'Review the compliance checklist in Notion. Check which items are due this month. Verify documentation is up to date for each active compliance requirement. Flag any overdue items as urgent. Draft a compliance status report. Send to the compliance owner in Slack. Log all checks in the audit trail.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Compliance Items Current","description":"Percentage of requirements met","unit":"%","target":100},{"name":"Audit Items Documented","description":"Compliance evidence documents maintained","unit":"documents","target":20}]',
 false),

('ai-process-documenter', 'AI Process Documenter', '📝', 'Process Documentation Specialist', 'Operations',
 'Turns tribal knowledge into clear, searchable documentation.',
 'Interviews team members (via Slack), watches workflows, and documents processes in a clear, structured format.',
 'Review Notion for processes with outdated or missing documentation. Post a Slack question to the relevant team member to gather process details. Draft a structured SOP (Standard Operating Procedure) document for each process: overview, when to use, step-by-step, edge cases. Save to the processes folder in Notion.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"SOPs Created","description":"Standard operating procedures documented","unit":"SOPs","target":3},{"name":"Process Coverage","description":"Percentage of key processes documented","unit":"%","target":80}]',
 false),

('ai-budget-tracker', 'AI Budget Tracker', '💰', 'Budget Monitoring & Variance Specialist', 'Operations',
 'Tracks spending vs budget and flags variances before they become problems.',
 'Monitors departmental spending, compares to budget, flags overspend risk, and delivers weekly budget health reports.',
 'Pull this week''s expense data from the tracking spreadsheet. Compare actual spend to budget for each department. Flag departments more than 20% over budget. Calculate burn rate and projected month-end spend. Write a weekly budget health report with: total spend, by department, variances, flags. Post to Slack #finance.',
 ARRAY['GOOGLESHEETS','SLACK','GOOGLEDOCS'],
 '[{"name":"Budget Variance","description":"Actual vs budget variance percentage","unit":"%","target":5},{"name":"Departments Tracked","description":"Budget lines actively monitored","unit":"departments","target":8}]',
 false),

('ai-office-coordinator', 'AI Office Coordinator', '🏢', 'Office & Facilities Management Specialist', 'Operations',
 'Manages office logistics, visitor coordination, and facilities requests.',
 'Handles meeting room bookings, visitor registration, facilities requests, and office supply ordering.',
 'Check for new facilities requests in the Notion request queue. Prioritize by urgency. Process meeting room bookings for the week. Check office supply inventory and reorder anything below threshold. Send visitor confirmation emails for scheduled visits. Post daily facilities update to Slack #office.',
 ARRAY['NOTION','GMAIL','SLACK','GOOGLECALENDAR'],
 '[{"name":"Requests Processed","description":"Facilities requests handled","unit":"requests","target":20},{"name":"Room Utilization","description":"Meeting room booking efficiency","unit":"%","target":70}]',
 false),

-- ── FINANCE (8) ──────────────────────────────────────────────────────────────
('ai-bookkeeper', 'AI Bookkeeper', '📒', 'Bookkeeping & Transaction Categorization Specialist', 'Finance',
 'Categorizes transactions and keeps the books tidy automatically.',
 'Reviews financial transactions, categorizes expenses, flags anomalies, and prepares reconciliation reports.',
 'Review this week''s transactions in the expense tracking spreadsheet. Categorize each uncategorized transaction into the right GL account. Flag any transactions over $500 that lack receipts. Identify any duplicate charges. Write a weekly transaction summary with: total in/out, by category, anomalies flagged. Post to Slack #finance.',
 ARRAY['GOOGLESHEETS','SLACK','GOOGLEDOCS'],
 '[{"name":"Transactions Categorized","description":"Expense transactions properly categorized","unit":"transactions","target":100},{"name":"Anomalies Flagged","description":"Unusual transactions identified for review","unit":"flags","target":5}]',
 false),

('ai-invoice-manager', 'AI Invoice Manager', '🧾', 'Accounts Receivable & Invoice Specialist', 'Finance',
 'Creates, sends, and follows up on invoices so you always get paid on time.',
 'Generates invoices from contract data, sends to clients, monitors payment status, and triggers overdue reminders.',
 'Check for new billable work or milestone completions in the project tracker. Generate invoices for each. Send invoices via email. Check for overdue invoices (30+ days). Send payment reminder email to each overdue account. Flag invoices 60+ days overdue for escalation. Report: invoices sent, paid, overdue.',
 ARRAY['GMAIL','GOOGLESHEETS','SLACK','NOTION'],
 '[{"name":"Invoices Sent","description":"Invoices generated and delivered","unit":"invoices","target":20},{"name":"DSO","description":"Days sales outstanding","unit":"days","target":30}]',
 false),

('ai-expense-reviewer', 'AI Expense Reviewer', '🧮', 'Expense Report Audit Specialist', 'Finance',
 'Reviews expense reports for policy compliance and approves routine claims.',
 'Audits submitted expense reports against policy, approves compliant claims, flags violations, and requests missing receipts.',
 'Review all pending expense reports submitted this week. Check each expense against the expense policy: within category limits, receipts attached, business purpose stated. Auto-approve fully compliant reports. Flag non-compliant items with specific reason. Send approval/rejection email to each submitter. Report: reviewed, approved, flagged.',
 ARRAY['GMAIL','GOOGLESHEETS','SLACK'],
 '[{"name":"Reports Reviewed","description":"Expense reports audited","unit":"reports","target":20},{"name":"Policy Compliance Rate","description":"Percentage of expenses submitted in compliance","unit":"%","target":90}]',
 false),

('ai-cash-flow-analyst', 'AI Cash Flow Analyst', '💧', 'Cash Flow Forecasting Specialist', 'Finance',
 'Monitors cash position and forecasts 13-week cash flow automatically.',
 'Pulls revenue and expense data, builds rolling cash flow forecasts, flags shortfalls, and delivers weekly treasury reports.',
 'Pull current bank balance, accounts receivable, and upcoming payables from the tracking spreadsheet. Build a 13-week cash flow forecast. Flag any weeks where projected cash falls below the minimum reserve. Write a cash flow report with: current position, 30/60/90-day outlook, risks. Send to CFO via Slack and email.',
 ARRAY['GOOGLESHEETS','SLACK','GMAIL','GOOGLEDOCS'],
 '[{"name":"Cash Flow Accuracy","description":"Forecast vs actual variance","unit":"%","target":10},{"name":"Runway Visibility","description":"Weeks of cash runway forecasted","unit":"weeks","target":13}]',
 false),

('ai-payroll-checker', 'AI Payroll Checker', '💵', 'Payroll Accuracy & Compliance Specialist', 'Finance',
 'Verifies payroll data before processing to prevent errors.',
 'Cross-checks timesheets, contractor invoices, and payroll inputs before each pay run to catch discrepancies early.',
 'Before payroll run: pull timesheet data from the tracking spreadsheet. Verify hours match approved timesheets. Check for new hires, terminations, or salary changes. Flag any anomalies (hours spike, new payee, changed bank details). Write a payroll pre-check report. Notify the payroll manager in Slack.',
 ARRAY['GOOGLESHEETS','SLACK','GOOGLEDOCS'],
 '[{"name":"Payroll Errors Caught","description":"Discrepancies found before processing","unit":"errors","target":0},{"name":"Payroll Accuracy","description":"Percentage of payroll runs with zero errors","unit":"%","target":100}]',
 false),

('ai-tax-preparer', 'AI Tax Preparation Assistant', '🏛️', 'Tax Compliance & Documentation Specialist', 'Finance',
 'Organizes tax documents, tracks deadlines, and prepares filing checklists.',
 'Monitors tax filing deadlines, organizes supporting documents, identifies deduction opportunities, and prepares documentation for accountants.',
 'Check the tax compliance calendar for upcoming deadlines in the next 90 days. For each deadline, verify required documents are collected and organized in Google Drive. Identify missing items and request them via email. Prepare a filing checklist document. Post upcoming tax deadlines to Slack #finance.',
 ARRAY['GOOGLEDOCS','GMAIL','SLACK','GOOGLESHEETS'],
 '[{"name":"Deadlines Met","description":"Tax filing deadlines completed on time","unit":"%","target":100},{"name":"Documents Organized","description":"Supporting tax documents filed","unit":"documents","target":50}]',
 false),

('ai-financial-reporter', 'AI Financial Reporter', '📈', 'Financial Reporting & MIS Specialist', 'Finance',
 'Produces monthly P&L, budget variance, and KPI reports automatically.',
 'Compiles financial data from multiple sources, calculates key metrics, and produces management information reports on schedule.',
 'Pull this month''s revenue, expense, and headcount data from the tracking spreadsheets. Calculate: revenue vs target, gross margin, operating expenses by category, burn rate, MRR/ARR. Write the monthly financial report with executive summary. Post to Slack #finance-team and save to Notion.',
 ARRAY['GOOGLESHEETS','GOOGLEDOCS','SLACK','NOTION'],
 '[{"name":"Reports On Time","description":"Financial reports delivered by deadline","unit":"%","target":100},{"name":"Metrics Tracked","description":"Financial KPIs monitored monthly","unit":"metrics","target":15}]',
 false),

('ai-fundraising-assistant', 'AI Fundraising Assistant', '🚀', 'Investor Relations & Fundraising Specialist', 'Finance',
 'Manages investor updates, tracks fundraising pipeline, and prepares materials.',
 'Sends monthly investor updates, tracks warm introductions, maintains the fundraising CRM, and prepares data room materials.',
 'Draft this month''s investor update: key metrics (MRR, growth rate, team size), highlights, challenges, ask. Send to investor list via email. Check fundraising pipeline in Notion for new intros to follow up. Update the data room with latest financials. Report: investors updated, pipeline status, meetings scheduled.',
 ARRAY['GMAIL','NOTION','GOOGLEDOCS','SLACK'],
 '[{"name":"Investors Updated","description":"Monthly investor updates sent","unit":"updates","target":1},{"name":"Investor Meetings Scheduled","description":"Investor conversations initiated","unit":"meetings","target":5}]',
 false),

-- ── HUMAN RESOURCES (8) ──────────────────────────────────────────────────────
('ai-recruiter', 'AI Recruiter', '🎯', 'Talent Acquisition Specialist', 'HR',
 'Screens applicants, schedules interviews, and manages the hiring pipeline.',
 'Reviews job applications, screens candidates against the job description, schedules interviews, and manages candidate communications.',
 'Review new job applications submitted this week. Screen each against the job requirements: experience, skills, location. Send personalized rejection emails to unqualified candidates within 24 hours. Schedule phone screens for qualified candidates. Send interview confirmation emails with agenda. Update ATS in Notion. Report: applications reviewed, interviews scheduled.',
 ARRAY['GMAIL','NOTION','GOOGLECALENDAR','SLACK'],
 '[{"name":"Applications Reviewed","description":"Job applications screened","unit":"applications","target":30},{"name":"Time to Screen","description":"Average hours from application to response","unit":"hours","target":24}]',
 true),

('ai-hr-coordinator', 'AI HR Coordinator', '🤗', 'HR Operations & People Specialist', 'HR',
 'Handles HR admin so your team can focus on people, not paperwork.',
 'Manages HR administrative tasks: PTO tracking, policy Q&A, onboarding checklists, and HR document management.',
 'Check Slack for any HR-related questions from employees. Draft policy-based answers for each. Review PTO requests submitted this week and verify against balance. Send PTO approval/denial emails. Check new hire onboarding checklist progress. Send reminders to new hires for incomplete items. Report: questions answered, PTO processed, onboarding progress.',
 ARRAY['GMAIL','SLACK','NOTION','GOOGLESHEETS'],
 '[{"name":"HR Requests Handled","description":"Employee HR queries resolved","unit":"requests","target":20},{"name":"Response Time","description":"Average hours to respond to HR queries","unit":"hours","target":4}]',
 false),

('ai-performance-manager', 'AI Performance Review Manager', '🎯', 'Performance Management Specialist', 'HR',
 'Manages the performance review cycle so nothing falls through the cracks.',
 'Coordinates performance review cycles, sends reminder emails, collects forms, and compiles review summaries.',
 'Check the performance review calendar in Notion. Send reminder emails to managers with reviews due this week. For completed reviews, compile a summary with: goals met, ratings distribution, development themes. Flag any incomplete reviews past due. Post cycle status to Slack #people-ops.',
 ARRAY['GMAIL','NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Reviews Completed","description":"Performance reviews submitted on time","unit":"%","target":90},{"name":"Review Cycle Length","description":"Average days from kickoff to completion","unit":"days","target":21}]',
 false),

('ai-learning-coordinator', 'AI Learning & Development Coordinator', '📚', 'L&D Program Specialist', 'HR',
 'Recommends learning paths and tracks training completion.',
 'Identifies skill gaps, recommends training resources, tracks L&D budget utilization, and sends learning nudges to employees.',
 'Review the skills matrix in Notion. Identify top 3 skill gaps across the team. Recommend 2 training resources per gap (courses, books, workshops). Check L&D budget utilization. Send a weekly learning digest to the team in Slack with: featured course, article, and upcoming webinar. Report: employees learning, completion rates.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Training Completions","description":"Learning modules completed by team","unit":"completions","target":10},{"name":"L&D Budget Utilization","description":"Percentage of L&D budget used","unit":"%","target":80}]',
 false),

('ai-culture-agent', 'AI Culture & Engagement Agent', '🎉', 'Employee Engagement Specialist', 'HR',
 'Runs recognition programs, surveys, and engagement initiatives automatically.',
 'Manages employee recognition, runs engagement pulse surveys, celebrates milestones, and reports on team morale.',
 'Check for employee birthdays and work anniversaries this week — send personalized celebration messages in Slack. Review any pulse survey responses from this week and summarize themes. Draft a shoutout message for the top performer of the week based on peer nominations. Post a Friday fun question to #general to boost engagement.',
 ARRAY['SLACK','NOTION','GOOGLEDOCS'],
 '[{"name":"Recognitions Sent","description":"Employee milestones and wins celebrated","unit":"recognitions","target":10},{"name":"Engagement Score","description":"Pulse survey engagement score","unit":"score","target":8}]',
 false),

('ai-benefits-manager', 'AI Benefits Manager', '🏥', 'Benefits Administration Specialist', 'HR',
 'Answers benefits questions and manages enrollment periods.',
 'Handles benefits inquiries, manages open enrollment communications, tracks benefit utilization, and ensures compliance.',
 'Check inbox and Slack for benefits-related questions. Draft policy-based answers for each. Review benefits utilization data in the tracking spreadsheet. For open enrollment period: send reminder emails to employees who haven''t enrolled. Write a benefits FAQ update based on common questions this month. Report: questions answered, enrollment status.',
 ARRAY['GMAIL','SLACK','GOOGLESHEETS','GOOGLEDOCS'],
 '[{"name":"Benefits Questions Resolved","description":"Employee benefits queries answered","unit":"queries","target":20},{"name":"Enrollment Rate","description":"Percentage of eligible employees enrolled","unit":"%","target":95}]',
 false),

('ai-offboarding-manager', 'AI Offboarding Manager', '👋', 'Employee Offboarding Specialist', 'HR',
 'Manages departing employee transitions so nothing is forgotten.',
 'Coordinates the offboarding checklist, schedules exit interviews, revokes system access, and handles knowledge transfer.',
 'For employees leaving this week: send the offboarding checklist to the manager. Schedule an exit interview. Send access revocation requests to IT. Notify relevant team leads. Create a knowledge transfer document template. Send the departing employee a farewell email with final pay details and reference policy. Report: offboarding tasks completed.',
 ARRAY['GMAIL','NOTION','SLACK','GOOGLECALENDAR'],
 '[{"name":"Offboarding Completed On Time","description":"Offboarding checklists completed before last day","unit":"%","target":100},{"name":"Exit Interviews Conducted","description":"Exit interviews successfully scheduled","unit":"%","target":90}]',
 false),

('ai-headcount-planner', 'AI Headcount Planner', '👤', 'Workforce Planning Specialist', 'HR',
 'Models headcount scenarios and tracks hiring plan progress.',
 'Maintains headcount models, tracks open roles, monitors hiring velocity, and alerts when hiring plan is off-track.',
 'Pull current headcount data from the spreadsheet. Compare to the approved hiring plan. Calculate open roles by department and time-to-fill for each. Flag departments behind hiring plan. Write a monthly headcount report: current vs plan, open roles, hiring velocity, projected year-end. Post to Slack #people-ops.',
 ARRAY['GOOGLESHEETS','SLACK','GOOGLEDOCS','NOTION'],
 '[{"name":"Hiring Plan Adherence","description":"Percentage of roles filled per plan","unit":"%","target":90},{"name":"Time to Fill","description":"Average days from open to offer accepted","unit":"days","target":45}]',
 false),

-- ── ENGINEERING (8) ──────────────────────────────────────────────────────────
('ai-code-reviewer', 'AI Code Review Assistant', '👨‍💻', 'Code Quality & Review Specialist', 'Engineering',
 'Reviews PRs, flags issues, and helps enforce code standards.',
 'Reviews pull requests for common issues, enforces code standards, checks for security vulnerabilities, and provides constructive feedback.',
 'Check GitHub for open pull requests awaiting review. For each PR: review the diff for common issues (security vulnerabilities, missing error handling, code style, test coverage). Post a review comment with specific, constructive feedback. Approve PRs that meet standards. Flag critical security issues as urgent in Slack #engineering.',
 ARRAY['GITHUB','SLACK','NOTION'],
 '[{"name":"PRs Reviewed","description":"Pull requests reviewed per week","unit":"PRs","target":10},{"name":"Issues Caught","description":"Code issues identified before merge","unit":"issues","target":15}]',
 true),

('ai-bug-tracker', 'AI Bug Triage Specialist', '🐛', 'Bug Management & Prioritization Specialist', 'Engineering',
 'Triages bug reports, prioritizes by severity, and keeps the backlog clean.',
 'Reviews new bug reports, assesses severity, gathers reproduction steps, prioritizes the backlog, and assigns to the right engineer.',
 'Review all new bug reports submitted this week. For each: assess severity (P0-P3), verify reproduction steps are complete (request more info if not), assign to the right team/engineer, add to the sprint backlog with correct priority. Write a weekly bug report: total open, by severity, resolved this week, new this week. Post to Slack #engineering.',
 ARRAY['GITHUB','SLACK','NOTION'],
 '[{"name":"Bugs Triaged","description":"Bug reports assessed and prioritized","unit":"bugs","target":20},{"name":"P0 Response Time","description":"Hours from P0 report to engineer assigned","unit":"hours","target":1}]',
 false),

('ai-devops-monitor', 'AI DevOps Monitor', '🖥️', 'Infrastructure & Deployment Specialist', 'Engineering',
 'Monitors deployments, infrastructure health, and incident response.',
 'Watches for deployment failures, monitors system health, alerts on anomalies, and documents incident post-mortems.',
 'Check the last 24 hours of deployment and infrastructure logs. Identify any failed deployments, error spikes, or performance degradations. For each issue, post an alert to Slack #incidents with: what happened, impact, recommended action. Write post-mortems for any incidents resolved this week. Update the system health dashboard in Notion.',
 ARRAY['SLACK','NOTION','GITHUB'],
 '[{"name":"Incidents Detected","description":"Infrastructure issues caught proactively","unit":"incidents","target":5},{"name":"MTTR","description":"Mean time to resolve incidents","unit":"minutes","target":30}]',
 false),

('ai-sprint-manager', 'AI Sprint Manager', '🏃', 'Agile Sprint Management Specialist', 'Engineering',
 'Runs sprint ceremonies, tracks velocity, and keeps delivery on track.',
 'Manages sprint planning, daily standups, sprint reviews, and retrospectives through automated coordination and summaries.',
 'Check the sprint board in Notion. Compile the daily standup summary: completed yesterday, planned today, blockers. Flag any stories not started with 2 days remaining in sprint. Write a sprint progress report: velocity vs planned, at-risk stories, blockers. Post to Slack #engineering. Alert team lead to any sprint risk.',
 ARRAY['NOTION','SLACK','GITHUB'],
 '[{"name":"Sprint Velocity","description":"Story points completed per sprint","unit":"points","target":40},{"name":"Sprint Goal Achievement","description":"Percentage of sprint goals met","unit":"%","target":85}]',
 false),

('ai-api-monitor', 'AI API Monitor', '🔌', 'API Health & Documentation Specialist', 'Engineering',
 'Monitors API health, documents endpoints, and alerts on degradation.',
 'Tests API endpoints, tracks response times, monitors error rates, and keeps API documentation up to date.',
 'Run health checks on all registered API endpoints. Log response times and error rates. Flag endpoints with >500ms response time or >1% error rate as degraded. Check API documentation in Notion for endpoints added or changed this week — update docs accordingly. Post weekly API health report to Slack #engineering.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"API Uptime","description":"Percentage uptime across all endpoints","unit":"%","target":99.9},{"name":"Avg Response Time","description":"Average API response time in milliseconds","unit":"ms","target":200}]',
 false),

('ai-security-scanner', 'AI Security Scanner', '🔐', 'Application Security Specialist', 'Engineering',
 'Scans code and infrastructure for security vulnerabilities weekly.',
 'Runs security checks on new code, monitors for dependency vulnerabilities, checks configuration security, and reports findings.',
 'Review the GitHub repository for: newly merged code with potential security issues (injection, auth bypass, exposed secrets), dependency updates with security patches, exposed environment variables or API keys. Write a weekly security scan report with findings by severity. Post critical findings to Slack #security immediately.',
 ARRAY['GITHUB','SLACK','NOTION'],
 '[{"name":"Vulnerabilities Found","description":"Security issues identified before production","unit":"vulnerabilities","target":5},{"name":"Critical Issues Response Time","description":"Hours from discovery to fix started","unit":"hours","target":4}]',
 false),

('ai-release-manager', 'AI Release Manager', '🚢', 'Release Coordination Specialist', 'Engineering',
 'Coordinates releases, writes changelogs, and manages rollout communications.',
 'Manages the release process: coordinates stakeholders, writes changelogs from commits, sends release announcements, and monitors post-release metrics.',
 'Check GitHub for commits merged to main since the last release. Write a changelog organized by: New Features, Improvements, Bug Fixes. Draft a release announcement email and Slack post. Coordinate with QA for final sign-off. Update the product changelog in Notion. Send post-release monitoring alert to Slack #engineering.',
 ARRAY['GITHUB','SLACK','NOTION','GMAIL'],
 '[{"name":"Releases Shipped","description":"Production releases successfully deployed","unit":"releases","target":4},{"name":"Release Notes Quality","description":"Stakeholder satisfaction with release comms","unit":"score","target":4}]',
 false),

('ai-tech-debt-tracker', 'AI Tech Debt Tracker', '🗃️', 'Technical Debt Management Specialist', 'Engineering',
 'Tracks tech debt, prioritizes paydown, and reports progress.',
 'Maintains the tech debt registry, prioritizes items by impact and effort, advocates for paydown time, and tracks progress.',
 'Review the tech debt backlog in Notion. For each item, assess: business impact if unaddressed, estimated fix effort. Prioritize top 5 items to address this sprint. Write a monthly tech debt report: total items, by category (security, performance, scalability, maintainability), paydown progress. Post to Slack #engineering.',
 ARRAY['NOTION','SLACK','GITHUB'],
 '[{"name":"Tech Debt Items Resolved","description":"Technical debt tickets closed per month","unit":"items","target":5},{"name":"Debt Ratio","description":"Percentage of sprint time allocated to tech debt","unit":"%","target":20}]',
 false),

-- ── DATA & ANALYTICS (8) ──────────────────────────────────────────────────────
('ai-data-analyst', 'AI Data Analyst', '📊', 'Business Intelligence & Analytics Specialist', 'Data',
 'Answers business questions with data and delivers insights on a schedule.',
 'Runs regular data analyses, builds dashboards, answers ad-hoc questions, and delivers weekly business intelligence reports.',
 'Pull this week''s key business metrics from the data spreadsheet: revenue, users, engagement, churn. Calculate week-over-week and month-over-month changes. Identify the 3 most significant trends or anomalies. Write a weekly data insights report with: headline metrics, key trends, anomalies, recommended focus areas. Post to Slack #data.',
 ARRAY['GOOGLESHEETS','NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Reports Delivered","description":"Data reports produced on schedule","unit":"reports","target":4},{"name":"Insights Actioned","description":"Data-driven decisions made from reports","unit":"decisions","target":5}]',
 true),

('ai-metrics-reporter', 'AI Metrics Reporter', '📉', 'KPI Tracking & Reporting Specialist', 'Data',
 'Tracks all your KPIs and makes sure nothing dips without you knowing.',
 'Monitors KPI targets, alerts on metric anomalies, tracks goal progress, and delivers daily metric snapshots.',
 'Pull today''s key metrics from all tracking sources. Compare to targets, prior day, and prior week. Flag any metric more than 20% off target or showing significant week-over-week decline. Write a daily metrics snapshot (5 bullets max). Post to Slack #metrics every morning at 9am.',
 ARRAY['GOOGLESHEETS','SLACK','NOTION'],
 '[{"name":"Metrics On Track","description":"KPIs meeting or exceeding target","unit":"%","target":80},{"name":"Anomalies Flagged","description":"Metric deviations detected and surfaced","unit":"flags","target":3}]',
 false),

('ai-customer-segmentation', 'AI Customer Segmentation Analyst', '🎯', 'Customer Segmentation & Cohort Specialist', 'Data',
 'Segments your customer base to drive personalized marketing and product decisions.',
 'Analyzes customer behavior data to create and maintain segments, run cohort analyses, and surface actionable insights.',
 'Analyze customer data in the spreadsheet. Segment customers by: plan tier, signup cohort, usage level, industry. Calculate retention rate by cohort. Identify the highest-LTV segment characteristics. Write a monthly segmentation report with: segment sizes, health metrics, growth trends, recommendations. Save to Notion.',
 ARRAY['GOOGLESHEETS','NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Segments Maintained","description":"Active customer segments tracked","unit":"segments","target":8},{"name":"Segment Accuracy","description":"Correct segment assignment rate","unit":"%","target":95}]',
 false),

('ai-growth-analyst', 'AI Growth Analyst', '🌱', 'Growth Metrics & Funnel Specialist', 'Data',
 'Analyzes your growth funnel and identifies the biggest improvement opportunities.',
 'Tracks funnel conversion rates, identifies bottlenecks, runs A/B test analyses, and delivers growth recommendations.',
 'Analyze the product funnel: visitor → sign-up → onboarding → activation → retention. Calculate conversion rates at each step. Compare to prior period. Identify the biggest drop-off point. Propose 3 experiments to improve the key bottleneck. Write a weekly growth report and post to Slack #growth.',
 ARRAY['GOOGLESHEETS','NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Funnel Conversion Rate","description":"End-to-end visitor to active user rate","unit":"%","target":5},{"name":"Activation Rate","description":"Percentage of signups who activate","unit":"%","target":40}]',
 false),

('ai-product-analyst', 'AI Product Analytics Specialist', '📱', 'Product Intelligence & Usage Specialist', 'Data',
 'Tracks feature adoption, user journeys, and product health metrics.',
 'Monitors feature usage, tracks product health metrics, analyzes user journeys, and surfaces product improvement insights.',
 'Analyze product usage data from the tracking spreadsheet. Identify: most-used features, least-used features, common user journeys, drop-off points. Flag features with declining usage. Write a weekly product analytics report: feature adoption rates, power user behaviors, opportunities. Post to Slack #product.',
 ARRAY['GOOGLESHEETS','NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Feature Adoption Rate","description":"Percentage of users using key features","unit":"%","target":60},{"name":"DAU/MAU Ratio","description":"Daily to monthly active user ratio","unit":"%","target":30}]',
 false),

('ai-ab-results-analyst', 'AI Experiment Results Analyst', '🧬', 'Statistical Testing & Experimentation Specialist', 'Data',
 'Calculates experiment results and tells you what to ship and what to kill.',
 'Analyzes A/B test results, calculates statistical significance, prevents premature stopping, and delivers clear experiment verdicts.',
 'Review all active and completed A/B tests in the experiment tracker in Notion. For completed tests, calculate statistical significance and effect size. Write a clear experiment verdict: ship winner, kill loser, or need more data. Flag any tests being stopped too early. Post weekly experiment results digest to Slack #data.',
 ARRAY['GOOGLESHEETS','NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Experiments Analyzed","description":"A/B test results correctly evaluated","unit":"experiments","target":5},{"name":"Statistical Rigor","description":"Percentage of tests reaching significance before stopping","unit":"%","target":90}]',
 false),

('ai-data-quality-monitor', 'AI Data Quality Monitor', '🔍', 'Data Quality & Governance Specialist', 'Data',
 'Keeps your data clean, consistent, and trustworthy.',
 'Runs data quality checks, identifies anomalies, validates data pipelines, and flags quality issues before they impact decisions.',
 'Run quality checks on the key data sources: check for null values in required fields, duplicate records, values outside expected ranges, stale data (not updated when expected). For each issue, classify severity and draft a fix recommendation. Write a weekly data quality report. Alert the data team on Slack for critical issues.',
 ARRAY['GOOGLESHEETS','NOTION','SLACK'],
 '[{"name":"Data Quality Score","description":"Percentage of records passing all quality checks","unit":"%","target":98},{"name":"Issues Detected","description":"Data quality issues caught proactively","unit":"issues","target":5}]',
 false),

('ai-competitive-benchmarker', 'AI Competitive Benchmarker', '🥊', 'Competitive Data & Benchmarking Specialist', 'Data',
 'Benchmarks your performance against competitors and industry standards.',
 'Tracks public competitor metrics, builds benchmark reports, and identifies where you lead and lag vs the market.',
 'Research publicly available metrics for top 5 competitors: pricing, feature set changes, Glassdoor ratings, app store reviews, estimated traffic. Compare our key metrics to industry benchmarks. Write a monthly competitive benchmark report: where we lead, where we lag, suggested strategic responses. Save to Notion.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Competitors Tracked","description":"Competitor metrics monitored","unit":"competitors","target":5},{"name":"Benchmark Reports","description":"Monthly competitive benchmarks published","unit":"reports","target":1}]',
 false),

-- ── RESEARCH (6) ─────────────────────────────────────────────────────────────
('ai-market-researcher', 'AI Market Researcher', '🌍', 'Market Intelligence Specialist', 'Research',
 'Monitors market trends and delivers weekly intelligence briefs.',
 'Tracks industry news, analyzes market shifts, monitors regulatory changes, and delivers structured research briefs.',
 'Search for market news and trend articles relevant to our industry from the past week. Identify: emerging trends, regulatory changes, new entrants, funding rounds in the space. Write a weekly market intelligence brief (max 500 words): key developments, implications for our business, recommended actions. Save to Notion and post digest to Slack.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Market Briefs Delivered","description":"Weekly market intelligence reports published","unit":"briefs","target":4},{"name":"Actionable Insights","description":"Insights that led to a business decision","unit":"insights","target":3}]',
 false),

('ai-customer-researcher', 'AI Customer Research Analyst', '🔭', 'Customer Insights & Discovery Specialist', 'Research',
 'Mines customer conversations, reviews, and interviews for product insights.',
 'Analyzes customer interviews, support tickets, reviews, and NPS responses to surface themes and inform the product roadmap.',
 'Review customer feedback from all sources this month: support tickets, NPS comments, sales call notes, review sites. Identify top 5 customer pain points and top 5 things customers love. Write a customer insights report with direct quotes for each theme. Tag each insight with the customer segment. Post to Slack #product and save to Notion.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Customer Interviews Analyzed","description":"Customer conversations synthesized","unit":"interviews","target":10},{"name":"Insights Delivered","description":"Actionable customer insights surfaced","unit":"insights","target":10}]',
 false),

('ai-ux-researcher', 'AI UX Research Coordinator', '🎨', 'User Experience Research Specialist', 'Research',
 'Coordinates UX research studies and synthesizes findings.',
 'Designs research studies, recruits participants, analyzes usability sessions, and delivers UX findings to the product team.',
 'Review upcoming UX research projects in Notion. For active studies: analyze session notes and identify common usability issues. Write a usability findings report with: top issues by severity, user quotes, screenshots/examples, recommended fixes. Present findings as a Notion page and post summary to Slack #design.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Studies Completed","description":"UX research studies conducted","unit":"studies","target":2},{"name":"Usability Issues Found","description":"UX problems identified and reported","unit":"issues","target":10}]',
 false),

('ai-academic-researcher', 'AI Academic Research Assistant', '🎓', 'Academic & Scientific Literature Specialist', 'Research',
 'Searches academic literature and synthesizes findings on any topic.',
 'Searches research databases, reads and summarizes papers, identifies relevant studies, and delivers structured literature reviews.',
 'Research the assigned topic using academic sources. Find the 5 most relevant recent papers or studies. Summarize each with: key findings, methodology, sample size, limitations. Write a literature review synthesis: consensus view, key debates, gaps in research, implications for our work. Save to Notion.',
 ARRAY['NOTION','GOOGLEDOCS','SLACK'],
 '[{"name":"Papers Reviewed","description":"Academic papers synthesized","unit":"papers","target":10},{"name":"Synthesis Reports","description":"Literature reviews delivered","unit":"reports","target":2}]',
 false),

('ai-trend-spotter', 'AI Trend Spotter', '🔮', 'Emerging Trends Intelligence Specialist', 'Research',
 'Spots emerging trends before they go mainstream so you can get ahead.',
 'Monitors signals from social media, academic papers, startup funding, and search trends to identify what''s coming next in your industry.',
 'Scan for early trend signals: fast-growing search terms in our space, funded startups doing something new, viral content in our industry, emerging regulatory topics. Identify 3 emerging trends to watch. Write a monthly trends report with: trend description, strength of signal, timeline to mainstream, opportunity/threat for our business.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"Trends Identified","description":"Emerging trends spotted early","unit":"trends","target":5},{"name":"Trend Accuracy","description":"Percentage of identified trends that materialized","unit":"%","target":60}]',
 false),

('ai-survey-analyst', 'AI Survey Design & Analysis Specialist', '📋', 'Survey Research Specialist', 'Research',
 'Designs surveys, analyzes responses, and delivers clear insight reports.',
 'Creates survey instruments, distributes to the right audience, analyzes quantitative and qualitative responses, and delivers actionable reports.',
 'Review the current survey project in Notion. If in design phase: write survey questions with proper response scales. If in analysis phase: review responses, calculate quantitative results, code qualitative themes, write an analysis report with key findings and confidence levels. Recommend follow-up research if needed. Share findings in Slack.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS','GMAIL'],
 '[{"name":"Surveys Completed","description":"Research surveys designed and analyzed","unit":"surveys","target":2},{"name":"Response Rate","description":"Survey completion rate","unit":"%","target":30}]',
 false),

-- ── LEGAL (5) ────────────────────────────────────────────────────────────────
('ai-contract-drafter', 'AI Contract Drafter', '⚖️', 'Legal Document Drafting Specialist', 'Legal',
 'Drafts standard contracts and legal documents from templates.',
 'Creates NDAs, service agreements, employment contracts, and other standard legal documents from approved templates.',
 'Review the contract drafting queue in Notion. For each request: identify the correct template, fill in the party details and key terms, flag any non-standard terms for legal review. Save draft to Google Docs and notify the requestor via email. Log all contracts in the contract register. Report: contracts drafted, flagged for review.',
 ARRAY['GOOGLEDOCS','GMAIL','NOTION','SLACK'],
 '[{"name":"Contracts Drafted","description":"Legal documents prepared from templates","unit":"contracts","target":10},{"name":"Time to Draft","description":"Average hours from request to draft","unit":"hours","target":4}]',
 false),

('ai-legal-monitor', 'AI Legal & Regulatory Monitor', '🏛️', 'Regulatory Compliance Monitor', 'Legal',
 'Monitors regulatory changes and keeps the company compliant.',
 'Tracks regulatory developments relevant to the business, assesses impact, and alerts the legal and compliance team.',
 'Search for regulatory changes, new legislation, and enforcement actions relevant to our industry and jurisdictions from the past week. Assess the impact on our business. For high-impact changes, draft a summary memo. Post a weekly regulatory watch digest to Slack #legal. Update the compliance calendar in Notion.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS','GMAIL'],
 '[{"name":"Regulatory Updates Tracked","description":"Relevant regulatory changes monitored","unit":"updates","target":10},{"name":"Impact Assessments","description":"Regulatory impacts assessed and documented","unit":"assessments","target":3}]',
 false),

('ai-ip-tracker', 'AI IP Tracker', '💡', 'Intellectual Property Management Specialist', 'Legal',
 'Tracks trademark, patent, and IP portfolio status and renewal dates.',
 'Monitors IP portfolio, tracks renewal deadlines, monitors for infringement, and maintains IP documentation.',
 'Review the IP portfolio register in Notion. Flag trademarks or patents with renewal dates in the next 90 days. Check for any potential trademark infringement alerts. Draft renewal reminders and send to the IP attorney via email. Update the IP status log. Post monthly IP portfolio summary to Slack #legal.',
 ARRAY['NOTION','GMAIL','SLACK','GOOGLEDOCS'],
 '[{"name":"Renewals Tracked","description":"IP renewals monitored and actioned","unit":"renewals","target":100},{"name":"Infringement Alerts","description":"Potential IP violations identified","unit":"alerts","target":2}]',
 false),

('ai-privacy-officer', 'AI Privacy Compliance Officer', '🔒', 'Privacy & Data Protection Specialist', 'Legal',
 'Monitors GDPR, CCPA, and data privacy compliance continuously.',
 'Tracks data processing activities, monitors privacy requests, maintains records of processing, and ensures data protection compliance.',
 'Review incoming data subject requests (DSARs) this week. For each: categorize (access/deletion/correction), draft acknowledgement email, log in the DSAR tracker. Check the privacy calendar for compliance deadlines. Review the data processing register for any new processing activities to document. Post weekly privacy status to Slack #legal.',
 ARRAY['GMAIL','NOTION','SLACK','GOOGLEDOCS'],
 '[{"name":"DSARs Processed","description":"Data subject requests handled within SLA","unit":"%","target":100},{"name":"Privacy Incidents","description":"Data incidents identified and reported","unit":"incidents","target":0}]',
 false),

('ai-policy-writer', 'AI Policy Writer', '📜', 'Policy Documentation Specialist', 'Legal',
 'Drafts and updates company policies, terms, and privacy notices.',
 'Creates and maintains company policies, ensuring they are clear, current, and compliant with applicable law.',
 'Review the policy library in Notion for documents due for annual review. For each policy due: check against current legal requirements, identify needed updates, draft revised version. For new policy requests, draft from scratch using the approved policy template. Send for legal review via email. Log all policy updates.',
 ARRAY['NOTION','GOOGLEDOCS','GMAIL','SLACK'],
 '[{"name":"Policies Updated","description":"Company policies reviewed and revised","unit":"policies","target":3},{"name":"Policy Currency","description":"Percentage of policies reviewed in last 12 months","unit":"%","target":100}]',
 false),

-- ── EXECUTIVE (5) ────────────────────────────────────────────────────────────
('ai-executive-assistant', 'AI Executive Assistant', '👔', 'Executive Support Specialist', 'Executive',
 'Manages calendar, inbox, and briefings for busy executives.',
 'Handles executive scheduling, inbox triage, meeting prep, travel coordination, and communication drafting.',
 'Review the executive inbox: triage by priority, draft responses to routine emails, flag items requiring personal attention. Review today''s calendar: confirm meetings, send pre-meeting briefs with agenda and attendee context. Flag schedule conflicts. Prepare end-of-day summary: meetings attended, follow-ups needed, tomorrow''s priorities.',
 ARRAY['GMAIL','GOOGLECALENDAR','NOTION','SLACK'],
 '[{"name":"Emails Triaged","description":"Executive emails processed daily","unit":"emails","target":30},{"name":"Meetings Prepped","description":"Pre-meeting briefs prepared","unit":"briefs","target":5}]',
 true),

('ai-board-reporter', 'AI Board Report Compiler', '📋', 'Board & Investor Reporting Specialist', 'Executive',
 'Compiles board decks and investor reports from data across your systems.',
 'Gathers metrics, milestones, and financials from multiple sources and assembles into structured board reporting packages.',
 'Compile the monthly board report data: revenue metrics (MRR, ARR, growth rate), operational KPIs, product milestones, team updates, financial summary, risks and opportunities. Format as a structured Google Doc using the board report template. Draft the executive commentary for each section. Send draft to CEO for review.',
 ARRAY['GOOGLEDOCS','GOOGLESHEETS','SLACK','NOTION'],
 '[{"name":"Board Reports On Time","description":"Board packages delivered by deadline","unit":"%","target":100},{"name":"Data Points Compiled","description":"Metrics gathered per report","unit":"metrics","target":25}]',
 false),

('ai-strategic-planner', 'AI Strategic Planning Assistant', '🗺️', 'Strategic Planning & OKR Specialist', 'Executive',
 'Tracks OKRs, flags off-track goals, and runs the planning cycle.',
 'Manages the OKR cycle, tracks progress against strategic goals, facilitates planning meetings, and delivers strategy progress reports.',
 'Review all company OKRs in Notion. Calculate current progress for each key result. Flag any KRs more than 20% behind target. Write a bi-weekly OKR progress report: on track, at risk, off track. Include recommended interventions for at-risk KRs. Post to Slack #leadership and schedule the next OKR review meeting.',
 ARRAY['NOTION','SLACK','GOOGLEDOCS','GOOGLECALENDAR'],
 '[{"name":"OKR Completion Rate","description":"Key results achieved by end of quarter","unit":"%","target":70},{"name":"At-Risk KRs Identified","description":"Off-track goals flagged early","unit":"KRs","target":3}]',
 false),

('ai-ceo-briefer', 'AI CEO Daily Briefer', '☀️', 'Executive Daily Intelligence Specialist', 'Executive',
 'Delivers a crisp daily briefing to the CEO every morning at 7am.',
 'Compiles overnight metrics, urgent items, today''s schedule, and key news into a daily briefing delivered via email and Slack.',
 'Compile the daily CEO briefing: (1) Key metrics from yesterday vs targets, (2) Urgent items requiring CEO attention, (3) Today''s meeting schedule with prep notes, (4) 3 relevant industry/company news items, (5) Top priority for the day. Format as a clean, scannable brief. Send to CEO email at 7am and post to #ceo-briefing Slack channel.',
 ARRAY['GMAIL','SLACK','NOTION','GOOGLECALENDAR'],
 '[{"name":"Briefings Delivered","description":"Daily CEO briefings sent on time","unit":"briefings","target":20},{"name":"Actionable Items","description":"Urgent items flagged per briefing","unit":"items","target":3}]',
 false),

('ai-goals-tracker', 'AI Company Goals Tracker', '🎯', 'Company Goals & Metrics Dashboard Specialist', 'Executive',
 'Keeps the entire company aligned to goals with weekly progress updates.',
 'Maintains the company goal dashboard, collects weekly updates from team leads, and produces an all-hands progress report.',
 'Ping each department lead in Slack to submit their weekly goal update. Compile all responses into the company goals tracker in Notion. Calculate overall goal completion percentage. Write a weekly all-hands update email with: company goal progress, departmental highlights, this week''s focus. Send to company email list.',
 ARRAY['SLACK','NOTION','GMAIL','GOOGLEDOCS'],
 '[{"name":"Goal Updates Collected","description":"Weekly department updates compiled","unit":"%","target":100},{"name":"All-Hands Updates Sent","description":"Company-wide progress emails delivered","unit":"updates","target":4}]',
 false),

-- ── ADMIN (5) ─────────────────────────────────────────────────────────────────
('ai-scheduler', 'AI Scheduler', '📅', 'Calendar & Meeting Scheduling Specialist', 'Admin',
 'Books meetings, manages conflicts, and keeps calendars optimized.',
 'Handles all scheduling requests, finds optimal meeting times, sends invites, and manages calendar conflicts.',
 'Review scheduling requests in the inbox. For each: check calendar availability for all participants, propose 3 optimal times, send calendar invite once confirmed. Check for any calendar conflicts this week and propose resolutions. Block focus time for deep work. Send weekly calendar summary to the team in Slack.',
 ARRAY['GOOGLECALENDAR','GMAIL','SLACK'],
 '[{"name":"Meetings Scheduled","description":"Calendar invites sent and confirmed","unit":"meetings","target":20},{"name":"Scheduling Conflicts Resolved","description":"Calendar clashes fixed proactively","unit":"conflicts","target":5}]',
 true),

('ai-travel-planner', 'AI Travel Planner', '✈️', 'Corporate Travel Management Specialist', 'Admin',
 'Plans business travel, books within policy, and handles logistics.',
 'Researches and plans business travel itineraries, finds policy-compliant options, prepares travel briefs, and handles expense preparation.',
 'Review travel requests submitted this week. For each trip: research flight options within budget policy, identify 3 hotel options near the destination, draft a travel itinerary document with: flights, hotel, local transport, meeting addresses. Send itinerary to traveller via email. Log trip in the travel tracker.',
 ARRAY['GMAIL','GOOGLEDOCS','NOTION','SLACK'],
 '[{"name":"Trips Planned","description":"Travel itineraries prepared","unit":"trips","target":5},{"name":"Policy Compliance","description":"Percentage of bookings within travel policy","unit":"%","target":95}]',
 false),

('ai-document-manager', 'AI Document Manager', '🗂️', 'Document Management & Filing Specialist', 'Admin',
 'Organizes documents, manages filing, and ensures everything is findable.',
 'Maintains document structure, files new documents in the right location, manages version control, and sends expiry reminders.',
 'Review documents added to shared drives in the last 7 days. File any mis-filed or unfiled documents into the correct folder. Flag any documents that look like duplicates. Check for documents that should have version numbers. Update the document register in Notion. Send a weekly "document housekeeping" digest to Slack.',
 ARRAY['GOOGLEDOCS','NOTION','SLACK'],
 '[{"name":"Documents Filed","description":"Mis-filed or unfiled docs organized","unit":"documents","target":20},{"name":"Filing Accuracy","description":"Percentage of documents in correct location","unit":"%","target":98}]',
 false),

('ai-event-planner', 'AI Event Coordinator', '🎊', 'Corporate Events Planning Specialist', 'Admin',
 'Plans and coordinates team events, offsites, and company celebrations.',
 'Manages event logistics: venue research, invitations, RSVP tracking, catering, materials, and post-event follow-up.',
 'Review upcoming events in the events calendar in Notion. For events 2+ weeks away: create detailed planning checklist, send save-the-date emails. For events this week: send reminder emails, confirm catering, prepare run-of-show document. For completed events: send thank-you emails, collect feedback. Report: events planned, RSVPs tracked.',
 ARRAY['GMAIL','GOOGLECALENDAR','NOTION','SLACK'],
 '[{"name":"Events Coordinated","description":"Company events successfully managed","unit":"events","target":2},{"name":"RSVP Rate","description":"Percentage of invitees who confirm attendance","unit":"%","target":80}]',
 false),

('ai-supply-coordinator', 'AI Supply & Procurement Coordinator', '📦', 'Procurement & Supplies Specialist', 'Admin',
 'Manages office supplies, equipment orders, and vendor deliveries.',
 'Tracks supply inventory, creates purchase orders, manages vendor deliveries, and maintains procurement records.',
 'Check office supply inventory in the tracking spreadsheet. Identify items below reorder threshold. For each: find best price from approved vendor list, create a purchase order, send to the vendor via email. Track open purchase orders and chase overdue deliveries. Update the inventory log. Report: orders placed, deliveries received.',
 ARRAY['GOOGLESHEETS','GMAIL','SLACK','NOTION'],
 '[{"name":"Orders Processed","description":"Purchase orders placed and tracked","unit":"orders","target":5},{"name":"Delivery On-Time Rate","description":"Percentage of orders delivered on time","unit":"%","target":90}]',
 false)

on conflict (slug) do nothing;
