-- Builder-facing audio generation (voiceover/narration assets for a project),
-- reusing the same ElevenLabs/OpenAI-TTS providers the AI Employees voice
-- feature already uses (021_employee_voice_clips.sql) via src/lib/audio-gen.ts.
-- No new table needed — generated audio just needs a Storage bucket; nothing
-- is logged per-generation the way employee_voice_clips does, since these are
-- one-off project assets referenced directly from the app the user is building.
--
-- Storage bucket (same convention as 021_employee_voice_clips.sql's
-- employee-voice-clips bucket: public read, writes only via the service-role
-- client — src/app/api/generate-audio/route.ts never uploads with the anon
-- key, so no additional storage.objects RLS policy is needed here, matching
-- employee-voice-clips which also ships with none).
insert into storage.buckets (id, name, public) values ('project-audio', 'project-audio', true) on conflict do nothing;
